<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>f55a3913-22c5-4a59-9662-42ae2745fe87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Logout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='actiongroup']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>21970dcf-1cc5-4cde-b3e2-5bce62102c2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>f665523c-76d1-42f4-8f98-98fd983c8e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://policyexpress-qa.hastingsmutual.com/Services/GlobalLogout</value>
      <webElementGuid>8ce1082d-bb22-4b7c-a0c0-53dbbf840ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcref</name>
      <type>Main</type>
      <value>/DuckCreek?targetPage=logout</value>
      <webElementGuid>4d0da9b8-d652-47a2-a33b-4fda46240c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>f1b92ac3-6fe3-49b6-becb-aa0aef0bfcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actiongroup&quot;)/ul[1]/li[2]/a[1]</value>
      <webElementGuid>77cbfbc7-7040-4518-be4a-0d95d8c69760</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actiongroup']/ul/li[2]/a</value>
      <webElementGuid>d47d6304-b579-4116-935a-a406a6c63fed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>7d2ba459-e320-4b65-9152-ddaa265919f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>cfcd2a42-17b6-48d8-8b61-88f339e204ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency'])[1]/preceding::a[3]</value>
      <webElementGuid>8169b5e1-0c7b-4ff4-a328-7c0469cf6532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote Name'])[1]/preceding::a[3]</value>
      <webElementGuid>f8fbfefa-43e4-41bf-b0ea-11973918a125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>8f0dc396-ae22-4401-8aa3-f5f7551faeba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://policyexpress-qa.hastingsmutual.com/Services/GlobalLogout')]</value>
      <webElementGuid>4ea0d5de-1e8f-47c5-8f62-d1fc0e43b45b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>2aad4045-81b4-4103-beb8-896a8f635d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Logout' and @href = 'https://policyexpress-qa.hastingsmutual.com/Services/GlobalLogout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>fd2dbf4e-a27f-4f50-baef-180ade35486a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
