<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit Quote</name>
   <tag></tag>
   <elementGuidId>02a96226-013a-4b68-8575-a60ed0067d02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#hmi-button-submit-policy > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='hmi-button-submit-policy']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>03033fb6-2dfe-4ab6-a59c-3b4db84b9ff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>c3407ca0-dfb9-4c58-ba92-60c9a6b3e8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Quote</value>
      <webElementGuid>b9853425-ea6a-4574-b9e1-e148ec3a0216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmi-button-submit-policy&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>9bda36d1-d5dd-4089-97b5-5207b474acd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='hmi-button-submit-policy']/span[2]</value>
      <webElementGuid>669f05ab-f8d4-40ab-bfae-a571b91c75b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agent Comments to Underwriting'])[1]/following::span[2]</value>
      <webElementGuid>9e758d0f-37fb-4c04-a941-84aa51fe313b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fax Number'])[1]/following::span[2]</value>
      <webElementGuid>3ed625b0-b6d8-4e8f-b434-6ce86c442c80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::span[2]</value>
      <webElementGuid>eced56a9-8ea8-474c-8267-2edbfaab7d73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright © 2009 - 2023 Hastings Mutual Insurance Company'])[1]/preceding::span[3]</value>
      <webElementGuid>bf02f39a-2f45-4dc1-897e-8cf616bbb983</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Quote']/parent::*</value>
      <webElementGuid>daec1514-da06-4189-8005-db74f28933f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span[2]</value>
      <webElementGuid>dd0e264d-baba-4b46-bad0-99732617069b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submit Quote' or . = 'Submit Quote')]</value>
      <webElementGuid>b188a182-9dbf-4e00-b81f-a88574c52fc0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
