<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_DriverName</name>
   <tag></tag>
   <elementGuidId>c7d62856-5225-4bed-a8de-6d481672b4fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DriverName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DriverName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f553d2b8-8616-41a4-b00c-b19e6888a3b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ad24e581-eb74-4cd4-b78c-b788b5cac611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DriverName</value>
      <webElementGuid>b0a17562-8220-456d-bd4b-b4ce4e3fec50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DriverName</value>
      <webElementGuid>514d3acc-b741-45e4-a5c1-efad4be91b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>57063487-17c2-48a9-8246-18c81405095a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>8c2c7c9f-36dc-46c0-9922-adfd0a85614e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>d10c2c1f-7628-47c1-beab-8dc9acbd449b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>34e6f96b-0bfe-459a-bd89-776cfc8ec494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>839d549a-dacb-4eea-aca6-905ee1bf6d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DriverName&quot;)</value>
      <webElementGuid>c922f6ac-382c-4d00-a80d-91b2ba00d868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DriverName']</value>
      <webElementGuid>7d178441-8432-485b-b5ed-a4f790f2c9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hmi-form-save-driverinfo']/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>d1a696ed-591b-4131-b0e7-25265df19694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>8c375d08-4fcd-4823-84ab-424481e411cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DriverName' and @name = 'DriverName' and @type = 'text']</value>
      <webElementGuid>cbff9097-1ab8-4112-b047-9065826244f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
