<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyHoldHarmlessAgreementsAnswer</name>
   <tag></tag>
   <elementGuidId>be693cba-8527-4d41-8c8a-1bcb926caa83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyHoldHarmlessAgreementsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyHoldHarmlessAgreementsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>43e3675f-f923-4feb-beb8-27eb371c1be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>7480b970-55bd-4778-a9f5-aa706812a895</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyHoldHarmlessAgreementsAnswer</value>
      <webElementGuid>8641e512-f7e3-4160-adf5-7dbb2eba533a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyHoldHarmlessAgreementsAnswer</value>
      <webElementGuid>273955a3-62e6-4652-89ca-42dbdbddfe7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>8c0e7db2-85fe-4392-ba1c-51dbf97c3c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>699c74d8-30ed-4606-be62-fedaeb356569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>45f975d4-4779-41f7-b7e8-1f5880477127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyHoldHarmlessAgreementsAnswer&quot;)</value>
      <webElementGuid>7e17cb8b-0064-4e84-9b5c-bfbb5e742ac5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyHoldHarmlessAgreementsAnswer']</value>
      <webElementGuid>b04d1f9e-afe9-414c-b280-6cd391a482fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[15]/td/table/tbody/tr/td/select</value>
      <webElementGuid>3df40ea9-eca5-4e19-82d7-ceb2aa44d7af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/following::select[1]</value>
      <webElementGuid>44f71b3d-7025-4d5d-b78e-6ff2376243e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do operations involve transporting hazardous material?'])[1]/following::select[1]</value>
      <webElementGuid>e6cea6bd-fc69-4afc-9212-92ba3ebc2364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any Hold Harmless agreements?'])[1]/preceding::select[1]</value>
      <webElementGuid>89f97c44-bef4-4bf4-853f-de164199a199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[6]/preceding::select[1]</value>
      <webElementGuid>ca4dbe75-a51b-4807-99a8-81cc0ca2e639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td/table/tbody/tr/td/select</value>
      <webElementGuid>012b5fd6-11dc-42b1-98bc-fc7d076e442a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyHoldHarmlessAgreementsAnswer' and @name = 'AnyHoldHarmlessAgreementsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>cac618d5-0c75-450f-8c08-4aa6884381ea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
