<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VehicleUsedByFamilyMembersAnswer</name>
   <tag></tag>
   <elementGuidId>e7d084bd-c558-480b-bb95-818ef1c433db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehicleUsedByFamilyMembersAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehicleUsedByFamilyMembersAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ca3d0773-16f5-4ed5-bd8a-b3e491551908</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>1c819e64-b185-4de9-a796-d048fa932415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehicleUsedByFamilyMembersAnswer</value>
      <webElementGuid>c744b1ff-74a0-46c5-863e-16b734db8ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehicleUsedByFamilyMembersAnswer</value>
      <webElementGuid>4f11851b-2fa3-4637-bd5c-02c2ee2e2538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>8ef443bb-b7b2-4aa4-bcaf-b99fa223f811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>dcf5900c-2a3a-43d5-ac15-47c1bdc52080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>ec7fa20c-2760-4cf3-b32d-42bd1510ee3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehicleUsedByFamilyMembersAnswer&quot;)</value>
      <webElementGuid>90c15fc1-3b01-4a0e-ba2b-0a46f29c558e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehicleUsedByFamilyMembersAnswer']</value>
      <webElementGuid>19703262-d603-427f-a548-7da3d4b5e901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>c7dab62b-c2b8-4d78-99af-cbeca03492f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[6]/following::select[1]</value>
      <webElementGuid>518e5347-28a9-46ec-a809-42aa1077fa51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any Hold Harmless agreements?'])[1]/following::select[1]</value>
      <webElementGuid>f734044e-aac7-483b-8e6b-803ce260f705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any vehicles used by family members? If so, identify.'])[1]/preceding::select[1]</value>
      <webElementGuid>cfe1caae-c252-4cdc-a8df-f02126d7a55a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[7]/preceding::select[1]</value>
      <webElementGuid>c847b81f-6648-43a9-ba45-10cfdfc56d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>1b9d6adf-b824-4dbf-9591-0058f424eab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehicleUsedByFamilyMembersAnswer' and @name = 'VehicleUsedByFamilyMembersAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>158e2e0c-d007-4866-9878-5bdf19231a89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
