<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyVehiclesNotSolelyOwnedByApplicantAnswer</name>
   <tag></tag>
   <elementGuidId>87b1be38-da59-4ab9-b76d-9cec58852a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AllVehiclesIncludedPartOfFleetAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyVehiclesNotSolelyOwnedByApplicantAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6bbb6def-38e5-4e54-83bd-96fe06f44f82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>1747d376-ad4b-4b7f-9620-084cc8b30d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AllVehiclesIncludedPartOfFleetAnswer</value>
      <webElementGuid>b9bb21ec-98a6-4997-99c6-e34bf1bc8c0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AllVehiclesIncludedPartOfFleetAnswer</value>
      <webElementGuid>83513499-506d-4867-a730-0c4571d6753f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>88f653a3-0ee5-4382-b01f-a732d89ffce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>5d78e8b7-9816-47bf-a439-63b6c1a06ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>745daf2d-714a-461d-a46a-0366f3e13c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AllVehiclesIncludedPartOfFleetAnswer&quot;)</value>
      <webElementGuid>fe7fb4f1-4908-469e-88ea-68c3187d3e65</webElementGuid>
   </webElementProperties>
</WebElementEntity>
