<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_VehiclesLeasedToOthersAnswer</name>
   <tag></tag>
   <elementGuidId>dee09c91-12f4-4d94-a3ff-1d8cbc40f811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehiclesLeasedToOthersAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehiclesLeasedToOthersAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cbde47ab-542a-42bd-b888-9ab76b17c8fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>31a09bbd-ff6d-4bf6-ba96-a8480c0a6cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehiclesLeasedToOthersAnswer</value>
      <webElementGuid>d1ea75f7-1cce-4c8e-be54-c2fa311eedc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehiclesLeasedToOthersAnswer</value>
      <webElementGuid>16747b01-8b4d-47c2-b5ba-1c511dc738af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>a13bbafc-1d7e-4153-8b38-4e3c7d73944c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>0db33a2e-0b73-4acc-b844-42f97db3acae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>315bf99b-63db-4266-9bd7-d0347b671b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehiclesLeasedToOthersAnswer&quot;)</value>
      <webElementGuid>161b6ed2-b5bf-4590-ace1-de643021d433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehiclesLeasedToOthersAnswer']</value>
      <webElementGuid>817ad0d0-17e1-47db-aa23-31ab90691f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2ef85d9a-ab3c-4c5f-b605-2bad486ccd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[2]/following::select[1]</value>
      <webElementGuid>ac706396-eecd-4616-9ad6-22eadd4e3086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is there a vehicle maintenance program in operation?'])[1]/following::select[1]</value>
      <webElementGuid>09a48d13-ed30-4cd7-af08-c842cdf642b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are any vehicles leased to others?'])[1]/preceding::select[1]</value>
      <webElementGuid>26011bb0-96c9-4317-87e4-a3d415bd6815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/preceding::select[1]</value>
      <webElementGuid>ddb408d6-040f-4c4e-8efd-791be8a7505f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>5ead4f26-9da9-460d-8aab-5fa49db4598f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehiclesLeasedToOthersAnswer' and @name = 'VehiclesLeasedToOthersAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>1fcd4139-a7e1-4ca4-93fb-18ae7115688a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
