<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OperationsInvolveTransportHazardousMaterialAnswer</name>
   <tag></tag>
   <elementGuidId>7130d9e1-1291-4535-a3e8-8d12e3d7da5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OperationsInvolveTransportHazardousMaterialAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OperationsInvolveTransportHazardousMaterialAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>40797a00-2faf-4f4b-af16-79267193ba8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5dbacc9d-de2b-4b24-a8cc-6dda665f14b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OperationsInvolveTransportHazardousMaterialAnswer</value>
      <webElementGuid>d8ef0689-b44a-4dd9-b374-1f8212be0440</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OperationsInvolveTransportHazardousMaterialAnswer</value>
      <webElementGuid>f2450411-458f-4d2e-98aa-29f1892a6743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>9c88a3fd-6f5b-4c86-9317-f961410d0ea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>9a812d2a-0b5b-4cd4-8d97-9727f96a5b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>ab64c42d-1072-4b85-a255-932bf4765ddc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OperationsInvolveTransportHazardousMaterialAnswer&quot;)</value>
      <webElementGuid>30f3f047-d397-4f7e-8f2b-01e89d6dfb30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OperationsInvolveTransportHazardousMaterialAnswer']</value>
      <webElementGuid>053331e8-dd76-43da-bd00-3a2d53211e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[13]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2a36a2fa-f0e0-4e54-9342-a4be9a94d3dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/following::select[1]</value>
      <webElementGuid>caa46d0a-933c-430c-803e-85e2c2691e71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost'])[2]/following::select[2]</value>
      <webElementGuid>12629596-b0f6-4337-a667-bf48ee9a7702</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do operations involve transporting hazardous material?'])[1]/preceding::select[1]</value>
      <webElementGuid>45b81f0e-6833-450e-a799-54ae46107013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/preceding::select[1]</value>
      <webElementGuid>eea8ce91-5124-42c5-ab6f-6dd97c660514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2b81eaae-75bf-4da9-9e07-ec487460f1da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OperationsInvolveTransportHazardousMaterialAnswer' and @name = 'OperationsInvolveTransportHazardousMaterialAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>e8f7df87-821c-4624-b7f9-37d5b94af918</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
