<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyDriversConvictedForMovingViolationsAnswer</name>
   <tag></tag>
   <elementGuidId>508b3b27-bc5c-4dba-85fc-f3785ce56a47</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyDriversConvictedForMovingViolationsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyDriversConvictedForMovingViolationsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4f855c47-4c24-4813-b75a-039b0d70394c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3d1e2872-2747-42c0-a129-72c2f4867018</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyDriversConvictedForMovingViolationsAnswer</value>
      <webElementGuid>2eba672a-557e-42a1-9ffb-eb56c7a274a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyDriversConvictedForMovingViolationsAnswer</value>
      <webElementGuid>16053ecf-f01f-44d5-baeb-5aaa98bccd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>addd824c-c3ae-4a67-8332-021b1c5ea7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>0cf0ff37-2b7d-4a7c-9fe6-08bde837e512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>a4094100-28ea-49e5-aeef-2a4daacbb675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyDriversConvictedForMovingViolationsAnswer&quot;)</value>
      <webElementGuid>a75798e1-8d71-40ca-928d-fce3860053a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyDriversConvictedForMovingViolationsAnswer']</value>
      <webElementGuid>8f299d79-7a08-4ce4-9bda-ec82f2f4f29f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[27]/td/table/tbody/tr/td/select</value>
      <webElementGuid>c6c30713-acca-4b18-85e0-49f54d1dada8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[11]/following::select[1]</value>
      <webElementGuid>17cddf3e-17b2-4315-aaf8-5b9d970c80f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any vehicles owned but not scheduled on this application?'])[1]/following::select[1]</value>
      <webElementGuid>eef07b4c-281d-4c93-be41-d61e14202260</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any drivers with convictions for moving traffic violations?'])[1]/preceding::select[1]</value>
      <webElementGuid>fba85b84-79ad-4763-940e-39e3cbc80bae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Driver Number'])[1]/preceding::select[1]</value>
      <webElementGuid>acd05420-1962-4720-9118-0904ff711afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td/table/tbody/tr/td/select</value>
      <webElementGuid>05dd5efb-8aff-4a0b-b0c6-6182f318ee23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyDriversConvictedForMovingViolationsAnswer' and @name = 'AnyDriversConvictedForMovingViolationsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>ce30000c-7844-441c-9327-4446988825b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
