<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyDriversNotCoveredByWorkersCompensationAnswer</name>
   <tag></tag>
   <elementGuidId>34bdfac4-cff4-42ed-84e0-8b5a099f3ce3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyDriversNotCoveredByWorkersCompensationAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyDriversNotCoveredByWorkersCompensationAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bbec2ac0-43b5-4c4a-86ed-c4efe0bf8b2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>fe650075-837e-4c67-8e6d-fb2a58739d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyDriversNotCoveredByWorkersCompensationAnswer</value>
      <webElementGuid>13d4dffb-c08d-4e79-ab6f-8fae11136301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyDriversNotCoveredByWorkersCompensationAnswer</value>
      <webElementGuid>ae5c9a69-dce0-4ff2-a31f-96d3a964075e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>d2d981d6-f68b-4257-9e90-5accb5c590a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>5133e9f1-035a-497a-8fc8-e38693dcc1b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>68f3e9b3-7119-4b3b-b7db-3abdc395e63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyDriversNotCoveredByWorkersCompensationAnswer&quot;)</value>
      <webElementGuid>408a29e8-a600-4f76-a908-c4551cfe0842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyDriversNotCoveredByWorkersCompensationAnswer']</value>
      <webElementGuid>22396b1a-d185-4015-ac04-20b6ad8bcdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>d0e450a7-c3a0-4753-8fcf-8821e4009732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[9]/following::select[1]</value>
      <webElementGuid>38c7ccf8-1c46-43ef-9922-2bf3fe9d6e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the applicant have a specific driver recruiting method?'])[1]/following::select[1]</value>
      <webElementGuid>7777eedf-702f-41b9-aaad-5b573e466ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are any drivers not covered by workers compensation?'])[1]/preceding::select[1]</value>
      <webElementGuid>724c9ef5-3afc-42ca-b9ae-8b37c3a23145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[10]/preceding::select[1]</value>
      <webElementGuid>ccf03c01-6a81-4cef-b8a6-6e15ac8e96ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8fd56cfb-c17e-4210-8210-df2c1375bb34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyDriversNotCoveredByWorkersCompensationAnswer' and @name = 'AnyDriversNotCoveredByWorkersCompensationAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>b87ea910-0062-48f0-9482-fc39e69ea53b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
