<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_AnyModifiedSpecialEquipmentAnswer</name>
   <tag></tag>
   <elementGuidId>287bf6ac-1a82-4caf-a15f-c6550db52381</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyModifiedSpecialEquipmentAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyModifiedSpecialEquipmentAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f22ebefc-1153-4086-aad4-2025e8e95fb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>53392ee3-8110-4c35-805a-3122379f100b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyModifiedSpecialEquipmentAnswer</value>
      <webElementGuid>1bff59cb-c65b-46ec-b9cc-61b46094c474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyModifiedSpecialEquipmentAnswer</value>
      <webElementGuid>a06ae345-c868-4d1b-8730-497d0aa14cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>69a72c69-b4ae-45c3-91ef-d1a723f705c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>d611e0ca-199a-47c1-9a5c-55ce66fc06e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>ad829b44-bd6e-4f6b-91a3-b466ff08eaa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyModifiedSpecialEquipmentAnswer&quot;)</value>
      <webElementGuid>8efbcae4-818c-4df4-9837-9442c349296a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyModifiedSpecialEquipmentAnswer']</value>
      <webElementGuid>fa7f8080-c2e7-429a-b51f-32291aaaafda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>32f830cb-12bb-481b-8b55-e2cda69604c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/following::select[1]</value>
      <webElementGuid>48ef26b9-5851-40bd-84b6-e3e3f75e2f92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are any vehicles leased to others?'])[1]/following::select[1]</value>
      <webElementGuid>661cf383-e52a-41dc-b7a9-89f6b39e1f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any car modified/special equipment? (Include customized vans/pickups)'])[1]/preceding::select[1]</value>
      <webElementGuid>9eb9b9d2-38af-407a-b805-efcdbd8d6ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle #'])[3]/preceding::select[1]</value>
      <webElementGuid>c5612174-c560-4104-8059-ba418ed1d7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>a034de52-52ef-4ad6-95e8-bcf85b456835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyModifiedSpecialEquipmentAnswer' and @name = 'AnyModifiedSpecialEquipmentAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>b87f64b7-3a2c-4399-9985-79d992e0b33e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
