<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IUCorPUCorOtherFilingsRequiredAnswer</name>
   <tag></tag>
   <elementGuidId>d030b1bf-ac2e-41cd-bd0b-fdf243b5e7ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IUCorPUCorOtherFilingsRequiredAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IUCorPUCorOtherFilingsRequiredAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>59e82271-d436-43f8-a434-eda712a227ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cdef8c3d-67fd-4040-ae5d-38d987145d87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IUCorPUCorOtherFilingsRequiredAnswer</value>
      <webElementGuid>da05b6b1-3665-48e6-9306-c49a9109d39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IUCorPUCorOtherFilingsRequiredAnswer</value>
      <webElementGuid>5d34e9c5-5475-4d01-b969-379fceed67ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>53c55d2e-8816-4489-94a8-5c2d7226d647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>21</value>
      <webElementGuid>636809f6-5e92-4e13-8a64-75bf8bbb03bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>463bd6bf-512b-46f9-adbf-5c3e6b241cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IUCorPUCorOtherFilingsRequiredAnswer&quot;)</value>
      <webElementGuid>45da543d-20e2-4e49-95c4-472f56962c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IUCorPUCorOtherFilingsRequiredAnswer']</value>
      <webElementGuid>cf3877ed-01fc-4fcd-9e6f-a5506c8fa7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8f46d6c0-cb16-4239-ae76-5fdb0542b183</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost'])[2]/following::select[1]</value>
      <webElementGuid>bec78a8a-5406-44d8-a8fb-abd953bf0468</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Descript.'])[2]/following::select[1]</value>
      <webElementGuid>c0360e90-c7e2-4815-8872-6207886020ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/preceding::select[1]</value>
      <webElementGuid>c6264603-0901-46c5-8794-f337e516832d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do operations involve transporting hazardous material?'])[1]/preceding::select[2]</value>
      <webElementGuid>bb1cfa52-8f51-4931-8776-209c12ac807d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>5b81707c-9f6c-47bf-8680-dfbabb80ef0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IUCorPUCorOtherFilingsRequiredAnswer' and @name = 'IUCorPUCorOtherFilingsRequiredAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>d1afb79d-462b-4f7e-9757-012e3e3d86de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
