<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Drivers License (Do not use Social Se_ad877a</name>
   <tag></tag>
   <elementGuidId>30c3a153-196c-488f-afe2-94c2df5e36d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DriversLicenseNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DriversLicenseNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>29508776-5ba1-4e15-a194-c1f5afc968db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>09149169-da11-4a7e-84a0-1c0d2c704047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DriversLicenseNumber</value>
      <webElementGuid>e6571afa-a8c0-4eb6-a832-dbf25572e899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DriversLicenseNumber</value>
      <webElementGuid>3f5dcb5d-42c4-4a03-8a58-88f07f492a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>9236fb02-9567-4eb7-b1ed-15c4592d8f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>fe4fe170-990d-476d-b7e7-4fac88a93c4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z]+$</value>
      <webElementGuid>0f408cb1-625b-4857-8d76-3f2f37920ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>0930a66b-d1f2-4867-b23e-fb935bfb0f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>00b7debc-6f0d-4878-91df-ee108724cf06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DriversLicenseNumber&quot;)</value>
      <webElementGuid>345c3f34-6047-4d48-96a2-5205110ac680</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DriversLicenseNumber']</value>
      <webElementGuid>93153fc0-f706-40ac-95bd-ffe5b7b18aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[7]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>9a3b4cd1-72f5-4082-b87f-cede16c8a06a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>024ef05f-552d-458f-8e0c-f41355f602e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DriversLicenseNumber' and @name = 'DriversLicenseNumber' and @type = 'text']</value>
      <webElementGuid>3ea22f18-7863-4da3-8305-85b4d2e6436e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
