<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Insured  Spouse  Child  Gr_e99461</name>
   <tag></tag>
   <elementGuidId>7b44cd31-cdd4-4a40-a99d-7514922e04ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RelationshipToInsured']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RelationshipToInsured</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3c999446-2d5f-44e4-93b0-0ac994ad165a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4baa8e9d-f6fb-4502-b4f4-ddefe7c8b0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RelationshipToInsured</value>
      <webElementGuid>1fc3ce49-eaf3-481d-b2c7-eba66791800f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RelationshipToInsured</value>
      <webElementGuid>8583f91e-8aef-49eb-ae47-cbc8da559bda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>1814c68e-ef0c-4fe8-b00c-13459fb3c38c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Insured  Spouse  Child  Grandparent  Relative  Not Related </value>
      <webElementGuid>e7019fe2-1640-4ce6-8fa2-e7b3959f10a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RelationshipToInsured&quot;)</value>
      <webElementGuid>36cfdf51-7b9c-4136-83eb-eca9134cf01c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RelationshipToInsured']</value>
      <webElementGuid>dd9e1c18-29f3-4813-b12a-850f3101d3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[6]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>729a87d6-49ca-4676-96d5-b1f1d7e14206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship to Insured'])[1]/following::select[1]</value>
      <webElementGuid>1458cc6d-4e45-4677-908b-506c8ba4ae5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide Explanation'])[1]/following::select[1]</value>
      <webElementGuid>97fef15b-e7d8-4d57-9c2d-38684fe9d134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers License #(Do not use Social Security Number)'])[1]/preceding::select[1]</value>
      <webElementGuid>afd6b24d-ae45-465d-9349-3a9b5afb8ff4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License State'])[1]/preceding::select[1]</value>
      <webElementGuid>7b6802c3-997a-42f4-96bd-fd7be7e9ea0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>de2efce0-c16c-447d-afc2-93588cfe91bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RelationshipToInsured' and @name = 'RelationshipToInsured' and (text() = ' (Select)  Insured  Spouse  Child  Grandparent  Relative  Not Related ' or . = ' (Select)  Insured  Spouse  Child  Grandparent  Relative  Not Related ')]</value>
      <webElementGuid>9b568cd8-2c74-40c4-aaf5-d1015937740c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
