<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Alabama  Alaska  Arizona  _1e4f5a</name>
   <tag></tag>
   <elementGuidId>0e027b4b-fd51-47f6-8d40-7a5af61eb742</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DriversLicenseState']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DriversLicenseState</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c4ff08ec-a52d-45b2-8ec3-a600c33d4e32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d5b4b936-a20b-490e-b8b2-e3e8d48b2944</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DriversLicenseState</value>
      <webElementGuid>748094fe-316f-4138-bd5c-a48c4a49d7a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DriversLicenseState</value>
      <webElementGuid>44d5dc4f-cd0d-4167-8c07-2e9347de198d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-text-highlight hmi-ui-dirty</value>
      <webElementGuid>61f115b0-1c72-4829-bb0d-4286085ec41a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Alabama  Alaska  Arizona  Arkansas  California  Colorado  Connecticut  District of Columbia  Delaware  Florida  Georgia  Hawaii  Idaho  Illinois  Indiana  Iowa  Kansas  Kentucky  Louisiana  Maine  Maryland  Massachusetts  Michigan  Minnesota  Mississippi  Missouri  Montana  Nebraska  Nevada  New Hampshire  New Jersey  New Mexico  New York  North Carolina  North Dakota  Ohio  Oklahoma  Oregon  Pennsylvania  Rhode Island  South Carolina  South Dakota  Tennessee  Texas  Utah  Vermont  Virginia  Washington  West Virginia  Wisconsin  Wyoming  Alberta  British Columbia  Manitoba  New Brunswick  Newfoundland  Northwest Territories  Nova Scotia  Ontario  Prince Edward Island  Quebec  Saskatchewan  Yukon </value>
      <webElementGuid>8152e869-9954-4284-8832-f17914f93e54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DriversLicenseState&quot;)</value>
      <webElementGuid>5a47a24a-8281-46c0-ab5c-0dc13ac4f3ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DriversLicenseState']</value>
      <webElementGuid>e6b8338b-a281-4355-8864-1034bce6b3c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[7]/td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>28e0497e-4c8d-4494-8780-0544179c587a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License State'])[1]/following::select[1]</value>
      <webElementGuid>d24aba21-f549-460c-91a7-639c8683db90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Drivers License #(Do not use Social Security Number)'])[1]/following::select[1]</value>
      <webElementGuid>a1696155-e9e8-436a-8693-0e69d7c8d57d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Age'])[1]/preceding::select[1]</value>
      <webElementGuid>6423798f-45a2-4b47-972b-450cd19cdb81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>406cff83-400e-4b87-b23f-8fd259c46ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DriversLicenseState' and @name = 'DriversLicenseState' and (text() = ' (Select)  Alabama  Alaska  Arizona  Arkansas  California  Colorado  Connecticut  District of Columbia  Delaware  Florida  Georgia  Hawaii  Idaho  Illinois  Indiana  Iowa  Kansas  Kentucky  Louisiana  Maine  Maryland  Massachusetts  Michigan  Minnesota  Mississippi  Missouri  Montana  Nebraska  Nevada  New Hampshire  New Jersey  New Mexico  New York  North Carolina  North Dakota  Ohio  Oklahoma  Oregon  Pennsylvania  Rhode Island  South Carolina  South Dakota  Tennessee  Texas  Utah  Vermont  Virginia  Washington  West Virginia  Wisconsin  Wyoming  Alberta  British Columbia  Manitoba  New Brunswick  Newfoundland  Northwest Territories  Nova Scotia  Ontario  Prince Edward Island  Quebec  Saskatchewan  Yukon ' or . = ' (Select)  Alabama  Alaska  Arizona  Arkansas  California  Colorado  Connecticut  District of Columbia  Delaware  Florida  Georgia  Hawaii  Idaho  Illinois  Indiana  Iowa  Kansas  Kentucky  Louisiana  Maine  Maryland  Massachusetts  Michigan  Minnesota  Mississippi  Missouri  Montana  Nebraska  Nevada  New Hampshire  New Jersey  New Mexico  New York  North Carolina  North Dakota  Ohio  Oklahoma  Oregon  Pennsylvania  Rhode Island  South Carolina  South Dakota  Tennessee  Texas  Utah  Vermont  Virginia  Washington  West Virginia  Wisconsin  Wyoming  Alberta  British Columbia  Manitoba  New Brunswick  Newfoundland  Northwest Territories  Nova Scotia  Ontario  Prince Edward Island  Quebec  Saskatchewan  Yukon ')]</value>
      <webElementGuid>828b4f44-cf92-4ac3-aa44-cd8aa72ada27</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
