<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit_stockLimit</name>
   <tag></tag>
   <elementGuidId>b7f841f7-6d2d-4987-a91d-1f82729ef30f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#stockLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='stockLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d1a9eedf-3bc7-44c3-8541-7b7900cd0a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>113ac09c-b404-4995-844a-1e928ee9488b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>stockLimit</value>
      <webElementGuid>78df8662-c2af-4f88-83a8-649f74c6384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>stockLimit</value>
      <webElementGuid>21d0ea8f-6987-48d6-b48b-1aa6934f44ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit8</value>
      <webElementGuid>649d2371-b203-44d7-a0df-a534c0a9ffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>79ea00e2-48b9-40a0-b5e1-687dc1fa58a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>51</value>
      <webElementGuid>6cd87a5b-0181-4349-aae3-f3b3307f6253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>86a95db6-dc0e-4205-bfd9-63026ac89b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;stockLimit&quot;)</value>
      <webElementGuid>54db2457-879b-4c4a-ac20-5031deeb930c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='stockLimit']</value>
      <webElementGuid>88b578ac-b5dd-4fbf-b903-ca764a4c6a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coverage-container']/table[6]/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>b0e8ee98-d53f-41c9-8b27-c28b037ac1d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[6]/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>8a12d0a9-faea-4267-a8d6-0f356c98d0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'stockLimit' and @name = 'stockLimit' and @alt = 'limit8' and @type = 'text']</value>
      <webElementGuid>be9f28be-18a5-4993-a1f5-49ac7b21c82e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
