<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit_contentsCoverageLimit</name>
   <tag></tag>
   <elementGuidId>49b2d6f6-1800-4d69-a86e-40e7a4c60546</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contentsCoverageLimit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contentsCoverageLimit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6a93fd9e-d21e-48c0-88c0-5116ac5dcf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e682529a-b936-4f31-addd-91eefeaf85a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contentsCoverageLimit</value>
      <webElementGuid>264c8d01-7b31-48b7-befd-59486ba74004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contentsCoverageLimit</value>
      <webElementGuid>fb9dc4bd-335c-4819-908b-e81470380747</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit8</value>
      <webElementGuid>ecf0d90b-4f25-470b-a1fa-c52123676547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>1008d39c-54ab-4ba9-936f-0ce573325bde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>431011d2-f52a-43e0-98c0-9dc2e117d672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfec2e0c-9a19-456d-a3c8-d0461287b9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contentsCoverageLimit&quot;)</value>
      <webElementGuid>a1723d4b-9d32-4143-bb1f-4acaba2145f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contentsCoverageLimit']</value>
      <webElementGuid>70cc11b4-d076-40ab-ae5f-5676ab994291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coverage-container']/table[2]/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>3a6ee12a-9a97-4b46-a000-5418320b22c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr[2]/td[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>baee08b1-d381-400d-9361-c09f6911984d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contentsCoverageLimit' and @name = 'contentsCoverageLimit' and @alt = 'limit8' and @type = 'text']</value>
      <webElementGuid>fb2dc4a1-17c5-4d8d-bbad-22dd6804bb2c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
