<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Endorsements_buildingCoverage</name>
   <tag></tag>
   <elementGuidId>f4635894-5057-4980-88c6-fbb921a04be7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildingCoverage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildingCoverage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>46af0998-c3c4-4b8a-a677-1e3ad58c9d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>22dd8361-ecb9-47f3-886b-9b9d0859f177</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>74b5d479-c618-46f3-8db8-259119f74424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildingCoverage</value>
      <webElementGuid>9f911b0b-fb67-4dad-ac88-eeb28943f5d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildingCoverage</value>
      <webElementGuid>7fa3dab1-61e1-460f-839c-81053923d51c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>4aa2c8ad-c637-4772-900c-d799d1626f02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>764da106-bcd3-4163-a0fb-8ebb5211926b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>54f4cbc8-b8fd-48ea-b92e-cacc24371fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildingCoverage&quot;)</value>
      <webElementGuid>4773e595-c7b7-4f76-81a1-d641434c601f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildingCoverage']</value>
      <webElementGuid>05402045-877d-4dbc-b56f-4ce358cabd8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='coverage-container']/table/tbody/tr/td/input</value>
      <webElementGuid>195d9a88-5991-4032-8f85-c8028a899e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/table/tbody/tr/td/input</value>
      <webElementGuid>65e91838-ae53-4eee-909b-d905e2d438ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buildingCoverage' and @name = 'buildingCoverage' and @type = 'checkbox']</value>
      <webElementGuid>1b817317-2370-445a-b343-7cb22138fa5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
