<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Class Code or Description_C_15c1d5</name>
   <tag></tag>
   <elementGuidId>b467015c-fea6-4f1a-92bf-e58c223269b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ClassCodeSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ClassCodeSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d65ad47c-eb65-47a6-9b3e-77d400fe3bec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e2470adf-46bf-47ac-b772-ba5f69152cfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClassCodeSearch</value>
      <webElementGuid>66ed7fd5-4922-4ee9-a83c-89f961f69813</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClassCodeSearch</value>
      <webElementGuid>55943c5e-b0ee-4658-9f83-2ce35084ac5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>129f2852-8c44-4637-b57e-2a2002110f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 0531 or Beverage</value>
      <webElementGuid>f8c50e1b-ad26-4a9f-b702-9c0b633678d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>type 3 letters or more to search...</value>
      <webElementGuid>1d805ccf-88a9-459c-bd9f-7da88b261fc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>4180300c-2486-4618-a1dd-a1bf22d7e7db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4b03cbd9-68a1-4488-825c-db071c87f5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27eabfa1-3194-49c0-a427-b999bb46178a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>82a987cb-04bb-4b4a-ab3c-0911a0186daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClassCodeSearch&quot;)</value>
      <webElementGuid>09587cf0-4b17-4ac1-bfb5-eca9b517fe17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ClassCodeSearch']</value>
      <webElementGuid>b3cad21d-9eff-4c0a-937f-f0ef3fd0f135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div/table[3]/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>37bf789b-0a94-4ec0-9afb-494fd76a76ef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[3]/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>5cf9ff56-4fcc-4b99-8bba-36fe827f3d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ClassCodeSearch' and @name = 'ClassCodeSearch' and @placeholder = 'Ex: 0531 or Beverage' and @title = 'type 3 letters or more to search...' and @type = 'text']</value>
      <webElementGuid>bf3dd3d8-3cca-462d-83d0-e01b959ac855</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
