<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No_1</name>
   <tag></tag>
   <elementGuidId>4d0b5d9e-8341-4e25-849e-dc1e9c16383e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RenovationsReconstruction']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RenovationsReconstruction</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ed6c0002-8f80-41d1-bbfa-c5fd4068227c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>297dae6f-2b69-4cb9-9fbb-51a9cb786334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RenovationsReconstruction</value>
      <webElementGuid>39d3cb73-5771-4c49-8a34-34f7be6622cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RenovationsReconstruction</value>
      <webElementGuid>2bfdc402-7c0c-4de7-a104-5c6f1103ef46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1bbf9d91-ca28-4fe0-89bb-35a44995838a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>2fd02c8f-bb68-415e-9f35-920cbfe632cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>2cecb992-c382-4d79-ba47-5148e47e5838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>6a4b6baf-0334-4cf2-9fec-0e0365b10d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RenovationsReconstruction&quot;)</value>
      <webElementGuid>b3be8c54-ede8-4f78-ba64-5835f3b33715</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RenovationsReconstruction']</value>
      <webElementGuid>66cf38ab-d323-4d4c-a857-81d588e34f50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table[2]/tbody/tr/td[2]/div/form/div[2]/table/tbody/tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8e31deb9-dca2-4bfa-b0ff-fedda3bf02b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to General Policy Information'])[1]/following::select[5]</value>
      <webElementGuid>0049c483-e673-4040-b10e-882277b55236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead paint hazard exists.'])[1]/following::select[5]</value>
      <webElementGuid>893a5801-1b0a-4c7d-8e03-66c573f3b448</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describe Renovation:'])[1]/preceding::select[1]</value>
      <webElementGuid>c02356dd-4281-48b7-a3f3-06f0e12ff33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to General Policy Information'])[2]/preceding::select[7]</value>
      <webElementGuid>6c4858f2-4953-4a78-a07f-a18ab0beee0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>4582b5a2-f181-491d-b7e0-9bf07abfde6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RenovationsReconstruction' and @name = 'RenovationsReconstruction' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>9cc96388-4bc6-4487-838d-efb745242c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
