<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No (1)</name>
   <tag></tag>
   <elementGuidId>5bf40007-3a71-45e6-bd87-6029be9c4387</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IsThereCentralHeat']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IsThereCentralHeat</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f7af82cd-7a3a-440a-a9a4-af9affa9e8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>017abb3e-b5fb-4f8a-93c0-fa78c981c471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsThereCentralHeat</value>
      <webElementGuid>a1e767d5-6601-49ce-a15e-330c951d6090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsThereCentralHeat</value>
      <webElementGuid>15eec292-2201-460b-91c1-8004fb6c89bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>317f67c2-9d9b-473e-b3b0-f8625437667c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>b12cafa3-c893-436a-bcec-c276aa90770c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5d647f9a-57c9-4546-b94a-eb1d1c38b052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>c799a8aa-04df-48ac-9962-ee6474aad09f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsThereCentralHeat&quot;)</value>
      <webElementGuid>4b78d852-c94c-4421-9a0d-29324d8fa6ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IsThereCentralHeat']</value>
      <webElementGuid>f5e1f6f2-b5d5-466b-b5a6-9f3fe80f82aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table[2]/tbody/tr/td[2]/div/form/div[2]/table/tbody/tr[8]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8e25ae7d-2d91-4936-b187-7f2fc3da18ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to General Policy Information'])[1]/following::select[4]</value>
      <webElementGuid>1fbc5d4b-f9f6-4b1b-b048-21c7651f7089</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead paint hazard exists.'])[1]/following::select[4]</value>
      <webElementGuid>6f18dc7f-7f13-41cd-b208-8cf293cb6a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describe Renovation:'])[1]/preceding::select[2]</value>
      <webElementGuid>8b092082-f1e7-4d83-be9a-84e2e87f334f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to General Policy Information'])[2]/preceding::select[8]</value>
      <webElementGuid>45efaa42-3d39-4894-ac6a-8803c859b53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td/table/tbody/tr/td/select</value>
      <webElementGuid>0eb7e6ef-2f0e-40a9-8caf-f4d00d7dccbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IsThereCentralHeat' and @name = 'IsThereCentralHeat' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>bfdac5f1-928f-4242-a1b6-f2ba2a56f3ca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
