<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>369a0c22-0b6b-49fc-bf80-52129640cc99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IsThereASolidFuelBurnerOnThePremises']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IsThereASolidFuelBurnerOnThePremises</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eb7e5771-6232-4976-85be-995b73d81111</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>dce7bec2-5225-40d3-861b-a6716c57a365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsThereASolidFuelBurnerOnThePremises</value>
      <webElementGuid>586b0172-ffac-40c1-b089-0984412f7941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsThereASolidFuelBurnerOnThePremises</value>
      <webElementGuid>4d3daae4-6aa4-4227-8fdf-679418807c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>060fa6fd-6d9a-40df-ac8e-1075014e034d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>4d221edd-f325-4794-b60a-3230b54561a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>95f5582e-cf13-4423-a8bc-b8d28941205b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsThereASolidFuelBurnerOnThePremises&quot;)</value>
      <webElementGuid>778fd4b2-be27-4f66-9b3e-d3c0a4b0e476</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IsThereASolidFuelBurnerOnThePremises']</value>
      <webElementGuid>4730a7d7-4bc7-4084-a913-2a3f0ec020e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table[2]/tbody/tr/td[2]/div/form/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td/select</value>
      <webElementGuid>d5e9d0d3-737c-4899-aabc-de700c05e713</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to General Policy Information'])[1]/following::select[1]</value>
      <webElementGuid>2d079722-d55a-4d74-84c4-cf2cf5c6eb0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lead paint hazard exists.'])[1]/following::select[1]</value>
      <webElementGuid>6e4b2566-1126-4943-9fb5-19203fc1e1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describe Renovation:'])[1]/preceding::select[5]</value>
      <webElementGuid>75c89067-642c-4ab3-95f0-a8d6f8e24c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to General Policy Information'])[2]/preceding::select[11]</value>
      <webElementGuid>f67958a3-540f-424d-bf25-05853475abea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7236bc82-c156-4612-99b2-11768dbc3e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IsThereASolidFuelBurnerOnThePremises' and @name = 'IsThereASolidFuelBurnerOnThePremises' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>379752dc-3254-4126-ae56-b61ed65888c3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
