<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1</name>
   <tag></tag>
   <elementGuidId>09539859-7da6-4a6b-b0d5-e502e5ff5a83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PriorCarrierIsHMIC']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PriorCarrierIsHMIC</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9d2137f3-dcfe-4904-969d-231bca36a61e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f8f7dfa7-14d2-4de1-bc43-d1c094302d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PriorCarrierIsHMIC</value>
      <webElementGuid>33be29b9-ef12-4d02-8b10-3a8a72073994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PriorCarrierIsHMIC</value>
      <webElementGuid>98bbab06-7bc3-4511-b03d-97d4bfbd9e3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>4690403a-8c8e-49ea-bb17-8667051ea561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6ef48ba8-3641-401a-8f57-40cc07f4ec60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>82360e04-964d-4f35-a85f-7daab7aad76b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PriorCarrierIsHMIC&quot;)</value>
      <webElementGuid>203b9cee-01c6-48f1-b62a-5330d22cdc85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PriorCarrierIsHMIC']</value>
      <webElementGuid>f1ec7ccd-c377-4ab7-84c3-8731a33813ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>96d4a645-3209-48a6-834b-60d5ee2edfd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Prior Carrier Hastings Mutual?'])[1]/following::select[1]</value>
      <webElementGuid>3ca7f79f-fbd5-47c6-862f-c1e3d694937c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has there been continuous coverage for the past six months?'])[1]/following::select[2]</value>
      <webElementGuid>8b0c97f5-b744-42fd-81e7-1afaf3707b20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[1]/preceding::select[1]</value>
      <webElementGuid>819e435d-dc52-453e-95a9-81b084f3645d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years with Prior Carrier'])[1]/preceding::select[1]</value>
      <webElementGuid>6506134e-008c-46bd-9482-30f0f87f8990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>1928dffa-bac1-4d45-95f5-4e3d36523ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PriorCarrierIsHMIC' and @name = 'PriorCarrierIsHMIC' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>fdbdbc9e-8cdc-4b5d-b851-039fe403ea7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
