<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Less than 6 months  6 mont_8fd8ff</name>
   <tag></tag>
   <elementGuidId>dd8a8b6f-6d84-4fd4-b423-29ef1f99295b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NumberOfMonthsLossFree']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NumberOfMonthsLossFree</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3fe0ee6d-e002-4374-92f1-9514972ca0a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>992c0148-52f8-4f7c-ae45-1d9830da4cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberOfMonthsLossFree</value>
      <webElementGuid>165cbd52-f291-4182-9efb-05d38f01673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumberOfMonthsLossFree</value>
      <webElementGuid>c92dbfe1-46ca-4bb5-9cd1-fb5eceb97e01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>cabecae9-3359-4235-a98e-8d8a65df5148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>51bcd14d-fa08-481c-ab1f-779952fdc0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Less than 6 months  6 months  12 months  18 months  24 months  30 months  36 months  42 months  48 months  54 months  60 months </value>
      <webElementGuid>1fd2d22b-5c93-4253-8f58-c502692b5840</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberOfMonthsLossFree&quot;)</value>
      <webElementGuid>41202d6f-18fc-48d3-9d24-44b4554392ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NumberOfMonthsLossFree']</value>
      <webElementGuid>9b186490-e109-4da7-bd43-b92fdd8a23b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>545c776d-e12b-4bf8-a115-fe3b6893d912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss Free Discount'])[1]/following::select[1]</value>
      <webElementGuid>5fca8f0b-260f-4fa7-bc01-a1854e300d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Months Loss Free'])[1]/following::select[1]</value>
      <webElementGuid>6f1ce3f4-2b87-4cff-85b0-b45af32fc5e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Multi-Car Discount'])[1]/preceding::select[1]</value>
      <webElementGuid>aa0ade9a-ad3a-4651-ae98-c453f90de76c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[6]/preceding::select[1]</value>
      <webElementGuid>0c88e1e9-7d8e-4790-9989-142eb300a82d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>3727f64f-d285-4a4a-83ea-4010ac2bd4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NumberOfMonthsLossFree' and @name = 'NumberOfMonthsLossFree' and (text() = ' (select)  Less than 6 months  6 months  12 months  18 months  24 months  30 months  36 months  42 months  48 months  54 months  60 months ' or . = ' (select)  Less than 6 months  6 months  12 months  18 months  24 months  30 months  36 months  42 months  48 months  54 months  60 months ')]</value>
      <webElementGuid>b3232355-5a5f-4df2-995f-c55be6a8b8cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
