<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  0  1 Years  2 Years  3 Yea_ad0446</name>
   <tag></tag>
   <elementGuidId>8ddf4f21-7011-4ff5-a89e-782fdc6fcb67</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='YearsWithPriorCarrier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#YearsWithPriorCarrier</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c46b585e-ad97-4314-9be0-979b984ea132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>27f44489-3af7-4e2a-96c5-e65e38d0c15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YearsWithPriorCarrier</value>
      <webElementGuid>c4735f6c-2c1f-4ecc-a1c2-bac9ac3ebb91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>YearsWithPriorCarrier</value>
      <webElementGuid>52ef28f5-d891-4176-8ad9-d7a14533af6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>0332db1f-e12c-455e-8e4b-426943ed1080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>f1224b02-0431-4f95-9e82-5e51709174e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  0  1 Years  2 Years  3 Years  4 Years  5 Years  6 Years  7 Years  8 Years  9 Years  10 Years  11 Years  12 Years  13 Years  14 Years  15+ Years </value>
      <webElementGuid>7911e2ba-b20f-4171-8f81-47de5faf4863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YearsWithPriorCarrier&quot;)</value>
      <webElementGuid>1a556801-7f7c-41f7-9de0-7aee680fdcb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='YearsWithPriorCarrier']</value>
      <webElementGuid>8697f377-f514-49dd-96a4-ad2ed19d2dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr[4]/td[3]/table/tbody/tr/td/select</value>
      <webElementGuid>1c60e114-57bb-46c5-84b8-b49bbeebe9df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years with Prior Carrier'])[1]/following::select[1]</value>
      <webElementGuid>58aa8a55-a279-4779-8e20-7fd1dfe50457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Expiration Date'])[1]/following::select[1]</value>
      <webElementGuid>e4afcdb8-a4da-45a6-993c-5f1fe9d088a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is Applicant returning military?'])[1]/preceding::select[1]</value>
      <webElementGuid>78fa4429-fc05-4119-bdb4-234639365439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Credits'])[1]/preceding::select[2]</value>
      <webElementGuid>85e4b9eb-9c8b-4c94-a249-31094ac55c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/select</value>
      <webElementGuid>a736d3ef-a0ce-41cd-9356-63be83fb0516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'YearsWithPriorCarrier' and @name = 'YearsWithPriorCarrier' and (text() = ' (select)  0  1 Years  2 Years  3 Years  4 Years  5 Years  6 Years  7 Years  8 Years  9 Years  10 Years  11 Years  12 Years  13 Years  14 Years  15+ Years ' or . = ' (select)  0  1 Years  2 Years  3 Years  4 Years  5 Years  6 Years  7 Years  8 Years  9 Years  10 Years  11 Years  12 Years  13 Years  14 Years  15+ Years ')]</value>
      <webElementGuid>3a8d4234-451c-4f5d-8532-fc054490725b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
