<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_Lastname</name>
   <tag></tag>
   <elementGuidId>d25f78d3-6e73-47ed-80fb-2dcde2777c6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Lastname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Lastname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dfa90c57-84b1-4df3-b8a9-ea22e5a26456</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>AddApplicant</value>
      <webElementGuid>392643bd-0f23-4004-aaa6-305faba8ca8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>help</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>cdbe0a0a-8e76-4307-94ca-3c78109260de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>d129b7d7-23dc-4aa0-958e-b43ed2e91db2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Lastname</value>
      <webElementGuid>01493567-153e-469c-8f51-93e511de4459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-text-focus hmi-ui-state-dirty</value>
      <webElementGuid>7bbb769f-870e-4780-bff4-3a50e4b651aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>e04467e8-3ff4-4460-a3a3-51c4ba99de0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>776eb8f7-6435-4d17-9142-e74b39b0b27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>668dc4bd-c975-4b79-877c-cb6d668a4c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Lastname&quot;)</value>
      <webElementGuid>6785218b-66e0-4ffc-bd46-00c48ad8cc98</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Lastname']</value>
      <webElementGuid>01258c0d-a060-4c40-b2d4-efd3a340df38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-applicant-Add']/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>2c32f3c3-a0aa-4642-886a-d3701294934b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>89b53e4e-372c-4305-8043-627997b2e26e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Lastname' and @name = 'Lastname' and @type = 'text']</value>
      <webElementGuid>5ca8641b-4974-4298-aa6a-b56e839f8999</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
