<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_Firstname</name>
   <tag></tag>
   <elementGuidId>3206903c-74b1-44b4-9b4e-537b517df4de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Firstname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcd28322-d945-45c5-a115-748e12c9bc0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>AddApplicant</value>
      <webElementGuid>8dabded8-594f-454c-aa9b-b983c3da13e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>help</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>92730d9a-bf56-4766-b162-6ff8a6df27cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Firstname</value>
      <webElementGuid>662ab3dc-ef0f-495c-9808-318b98af61a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Firstname</value>
      <webElementGuid>d816cb2b-8f78-4f4c-9aca-642e8b415797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text</value>
      <webElementGuid>cdc86076-57de-4b7f-9cd6-81cc3279f498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9580be87-49ce-45c1-96d1-bad1eca7e025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c6748e5e-cc47-4641-a22a-f4ba4a0adc32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4d88c5ba-c1f8-4698-8c0f-33d316d2d62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Firstname&quot;)</value>
      <webElementGuid>33647e8b-ca7b-449b-bc25-6099524329b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Firstname']</value>
      <webElementGuid>3b701ccd-a1e6-4f2b-ad61-024d55665732</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-applicant-Add']/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>39074176-563e-4a25-b374-0c5b1db2547b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>d261ebe3-1255-4a64-b97c-b1b5d9505faf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Firstname' and @name = 'Firstname' and @type = 'text']</value>
      <webElementGuid>0e617314-e6d8-44a5-9b2a-172aa4f6f4df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
