<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue to Locations</name>
   <tag></tag>
   <elementGuidId>3bd29e64-b704-415d-94e7-ff5a65ce8d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next-button > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next-button']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8c3c8d06-909e-416c-965f-dceb0239566d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>daab6b60-51bf-49b9-a463-2ac096e4fadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to Locations</value>
      <webElementGuid>d0015569-73a6-49ce-9a94-01ed59b71b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next-button&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>bba3e876-74e1-42e2-86c9-5bd277bfd2fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='next-button']/span[2]</value>
      <webElementGuid>ae6fcca2-dd01-415e-845e-4658042e3990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Go back to general policy information'])[1]/following::span[2]</value>
      <webElementGuid>3d0a0ff3-37e5-4345-b7a3-29af4a849dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Applicant'])[1]/following::span[4]</value>
      <webElementGuid>1e74ec8c-d2f5-40ac-acd6-6d6503054694</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue to Locations']/parent::*</value>
      <webElementGuid>85f693a1-2c09-4df7-95b5-be3aa8a2255a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/button/span[2]</value>
      <webElementGuid>0bf91f5a-3d98-434f-a52f-eee63ab62b3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continue to Locations' or . = 'Continue to Locations')]</value>
      <webElementGuid>84887b1d-6261-4fc8-b9f1-8b6aed9a6036</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
