<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7</name>
   <tag></tag>
   <elementGuidId>d4d18d56-aafa-4411-a7e8-e4a4d8fb7310</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Question8']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Question8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>77056243-b8cc-42ba-99b0-94a4d64959ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>bc5285ca-393c-44f3-b7bc-fb9038d7e2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Question8</value>
      <webElementGuid>4441cf38-6c4e-45c2-8b44-fe3ee5eacadd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Question8</value>
      <webElementGuid>52ce2b88-c807-4f25-8a88-7d933171f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>showclass</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>7583e7a8-f6cc-450d-b116-1f005e06d55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>85677c59-a868-4995-ae65-a75e64baaa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>fe316867-0055-481a-8a53-71ae29d6b7a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>81f046ed-d0d4-4218-b045-fcb2a25c51fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Question8&quot;)</value>
      <webElementGuid>b4f178ef-8dc6-441c-8363-f5e4fa8aa30c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Question8']</value>
      <webElementGuid>86c444d7-583d-4278-9b1d-7ccd6f63a503</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[10]/td/table/tbody/tr/td/select</value>
      <webElementGuid>65283d2a-5f3b-4ec4-9a93-898f574743b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you intending to quote an ATV, dirt bike, golf cart, motorcycle, RV or snowmobile?'])[1]/following::select[1]</value>
      <webElementGuid>ff6744ef-2f8a-4738-9135-96bf9011641a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does at least one vehicle have liability coverage?'])[1]/following::select[3]</value>
      <webElementGuid>c119e3b1-6b7d-4527-a653-189f2ea02a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does any vehicle have a salvage title?'])[1]/preceding::select[2]</value>
      <webElementGuid>1cb8ac6a-7118-4ba2-b287-841371653ec7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are the only vehicles listed on the policy a recreational or utility trailer?'])[1]/preceding::select[5]</value>
      <webElementGuid>c7206d47-6248-430a-ad85-5088239e5ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/table/tbody/tr/td/select</value>
      <webElementGuid>6f73a029-2cb6-4766-be68-01c4da9f75c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Question8' and @name = 'Question8' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>681a30c4-4bd0-4497-9fb7-1effc12f7abb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
