<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Drivers License Number_b574e8ed42d099_b70ce2</name>
   <tag></tag>
   <elementGuidId>012f4950-d8a3-4a13-a67d-a0f9caaaa32d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#b574e8ed42d09930f07788acbd63_LicenseNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'LicenseNumber')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c703152-8922-43a1-8ad9-51486751a41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b4c10e6b-43ee-4f27-aa37-fe04a16bc296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>b574e8ed42d09930f07788acbd63_LicenseNumber</value>
      <webElementGuid>966f1fa8-8baa-4d8b-83fd-a8f825555db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>b574e8ed42d09930f07788acbd63_LicenseNumber</value>
      <webElementGuid>d29e47ad-0205-4978-b119-d4fe1f5ef135</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>0e5112d0-6864-4f82-9c80-6789f3c1a05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>e96d6447-e464-495f-82bb-538d059b0093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z]+$</value>
      <webElementGuid>b5265c27-91a3-4653-8ac5-aac91b4d792f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>e00b1cfe-1c1b-4fb9-8d98-5216d76a6422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>cccbaa03-a24e-4dff-9c26-18f069438a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>45d0f4ac-ba63-446f-b54e-6280e92b9212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b574e8ed42d09930f07788acbd63_LicenseNumber&quot;)</value>
      <webElementGuid>868f4098-0d49-4462-a11c-b431bff82cf4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='b574e8ed42d09930f07788acbd63_LicenseNumber']</value>
      <webElementGuid>a697c138-0426-42bb-a213-cd3c41019b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='operator-list']/table/tbody/tr[4]/td/table/tbody/tr/td/input</value>
      <webElementGuid>485e346b-dc75-4016-b19b-62182c66153c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/table/tbody/tr/td/input</value>
      <webElementGuid>ab62eebe-af42-4b89-a0fa-c888a1d675d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'b574e8ed42d09930f07788acbd63_LicenseNumber' and @name = 'b574e8ed42d09930f07788acbd63_LicenseNumber' and @type = 'text']</value>
      <webElementGuid>3f6f25b2-d41a-4974-95b3-f674cb6fdea2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
