<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Amount of Insurance</name>
   <tag></tag>
   <elementGuidId>9ba1775a-bd19-4b69-bb53-e0feae2c3289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'EquipmentItem_AmountOfInsurance')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>093101fc-48c5-487e-9fe0-87c8ae461cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ba1c3f6b-b670-45c2-98ae-80ed24b6d0a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance</value>
      <webElementGuid>86d703e5-be6f-4749-bf01-dc13c3bf2f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance</value>
      <webElementGuid>89b053f9-c9ce-4c42-b18e-1acf553397ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>equipment-item-amount hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>2a938b9c-5bee-4521-a0ab-1aea676712cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>54dabc37-386f-4322-92af-1db6598b7d1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>3d6e0c06-1ad8-4d56-9376-dc4494034f55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>24374401-bb20-433f-ad5c-a8708342e955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f290ac8-4f2e-4cd6-8c0c-4d814bb7c337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance&quot;)</value>
      <webElementGuid>82cc5963-9160-48c9-8317-3f75ae689088</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance']</value>
      <webElementGuid>f64dfcb4-5607-46a0-9563-81a712095e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ContractorsEquipment_0']/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>411e51e3-c615-435f-baf2-5a77b99bb7c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>edb1ef53-63b4-4e18-97f5-fc8d4e5f9e06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance' and @name = 'cc35336732b24b7696c24027238e69cd_EquipmentItem_AmountOfInsurance' and @alt = 'limit' and @type = 'text']</value>
      <webElementGuid>07e80b4c-254e-4eaa-b037-bf6246dcd785</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
