<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>eb027ca9-8e0f-4ba8-b4cc-a2b0cf59bc01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EquipmentRented_Answer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EquipmentRented_Answer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb5733c8-cf76-4a46-87d6-0e348201994a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>db71622c-d31a-412f-a7e6-1944bd71688c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EquipmentRented_Answer</value>
      <webElementGuid>4e62f466-8be5-4d06-9ba5-6fa148aecff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EquipmentRented_Answer</value>
      <webElementGuid>39638451-df9a-4bca-9599-9f312245c464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>98adaa70-d7f1-47b1-8c6a-84efca908c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>69d0f46c-f997-42bb-8c51-fd4d25dd3e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>7ef5e9d5-a876-4189-8aae-6edf913c5453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EquipmentRented_Answer&quot;)</value>
      <webElementGuid>f24e64a5-b7ca-47ba-aad8-e415cd7dca87</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EquipmentRented_Answer']</value>
      <webElementGuid>e1aee957-af10-4bfe-bae4-2ca347c33975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>398fbfa0-b0b7-4dea-a3bc-d7ae1d0271c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Questions'])[1]/following::select[1]</value>
      <webElementGuid>811be9c3-9535-4dc6-ad68-344687bbc49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$0'])[1]/following::select[1]</value>
      <webElementGuid>cc163f15-db86-485c-baa7-f96d2bc3f7ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Equipment rented, loaned to/from others with/without operators?'])[1]/preceding::select[1]</value>
      <webElementGuid>c9593397-2362-44bb-9239-ce6832bc3fd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/preceding::select[1]</value>
      <webElementGuid>b68025d8-0084-4981-ab40-20d6544e0ffa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>86f8e6d1-c83a-47e3-8d95-f1190b1f9810</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EquipmentRented_Answer' and @name = 'EquipmentRented_Answer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>d714296b-9609-473a-9b49-a11676ff6dd8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
