<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Logout</name>
   <tag></tag>
   <elementGuidId>fc016c34-3387-475b-803f-6fab970d9240</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Logout&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='actiongroup']/ul/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55ec477c-22d4-4a38-b65f-d6479988109f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>d279c53e-844f-4770-b5f7-3aa0c9b80b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://policyexpress-qa.hastingsmutual.com/Services/GlobalLogout</value>
      <webElementGuid>9047eede-851c-4764-a2b0-27e067526f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dcref</name>
      <type>Main</type>
      <value>/DuckCreek?targetPage=logout</value>
      <webElementGuid>4b6eb821-9ee5-475a-9d9e-a7ec7095c530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Logout</value>
      <webElementGuid>e7bec31c-86e3-4621-985a-ce154ca2b7ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;actiongroup&quot;)/ul[1]/li[2]/a[1]</value>
      <webElementGuid>b51f0018-058c-4eb4-ba27-1c789b17937b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='actiongroup']/ul/li[2]/a</value>
      <webElementGuid>04792b03-1aa9-431f-bf0a-1bec824ddd7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Logout')]</value>
      <webElementGuid>81b1c302-9e62-45d0-bc15-8b1cc778f648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::a[1]</value>
      <webElementGuid>c95384ec-b15e-471f-858e-2512e7c0d29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Agency'])[1]/preceding::a[3]</value>
      <webElementGuid>933e1c4a-fbb5-46af-8e4b-5649c80397aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote Name'])[1]/preceding::a[3]</value>
      <webElementGuid>4bb34062-1173-4c2e-b355-9de8913c1cf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Logout']/parent::*</value>
      <webElementGuid>ad48ee0d-b86c-405e-8b2c-d2b087079d61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://policyexpress-qa.hastingsmutual.com/Services/GlobalLogout')]</value>
      <webElementGuid>5aff1e1a-33f1-4a9a-9faa-0f424c077835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>063cb064-6025-4cbd-893f-0f002e0ea585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Logout' and @href = 'https://policyexpress-qa.hastingsmutual.com/Services/GlobalLogout' and (text() = 'Logout' or . = 'Logout')]</value>
      <webElementGuid>e6a203be-3ef0-4fa7-934d-d15461fa2a15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
