<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Effective Date_ui-datepicker-trigger</name>
   <tag></tag>
   <elementGuidId>a6d25315-a584-48c1-baeb-435099a38f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.ui-datepicker-trigger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div/div/table/tbody/tr/td[3]/table/tbody/tr/td/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fcbe926c-c0f0-41a3-8d88-3418eb280caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-datepicker-trigger</value>
      <webElementGuid>e58827b8-cc68-4104-9386-a465e6a99e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Content/Images/cal.gif</value>
      <webElementGuid>6eb6211b-1fc1-4c91-9237-14125ef44fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>d06a985f-ae73-4034-b1e7-bc1ba9a252e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>...</value>
      <webElementGuid>e3d2fc7d-b1d3-41ec-bf25-ce9b9c4fd74a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmi-layout-mainContent&quot;)/div[1]/div[@class=&quot;ui-tabs ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;hmi-layout-column-container ui-helper-clearfix&quot;]/div[2]/div[@class=&quot;ui-widget-content&quot;]/div[1]/form[1]/div[1]/div[@class=&quot;hmi-layout-wrap&quot;]/div[@class=&quot;list-container&quot;]/table[@class=&quot;hmi-table hmi-label-left&quot;]/tbody[1]/tr[1]/td[@class=&quot;ui-state-default ui-state-hover&quot;]/table[@class=&quot;vTbl&quot;]/tbody[1]/tr[1]/td[1]/img[@class=&quot;ui-datepicker-trigger&quot;]</value>
      <webElementGuid>bf92f6a9-225e-4509-ac62-0e9bc465686c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div/div/table/tbody/tr/td[3]/table/tbody/tr/td/img</value>
      <webElementGuid>ecb9d0ec-4a96-4dea-9443-4f001638c115</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='...']</value>
      <webElementGuid>05964e3d-1eb1-4924-99f2-53cc29d772ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/img</value>
      <webElementGuid>265f8db5-3e26-4183-b621-eeefa651d210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/Content/Images/cal.gif' and @alt = '...' and @title = '...']</value>
      <webElementGuid>c9d7d893-71cf-4570-a958-9d5b04af2292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
