<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Professional Liability (EO)_VendorsLi_ca24f6</name>
   <tag></tag>
   <elementGuidId>93c86310-9070-4120-9a29-a98becaf019b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VendorsLiabilityCoverage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VendorsLiabilityCoverage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>baca3a02-90c5-4966-8b65-c8ea7e980c5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>76ffa7d1-190f-4165-9097-abd87f8b6820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>820c2b63-3b9b-49cf-a5e0-f6085db78659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VendorsLiabilityCoverage</value>
      <webElementGuid>37a975ac-71e7-4619-9d14-42c89bf22509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VendorsLiabilityCoverage</value>
      <webElementGuid>43c34288-77ef-4c08-a89f-dcd679591ae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-for-coveragesExposures hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>538c492c-dbb4-4928-9665-4a59322fcc86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>7507e5c3-af5e-46ea-a4e3-7a66f24d9c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>6cb89b47-e5e4-4cc4-99e7-c7c8b34254b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VendorsLiabilityCoverage&quot;)</value>
      <webElementGuid>d1b4051a-b5d7-456c-87b0-668b022f97bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VendorsLiabilityCoverage']</value>
      <webElementGuid>71dc2556-9605-4474-b60b-8fabe4c84b58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[6]/div/table/tbody/tr/td[3]/table/tbody/tr[6]/td/input</value>
      <webElementGuid>a5375530-4765-4e47-8377-6c43d9caa95f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[6]/td/input</value>
      <webElementGuid>2126f29b-6218-4a21-9a8d-af0772ee7746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'VendorsLiabilityCoverage' and @name = 'VendorsLiabilityCoverage' and @type = 'checkbox']</value>
      <webElementGuid>c15c3c2b-2510-4090-b507-24e1a3556a90</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
