<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_EffectiveDateACVabdbc3_a738bb</name>
   <tag></tag>
   <elementGuidId>7c22fd34-b1a3-464e-90b1-f5f57b5d58f7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2672c585-1fb7-4197-b089-fbb0d59ec1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d62248a1-e077-48d6-bbe2-ba54e3656c9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8</value>
      <webElementGuid>31914daa-5ac6-4d56-aef6-00d9cc0f7089</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8</value>
      <webElementGuid>f91f765f-f6ec-45f8-a8d3-f29633983716</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9/]</value>
      <webElementGuid>e8877848-e6de-4d84-9318-b6401c0b9289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DisplayCalendar hmi-ui hmi-ui-text hmi-ui-editor hasDatepicker hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>89cd553c-35f8-42d4-8497-233188500672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>0228f228-a19e-4d75-9576-ad26e47d4e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>a0e4b4c2-1ad6-4454-bd6d-92f505d35fdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f118e37d-868f-4529-88be-410ccf5538b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f00f25f-3cf3-4679-93da-315382c2646c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8&quot;)</value>
      <webElementGuid>d3b850db-f760-4598-b2a8-73cd9eb11957</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8']</value>
      <webElementGuid>d670f4ae-eb25-43fc-9021-2f03fdfd805a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>fe78a88a-3d42-4b4d-9c2f-415e2776f9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>61812b47-b869-4503-9e22-53175655df88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8' and @name = 'EffectiveDateACVabdbc3b010e74f2aa81eb34bdc8e27b8' and @type = 'text']</value>
      <webElementGuid>8fc1d49d-859b-4141-b4ad-54483c57c142</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
