<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LimitMedicalExpensesGL</name>
   <tag></tag>
   <elementGuidId>258e0c9c-d78e-438d-889b-a5c41e79a283</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'LimitMedicalExpensesGL')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ac59da8-e379-498c-9dfa-d01f6ad0d49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f2451518-c210-4c69-9fcc-178df2e2063d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>0bf9503e-4e58-4ab5-95ee-93107185774a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>af3a5223-d3ca-4c3a-8d7c-24e2e4473a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bd501942-5eff-48eb-a064-fd7e3c805e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit8</value>
      <webElementGuid>1009db9b-dbf0-4589-97d8-269638312959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>657d361d-19db-4c0f-98ee-53cad841a266</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>41b28b47-3709-431e-a6b0-af58e9fecf04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4443ae4e-e1e7-4904-8b19-3484a9867bb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5&quot;)</value>
      <webElementGuid>f022af1a-39c6-47e8-88dc-233b4192fa0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5']</value>
      <webElementGuid>fc8ece22-7bb4-4ed0-961a-a2431ddeeaa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>dd7646c7-ecbd-49ae-a994-93976ef58ae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>139e82ff-468c-4be0-89ff-653a7a3c574a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5' and @name = 'LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5' and @alt = 'limit8' and @type = 'text']</value>
      <webElementGuid>d12e2268-423c-4610-96d1-b4468458224b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
