<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_ExpirationDateGLab009_c26035</name>
   <tag></tag>
   <elementGuidId>5548588c-c93f-409f-9173-238a8cbddd29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ExpirationDateGLab0099d05064836b464d0053b8c53a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d473b132-1bbc-4038-8f66-997294d93d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b3da692e-8038-4e26-9009-4e34b2488f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExpirationDateGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>d229ab4b-1ce2-4d46-8636-425304ab40ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExpirationDateGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>2b37c0cc-5eaf-4ee4-927e-b86a53300996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9/]</value>
      <webElementGuid>71736003-1703-46e4-8087-9e4152cebae8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DisplayCalendar hmi-ui hmi-ui-text hmi-ui-editor hasDatepicker hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>3a1d2b7c-e525-4bf5-8deb-cbc556e9711a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>adbcdf4b-3c58-44b2-a3a0-47cc40ed8d35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>30c5b5c4-2d49-4a70-961b-de76331c4b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>9612dc62-39f1-408e-8b9f-91b24cac86c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a2ed5e11-7d31-4ece-9f55-30b1d965c5c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpirationDateGLab0099d05064836b464d0053b8c53a5&quot;)</value>
      <webElementGuid>43188948-0f6a-4fc7-bb65-df5f18a0329c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExpirationDateGLab0099d05064836b464d0053b8c53a5']</value>
      <webElementGuid>259d9c59-3cd0-40a3-9ed8-2fcb9f5be092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>1ef215d3-83ce-4e1a-b3c0-be4570890fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>e5e6f457-3761-43ce-8292-4a6f2b32b19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ExpirationDateGLab0099d05064836b464d0053b8c53a5' and @name = 'ExpirationDateGLab0099d05064836b464d0053b8c53a5' and @type = 'text']</value>
      <webElementGuid>34ea3190-e343-482d-89eb-77d909f47b8e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
