<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Expiration Date_ExpirationDateBOPeb6a_07d621</name>
   <tag></tag>
   <elementGuidId>fae6b4a4-d3d6-419c-ba5f-90961d6bba5b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[4]/div/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ExpirationDateBOPeb6a269232ae4485a41489434a1e273c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0e4c5f8a-8b01-4a34-8774-45be49851048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>6eef3a6a-e76f-4398-ab61-928c12600f5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExpirationDateBOPeb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>5450e162-a2df-4e28-a862-113448cf4f3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExpirationDateBOPeb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>b57eb7f7-aff3-40ce-bdd2-5df6c518d0fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9/]</value>
      <webElementGuid>0e33dd13-45b1-435c-b3b7-a64ee8d3faa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DisplayCalendar hmi-ui hmi-ui-text hmi-ui-editor hasDatepicker hmi-ui-text-highlight</value>
      <webElementGuid>dc6ce0df-3c62-41a8-b3b7-6f5f7962932f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>e3072297-2758-4dce-8477-70c8a5af6b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>31512ecb-65a6-4456-baee-33965e35bedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>afabe703-f373-4920-9f40-583d43fcbaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>be825a25-bdd2-40cc-8a79-2d6f80d5ccc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExpirationDateBOPeb6a269232ae4485a41489434a1e273c&quot;)</value>
      <webElementGuid>993dde3d-ee89-4d95-8dcf-d5dc331eca18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ExpirationDateBOPeb6a269232ae4485a41489434a1e273c']</value>
      <webElementGuid>498914aa-ac79-4780-adc3-4a9b4d63bfb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[4]/div/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>4770a4cb-588b-45cb-8939-a4a98b9353c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>56f121fb-ae68-4895-a803-de34fed4c8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ExpirationDateBOPeb6a269232ae4485a41489434a1e273c' and @name = 'ExpirationDateBOPeb6a269232ae4485a41489434a1e273c' and @type = 'text']</value>
      <webElementGuid>bfdc48ee-0c11-457b-94d3-8b3ce35eb2bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
