<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_EffectiveDateGLab0099d_f79da3</name>
   <tag></tag>
   <elementGuidId>275bca4c-ec43-45a2-ba20-524284ad622f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EffectiveDateGLab0099d05064836b464d0053b8c53a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5db82994-3aac-4def-b257-77ec034a48c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e262d0a7-b7cf-4d47-882d-9096821861ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EffectiveDateGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>afbcd4ea-e0de-4480-8deb-c53a4c6d5722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EffectiveDateGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>80002b0b-91e0-43b1-b173-ae315741b169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9/]</value>
      <webElementGuid>3d38f516-7401-4877-b38d-4ffc86c47a85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DisplayCalendar hmi-ui hmi-ui-text hmi-ui-editor hasDatepicker hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>ffa24fa2-77f2-4891-9152-fada36a2bb36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>2fa3e5aa-5cda-4b89-b7bf-9787217a3f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f1e8e11f-b1f5-4be0-a5ca-147fc80124cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>f5843a57-9ed9-4157-bf48-b703430e8f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>99e3f08d-37c4-42dc-a3fa-1d9efc92ccbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EffectiveDateGLab0099d05064836b464d0053b8c53a5&quot;)</value>
      <webElementGuid>9224b517-0abf-462e-97c0-f309f83a7a00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EffectiveDateGLab0099d05064836b464d0053b8c53a5']</value>
      <webElementGuid>f164d33c-a1df-470a-b560-4bae7b2ec386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>caed4a46-f693-403a-ac63-2d54ecee9767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>8cbe5a6b-447a-4319-b314-0352525f08c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EffectiveDateGLab0099d05064836b464d0053b8c53a5' and @name = 'EffectiveDateGLab0099d05064836b464d0053b8c53a5' and @type = 'text']</value>
      <webElementGuid>a420b6f9-943b-4aab-a203-b28eea17d63f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
