<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Liquor Liability_PollutionLiabilityCoverage</name>
   <tag></tag>
   <elementGuidId>f1273b59-ab89-40e6-afcb-0f2c2346ce76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PollutionLiabilityCoverage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PollutionLiabilityCoverage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ef982bcd-8585-40d0-b921-b6ca65280170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>81dcb965-f461-43bf-a00e-0528e85a6f6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>d65da682-55bb-4ff9-b57f-9c5fcfccac9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PollutionLiabilityCoverage</value>
      <webElementGuid>9470fcda-4efb-43b4-9d0b-79c90eed3eaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PollutionLiabilityCoverage</value>
      <webElementGuid>beaec858-0c1f-4117-9cfa-b8bcda686289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-for-coveragesExposures hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>46670807-d3bb-4cb1-9f31-7f080c918f9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>49</value>
      <webElementGuid>20c8de48-5bd9-4873-9cca-22ae294dd0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2da18ef0-7d56-4cf4-825c-370dd2162b03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PollutionLiabilityCoverage&quot;)</value>
      <webElementGuid>c3c1238f-9905-4070-91fa-3039f4f905ef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PollutionLiabilityCoverage']</value>
      <webElementGuid>ebf5ba2d-ecd6-474c-8bdd-4ee1c35d95ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[6]/div/table/tbody/tr/td[3]/table/tbody/tr[4]/td/input</value>
      <webElementGuid>153bf647-f0ff-4a58-967a-5c676c8d7c73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[4]/td/input</value>
      <webElementGuid>9c907c70-e6b6-412e-a8c4-c9bfeba7fae5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PollutionLiabilityCoverage' and @name = 'PollutionLiabilityCoverage' and @type = 'checkbox']</value>
      <webElementGuid>9dd8f01d-9b25-488e-aae9-94e218547c70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
