<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Explanation_PreviousExperienceClaimsE_9275a9</name>
   <tag></tag>
   <elementGuidId>12a4630e-f3bb-4d89-8c3b-78967847bd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PreviousExperienceClaimsExplanation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PreviousExperienceClaimsExplanation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9725fdf-937e-413e-b990-6d0bd6a4a2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>0f5e3d08-200d-45ed-bc46-064140094b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PreviousExperienceClaimsExplanation</value>
      <webElementGuid>9f04d173-9338-4973-a7e6-5bb2afb7ce3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PreviousExperienceClaimsExplanation</value>
      <webElementGuid>74ddbcf2-4572-49d2-be14-0a4aa694fb5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>85</value>
      <webElementGuid>61528ee5-14b2-4fc9-806d-5bd226ed5da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight</value>
      <webElementGuid>8b01908a-b225-42fe-a065-98ea489584d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>8c845cdf-ccf2-43f1-9a63-b15c73c3142f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>76e5b0a9-e02a-4b6a-9855-c5ff1cc0af31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PreviousExperienceClaimsExplanation&quot;)</value>
      <webElementGuid>35350bdc-4776-44c5-8f55-442abfb48ec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PreviousExperienceClaimsExplanation']</value>
      <webElementGuid>b64f03a3-04b9-41d1-9a33-1c4989aaecbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[7]/div/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>aa7d3d21-d322-4bf5-a984-7a4f064e6ed1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>99bac760-01bf-4764-bca1-4345d4a8f4b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PreviousExperienceClaimsExplanation' and @name = 'PreviousExperienceClaimsExplanation' and @type = 'text']</value>
      <webElementGuid>7f080f9f-4cb0-4143-9d87-b2a23371fd8f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
