<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Personal  Adv Injury_LimitPersAdvInju_b54a48</name>
   <tag></tag>
   <elementGuidId>f77ad71a-bff2-438a-8aaa-31151b426177</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>85c2422d-2a45-43c1-9477-80c2d2f975f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f83b2272-ca00-4aa5-bf20-7e494a99d280</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>24a2093d-06e2-4afe-b1c1-2c5daaecff0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>0654f3a5-2e4a-498c-96e5-2b12109bca69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6557e352-027b-4e71-8c31-34990182c10a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit8</value>
      <webElementGuid>169ba33b-ae6e-4347-bce0-1bed1d72a8b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>56215ecf-ea9f-4784-a6ee-4faee2c3782a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>541683e6-74f5-4254-9b84-b1a5fae30361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b4dfcc9f-8a1d-4caf-a284-6140025d27da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5&quot;)</value>
      <webElementGuid>faa77582-8084-420e-9998-b89575eb0b21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5']</value>
      <webElementGuid>fb4fed1f-3452-45ef-ad5c-2d7f4f61be61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>a1afc412-a3d2-40a7-8cdc-412b1e7f5c6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>3ce1b6db-d2c3-44ea-a9e4-889101373e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5' and @name = 'LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5' and @alt = 'limit8' and @type = 'text']</value>
      <webElementGuid>7e0ad195-317b-41e4-b47d-1df0df2a3d5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
