<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Effective Date_EffectiveDateBOPeb6a26_662ccf</name>
   <tag></tag>
   <elementGuidId>0eb6b20a-05b5-4a8f-bb48-d47567e7bd78</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[4]/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EffectiveDateBOPeb6a269232ae4485a41489434a1e273c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d9aee55f-c82b-4550-a44d-e5c1f4d66924</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>bdddd033-1bae-48a6-b141-f0f6349d0530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EffectiveDateBOPeb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>3301c081-a6fa-4ca8-a724-e77a8a089fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EffectiveDateBOPeb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>acfc8496-1563-4ce5-ac38-c3132f631382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9/]</value>
      <webElementGuid>b3205bc8-298a-4849-a43e-70b2dc23f628</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>DisplayCalendar hmi-ui hmi-ui-text hmi-ui-editor hasDatepicker hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>9f78bb12-e65c-4d30-8d12-1fdb33953bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>ffa734f5-0faa-4449-b0b1-e1ad345d03be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>66a7237e-fd8b-45d3-aeed-2e23bd3f1bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>3c65b21c-3c08-4ef1-9a03-967c20ae5de9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>14c0ba4b-bbbe-4b58-aa7c-3ce951e0721e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EffectiveDateBOPeb6a269232ae4485a41489434a1e273c&quot;)</value>
      <webElementGuid>282fc83f-26c2-4b94-99a2-23bdc223f941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EffectiveDateBOPeb6a269232ae4485a41489434a1e273c']</value>
      <webElementGuid>f2aecf91-20b3-4e12-9d20-0c7450c19747</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[4]/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>8edb46b6-60bb-4038-a005-cef3ca397591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>85b7f97e-e6db-4fda-b86d-0d0d2fc0c199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EffectiveDateBOPeb6a269232ae4485a41489434a1e273c' and @name = 'EffectiveDateBOPeb6a269232ae4485a41489434a1e273c' and @type = 'text']</value>
      <webElementGuid>05089ade-4c17-46e5-81dc-b4bab9547980</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
