<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LimitDamageRentedPremisesGL</name>
   <tag></tag>
   <elementGuidId>ab5ca5fb-71ce-4beb-9c0f-c678c67cb504</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'LimitDamageRentedPremisesGL')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>262d0d46-486b-4397-b30f-41a4242f864a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cb05a4fc-5359-43f6-997f-3caf4fb5a36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>728a8cba-3a81-4a7b-ab1c-1b13f9863c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>4a0c1202-61b2-4702-b556-7dd5110c838b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1539ec29-d7c7-4f5e-86b0-e18d5dba635a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit8</value>
      <webElementGuid>2885d5ef-f14f-4a27-98b0-77c87df0df11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>84c788fb-f14c-43cf-ac31-ec5cdf35716e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>11f18ef2-1f1c-4327-aaeb-ca47ccd6fb3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a23bc0a6-0b8f-46ae-a8a0-3b922811f454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5&quot;)</value>
      <webElementGuid>e24c4ae6-d364-405d-9d47-6ff7b4a0d4b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5']</value>
      <webElementGuid>724d28e5-586b-4e33-8509-105971c5c9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[2]/div/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>963ebe3f-2321-4c00-8dd3-ce4d84c442ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>63f8b369-7dd6-4191-a199-4fab9920f822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5' and @name = 'LimitPersAdvInjuryGLab0099d05064836b464d0053b8c53a5' and @alt = 'limit8' and @type = 'text']</value>
      <webElementGuid>a2597701-3857-4604-b5d0-53209a843f26</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
