<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Incidental Medical Malpractice_Liquor_316892</name>
   <tag></tag>
   <elementGuidId>67a40492-f0e4-41c9-ab2a-981a8af1feac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LiquorLiabilityCoverage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='LiquorLiabilityCoverage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c868f53b-e8d3-4418-b3fd-63980f4da5da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>74647d0a-8c36-4979-a7f4-a6ce55508593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>a9ee0802-32fc-4583-9765-119b1181042f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LiquorLiabilityCoverage</value>
      <webElementGuid>4c55b24e-ef5b-478c-b96a-f83cebd1687f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LiquorLiabilityCoverage</value>
      <webElementGuid>06893cfa-b3dc-49be-a97d-3c5cb8372db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-for-coveragesExposures hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>525a82f2-2ba3-425f-ad4c-5aebbed2dbf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>59a6bcc2-1d14-4957-9484-5061c507035a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>b2280cef-03b4-43d7-804f-38b96798aa49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LiquorLiabilityCoverage&quot;)</value>
      <webElementGuid>7cb5b88f-241e-44b0-9cee-7e8cb0de5483</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='LiquorLiabilityCoverage']</value>
      <webElementGuid>4d2b861e-89c0-414d-8c00-dcf93d90d21a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/div[6]/div/table/tbody/tr/td[3]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>8009c83e-66df-42d5-992e-826b35953a31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[3]/td/input</value>
      <webElementGuid>41227d7d-bcd4-457e-b945-43f4e3f8116a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'LiquorLiabilityCoverage' and @name = 'LiquorLiabilityCoverage' and @type = 'checkbox']</value>
      <webElementGuid>78b717c4-abbc-4bc3-af4e-dae37c1fe009</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
