<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Applicant InformationGeneral Informatio_9d1673</name>
   <tag></tag>
   <elementGuidId>60e5664e-9c18-4016-b678-fa623ec291c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.hmi-layout-column-container.ui-helper-clearfix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b0011fd3-a62c-4c62-91d6-1600516b5750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-layout-column-container ui-helper-clearfix</value>
      <webElementGuid>754bf443-ffc8-4e32-928f-ec356235f7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Applicant InformationGeneral InformationPrior CarrierLoss History404 E Woodlawn Ave- Building 1Liability General InformationContractors General InformationProducts/Completed OperationsAdditional InterestApplication Finished Liability General Information (select)  Yes  No  Any medical facilities provided or medical professionals employed or contracted?     Explain (select)  Yes  No  Any exposure to radioactive/nuclear materials?     Explain (select)  Yes  No  Do/have past, present or discontinued operations involve(d) storing, treating, discharging, applying, disposing, or transporting of hazardous material? (e.g. landfills, wastes, fuel tanks, etc)     Explain (select)  Yes  No  Any operations sold, acquired, or discontinued in last five (5) years?     Explain (select)  Yes  No  Machinery or equipment loaned or rented to others?     Explain (select)  Yes  No  Any watercraft, docks, floats owned, hired or leased?     Explain (select)  Yes  No  Any parking facilities owned/rented?     Explain (select)  Yes  No  Is a fee charged for parking?     Explain (select)  Yes  No  Recreation facilities provided?     Explain (select)  Yes  No  Is there a swimming pool on the premises?     Explain (select)  Yes  No  Sporting or social events sponsored?     Explain (select)  Yes  No  Any structural alterations contemplated?      Explain (select)  Yes  No  Any demolition exposure contemplated?     Explain (select)  Yes  No  Has Applicant been active in or is currently active in joint ventures?     Explain (select)  Yes  No  Do you lease employees to or from other employers?     Explain (select)  Yes  No  Is there a labor interchange with any other business or subsidiaries?     Explain (select)  Yes  No  Are day care facilities operated or controlled?     Explain (select)  Yes  No  Have any crimes occurred or been attempted on your premises within the last three (3) years?     Explain (select)  Yes  No  Is there a formal, written safety and security policy in effect?     Explain (select)  Yes  No  Does the businesses' promotional literature make any representations about the safety or security of the premises?     Explain General RemarksBack to Building 1        Continue to Contractors General Information</value>
      <webElementGuid>0fdd07ab-bbca-4c51-8ecc-1957ba08fc77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmi-layout-mainContent&quot;)/div[1]/div[@class=&quot;ui-tabs ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;ui-tabs ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;hmi-layout-column-container ui-helper-clearfix&quot;]</value>
      <webElementGuid>be4063e0-cb53-4e85-8692-9b28f545771f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div</value>
      <webElementGuid>83c27994-e59b-4036-a17a-4523ca7a6e98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit to Home Office'])[1]/following::div[6]</value>
      <webElementGuid>ee654320-0d36-4d27-bfdd-b2ffeb0fdffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provide Supporting Documentation'])[1]/following::div[6]</value>
      <webElementGuid>a75bed65-ce59-4730-b614-aefe5e6173f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div</value>
      <webElementGuid>67773cab-c739-4e47-9478-5b87a4a7881c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = concat(&quot;Applicant InformationGeneral InformationPrior CarrierLoss History404 E Woodlawn Ave- Building 1Liability General InformationContractors General InformationProducts/Completed OperationsAdditional InterestApplication Finished Liability General Information (select)  Yes  No  Any medical facilities provided or medical professionals employed or contracted?     Explain (select)  Yes  No  Any exposure to radioactive/nuclear materials?     Explain (select)  Yes  No  Do/have past, present or discontinued operations involve(d) storing, treating, discharging, applying, disposing, or transporting of hazardous material? (e.g. landfills, wastes, fuel tanks, etc)     Explain (select)  Yes  No  Any operations sold, acquired, or discontinued in last five (5) years?     Explain (select)  Yes  No  Machinery or equipment loaned or rented to others?     Explain (select)  Yes  No  Any watercraft, docks, floats owned, hired or leased?     Explain (select)  Yes  No  Any parking facilities owned/rented?     Explain (select)  Yes  No  Is a fee charged for parking?     Explain (select)  Yes  No  Recreation facilities provided?     Explain (select)  Yes  No  Is there a swimming pool on the premises?     Explain (select)  Yes  No  Sporting or social events sponsored?     Explain (select)  Yes  No  Any structural alterations contemplated?      Explain (select)  Yes  No  Any demolition exposure contemplated?     Explain (select)  Yes  No  Has Applicant been active in or is currently active in joint ventures?     Explain (select)  Yes  No  Do you lease employees to or from other employers?     Explain (select)  Yes  No  Is there a labor interchange with any other business or subsidiaries?     Explain (select)  Yes  No  Are day care facilities operated or controlled?     Explain (select)  Yes  No  Have any crimes occurred or been attempted on your premises within the last three (3) years?     Explain (select)  Yes  No  Is there a formal, written safety and security policy in effect?     Explain (select)  Yes  No  Does the businesses&quot; , &quot;'&quot; , &quot; promotional literature make any representations about the safety or security of the premises?     Explain General RemarksBack to Building 1        Continue to Contractors General Information&quot;) or . = concat(&quot;Applicant InformationGeneral InformationPrior CarrierLoss History404 E Woodlawn Ave- Building 1Liability General InformationContractors General InformationProducts/Completed OperationsAdditional InterestApplication Finished Liability General Information (select)  Yes  No  Any medical facilities provided or medical professionals employed or contracted?     Explain (select)  Yes  No  Any exposure to radioactive/nuclear materials?     Explain (select)  Yes  No  Do/have past, present or discontinued operations involve(d) storing, treating, discharging, applying, disposing, or transporting of hazardous material? (e.g. landfills, wastes, fuel tanks, etc)     Explain (select)  Yes  No  Any operations sold, acquired, or discontinued in last five (5) years?     Explain (select)  Yes  No  Machinery or equipment loaned or rented to others?     Explain (select)  Yes  No  Any watercraft, docks, floats owned, hired or leased?     Explain (select)  Yes  No  Any parking facilities owned/rented?     Explain (select)  Yes  No  Is a fee charged for parking?     Explain (select)  Yes  No  Recreation facilities provided?     Explain (select)  Yes  No  Is there a swimming pool on the premises?     Explain (select)  Yes  No  Sporting or social events sponsored?     Explain (select)  Yes  No  Any structural alterations contemplated?      Explain (select)  Yes  No  Any demolition exposure contemplated?     Explain (select)  Yes  No  Has Applicant been active in or is currently active in joint ventures?     Explain (select)  Yes  No  Do you lease employees to or from other employers?     Explain (select)  Yes  No  Is there a labor interchange with any other business or subsidiaries?     Explain (select)  Yes  No  Are day care facilities operated or controlled?     Explain (select)  Yes  No  Have any crimes occurred or been attempted on your premises within the last three (3) years?     Explain (select)  Yes  No  Is there a formal, written safety and security policy in effect?     Explain (select)  Yes  No  Does the businesses&quot; , &quot;'&quot; , &quot; promotional literature make any representations about the safety or security of the premises?     Explain General RemarksBack to Building 1        Continue to Contractors General Information&quot;))]</value>
      <webElementGuid>5437b34d-99ef-404c-aeeb-9bd74f00e27a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
