<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3</name>
   <tag></tag>
   <elementGuidId>4e6a7fb3-f95b-468f-802e-5e320d447e6c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyListedOperationsSoldAcquiredLastFiveYearsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyListedOperationsSoldAcquiredLastFiveYearsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0841d1ee-2d45-4b6c-a9f6-8be79fb71bf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d87d078c-7d5b-4f25-8a4e-d7a4cf73f408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyListedOperationsSoldAcquiredLastFiveYearsAnswer</value>
      <webElementGuid>1f88fc5c-288a-4af4-8e7c-04aef448d7d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyListedOperationsSoldAcquiredLastFiveYearsAnswer</value>
      <webElementGuid>81c09c17-c1b9-4cec-a7d1-0f9b2d0a2da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>dab87fb2-720b-41a9-8d82-76d652290999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>58a56e69-bc03-41df-a60c-160465523b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>2e152652-2aa1-40e3-902f-b481b8b54d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyListedOperationsSoldAcquiredLastFiveYearsAnswer&quot;)</value>
      <webElementGuid>f9cf52a2-a34e-482b-8358-090a5ec3672e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyListedOperationsSoldAcquiredLastFiveYearsAnswer']</value>
      <webElementGuid>8cbe6a2a-9d9d-4656-a6bb-460a3d20fcc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>713567db-899f-4420-b951-45df74fbe31f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/following::select[1]</value>
      <webElementGuid>f519427f-84b7-43b6-990c-7cf9be456ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[2]/following::select[2]</value>
      <webElementGuid>15b3a625-2fe2-4cc0-9a87-d405f04e57c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any operations sold, acquired, or discontinued in last five (5) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>371d780c-ac85-492c-afe6-812b92e8d0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/preceding::select[1]</value>
      <webElementGuid>3edecc0a-98b1-4feb-bb10-5e390dd8d277</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>76689a2c-66da-4d2f-9fe3-08883de2c0c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyListedOperationsSoldAcquiredLastFiveYearsAnswer' and @name = 'AnyListedOperationsSoldAcquiredLastFiveYearsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>88189592-5725-4770-b9a4-9b8723137c6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
