<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>244ab034-1a94-49e2-bfb6-07ce436f0dd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RecreationalFacilitiesProvidedAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RecreationalFacilitiesProvidedAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>23bcd334-8756-4cee-800c-0bd91f7983fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>28c272ba-8685-4bbb-8366-86e4e07735d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RecreationalFacilitiesProvidedAnswer</value>
      <webElementGuid>3c4a21d2-c134-451f-a88c-c1f6183ba07b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RecreationalFacilitiesProvidedAnswer</value>
      <webElementGuid>57689e47-ff56-46f1-9685-4094ad4e4371</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>67992f31-aad7-4da9-b079-87ca795f7c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>e464d98f-ea2e-4c67-be79-93cd1d0e79ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>5a04004c-6028-49dc-872c-b4ec4258cbb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RecreationalFacilitiesProvidedAnswer&quot;)</value>
      <webElementGuid>a31e15f1-aa0e-4ee8-9a4f-e389ae277fc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RecreationalFacilitiesProvidedAnswer']</value>
      <webElementGuid>d7f76b72-09bd-4785-a205-2639ae0ce434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>22cfc871-ff29-4763-98a7-6cb4601c3d1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[8]/following::select[1]</value>
      <webElementGuid>351c45b1-ea86-4903-b570-2d06101a96ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is a fee charged for parking?'])[1]/following::select[1]</value>
      <webElementGuid>eb0f7c39-14bd-4c9c-af04-b543240d357c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recreation facilities provided?'])[1]/preceding::select[1]</value>
      <webElementGuid>1c7f4bfb-3301-418f-9fe5-c9c03322f9a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[9]/preceding::select[1]</value>
      <webElementGuid>f92da75d-5f46-40e5-8b21-a84f1ca3cd35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>e5a78010-3fc0-4991-bb4d-2c5bbea4e755</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RecreationalFacilitiesProvidedAnswer' and @name = 'RecreationalFacilitiesProvidedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>58579d8d-5da4-4901-bdf9-5d012dd75120</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
