<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>089b3ca7-3952-404a-a3e9-1e4b404b41f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DemolitionExposureContemplatedAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DemolitionExposureContemplatedAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f815ace4-cbb6-4563-ab26-d563a1b816f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5071e075-b082-481f-96ba-b7945f5cef40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DemolitionExposureContemplatedAnswer</value>
      <webElementGuid>d7615f4b-66df-44e3-8ba2-64eb0b3b79e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DemolitionExposureContemplatedAnswer</value>
      <webElementGuid>75a5558a-49e0-4560-b62b-16528178e726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>ae55c813-ce36-41f7-9534-58c1a63d5a1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>7e9c8638-08b2-4b51-a288-e00e699b9874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>3e3f5110-d4e7-49ac-8e91-d3cf67056de7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DemolitionExposureContemplatedAnswer&quot;)</value>
      <webElementGuid>4cd3a1b8-4a56-4815-aa8b-6d28636f90ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DemolitionExposureContemplatedAnswer']</value>
      <webElementGuid>21b56690-8138-41c7-9c79-fd303f670a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>9a0ea136-2726-4929-8c82-5e08af8ae438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/following::select[1]</value>
      <webElementGuid>ced349e9-c0ab-4760-8d4f-78d4a88d48a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any structural alterations contemplated?'])[1]/following::select[1]</value>
      <webElementGuid>e3408f79-1bdd-4ccb-8852-1107422bba21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any demolition exposure contemplated?'])[1]/preceding::select[1]</value>
      <webElementGuid>b86f35e5-a8a8-4819-8e81-e81e5dd696d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[13]/preceding::select[1]</value>
      <webElementGuid>1aa45898-5db0-4610-bed2-01507a512351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>cb4892ad-b03e-49c9-9b78-03e9ed8a39fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DemolitionExposureContemplatedAnswer' and @name = 'DemolitionExposureContemplatedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>d73a540c-8094-41a9-807d-11397536d87c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
