<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>b2b69dad-b965-4e2c-99ae-8824876bb333</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SportingOrSocialEventsSponsoredAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SportingOrSocialEventsSponsoredAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>02c3309a-2251-409e-b22e-900480d4911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>99e44819-2a69-4f9b-a1a2-55fb0db73224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SportingOrSocialEventsSponsoredAnswer</value>
      <webElementGuid>555fbda0-7609-4264-9ca0-5e9fa31c5cc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SportingOrSocialEventsSponsoredAnswer</value>
      <webElementGuid>98e8e858-e8eb-4775-b9c4-32cf2f2141a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>36871420-a969-490a-8cea-82d13a282b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>a7a6c1e6-077a-43df-bff3-a5db501920a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>988dbe59-899c-4ffd-9db2-3c4821286052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SportingOrSocialEventsSponsoredAnswer&quot;)</value>
      <webElementGuid>0a9582e0-6d6f-429f-ae46-21429fbd6dc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SportingOrSocialEventsSponsoredAnswer']</value>
      <webElementGuid>7c5318b1-03af-45b4-a618-9dc0004c212e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>fd8e717b-3f51-4514-9e10-971500c4f949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[10]/following::select[1]</value>
      <webElementGuid>82de593b-f178-40f0-9aee-b2c640eeee48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is there a swimming pool on the premises?'])[1]/following::select[1]</value>
      <webElementGuid>7196e208-b3b5-4a7c-a991-2afdafb7c870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sporting or social events sponsored?'])[1]/preceding::select[1]</value>
      <webElementGuid>75a7295c-c788-4471-b4a6-4ef2eb18a1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[11]/preceding::select[1]</value>
      <webElementGuid>d56ec482-7cbb-4efd-b198-54b7f0821c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>9fea1e8e-dedb-498b-948a-b93e21658717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SportingOrSocialEventsSponsoredAnswer' and @name = 'SportingOrSocialEventsSponsoredAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>d556d458-bd27-4393-b6bc-2cadf44f9269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
