<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12_13_14</name>
   <tag></tag>
   <elementGuidId>47da0bcc-e038-4059-a5b1-264cd88e8d45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LeaseEmployeesToFromOthersAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LeaseEmployeesToFromOthersAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d33863f3-465f-45a9-b892-9b2dfeecedde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>88052e21-c39c-47e4-a0d1-ea90e9add118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LeaseEmployeesToFromOthersAnswer</value>
      <webElementGuid>4c4a891f-ffbf-4a06-b980-76f3345a6dc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LeaseEmployeesToFromOthersAnswer</value>
      <webElementGuid>e4f1d3e2-663e-42ff-83f6-3f97326f08a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>b2558000-7638-4a76-bc2b-4b9640e80b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>99a8aa28-17f8-44a4-8aee-bea7866970b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>f09a90a4-679c-40bd-a639-d51c1ab00707</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LeaseEmployeesToFromOthersAnswer&quot;)</value>
      <webElementGuid>26504f9e-50a1-4afa-9c75-edde3667c20d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LeaseEmployeesToFromOthersAnswer']</value>
      <webElementGuid>2c424f33-f0c5-4d7e-8dc6-1c0db1a4f2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[29]/td/table/tbody/tr/td/select</value>
      <webElementGuid>b828ec85-eb3c-4a33-a1a6-362d88ca343a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[14]/following::select[1]</value>
      <webElementGuid>29b85d96-baa5-421e-830d-e1a5ee853f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Applicant been active in or is currently active in joint ventures?'])[1]/following::select[1]</value>
      <webElementGuid>9d66340d-78a2-495c-80af-cf90e7bc8142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you lease employees to or from other employers?'])[1]/preceding::select[1]</value>
      <webElementGuid>bdbcae55-575a-49c6-9da0-4a148ef902d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[15]/preceding::select[1]</value>
      <webElementGuid>4b199087-3702-4f7a-afd5-a2dd400e95d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[29]/td/table/tbody/tr/td/select</value>
      <webElementGuid>376a0244-9332-4490-8f56-5d6405820d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LeaseEmployeesToFromOthersAnswer' and @name = 'LeaseEmployeesToFromOthersAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>5f7f04ff-e926-4743-b3b1-e86dedf164e3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
