<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1</name>
   <tag></tag>
   <elementGuidId>7b659791-8e86-4300-9003-9a8b15e52262</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AnyExposureRadioactiveMaterialsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyExposureRadioactiveMaterialsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fad56189-3387-447f-8fa4-e31eacea13a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>df2c206c-7ba0-40d0-a4d9-08224bdf7974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyExposureRadioactiveMaterialsAnswer</value>
      <webElementGuid>65f4bd67-88d2-485e-bc56-19f7a52846fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyExposureRadioactiveMaterialsAnswer</value>
      <webElementGuid>11a6498c-c72b-431a-9906-fc0bb8749c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>37b21ffd-f6f4-45ce-af0e-79b86d40d160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c997eb15-58f5-4724-acf9-a651610ffa6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>f1c6702e-7a15-4ce7-8115-6c09d26746f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyExposureRadioactiveMaterialsAnswer&quot;)</value>
      <webElementGuid>e3fb6191-27d3-4f86-87ee-4373bb53f868</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyExposureRadioactiveMaterialsAnswer']</value>
      <webElementGuid>a760e6de-1906-4284-822c-9e0f6d672594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>e4e95b2e-ce3b-4c33-8674-2cedbf3d0bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/following::select[1]</value>
      <webElementGuid>8d04910c-bcd9-47c6-846e-e1d14efaa701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any medical facilities provided or medical professionals employed or contracted?'])[1]/following::select[1]</value>
      <webElementGuid>42ec5da3-c177-44ed-87fe-a2add456a332</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any exposure to radioactive/nuclear materials?'])[1]/preceding::select[1]</value>
      <webElementGuid>15361c97-4e74-49b8-8bc5-90b31e701b36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[2]/preceding::select[1]</value>
      <webElementGuid>dec1238c-f488-4ed4-aa71-d2246cbc7591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>d766ac6d-5972-47d5-9e7a-88c539ba2fc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyExposureRadioactiveMaterialsAnswer' and @name = 'AnyExposureRadioactiveMaterialsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>8a9ffa3a-0bdc-4b6f-94cf-43e330c93d6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
