<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>8671bd94-2e86-4826-8cff-217c00c1db4b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MachineryOrEquipmentLoanedRentedOthersAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='MachineryOrEquipmentLoanedRentedOthersAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a41d0be6-6db9-4b5c-af62-3858e708c664</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>06ca9761-d3bd-4c84-9623-5c6bbf4a6a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MachineryOrEquipmentLoanedRentedOthersAnswer</value>
      <webElementGuid>e972731a-db1c-4a9f-8b29-b73f051609b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MachineryOrEquipmentLoanedRentedOthersAnswer</value>
      <webElementGuid>f1256ef0-a212-427c-bd28-15c7210c262d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>9e65907b-3d28-4415-8a82-a5db293340d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>1c0c220a-a618-48b9-8449-c6a2d32c74b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>425e3a56-4401-420e-9bf1-62698e35448a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MachineryOrEquipmentLoanedRentedOthersAnswer&quot;)</value>
      <webElementGuid>88c98ce1-6366-472d-bfdd-d9913be7ad57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='MachineryOrEquipmentLoanedRentedOthersAnswer']</value>
      <webElementGuid>f037c262-3d99-4627-a422-afe4d86973d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>546fb5da-32a4-4b08-9641-6f452bfa88ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/following::select[1]</value>
      <webElementGuid>3e557584-c24d-40be-8d7a-56dc8232279e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any operations sold, acquired, or discontinued in last five (5) years?'])[1]/following::select[1]</value>
      <webElementGuid>05d44ec5-49a2-49ae-ad3c-4b06113fb34c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Machinery or equipment loaned or rented to others?'])[1]/preceding::select[1]</value>
      <webElementGuid>cbb962e4-b42b-4f51-94ab-47a839e092f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/preceding::select[1]</value>
      <webElementGuid>0f036700-1fe7-4f7a-8310-ebfe116a7186</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>ff9aeb5f-ed8a-42a6-afc2-a0f07344f977</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'MachineryOrEquipmentLoanedRentedOthersAnswer' and @name = 'MachineryOrEquipmentLoanedRentedOthersAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>dd5c7c41-bef2-4a0c-904a-f93a329ccc82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
