<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17</name>
   <tag></tag>
   <elementGuidId>410a7c88-5b2c-45c6-9d12-58f4fb057ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CrimesOccurredOrAttemptedLastThreeYearsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CrimesOccurredOrAttemptedLastThreeYearsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>38fb185d-b64b-45bb-af3a-7b1658555ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f7167350-39f7-4b39-a6d0-999cb99c07d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CrimesOccurredOrAttemptedLastThreeYearsAnswer</value>
      <webElementGuid>4a294d60-f8e8-4a5e-ae89-107814c7f1fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CrimesOccurredOrAttemptedLastThreeYearsAnswer</value>
      <webElementGuid>9fe34822-888b-42fe-a577-38156b5a6136</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>2dd87f8b-5446-4d16-bcbb-aa1c9668aec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>4320f138-4da3-4277-826f-f52560a162ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>0c8d0126-2f07-4baa-956a-8593227c902f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CrimesOccurredOrAttemptedLastThreeYearsAnswer&quot;)</value>
      <webElementGuid>7a20f7ed-e906-40ae-b873-e617099bcc34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CrimesOccurredOrAttemptedLastThreeYearsAnswer']</value>
      <webElementGuid>296cb76e-4f0f-44a0-9bd8-6b987793ccbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[35]/td/table/tbody/tr/td/select</value>
      <webElementGuid>3ff6d1cf-4bc5-4baf-8d30-778e70ec7360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[17]/following::select[1]</value>
      <webElementGuid>6dc1b622-ce05-455a-8f7a-ff180ff21b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are day care facilities operated or controlled?'])[1]/following::select[1]</value>
      <webElementGuid>02a06e3c-3e70-4358-b848-bc43651eaf89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have any crimes occurred or been attempted on your premises within the last three (3) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>beb1ecaa-4364-4860-8213-1d179dc21a11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[18]/preceding::select[1]</value>
      <webElementGuid>c95c6a71-bc11-499f-b70b-e404bc7c1f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/select</value>
      <webElementGuid>f6e3428c-de7f-4213-b689-454895b7bb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CrimesOccurredOrAttemptedLastThreeYearsAnswer' and @name = 'CrimesOccurredOrAttemptedLastThreeYearsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>a121f631-cf5a-49ce-9f63-533ee6ddb21c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
