<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16</name>
   <tag></tag>
   <elementGuidId>75c74990-7f2f-43c2-ad31-7ad4c4ef4858</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DayCareFacilitiesOperatedAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DayCareFacilitiesOperatedAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e1eead3c-496f-40b8-a889-34ea6ff1eefa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>235271b8-2242-4374-82f3-47777977fc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DayCareFacilitiesOperatedAnswer</value>
      <webElementGuid>d15eea22-0919-4333-a878-3992c01cf77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DayCareFacilitiesOperatedAnswer</value>
      <webElementGuid>53a8cf3b-76a6-4f0f-a848-e14c5466c0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>67c7469e-0737-40fd-abaa-9f9cff080dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>5f9934c9-60ac-42a3-bc82-aa1f658c9555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>924745f0-be45-4ff9-b509-7b65b5c47558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DayCareFacilitiesOperatedAnswer&quot;)</value>
      <webElementGuid>78bc1891-6972-461f-875b-42377ad99f5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DayCareFacilitiesOperatedAnswer']</value>
      <webElementGuid>1d9363da-e0e7-48fb-b6e5-9ac85afbe0c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[33]/td/table/tbody/tr/td/select</value>
      <webElementGuid>70243caf-0451-4e09-998c-e8b553098799</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[16]/following::select[1]</value>
      <webElementGuid>2063aa67-1a23-44c2-ae99-57d3fcf19949</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is there a labor interchange with any other business or subsidiaries?'])[1]/following::select[1]</value>
      <webElementGuid>18457d7c-4360-40e8-8e61-3d276378a910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are day care facilities operated or controlled?'])[1]/preceding::select[1]</value>
      <webElementGuid>4b8ef0cc-c3fe-4e59-86f9-a80bf95b1fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[17]/preceding::select[1]</value>
      <webElementGuid>24c098dd-f9f7-43ce-a5aa-18ca3a5d8b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[33]/td/table/tbody/tr/td/select</value>
      <webElementGuid>7ee7c336-3bdc-4699-bd47-2914990256e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DayCareFacilitiesOperatedAnswer' and @name = 'DayCareFacilitiesOperatedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>8ce9d5d1-97e7-4004-8e68-74ba6b7d66fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
