<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2</name>
   <tag></tag>
   <elementGuidId>a8fe0400-6281-42e5-9663-63b44b856946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>01610e07-fcc0-4389-827b-0c96b80a7db1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>07f60fb4-8a66-4137-8312-50eece3312c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer</value>
      <webElementGuid>fbd51939-466c-4e47-8ad7-359ed3a4be21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer</value>
      <webElementGuid>55917c64-4dec-47c3-830d-ddc298c337c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>ff472d3f-ebc8-42da-9dcc-fcd938996773</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>cc0e14e5-43ef-4aa5-aa33-1bd28a141e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>46d6c159-4d9f-4350-8edd-45fb2113c335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer&quot;)</value>
      <webElementGuid>60a3bba6-a2b3-432b-a3ad-f1288a81387a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer']</value>
      <webElementGuid>d026f9e2-2249-4d5e-bd8c-48fcf645791f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>19aba333-551e-4e6a-a44e-a2b18bd227cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[2]/following::select[1]</value>
      <webElementGuid>462c96bf-d16c-45c2-a750-cf62bdcbf61a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any exposure to radioactive/nuclear materials?'])[1]/following::select[1]</value>
      <webElementGuid>6098d66a-d201-4656-b49c-47c27f761419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/preceding::select[1]</value>
      <webElementGuid>a1e14c11-600f-4915-9bd9-58c6142a1b08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any operations sold, acquired, or discontinued in last five (5) years?'])[1]/preceding::select[2]</value>
      <webElementGuid>78d0d258-5f1e-49a9-8984-849f611330cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>61e8f662-d9e2-4283-951f-8f208e797395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer' and @name = 'OperationsInvolveStoringDisposingTransportingHazardousMaterialAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>9ad6d839-173c-4306-ab65-bc156f8eb7e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
