<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>ddacdb5f-f557-4d68-a87e-7b53a588d0e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#StructuralAlterationsContemplatedAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StructuralAlterationsContemplatedAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d31c314-089e-435e-b320-9d9d131a5df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>c8489443-cac0-4249-9182-b3c9986996be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StructuralAlterationsContemplatedAnswer</value>
      <webElementGuid>d42030e0-10e5-4f49-961e-d637211a4f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StructuralAlterationsContemplatedAnswer</value>
      <webElementGuid>a3e8786e-043e-473b-b820-f3ecc5012cdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>547c5184-693b-480f-a5e8-ee1066f108f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>7bddf885-f467-493f-a96a-ddd9b6559c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>dd2f75a4-9361-41d8-87ea-f91a1949756c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StructuralAlterationsContemplatedAnswer&quot;)</value>
      <webElementGuid>5a6ecaa2-ddc7-42a2-8311-b4051bca2842</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StructuralAlterationsContemplatedAnswer']</value>
      <webElementGuid>896b3c5f-824f-4143-a883-551382583e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>bf721557-874b-411a-90ab-b0b5006f81ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[11]/following::select[1]</value>
      <webElementGuid>a5eb2d08-1331-4108-b026-e0a6485ed701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sporting or social events sponsored?'])[1]/following::select[1]</value>
      <webElementGuid>07e4f5fb-a540-41dd-be27-800446b0d13d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any structural alterations contemplated?'])[1]/preceding::select[1]</value>
      <webElementGuid>ee728060-9b24-4be7-a0b2-ae70f30c72ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/preceding::select[1]</value>
      <webElementGuid>2c241b2f-f825-412c-8553-8b1943d2f741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>6a26245f-1d99-485b-b7a3-0fe3265f84ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StructuralAlterationsContemplatedAnswer' and @name = 'StructuralAlterationsContemplatedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>6fe9c630-9318-46d6-9ca4-bdc1c8b895c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
