<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Employee Benefits Liability Inform_6c21f6</name>
   <tag></tag>
   <elementGuidId>9dd455e9-3191-4001-b63b-97109ace3e61</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ListOfOtherEmployeeBenifitPrograms</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='ListOfOtherEmployeeBenifitPrograms']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>e9327dcd-9eb3-427f-b69e-e7fa2a2a2c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b68cb036-b9cc-44d1-a20c-1a5f5800c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ListOfOtherEmployeeBenifitPrograms</value>
      <webElementGuid>8257ff2b-1620-4263-ba3d-b8103bd9e099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ListOfOtherEmployeeBenifitPrograms</value>
      <webElementGuid>72f2a169-2cc3-42c1-9004-2b138e0b1611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>46e65c62-9ae2-47af-ba04-94fc166c332b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>d93a5d7c-4a44-451a-8408-d60a9d316548</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-removes-coverage-when</name>
      <type>Main</type>
      <value>/contains text/</value>
      <webElementGuid>80e01aa2-19f7-481f-96ff-4c9217b62fde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text-highlight hmi-ui-state-dirty</value>
      <webElementGuid>86fe4267-1441-49e5-8e7d-d9a67fef08f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>7cd838fb-32fb-4d09-a942-a45a1993f244</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ListOfOtherEmployeeBenifitPrograms&quot;)</value>
      <webElementGuid>b64b1086-af53-4a33-ab6d-f4db607095a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='ListOfOtherEmployeeBenifitPrograms']</value>
      <webElementGuid>3bc6331b-d542-44da-a1ec-f32eabce109e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div/table/tbody/tr[2]/td[2]/table/tbody/tr/td/textarea</value>
      <webElementGuid>abd8c7ef-7175-4ca8-817a-f18549bcf1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>41951e7b-2805-4157-ad12-ab11128d24fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'ListOfOtherEmployeeBenifitPrograms' and @name = 'ListOfOtherEmployeeBenifitPrograms']</value>
      <webElementGuid>e3eb22ac-9402-4664-9583-c282a38956a8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
