<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>e7deaba9-86e6-40b7-9371-f01f2e1f7464</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JudgementOrLienAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JudgementOrLienAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>85c2b0d1-c285-48b3-a97c-fc28677462b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e888ef5a-b461-4a79-a814-174776126b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>b309898d-ca64-4838-a883-0c056797a333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>0b33a8b0-a54b-4a11-9302-09881fc89d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>31844463-53da-42e4-884b-04d170ac3096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>57</value>
      <webElementGuid>9119c436-8193-4de8-b090-2ad82e30f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>16bfc077-e5ff-4ab3-9174-471440150e5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JudgementOrLienAnswer&quot;)</value>
      <webElementGuid>67bbb8e3-fcc5-46db-915e-fa5e675489a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JudgementOrLienAnswer']</value>
      <webElementGuid>e151097c-f694-4759-a16c-2e40d2a4a1a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>ce0206be-177b-4e95-8c83-e104c819b06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[4]/following::select[1]</value>
      <webElementGuid>e8448bcd-6fff-4dcd-b602-0093fffac1b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[4]/following::select[1]</value>
      <webElementGuid>b498ab23-76a1-4578-8c33-82c2a7054336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Applicant had a judgment or lien during the last five (5) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>8c60609f-9571-4284-80b5-6d1c96b0eabd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[5]/preceding::select[1]</value>
      <webElementGuid>c3b5ca92-c553-4c2b-8635-d380569f3052</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>fb4e35d7-26e0-4e6a-88bc-2d146c9a136c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JudgementOrLienAnswer' and @name = 'JudgementOrLienAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>e072361e-d621-4483-bde8-42ffcff32a39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
