<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3</name>
   <tag></tag>
   <elementGuidId>a08b7b1b-5a7f-437e-853d-06a908e88012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExposureToFlammablesAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ExposureToFlammablesAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>81a7bde6-657d-406e-9b80-44650988061c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>9ebcd63f-c45c-466c-ac45-6d238a799e5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExposureToFlammablesAnswer</value>
      <webElementGuid>8d5ad8f1-0bc3-4d9a-a824-38ae5188f1b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExposureToFlammablesAnswer</value>
      <webElementGuid>551f08b4-9bae-4a17-8e91-931e557579c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>f3206868-6519-4b0f-9ccc-66c5cc9cea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>d1ce1a35-8ab9-4e17-876d-29ed955f801c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>30f958e9-aa72-44bc-816f-b9138f6a1b3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExposureToFlammablesAnswer&quot;)</value>
      <webElementGuid>fca945d9-5d0a-47e3-a586-74c5f5b8f085</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ExposureToFlammablesAnswer']</value>
      <webElementGuid>2b6ab407-9ecd-427a-ab4f-8ebd273b4112</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>bea427ea-9e82-4f49-9b85-d106d3e2d616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::select[1]</value>
      <webElementGuid>53b2dfa3-6178-4556-930d-edc0cf317e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OSHA'])[1]/following::select[1]</value>
      <webElementGuid>9c499b0c-aec6-482d-81ba-45f85bc30065</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any exposure to flammables, explosives, chemicals?'])[1]/preceding::select[1]</value>
      <webElementGuid>9adee795-49fb-4262-a966-748aa62fe969</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/preceding::select[1]</value>
      <webElementGuid>1416269a-bc13-4cee-8b8b-0978e27a3a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>1023eeb2-7034-4bba-bf41-639f8a557fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ExposureToFlammablesAnswer' and @name = 'ExposureToFlammablesAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>baf30538-9dc3-46dd-b5a3-450d0e3c4b3d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
