<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>bf29ce5d-91c4-4314-b6e4-a9100ada9ecd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantSubsidiaryOfAnotherEntityAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ApplicantSubsidiaryOfAnotherEntityAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ae65ee6d-7c7e-419d-84b0-32c382b0f297</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4ad70798-b8e9-40bd-8b14-ac75c4cc58f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantSubsidiaryOfAnotherEntityAnswer</value>
      <webElementGuid>854737ec-0cea-4eac-9aef-ec86afde81ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantSubsidiaryOfAnotherEntityAnswer</value>
      <webElementGuid>69b9f4a5-c05e-4eb5-9579-28ea1f458294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-dirty</value>
      <webElementGuid>16aa751a-3e1f-4987-9a9c-64d04a6595f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a0e1e9d5-a948-45bc-8eda-da7f0339977f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>e62ab252-7f6e-45dd-81e1-6ca262e558f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantSubsidiaryOfAnotherEntityAnswer&quot;)</value>
      <webElementGuid>2ed9636c-360e-4631-a197-6698179372d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ApplicantSubsidiaryOfAnotherEntityAnswer']</value>
      <webElementGuid>7356e4a4-7309-438e-a715-72ff22387cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>9ca8ba73-92d1-4de5-a699-daad2c8b5b89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Information'])[2]/following::select[1]</value>
      <webElementGuid>195ba833-d9a0-4ee7-897a-d2ff5d2ba562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Finished'])[1]/following::select[1]</value>
      <webElementGuid>41b2fcf5-f93d-4169-b743-6b5b6599924f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is the Applicant a subsidiary of another entity?'])[1]/preceding::select[1]</value>
      <webElementGuid>bbbc0f47-79c6-49eb-b5b2-148b9aa12919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent Company'])[1]/preceding::select[1]</value>
      <webElementGuid>e4d1352c-4a6b-49da-ae64-0851b24a6f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>83fd894f-3f82-46de-874b-76a999b4bf83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ApplicantSubsidiaryOfAnotherEntityAnswer' and @name = 'ApplicantSubsidiaryOfAnotherEntityAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>b8bc014b-6ce9-4bce-8b8d-8aea1cddcf13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
