<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2</name>
   <tag></tag>
   <elementGuidId>c58ba0c2-19cd-403a-a09b-2044b1342c49</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FormalSafetyProgramAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FormalSafetyProgramAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>13324bac-63b1-4068-9689-7334f07e41e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>44ac5353-1295-4211-8a9a-53987dbe2296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormalSafetyProgramAnswer</value>
      <webElementGuid>6b145fee-cbd8-403f-b1c9-f061cea7d64b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormalSafetyProgramAnswer</value>
      <webElementGuid>89453922-e826-46e4-80d0-92e8f601fb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>9a1c8955-85ed-4031-b767-04582d9fb12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>6cf25314-0a72-4942-85c5-9a9bb8663bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>0e8fd53c-4a1e-4735-b2c4-20df1c2be3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormalSafetyProgramAnswer&quot;)</value>
      <webElementGuid>1f6802da-a53a-432b-8552-b5ed91ac4608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FormalSafetyProgramAnswer']</value>
      <webElementGuid>2d4eb1e6-cae5-4bdf-b213-0793730f15c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>9b3c40ea-8e88-4a04-8718-907482b8c4a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% Owned'])[2]/following::select[1]</value>
      <webElementGuid>50667d57-e5c9-489c-9a8a-5103b0b065ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship Description'])[2]/following::select[1]</value>
      <webElementGuid>a351e866-33e3-4f69-806d-7f021695f62c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is a formal safety program in operation?'])[1]/preceding::select[1]</value>
      <webElementGuid>fc9774e0-0292-43b3-b526-3703008c06cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety Manual'])[1]/preceding::select[1]</value>
      <webElementGuid>348a2eda-1a08-4ec8-9d13-665bf67bf1bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8e4e58ca-807a-4e08-a5a6-b8fef16e95cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FormalSafetyProgramAnswer' and @name = 'FormalSafetyProgramAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>27332c03-13e0-44cb-92a8-6237c8149d88</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
