<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>b7544b5b-7d92-42e6-b5dd-fe2b4d65f53c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LossesRelatingToSexualAbuseAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LossesRelatingToSexualAbuseAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5a3886a9-3a95-4b5a-9ee3-57d90c1f7fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5ae18f68-e50b-435e-ba18-53d85e7618c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LossesRelatingToSexualAbuseAnswer</value>
      <webElementGuid>b54c31e8-1076-4b76-a121-fc282c5df022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LossesRelatingToSexualAbuseAnswer</value>
      <webElementGuid>775f4956-d23a-48c7-99d9-79b55fa56e2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>a0ce09bb-231c-4c33-8e07-04c8f9b765b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>2b4a4d61-1c40-4428-851a-f2cbb1c01b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>92a911db-eeda-4398-935b-f26e5b631742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LossesRelatingToSexualAbuseAnswer&quot;)</value>
      <webElementGuid>af239f97-5eca-452f-8fb9-1ee2c36e5500</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LossesRelatingToSexualAbuseAnswer']</value>
      <webElementGuid>bc29ed60-4ede-44c9-af7e-31796e2b96bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[13]/td/table/tbody/tr/td/select</value>
      <webElementGuid>ed5ac099-8b6d-4745-9a97-3627bc93ccd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[7]/following::select[1]</value>
      <webElementGuid>0e69e749-99c5-4a8c-9b39-28681b5a5a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[2]/following::select[1]</value>
      <webElementGuid>856a83bf-390e-4bde-9fc8-aa47d5de49c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[8]/preceding::select[1]</value>
      <webElementGuid>f04e0f9e-cb5b-4592-b984-fd5fdf1788a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[9]/preceding::select[2]</value>
      <webElementGuid>e203047e-57a2-484b-83d0-5d68b20501d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td/table/tbody/tr/td/select</value>
      <webElementGuid>7ef5213a-680f-4d76-8a6e-ab2caa39d21b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LossesRelatingToSexualAbuseAnswer' and @name = 'LossesRelatingToSexualAbuseAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>419092e4-cb63-4db9-b01d-a1117398cf04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
