<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>2b6d3461-5770-4b11-b760-b89bc658d6b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BusinessPlacedInTrustAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='BusinessPlacedInTrustAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b38d9ed-f470-46b7-9fc2-747208e34a62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3a12f127-78ba-4e9e-a89d-5832a5cbe6c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BusinessPlacedInTrustAnswer</value>
      <webElementGuid>520d8733-8756-4681-8c5a-0ad4a9fc9615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BusinessPlacedInTrustAnswer</value>
      <webElementGuid>cc577ea0-7287-446b-81a9-c950209ab461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>7ffe7170-5a7f-4d33-b739-17209c2b0811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>66</value>
      <webElementGuid>3c272264-8b20-464c-bf81-42a248727c3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>39e3d8c6-2037-4c07-b842-639e6c79840c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BusinessPlacedInTrustAnswer&quot;)</value>
      <webElementGuid>fefe6c7c-d86f-428f-a86e-fbbad0b46636</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='BusinessPlacedInTrustAnswer']</value>
      <webElementGuid>39a0321d-0929-4ee5-9ed3-2f0ee6be4717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>68690075-c8a1-4c72-b766-0bbfe4cb8316</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[6]/following::select[1]</value>
      <webElementGuid>a55d44f9-4d7e-4a8a-aecd-ee95319a939a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[6]/following::select[1]</value>
      <webElementGuid>c2854ac5-cfd8-4670-8887-778d877edcfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has business been placed in trust?'])[1]/preceding::select[1]</value>
      <webElementGuid>54ce7e05-60fa-488e-abbe-e2c2101e4734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/preceding::select[1]</value>
      <webElementGuid>d210df71-48ac-44c3-89ec-9023b3bc4ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>28d0900e-a2f6-4011-8654-bca290b43ced</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'BusinessPlacedInTrustAnswer' and @name = 'BusinessPlacedInTrustAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>de9f5144-f81e-4737-b9c9-2dbb8bd49580</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
