<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_of Stories_NumberOfStories</name>
   <tag></tag>
   <elementGuidId>aea718c0-5270-477c-b6cc-4da7059f93da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NumberOfStories</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumberOfStories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2a018a9d-9dc0-4817-927b-00352be74bcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>be3dad80-27c7-4624-a270-fbc3f9574d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberOfStories</value>
      <webElementGuid>b6ae3e8f-c9c3-44b1-b82c-e042ac251672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumberOfStories</value>
      <webElementGuid>00474f92-e6fd-4619-80ef-982154d3253f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>e52ebe94-7bb3-4b02-b6d1-0a672b80e206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>4d4ba00c-e138-4553-9762-ab7cc27b03d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c05fb2bc-43e0-4dc3-a366-ae5971eb3e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>92d48439-f6c7-408f-9e6f-f1e136ffe44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberOfStories&quot;)</value>
      <webElementGuid>ab2d26bb-ea0e-4d0f-9d12-4ec87898848f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumberOfStories']</value>
      <webElementGuid>2e4091e2-441c-4406-8dff-775b7fff0935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[2]/td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>be6e3049-c763-48ff-9138-4da1d80a95ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>07bc790c-0527-4689-9d1c-eaf2f005079c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NumberOfStories' and @name = 'NumberOfStories' and @type = 'text']</value>
      <webElementGuid>4156b10f-cecb-4a38-afe1-fd49f2acd74c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
