<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Inspection Contact Name_InspectionCon_c6b3b6</name>
   <tag></tag>
   <elementGuidId>13edfec5-a774-4441-8611-215fed6bee81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InspectionContactName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='InspectionContactName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4e059756-f371-48e0-b474-d340ea4643d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b3a098b0-bfdd-4a73-aeb2-33409ba524f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InspectionContactName</value>
      <webElementGuid>5274f3e3-4063-4e3c-bb2a-5a72084bb18a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InspectionContactName</value>
      <webElementGuid>75344309-b414-437a-b333-4718cf6fb460</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>4f2efe14-c065-417f-be65-097226d56a34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text</value>
      <webElementGuid>42673150-34f8-47e7-acf8-35fef20aea8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>a95e81f2-ebbc-4746-ad5c-986e2ade9431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1eb469e0-7978-4838-be13-919d69f78dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InspectionContactName&quot;)</value>
      <webElementGuid>252ceadb-d2c7-442a-8355-e475c5f3fe1a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='InspectionContactName']</value>
      <webElementGuid>e68f1315-16cb-435a-a375-1e7e05e66e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div[3]/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>bb38d410-a94a-418e-ad9a-8ed6de83cf1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>b32edc3c-b57d-48b1-a572-47bb83464ef5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'InspectionContactName' and @name = 'InspectionContactName' and @type = 'text']</value>
      <webElementGuid>00bf9838-6d5f-40d6-a517-e5d217561b3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
