<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description of Operation_Descripto_c0936c</name>
   <tag></tag>
   <elementGuidId>54b0489c-3316-4b4e-94bc-763d2528ac06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DescriptonOfOperations</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DescriptonOfOperations']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2ec0bd96-275f-4f2d-8b00-ed6cb137707a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e2aa3207-de69-44a5-972d-7bf9899fb70d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DescriptonOfOperations</value>
      <webElementGuid>b298c47f-3dbb-4384-8ec7-309dbf1795c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DescriptonOfOperations</value>
      <webElementGuid>290219ff-d3e2-4b6a-a9a2-80e165634f0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5bb1f220-6598-435e-89eb-a65e001671eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>c5b4cadd-d5df-4218-8b6c-132ca69335f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-state-dirty</value>
      <webElementGuid>d193fe3f-7e72-494f-9a80-51a09ae89a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>54b1e518-a2e8-4777-9589-0df01e6c1d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DescriptonOfOperations&quot;)</value>
      <webElementGuid>b9d059b5-ada4-4d12-8ccf-cda05dc4aee1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DescriptonOfOperations']</value>
      <webElementGuid>4eba99d0-7f2c-4320-893e-f3b85234ac4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div[3]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/textarea</value>
      <webElementGuid>98fc6449-67b0-403e-9b4d-f109c636ffb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/textarea</value>
      <webElementGuid>74cbf0c6-90c6-410e-8fc3-ff888d79b3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DescriptonOfOperations' and @name = 'DescriptonOfOperations']</value>
      <webElementGuid>c1366217-eb4c-40b9-a70c-eff879f43a95</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
