<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  No  Yes, I have Loss Runs _504ea5</name>
   <tag></tag>
   <elementGuidId>40dfc65d-2f98-42bd-9589-382167be961b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LossesExist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LossesExist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8b0861fd-46cb-46d8-a62b-35ef3ed2b543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>30c259c2-a32e-4c8c-b7f0-31dfb32900a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>94bf4567-01c4-44e8-9988-7b7d9ce60843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>6d35d778-eb6a-4f0f-85c8-fddc9e843cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>2f62671a-ff73-4036-9e4a-9467603b44e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>f7fb6a95-ba68-4d50-b293-1193c19dc7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information </value>
      <webElementGuid>d80c6acf-0a7e-473c-9e04-501ecfe38061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LossesExist&quot;)</value>
      <webElementGuid>b3ad9409-1e39-4cce-aa73-f79cd4778895</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LossesExist']</value>
      <webElementGuid>b46c0686-d092-43b0-a8c9-598ada88e6d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>537d8f5d-d198-471e-837c-24bd41b4f4fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any claims, losses, or occurrences in the last 3 years?'])[1]/following::select[1]</value>
      <webElementGuid>38f75dde-81ab-4829-a5f3-07c24507ab06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss History (3 Years)'])[1]/following::select[1]</value>
      <webElementGuid>95cd9e95-544f-47ee-8653-499d0337b0fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>c30d449a-5d9c-4297-98a0-6975d0f385e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please schedule all Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>d4d7361e-82a6-4861-bae5-3f4b97edf4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>358079c9-24db-43c9-8f63-fc9a3b112aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LossesExist' and @name = 'LossesExist' and (text() = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ' or . = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ')]</value>
      <webElementGuid>25fa644b-eba2-409d-ba24-ba01cfe01c61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
