<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_browse complete list of classification codes</name>
   <tag></tag>
   <elementGuidId>c31a37ec-4812-43a3-a031-41bd7a82e675</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#browse-class-codes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='browse-class-codes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5308388a-33b6-459c-8234-cc94ff6f4cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b03dd922-bdd0-4804-89bf-a00969ed33ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>browse-class-codes</value>
      <webElementGuid>eebdaab9-a7e0-465e-abab-998dc29606ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>browse complete list of classification codes</value>
      <webElementGuid>85caf592-0a24-470f-9d30-669b9ce967f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-class-codes&quot;)</value>
      <webElementGuid>5c49941f-394d-4d20-a514-0680be414879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='browse-class-codes']</value>
      <webElementGuid>c1379c72-5bd9-4e99-8506-fdc5aa790c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hmi-form-save-classification']/table/tbody/tr[2]/td[2]/a</value>
      <webElementGuid>84c1482a-62dd-4c9c-8417-1f123ac879e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'browse complete list of classification codes')]</value>
      <webElementGuid>5b9a91f2-ceb8-445b-93ba-533b28037eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exposure'])[1]/preceding::a[1]</value>
      <webElementGuid>c69c86d7-def0-4a82-86a2-73d8c6417824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exposure Basis'])[1]/preceding::a[1]</value>
      <webElementGuid>1c282ef6-38d0-4951-a1be-c77bde152ea4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='browse complete list of classification codes']/parent::*</value>
      <webElementGuid>5d4b6345-a2bb-4bae-a446-c7073a68948b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>0dfeabf3-0ccb-4172-a3bb-ff98f124b138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/a</value>
      <webElementGuid>2446c81a-8dc3-423d-8929-41b8b894f7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'browse-class-codes' and (text() = 'browse complete list of classification codes' or . = 'browse complete list of classification codes')]</value>
      <webElementGuid>1fea2d1e-70a8-4f69-9cda-9083f620ed91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
