<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Products  Completed Operations (a) Ra_ea04c4</name>
   <tag></tag>
   <elementGuidId>262949c3-edf3-4292-852a-af704e3e3c35</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductsCompletedOperationsARate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductsCompletedOperationsARate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b57e5bf5-d70f-4ed7-b2dc-67f6063357ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>2c066fcb-c19e-4969-aec3-2f982179bcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductsCompletedOperationsARate</value>
      <webElementGuid>25ac371d-2918-4d11-ad95-eb2f713de943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductsCompletedOperationsARate</value>
      <webElementGuid>c6f7a01f-98d7-43a7-9d25-079318a5d262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2c5ba886-5db3-4987-a068-64a97f142148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ad4cd19e-dd43-4262-8124-8595f4dfd4f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatRate hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>4e216287-e236-4296-b222-50d36ea49ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\d*(\.\d+)?$</value>
      <webElementGuid>2ed9a766-1d71-430e-a6cd-e1fa84f13a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.001</value>
      <webElementGuid>e3ebac1a-dd68-494e-b205-9fa3633a2958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ad314083-ae8b-46c9-9cae-a2574df0901b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5938dba7-6fc4-4491-87fd-154d18ee05d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductsCompletedOperationsARate&quot;)</value>
      <webElementGuid>3e4ba266-01a9-45b6-9697-d123e80c7720</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductsCompletedOperationsARate']</value>
      <webElementGuid>7e40f548-5f65-46ca-8660-7789642a3913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hmi-form-save-classification']/table/tbody/tr[4]/td/table/tbody/tr/td/input</value>
      <webElementGuid>517215e7-3016-4b59-a839-db19d477974d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/table/tbody/tr/td/input</value>
      <webElementGuid>95606cd3-9790-488f-ba1e-99f12d02a213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductsCompletedOperationsARate' and @name = 'ProductsCompletedOperationsARate' and @type = 'text']</value>
      <webElementGuid>fc2f9faf-9c9b-4cca-8bfd-544a01a8b61a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
