<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_NameOnPolicy</name>
   <tag></tag>
   <elementGuidId>3ca80c3b-9b36-4554-9895-5cd92b094684</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NameOnPolicy</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NameOnPolicy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>88726c73-17e3-4dbf-a496-011ddc71c5ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f2aa324f-5497-41fa-acec-fa714d3ad519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>help</name>
      <type>Main</type>
      <value>NameHelp</value>
      <webElementGuid>63b7789e-869e-4248-b641-d05a7fa47145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameOnPolicy</value>
      <webElementGuid>d6b93918-ce2d-45b8-8c83-ece337a9a863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NameOnPolicy</value>
      <webElementGuid>2c95aebe-7fec-4c6b-9071-e6c0292fa7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>4c9b7f37-7242-4be9-bf18-fe911f903a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-text-focus</value>
      <webElementGuid>e3cf36aa-139d-410c-abd2-858788b789d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Applicant Name</value>
      <webElementGuid>4cfa166a-85f9-47c3-a039-5d95b1f2d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>This is the name used to identify the applicant within Policy Express.</value>
      <webElementGuid>d0856be7-4b0e-4964-8dbc-8e59ba78e0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5c11ef29-164d-4f3d-909b-c34671040a67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[A-Za-z0-9,\.\*&amp;\+\/\-' @#!]+$</value>
      <webElementGuid>b2720b62-3191-43b0-8078-b1534e14458f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>2225f90d-c533-4903-b5d1-e10ae2f7d587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>70ee8233-bd33-42be-b5bd-8d61bdbc72c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameOnPolicy&quot;)</value>
      <webElementGuid>0e243201-8043-420b-b558-ff7e5e6734ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameOnPolicy']</value>
      <webElementGuid>5c8a606f-3f71-4d22-afd7-74b7e4811b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[2]/table/tbody/tr/td[2]/div/form/div/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>be820895-272f-438c-a753-b59e9af8129b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>79e23b03-795f-4bb4-884d-47cee3f74d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NameOnPolicy' and @name = 'NameOnPolicy' and @title = 'Applicant Name' and @type = 'text']</value>
      <webElementGuid>966ae420-9a9e-4581-acdd-30c58e16bc65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
