<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Explanation_Explanation</name>
   <tag></tag>
   <elementGuidId>e4b22189-14d3-402f-bdbd-1e398375f97b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Explanation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Explanation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d35388c7-3ee9-4a5c-aba8-f2ba3bd65cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>03358b79-6f17-4989-88b4-8af3bcc58507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Explanation</value>
      <webElementGuid>c54bef22-587c-4f8a-b262-4a1445dbaa75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Explanation</value>
      <webElementGuid>dd675dc4-ce1b-47c2-8188-d756b4b0976a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>7f5998c9-df7d-48e9-81ec-1558047ae454</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>eebc54a8-0a95-4360-9b7f-3c44f2c2fbf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>5831d12a-9d09-4a18-9854-354754be2c2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>007a0b0e-8351-46f1-a497-56d55cfdb6bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Explanation&quot;)</value>
      <webElementGuid>4891f70d-1ebf-4296-b0d3-abc284c6fc0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Explanation']</value>
      <webElementGuid>99b8f49f-693f-4bde-a811-301f7a491bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/table[2]/tbody/tr/td[2]/div/form/div[4]/table/tbody/tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7ed02b94-c02d-441e-b1db-d380f7f8f65e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>ccfe6b53-1496-41cb-baba-8ed6900f5b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Explanation' and @name = 'Explanation' and @type = 'text']</value>
      <webElementGuid>5ca6bd0f-6aaf-4699-97a7-a59ab9b01c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
