<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Choose how you would like to subm_913466</name>
   <tag></tag>
   <elementGuidId>156690bb-6c29-47a7-8f23-901249cac965</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SubmissionType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SubmissionType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c67fe90b-cde1-4d3f-81a6-8060817a6589</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>9974e9a1-cacf-4119-8bd6-683dabc7f8c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionType</value>
      <webElementGuid>af10501d-e5bc-4c90-a4b4-3a0224765cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionType</value>
      <webElementGuid>3d289884-cd3d-40ce-8bc6-f64494ac6528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>3a9c404f-a971-4d12-b484-42e735ab7fb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>3e453f10-3037-4f0b-91c8-c2f38fcee205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Choose how you would like to submit this quote --  Formal Quote  New Business </value>
      <webElementGuid>76e227eb-1732-4562-a072-57393f1ef6db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionType&quot;)</value>
      <webElementGuid>00467cdb-5543-4196-b943-a28d561e14b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SubmissionType']</value>
      <webElementGuid>bf425185-c5da-45be-9676-7343d6e6a716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/form/div/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>a16aaa14-9446-4134-942d-5deea74b4409</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit to Hastings Mutual as'])[1]/following::select[1]</value>
      <webElementGuid>56826c34-ffd1-4940-a2b4-951591e0eee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission'])[2]/following::select[1]</value>
      <webElementGuid>6055c728-b6df-4016-bf27-159394caf918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Quote'])[1]/preceding::select[1]</value>
      <webElementGuid>4dc4ce4b-67d2-4ec6-ab48-5cccbf087e3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue submission process'])[1]/preceding::select[1]</value>
      <webElementGuid>d4ee5029-381d-4693-8fc7-e7886c4a34c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>25f6d24b-6e5a-459f-848a-e77ff56da14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SubmissionType' and @name = 'SubmissionType' and (text() = ' -- Choose how you would like to submit this quote --  Formal Quote  New Business ' or . = ' -- Choose how you would like to submit this quote --  Formal Quote  New Business ')]</value>
      <webElementGuid>bdd3a38e-8f25-4c0a-a3e7-7848856273ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
