<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_login</name>
   <tag></tag>
   <elementGuidId>f6074644-1bb6-4c1f-afc1-0649e1f66135</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f5d603a8-76f6-4321-9bf9-7199affcd881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>cfd71fbb-95f9-4bc5-b967-991a619f30a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>11ee534e-4b7c-4f76-bfdd-9441f0cbabc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Log in</value>
      <webElementGuid>d5cf41c5-2cc3-448c-90b5-991eb4ff4359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>9de9608a-16d3-4ced-b682-3b663bc5406b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login&quot;)</value>
      <webElementGuid>424c3bce-22bd-481a-8128-ed0399107950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='login']</value>
      <webElementGuid>a8a593df-afcf-4947-a31a-f80bb0cfea3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginform']/div[2]/div/div[4]/div/input</value>
      <webElementGuid>f561ab4d-5475-4013-818c-74b5f5c6cb5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>f754638b-f43a-4e51-9a80-71ffecf5fc26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'login' and @type = 'submit']</value>
      <webElementGuid>a183c972-b4ba-48bb-8fab-d0b302706b39</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
