<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Coverage Amount_CoverageAmount</name>
   <tag></tag>
   <elementGuidId>bc37cbeb-d925-419b-860d-885b03823677</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CoverageAmount']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CoverageAmount</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8ecd3b9f-ae94-417b-88eb-4d448effaf47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>7f83419e-1ae8-4736-b1cb-e08cca959e16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoverageAmount</value>
      <webElementGuid>38da6aa1-d448-4dc2-b96b-dd4aee3d7d12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoverageAmount</value>
      <webElementGuid>9a9bb5b9-0c99-4f9c-9940-4528846d476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>7becd9ac-e21d-4b20-9d72-c3c006ed7ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit5</value>
      <webElementGuid>6491e24c-0794-4964-bc5e-3a5054076a14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>93718f5f-7190-4bd8-a412-0e80a0b66755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9f0e7cef-ba9f-40af-8fa6-d011b523c8ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>356c4302-61e7-4bd4-bdd6-caa2ec33b06e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoverageAmount&quot;)</value>
      <webElementGuid>2f654ec4-ab50-4967-9614-68d208c092bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CoverageAmount']</value>
      <webElementGuid>0063f765-3940-48bd-ac23-8ba47326f632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-recreationalVehicle-Add']/div/table[2]/tbody/tr/td/table/tbody/tr[6]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>ab76d078-d2ef-40f0-ab7f-970442284dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>cbcf7b9f-be84-423f-91dd-3cb97a377bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CoverageAmount' and @name = 'CoverageAmount' and @alt = 'limit5' and @type = 'text']</value>
      <webElementGuid>91ed9ecf-04d9-4d2a-a45c-540494d20047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
