<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Make  Model_MakeModel</name>
   <tag></tag>
   <elementGuidId>608ea392-4fa3-4740-8d27-a6deeb11f1f0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MakeModel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MakeModel</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4eb2e97-63af-4af0-b054-d43fa393dac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>0c818e9c-cabf-452c-9614-261f6cc371eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MakeModel</value>
      <webElementGuid>b821d735-b58b-41b3-b0ba-e64b89cd65de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MakeModel</value>
      <webElementGuid>16556fe1-dea6-44ee-8924-0ba8db7d6787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z '&amp;.,&quot;!@#$%*()-/]+$</value>
      <webElementGuid>f0d7b9fe-157f-4c80-b8ac-ca6572d321d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a9f559b3-f3bf-44bd-8c61-8a9b22bf5d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>83d95626-6d49-4d22-a5d6-043c99c629f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>fc13d13d-8ae4-458e-a12d-d1ef9ed52758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>44513c83-6b24-4f8f-82f8-fc1c0029eed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>90dd3934-e1d9-4941-bb7a-5b7df5858414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MakeModel&quot;)</value>
      <webElementGuid>0e84d57b-53a5-440e-baa5-010a8735ff57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MakeModel']</value>
      <webElementGuid>147cf1e8-45f3-44b5-85ee-00834e4072b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-RecreationalVehicle-Update']/table/tbody/tr/td/div/table[2]/tbody/tr/td/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>d82ee07d-5809-47ad-8b4f-dd3dafc98a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>1510664e-dd64-41ad-ae17-bea6387ea02c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MakeModel' and @name = 'MakeModel' and @type = 'text']</value>
      <webElementGuid>e8a16721-fc15-4559-ac16-8b0e60b84cdf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
