<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial  Identification Number_SerialI_5659dd</name>
   <tag></tag>
   <elementGuidId>c2a6f07a-e912-4bee-8e21-bcc2d62ca154</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SerialIdentificationNumber']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SerialIdentificationNumber</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>878c69b0-0921-48ac-802f-6252e646e646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>69e13089-eee1-45b8-a193-0e883bbbd234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SerialIdentificationNumber</value>
      <webElementGuid>c64dd817-2c44-459b-80d7-c511c6165057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SerialIdentificationNumber</value>
      <webElementGuid>486831de-87ef-4dbe-aacd-4705d98ed97f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z '&amp;.,&quot;!@#$%*()-/]+$</value>
      <webElementGuid>5dffd7b4-b741-4408-b461-c56a5deadd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>97076a46-21a4-44e8-aaa8-ba002c1dcf68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>f86ef2a7-e1d0-4eff-8b40-fb97d87c736d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>6133b782-066b-43a0-a8a8-14e3db45812b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>422f5d48-148f-490a-a8b8-1c17239167a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cdeced13-be38-44f6-ba18-86abc232abe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SerialIdentificationNumber&quot;)</value>
      <webElementGuid>471179de-e9ce-4f1e-8da0-e576fca4a4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SerialIdentificationNumber']</value>
      <webElementGuid>b8c9363d-edf8-4645-9651-4837c2d969d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-RecreationalVehicle-Update']/table/tbody/tr/td/div/table[2]/tbody/tr/td/table/tbody/tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>dd24b8d1-61ad-4dd9-8a69-a9b945c74d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7f5dc805-1fee-4103-a302-4c9bbbda05a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SerialIdentificationNumber' and @name = 'SerialIdentificationNumber' and @type = 'text']</value>
      <webElementGuid>8894a6f2-e179-4495-b600-d898c83e7071</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
