<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Snowmobile  Golf Cart  Tra_9fce2d</name>
   <tag></tag>
   <elementGuidId>b83737ac-b6ac-4b27-86b4-99fdf7eac61c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RMVClass']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RMVClass</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>31c57d28-4725-4fee-8875-6a0608df9cd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>54c876c7-40c9-44a2-8826-96ec8a01ea97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RMVClass</value>
      <webElementGuid>b84c7a3f-cdc0-49bb-8966-a4445c76dd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RMVClass</value>
      <webElementGuid>b37f8daf-d31b-43a7-98d0-c2e4e44eb8e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>e1e7d5d5-4d9e-4b51-85f1-9f4c94a7f31c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0708a321-59e9-4919-8002-2bc2bf51ce3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Snowmobile  Golf Cart  Trailer  ATV </value>
      <webElementGuid>d6adcc84-58a6-48bc-9714-67fb0ad3caaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RMVClass&quot;)</value>
      <webElementGuid>38b2a76a-fd44-428f-b4e1-571a839ebac2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RMVClass']</value>
      <webElementGuid>c187263f-4287-44bf-9653-2d3b0eeb8bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-recreationalVehicle-Add']/div/table[2]/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>53194a72-bbc6-4e2b-988b-e6f3b0a31696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class'])[1]/following::select[1]</value>
      <webElementGuid>60f4d41c-491a-4e6b-9f3d-815bf66a0c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The Recreational Motor Vehicle is not eligible for coverage.'])[1]/following::select[2]</value>
      <webElementGuid>704a7e43-8746-4563-8e47-e61c1f3c8a45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Model Year'])[1]/preceding::select[1]</value>
      <webElementGuid>25f23a0c-c333-4dce-a314-371e6d97dd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Make / Model'])[1]/preceding::select[1]</value>
      <webElementGuid>1e3fc54a-7063-4f61-a12f-118fd84eadc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>f49ec654-a15e-4f09-8ce3-ade4a59d53e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RMVClass' and @name = 'RMVClass' and (text() = ' (Select)  Snowmobile  Golf Cart  Trailer  ATV ' or . = ' (Select)  Snowmobile  Golf Cart  Trailer  ATV ')]</value>
      <webElementGuid>69c10dcd-cb66-495f-afaa-14245d91e211</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
