<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  50  100  250  500</name>
   <tag></tag>
   <elementGuidId>e27aac28-a795-4ed8-a19a-ee67658fde19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Deductible']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Deductible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e095491d-1ba5-432e-bf82-738196ccb90b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>1acc39d6-5872-42a7-bfca-d4c32a7db668</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Deductible</value>
      <webElementGuid>fc93a8fc-5dbb-4601-8bc8-2b6257ff62bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Deductible</value>
      <webElementGuid>c854b7b1-f275-4060-9f51-ff102b5a6ea0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>e0b5814f-9e37-4a55-8eb2-bdd84db52c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8c36e14e-638c-405e-b236-281ae5bee9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  50  100  250  500 </value>
      <webElementGuid>99e7f90d-6e96-40ee-9805-30a3740bbcf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Deductible&quot;)</value>
      <webElementGuid>d8d2af21-48a4-4daf-82db-f137c85f8a12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Deductible']</value>
      <webElementGuid>8fcef312-b515-484b-ada7-6903270eb898</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-recreationalVehicle-Add']/div/table[2]/tbody/tr/td/table/tbody/tr[7]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>10c64fe4-b80d-4f90-a822-a166e07b4adc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[1]</value>
      <webElementGuid>3a5144b2-3700-449c-ac22-178786ff1646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Amount'])[1]/following::select[1]</value>
      <webElementGuid>3cff96c4-7128-4206-ad54-81cd92ee9ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engine Displacement'])[1]/preceding::select[1]</value>
      <webElementGuid>f4519157-852e-40f6-9cbf-ab547370b280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Solely Titled to the Named Insured'])[1]/preceding::select[2]</value>
      <webElementGuid>104ef45b-5951-4aac-b40d-c464311527d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>273fda71-12ab-4115-a4df-cfc7c3dce75a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Deductible' and @name = 'Deductible' and (text() = ' (Select)  50  100  250  500 ' or . = ' (Select)  50  100  250  500 ')]</value>
      <webElementGuid>10619936-291c-45fe-860c-f7739e6ea822</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
