<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  0-600 ccs  Over 600 ccs</name>
   <tag></tag>
   <elementGuidId>19afdc61-8ff7-4c3f-82e4-65f1a29847c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EngineDisplacement']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EngineDisplacement</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c171d339-c3bb-48df-a90c-e0d148c01ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>2b0d20ac-f55a-4026-b342-42b3bbf29104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EngineDisplacement</value>
      <webElementGuid>1afea852-379b-463d-a38c-5b195e9b991c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EngineDisplacement</value>
      <webElementGuid>485c1810-a7a1-4a11-93bd-3bd927744ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>c335b210-a9d0-4f30-b78a-63764e479db9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>43ef52b9-ae09-47b6-ad28-e8ec632571d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  0-600 cc’s  Over 600 cc’s </value>
      <webElementGuid>2eef25ec-9064-4508-b09f-bf3ec511d232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EngineDisplacement&quot;)</value>
      <webElementGuid>8017765e-bb55-480f-966f-1663cb9321e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EngineDisplacement']</value>
      <webElementGuid>9f642226-aa03-4455-8b8b-29df7c89ecc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-recreationalVehicle-Add']/div/table[2]/tbody/tr/td/table/tbody/tr[8]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>adc063f1-4d30-4963-a837-d07c775fcbdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Engine Displacement'])[1]/following::select[1]</value>
      <webElementGuid>9e5ce92e-c18b-417a-8cd6-2435f0b5c90a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[2]</value>
      <webElementGuid>3aa04a8d-fea9-4fdb-b469-01211e82ca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Solely Titled to the Named Insured'])[1]/preceding::select[1]</value>
      <webElementGuid>1be0b59c-731b-4d9e-b99c-1971d95d83a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Titled Owner'])[1]/preceding::select[2]</value>
      <webElementGuid>e07efbd5-de90-414c-bf29-d39fb6a96a96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>bba48465-a3cb-44d0-9029-508d79685fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EngineDisplacement' and @name = 'EngineDisplacement' and (text() = ' (Select)  0-600 cc’s  Over 600 cc’s ' or . = ' (Select)  0-600 cc’s  Over 600 cc’s ')]</value>
      <webElementGuid>7a728649-d800-42e7-aaf6-ea1aaf81773b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
