<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  No  Yes, I have Loss Runs _504ea5</name>
   <tag></tag>
   <elementGuidId>9693463e-923f-4218-a09f-685ed66f785c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LossesExist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LossesExist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9de02625-891b-471c-9fa2-2b02d3311496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cf8f29e6-6e03-4eda-b4e2-418fd57e7992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>3ebbdb23-ca53-4a23-9090-814e03fb336c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>7f9b7f67-d831-419e-a807-cd8a28b66da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>80c57bee-68bc-4bc2-b07e-a6f64a41884a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>7ed3b3ec-8b50-40f3-a1a1-3160cb39ffea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information </value>
      <webElementGuid>a8d20023-48d9-4955-9955-5deefe0f4a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LossesExist&quot;)</value>
      <webElementGuid>ea5ecf82-3c43-4c6e-a400-6e3bdf4eb6d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LossesExist']</value>
      <webElementGuid>dcb88d5e-aad0-44b7-b010-9dee1fdd746e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>a12ff91f-add2-4694-b1e9-281884684baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any claims, losses, or occurrences in the last 3 years?'])[1]/following::select[1]</value>
      <webElementGuid>8d200205-7cf7-4909-a483-73774cedb611</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss History (3 Years)'])[1]/following::select[1]</value>
      <webElementGuid>2e6a4284-56d9-4486-a2a0-111810a661d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>66394488-cabc-40cf-b676-54214da98b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please schedule all Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>6390cc72-bedc-40fc-8e7a-05aabb572433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>31153183-1993-4126-9c5c-96dbc0501a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LossesExist' and @name = 'LossesExist' and (text() = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ' or . = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ')]</value>
      <webElementGuid>2feb2d5c-00d4-46d5-b3fb-f8790ebaeca2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
