<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Boiler  Electric  Natural _937852</name>
   <tag></tag>
   <elementGuidId>abcf9c60-9b25-4953-8181-e651931d5fbf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PrimaryHeatType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PrimaryHeatType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e51c0fe9-a307-4553-aec6-e54624a602d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d1a9e948-890c-45b5-b693-9baa1b8a87d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrimaryHeatType</value>
      <webElementGuid>487dd316-223c-46e2-825f-fbf62ba4f0c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrimaryHeatType</value>
      <webElementGuid>d8222535-84b2-4f49-ae72-15d108dd2a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>e76b4b1e-ba42-4f75-bb24-47fc2c6a540a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>8f358bf8-d8ec-40a4-9779-abdcc5a95ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Boiler  Electric  Natural Gas / Liquid Propane (LPG)  Oil  Solar  Space Heater  Other  None </value>
      <webElementGuid>cca3159d-d3aa-4a1a-abc7-d44edf170f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrimaryHeatType&quot;)</value>
      <webElementGuid>776c89ea-2079-479d-8f6c-549ef593b866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PrimaryHeatType']</value>
      <webElementGuid>d84f0e37-6055-4122-a77a-50b1f4373745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[3]/table/tbody/tr[13]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>b83bd0ee-59d4-4dd5-ae12-4cb2cfe6adbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Heat Type'])[1]/following::select[1]</value>
      <webElementGuid>43b0b6a3-4321-48d7-b51d-88a851dcc83b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photograph taken of risk'])[1]/following::select[2]</value>
      <webElementGuid>a592209a-0202-4b5b-a0d3-2063d32ab167</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary Heat Type'])[1]/preceding::select[1]</value>
      <webElementGuid>56ba6c8e-6ac9-4d7b-b1c0-932c0cab1ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dwelling Rented'])[1]/preceding::select[2]</value>
      <webElementGuid>e1d4651a-0401-4467-8cfc-3f40de07a7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>100b17dd-dfe8-4864-8769-1131c45ed712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PrimaryHeatType' and @name = 'PrimaryHeatType' and (text() = ' (select)  Boiler  Electric  Natural Gas / Liquid Propane (LPG)  Oil  Solar  Space Heater  Other  None ' or . = ' (select)  Boiler  Electric  Natural Gas / Liquid Propane (LPG)  Oil  Solar  Space Heater  Other  None ')]</value>
      <webElementGuid>52d2aa8b-4d90-4409-b44b-2ee8460e6cc7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
