<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Composition  Flat  Metal  _abd3da</name>
   <tag></tag>
   <elementGuidId>31a4ae1f-73be-4a45-b813-313d19aefc13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RoofType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RoofType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a92f12d3-7489-4d73-8451-2a609ae44d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3c98e2fd-c473-480e-8fbb-d63c33e23500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RoofType</value>
      <webElementGuid>8693a1f5-0327-406e-95d2-e5a38dcabf25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RoofType</value>
      <webElementGuid>83035b45-532e-49b3-a2cc-04821b4c7ae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>d7226a36-45a6-435c-aaae-d31cfc55b4db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>23</value>
      <webElementGuid>ec3ebbc7-27cb-47f5-95fe-e6c421cca042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Composition  Flat  Metal  Poured  Slate  Tile  Woodshake / Shingle  Other </value>
      <webElementGuid>604cb99b-fc36-4749-854c-e4ee0ca1d9b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RoofType&quot;)</value>
      <webElementGuid>4abf77cf-e7e2-48ad-8e01-9ee1ed8d587d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RoofType']</value>
      <webElementGuid>b4dd13b7-92da-4d69-8277-28e615103e86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[3]/table/tbody/tr[23]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>23d0b1b1-7247-4d8b-9a45-caef27b1dede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roof Type'])[1]/following::select[1]</value>
      <webElementGuid>ac6b93bd-7363-4c42-9379-ea3df9ba7f2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describe Business'])[1]/following::select[1]</value>
      <webElementGuid>a499aa16-4755-450c-8e84-fabb5a8a7970</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foundation'])[1]/preceding::select[1]</value>
      <webElementGuid>7e79ff7d-42b0-4e31-82bd-56e482b8118a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Dwelling Information and Coverages'])[1]/preceding::select[2]</value>
      <webElementGuid>83a5f8d1-d39c-408c-b889-52f9f90eb45c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>033b6cc9-cbae-4714-8b98-56aafe0a74e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RoofType' and @name = 'RoofType' and (text() = ' (select)  Composition  Flat  Metal  Poured  Slate  Tile  Woodshake / Shingle  Other ' or . = ' (select)  Composition  Flat  Metal  Poured  Slate  Tile  Woodshake / Shingle  Other ')]</value>
      <webElementGuid>9865b4b9-a5aa-48ea-8b2b-21da033deadf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
