<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Closed  Stilts  Poles  Pil_ba9362</name>
   <tag></tag>
   <elementGuidId>b68e4f26-ed0e-44bd-a5e5-254c791a5271</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Foundation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Foundation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e6345872-2093-43a4-b185-48940d87673a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>2e10d075-8dfe-4381-8b86-c4fdc615654d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Foundation</value>
      <webElementGuid>4c583cc8-c59f-4922-8f59-1fecb9cde411</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Foundation</value>
      <webElementGuid>f22ecb18-50d4-4876-841d-1144e21455fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>17d835a7-672a-45c2-ac82-b2b684cf90ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>8b4da71f-f332-4ff2-9bc1-e82d0f1e320f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Closed  Stilts / Poles / Pilings  Other </value>
      <webElementGuid>15981c7b-0159-4d09-981c-fcee981f8dea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Foundation&quot;)</value>
      <webElementGuid>e9decbbb-1ed9-43ea-95a5-5e5bd285880f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Foundation']</value>
      <webElementGuid>ea9635a5-1902-4bc0-9691-0065a91ea9c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[3]/table/tbody/tr[24]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>47eedaf9-656a-4406-a98a-de062f0971ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Foundation'])[1]/following::select[1]</value>
      <webElementGuid>a255cfe6-f71a-49b4-8d0a-33007feb73e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roof Type'])[1]/following::select[2]</value>
      <webElementGuid>04a963c1-ae2b-49ea-ab15-0fe43cf20199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Dwelling Information and Coverages'])[1]/preceding::select[1]</value>
      <webElementGuid>e05f3689-65dd-47bd-a87d-7f17708f5746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to Other Structures'])[1]/preceding::select[1]</value>
      <webElementGuid>de60becd-90a4-49e1-acd2-3f5390e2c17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[24]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>75500c87-37a0-4086-8d54-6c5241ba2490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Foundation' and @name = 'Foundation' and (text() = ' (select)  Closed  Stilts / Poles / Pilings  Other ' or . = ' (select)  Closed  Stilts / Poles / Pilings  Other ')]</value>
      <webElementGuid>c6320053-229c-4680-a0a6-7e4689b16a58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
