<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>539f9b43-f239-4bdd-b8bd-03dcf8712fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PhotographTakenOfRisk']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PhotographTakenOfRisk</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>65130768-5b18-4b4b-a4b9-ca35ad4a6645</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>01432336-0066-40db-8fe4-8bcfb8e3df1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhotographTakenOfRisk</value>
      <webElementGuid>2599e122-7a54-4d36-9b99-47edb3a7ac36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhotographTakenOfRisk</value>
      <webElementGuid>9d6fd7ca-1fc7-4e2b-a4e3-7e2546f42570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>b4afecdf-fc2d-4186-ab6e-471b8f0cb655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>6a403c2f-003e-43db-b36f-7ff7b3173bb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>a91c67d5-14ce-4080-a871-326bfdaba327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhotographTakenOfRisk&quot;)</value>
      <webElementGuid>f7bad4b0-0967-4192-8fb2-ec90cfb3b580</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PhotographTakenOfRisk']</value>
      <webElementGuid>4779b6d5-0267-4634-8061-7b02b218456c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[3]/table/tbody/tr[12]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>fb779f9c-3a84-475f-bce6-b650f1895ef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Photograph taken of risk'])[1]/following::select[1]</value>
      <webElementGuid>19604a2e-2ac7-4918-a878-100b5680e807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# of Units'])[1]/following::select[1]</value>
      <webElementGuid>d6f7531d-92b8-4561-aba6-6f04c567c166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary Heat Type'])[1]/preceding::select[1]</value>
      <webElementGuid>88ad97db-2308-42d3-9140-f09ec162c146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Secondary Heat Type'])[1]/preceding::select[2]</value>
      <webElementGuid>e06817e4-d533-4098-8047-924768d37100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[12]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>7f0d5115-2f2b-4427-9790-4bf43ee7e446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PhotographTakenOfRisk' and @name = 'PhotographTakenOfRisk' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>ed070563-8293-4d4e-b675-98f2f93f975a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
