<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone_MobilePhone</name>
   <tag></tag>
   <elementGuidId>01190973-5b14-4345-99bb-ede6aa2a9175</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MobilePhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MobilePhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1c4f229-d741-4b48-898e-c043898f78db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>16d43dda-492d-4f94-bd5b-7b96f27a4a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>51394840-5ed7-4c0c-98db-cdb04d63aac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>6e5971e2-2f95-4502-9bd8-134e6f11476e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pair-id</name>
      <type>Main</type>
      <value>contact-phone</value>
      <webElementGuid>7ff420da-4271-4458-881d-46223c9c03c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>fb92346d-0a69-4f2d-9f57-66cf3e9f7510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter phone number</value>
      <webElementGuid>66417879-6052-4522-8bcc-03f65a344e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter the telephone number without spaces or punctuation.&lt;br />&lt;br />&lt;b>Example: 6168675309&lt;/b></value>
      <webElementGuid>16d92de9-2567-4a43-831b-682aac65b1f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>e6fe43bb-ce4e-4c42-8568-7a15f5cf2b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\(?\d{3}\)?.*\d{3}.*\d{4}$</value>
      <webElementGuid>7aee19d4-038c-4dd9-8247-9930f45ebc39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>18215ed8-46cc-4d59-8418-454c9da18582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3ac8b2d-b872-4ed0-9b06-6bf1d57c00f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MobilePhone&quot;)</value>
      <webElementGuid>3ebb693a-1d01-4082-bd57-f5f5e9e4af0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MobilePhone']</value>
      <webElementGuid>ff404161-ae2d-4012-86c5-a99fe20036fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>8a0b37cc-0fb5-4dfc-ad90-2e6b24ed8794</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>f3fc7187-559f-4e31-a4ad-a314887c2d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MobilePhone' and @name = 'MobilePhone' and @title = 'Enter phone number' and @alt = 'phoneNumber' and @type = 'text']</value>
      <webElementGuid>1d6f8ca2-e632-4c52-8d89-0beb1a4aba44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
