<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Year Business Started_YearBusinessStarted</name>
   <tag></tag>
   <elementGuidId>6be6d3ff-d0a5-4920-8bf7-5997252482ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#YearBusinessStarted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='YearBusinessStarted']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c3924bf-38f1-4776-b193-b71bc73d49da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>6b56f62e-0dae-4cb3-98ef-5b245470ceb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>YearBusinessStarted</value>
      <webElementGuid>3ceceb66-59f1-47b6-bd31-e21f2be4e214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>YearBusinessStarted</value>
      <webElementGuid>cfb7ebc9-c073-46fb-b593-eafdae687098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>1480954b-b2e0-4bf8-8f98-546f3a921ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>386a5039-239d-40a3-8608-2f007127cff6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>9999</value>
      <webElementGuid>d2046e30-72ed-4b71-808d-883ae65e9a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>17d1b5ed-4744-46c7-a4ad-74a8b822d812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f6340891-1f93-48dc-afaa-0215cd0e7375</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3347d410-e93f-48bb-9e2f-d6cc87c326ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;YearBusinessStarted&quot;)</value>
      <webElementGuid>76b5b3c1-d6c7-4adb-b94e-c2c47865137e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='YearBusinessStarted']</value>
      <webElementGuid>0f9905ab-2b62-4976-b166-4c0578e7e515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[4]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>b1414e49-7222-4d53-a501-4cc58a50d456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>2d5a4ec4-5363-46e0-85c7-458360db7fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'YearBusinessStarted' and @name = 'YearBusinessStarted' and @alt = '9999' and @type = 'text']</value>
      <webElementGuid>fafb5b2a-a863-4a31-b7a0-9c0bc9fa7506</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
