<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Association  Corporation  _a924a5</name>
   <tag></tag>
   <elementGuidId>4e6ef13a-59e5-46ea-aeb1-fc8bcd313b29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Entity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Entity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f3a639c9-3ce3-4dab-909c-96d99a544020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>c9f8346a-17fc-4c6a-914e-9beb24ff5a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>42e74cdc-b7e3-450c-9c6f-e80338828444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>9ccf3ffb-0076-425e-8329-ff599cb999c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>d9296544-ef21-43c9-9a8e-b877b2fe842f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1dad284c-c19b-4cca-a47a-6e18e3644e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  Other  Partnership  LLC  Subchapter “S” Corp  Trust </value>
      <webElementGuid>a526a08c-9fad-42d7-b601-249d211718f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Entity&quot;)</value>
      <webElementGuid>36e22ce4-c4f6-47b4-b9ac-16ac7e43fb13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Entity']</value>
      <webElementGuid>549544ce-8662-4340-aff1-72faf1705b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>eb915964-225f-43a3-bd2e-a7f76d56ea1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity'])[1]/following::select[1]</value>
      <webElementGuid>d9af05bf-59cd-4d84-85ee-8abb10f00eab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Information'])[1]/following::select[1]</value>
      <webElementGuid>cf6dd176-7814-421c-bbc1-d9e360742b88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Description'])[1]/preceding::select[1]</value>
      <webElementGuid>6e367e23-61cc-4fdf-bbdf-6d83192d0131</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the applicant have a DBA name?'])[1]/preceding::select[1]</value>
      <webElementGuid>8a2a081b-ce6e-4359-b38a-4d10d4021717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a46570c4-2e8b-4021-9556-eacb17e7919f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Entity' and @name = 'Entity' and (text() = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  Other  Partnership  LLC  Subchapter “S” Corp  Trust ' or . = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  Other  Partnership  LLC  Subchapter “S” Corp  Trust ')]</value>
      <webElementGuid>495e74da-c317-4b37-9dc9-959cf0894f05</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
