<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description of Operation_Descripti_4b13ce</name>
   <tag></tag>
   <elementGuidId>b3b2612e-85ad-4dff-a7ff-2d0addb50934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DescriptionOfOperation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DescriptionOfOperation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>a4027fb2-dc63-4f0b-9e4a-30aae7a4473d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f9c1baee-f5a9-4ffc-8cc7-9263420215c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>0ecd5f27-490f-459d-97d9-6b69050162bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>5bdb1733-7f6a-4807-8fbe-ae13e5c82a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>76d250c5-979f-4343-879f-8dc9d6d3859d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>6f4a6efc-0a4e-4715-803d-455db0f847a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>768</value>
      <webElementGuid>88faaf9f-0147-4031-b693-3a4cf558abf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-editor hmi-ui-text-highlight</value>
      <webElementGuid>e9934206-3aec-48fa-b8ae-bc3ea0297ec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>0d0cb4f6-c8a1-4401-bd0b-86ffd6554606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DescriptionOfOperation&quot;)</value>
      <webElementGuid>18e5e9e2-decc-4712-97fc-fa6cea449e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DescriptionOfOperation']</value>
      <webElementGuid>f2e9a555-effd-423d-bed8-0266a538ab86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[4]/table/tbody/tr[2]/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>ce0aaf3b-e0bb-4c02-99d1-14e7edae218f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>1c769bb4-9077-4cef-934a-1bd7223fc39a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DescriptionOfOperation' and @name = 'DescriptionOfOperation']</value>
      <webElementGuid>2d75701c-8b16-44dd-ba40-334b6f603e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
