<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy Level Coverages_buildersRisk</name>
   <tag></tag>
   <elementGuidId>051a37fc-201f-4e5f-926b-56718d91b944</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildersRisk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildersRisk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c096c8fe-1fdb-4874-84c8-006c1910f9ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>9350f73c-c71b-48a9-bd23-9728784d9403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>0d82009f-b351-453e-bfdd-1ae8fc80905d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildersRisk</value>
      <webElementGuid>4b791680-4db4-42d0-8de4-75a21b43d8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildersRisk</value>
      <webElementGuid>0c94327e-60af-428d-b5ae-3abfc7adc968</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>e5b8ad07-eada-4c23-b9d0-321514b16e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ff8ea3c9-f73b-4a30-9dc5-a1a618c3ed37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>cbdf3a54-04af-4bc5-b028-f7143dc84fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildersRisk&quot;)</value>
      <webElementGuid>7dccb439-0c50-4ec4-a1a1-4d0fc1ca3851</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildersRisk']</value>
      <webElementGuid>9cabd885-8284-42c6-a465-23f10952c96c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div/div/form/div[2]/table[2]/tbody/tr/td/input</value>
      <webElementGuid>0435e75f-ca9b-4dae-82f5-95d3150f3f91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td/input</value>
      <webElementGuid>75da99f8-ce1b-4b01-905e-2bb810fd8b8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buildersRisk' and @name = 'buildersRisk' and @type = 'checkbox']</value>
      <webElementGuid>a221ddb4-c8ff-4973-bbf0-615d4bb1fa58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
