<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copy from Mailing Address</name>
   <tag></tag>
   <elementGuidId>70a4ed0f-277c-453d-81c4-1ef4dd955485</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#copyFromMailingAddress > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='copyFromMailingAddress']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>464fa079-7d35-4031-b343-f31e6e6b8309</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>92e1cd73-61fb-4574-b185-f14158f15d52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy from Mailing Address</value>
      <webElementGuid>1b8c01ed-caa1-43c9-b593-435d20c0f20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copyFromMailingAddress&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>947b55ae-5be7-4a9b-bef7-56ba325e2460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='copyFromMailingAddress']/span[2]</value>
      <webElementGuid>624facb0-32e3-4d78-b5b8-f203dac58352</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Address'])[1]/following::span[3]</value>
      <webElementGuid>597d7bef-e93a-47d8-b820-1a8357dee1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name'])[1]/following::span[4]</value>
      <webElementGuid>41e44916-1c49-4977-b3d9-22e018a2c2cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::span[1]</value>
      <webElementGuid>88ae338b-8d3f-47f3-af6c-15bb0ad19c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::span[1]</value>
      <webElementGuid>4904ff68-4971-4449-928a-6944f438fc53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy from Mailing Address']/parent::*</value>
      <webElementGuid>7aa2c4c3-931c-49be-bf0d-110513c8ff33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/span[2]</value>
      <webElementGuid>c12bffca-58ca-4158-8971-b4ebbef10e65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Copy from Mailing Address' or . = 'Copy from Mailing Address')]</value>
      <webElementGuid>9ff31700-7deb-4104-b75b-fb725a1f1102</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
