<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save and Close</name>
   <tag></tag>
   <elementGuidId>88a6ff28-db96-4644-84dd-549c029c8bdb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SaveAndClose > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='SaveAndClose']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d9be258b-9de8-4e17-a9fc-d9ce856fbed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>d59c4886-6732-4633-a22f-f8cc5dbc3b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save and Close</value>
      <webElementGuid>76d78f80-83a4-4799-ab6a-f2aa49be7a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SaveAndClose&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>a206dc38-db96-4196-a881-5cbae1b36d0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='SaveAndClose']/span[2]</value>
      <webElementGuid>5a032811-320a-483e-96df-ccd0e7f6ce6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::span[2]</value>
      <webElementGuid>ec22f900-3fd5-4b42-bd13-e78c1143b5fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ave and Close']/parent::*</value>
      <webElementGuid>405a0351-726d-43c0-9b40-7f039abb2d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/form/div[4]/button[2]/span[2]</value>
      <webElementGuid>356661c4-2e94-48d7-9cfb-fcab8ae58813</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Save and Close' or . = 'Save and Close')]</value>
      <webElementGuid>e04972d3-3d67-48a8-90ad-b81edd144f07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
