<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Agency Bill  Direct Bill C_b7d1a8</name>
   <tag></tag>
   <elementGuidId>942779a8-eae8-45ff-a6b7-22e0d757c595</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='BillingMethod']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#BillingMethod</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4f3e5459-8bcf-4703-9a80-03218b1872ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5aebb226-9881-48fd-8994-abbe6f0e4d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BillingMethod</value>
      <webElementGuid>a1e0eaeb-40bd-46ba-b1d2-d2d5922561c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BillingMethod</value>
      <webElementGuid>4012b0d6-1bcf-49b5-a8c7-690a82d05f20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-dirty</value>
      <webElementGuid>2fc16364-44a5-45c6-b2e2-cefa0d825584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ecc58768-537b-471c-8271-e3cf49aa525a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Agency Bill  Direct Bill Collection Method  Recurring Credit Card  Recurring EFT </value>
      <webElementGuid>11c4a2a1-cd6a-4843-b34d-821bcbf92fc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BillingMethod&quot;)</value>
      <webElementGuid>ac23f79f-d214-4423-a328-8bd31d1bba62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='BillingMethod']</value>
      <webElementGuid>b252f747-36c8-4368-84d8-53b5eaca707f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='PaymentPlan']/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>24d33078-9779-4044-a232-385fc486d227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How will this policy be billed?'])[1]/following::select[1]</value>
      <webElementGuid>8aad49f5-5372-428d-9190-1956ef8382ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Billing charges do not apply to Recurring EFT.'])[1]/following::select[1]</value>
      <webElementGuid>c0f4b75f-6f00-4294-92e6-2dc710011293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment Plan'])[1]/preceding::select[1]</value>
      <webElementGuid>c10d5e1b-99a1-4aab-84a0-3707bfe1ca19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Direct Bill, Paid in Full'])[1]/preceding::select[2]</value>
      <webElementGuid>d10e3b75-f6c9-4eab-94ba-077ecc2e6147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>aa117bb8-6a24-44df-aff6-8cd50b1d2fe8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'BillingMethod' and @name = 'BillingMethod' and (text() = ' (Select)  Agency Bill  Direct Bill Collection Method  Recurring Credit Card  Recurring EFT ' or . = ' (Select)  Agency Bill  Direct Bill Collection Method  Recurring Credit Card  Recurring EFT ')]</value>
      <webElementGuid>e2ddf3d2-1d1f-4591-9cb0-5343ca0826cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
