<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_IndictedOrConvictedOfFraudAnswer</name>
   <tag></tag>
   <elementGuidId>2b179d9c-39c9-4d2d-983a-dcc71797e804</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IndictedOrConvictedOfFraudAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IndictedOrConvictedOfFraudAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>edda1c5b-d0df-422d-93ee-f1443f622a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>25988b19-0ad8-437b-9a94-c8cc26c1ea8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IndictedOrConvictedOfFraudAnswer</value>
      <webElementGuid>2b9d845b-9e0c-43ec-8379-54092dac33e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IndictedOrConvictedOfFraudAnswer</value>
      <webElementGuid>37f8b4d9-c280-49f1-b83e-b09562d1be98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>6718a3b7-3754-47b7-ab15-567ff4571f94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>5577bb8f-f9e4-469a-90a4-80511badaaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>7a17756f-2824-495a-bdb4-498feca837cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IndictedOrConvictedOfFraudAnswer&quot;)</value>
      <webElementGuid>bcd400f6-2a13-4162-91d4-f381874574da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IndictedOrConvictedOfFraudAnswer']</value>
      <webElementGuid>cad2fa82-fa37-4791-a9a8-ce8508330a65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[15]/td/table/tbody/tr/td/select</value>
      <webElementGuid>9e28cf2e-d8a9-4889-9e82-b43afa486232</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/following::select[1]</value>
      <webElementGuid>798f4db6-9cb8-490f-8a5a-785474723be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/following::select[2]</value>
      <webElementGuid>49e36ba6-4266-47c8-b733-88f996167ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/preceding::select[1]</value>
      <webElementGuid>4e6928b3-84be-4051-b130-7f97722a9e04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any uncorrected fire and/or safety code violations?'])[1]/preceding::select[2]</value>
      <webElementGuid>3551f6a7-bdb6-47fd-9b3a-fa953b5b616b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td/table/tbody/tr/td/select</value>
      <webElementGuid>feedef25-d468-4bae-96b3-8dc096d7d6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IndictedOrConvictedOfFraudAnswer' and @name = 'IndictedOrConvictedOfFraudAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>858fe5a8-c874-4bff-8c02-6e086d098a25</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
