<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JudgementOrLienAnswer</name>
   <tag></tag>
   <elementGuidId>78a86275-44b0-41a5-bb14-d803cf0952a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JudgementOrLienAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JudgementOrLienAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27250cfd-af37-4227-84d1-dfd9f28f0296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>8f7868a8-a24d-41ca-9f25-152119ed8b75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>ded3c106-873c-4d70-a4fe-1015b58533b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>f90fed10-73bf-4625-b467-cf6a45650d9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>5ebba0c2-35ab-4695-8a44-c601ae16313f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>fa35beee-dc5c-4ea5-bb35-89edfc81c5d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>3ed7fc01-94f7-43a2-84b5-cc7c6c26649d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JudgementOrLienAnswer&quot;)</value>
      <webElementGuid>161b4224-954d-4854-880e-28940c816aac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JudgementOrLienAnswer']</value>
      <webElementGuid>61353694-a8c6-4fae-8c32-eac9aa2b7bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>5978a062-f430-4ab1-a50f-ae38d89eeea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[4]/following::select[1]</value>
      <webElementGuid>721f664d-85b2-4113-b448-c432d0229d4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[4]/following::select[1]</value>
      <webElementGuid>aae49620-0ed2-42b9-ac2e-ecb12d0d18ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Applicant had a judgment or lien during the last five (5) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>18254db3-9232-4b42-b54e-2d0f0b5034b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[5]/preceding::select[1]</value>
      <webElementGuid>5b6d3f99-5731-4e1d-8faf-45dbd23281e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>41a28fa9-16d2-49d2-ab8a-2a391306d442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JudgementOrLienAnswer' and @name = 'JudgementOrLienAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>5882ed59-a6ae-4305-a9ed-7a5368422760</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
