<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_OtherBusinessVenturesAnswer</name>
   <tag></tag>
   <elementGuidId>1faab8a2-8a0b-4b47-bf8a-7bf1b9638730</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtherBusinessVenturesAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OtherBusinessVenturesAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dd6cb5c6-717c-46a7-9c48-c474b4093ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f584b977-fcae-4e10-8217-63f54701092f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtherBusinessVenturesAnswer</value>
      <webElementGuid>905d91e7-a49b-42e9-bb71-4c7e5c6fb504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OtherBusinessVenturesAnswer</value>
      <webElementGuid>a0e28785-f986-4c09-9687-5651c699ef81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>ab93d06a-c087-4de5-99f5-45ce9885f614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>66</value>
      <webElementGuid>571e6a76-fb99-4b0f-b5e8-41d198427d73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>3e7220e1-02d5-4af3-a05e-9c2a176c979d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtherBusinessVenturesAnswer&quot;)</value>
      <webElementGuid>fdb86572-f906-487b-804a-1cee714992d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OtherBusinessVenturesAnswer']</value>
      <webElementGuid>ba31c707-82c1-433b-9090-b949a2fe9ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[27]/td/table/tbody/tr/td/select</value>
      <webElementGuid>b61bb103-5fad-4430-86b9-fb7dbfc6fdf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/following::select[1]</value>
      <webElementGuid>2769af0b-48a7-4e41-86cf-a9a3e3325de7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/following::select[2]</value>
      <webElementGuid>6bb00ca6-3936-44d0-82ce-8437434bec35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does Applicant have other business ventures for which coverage is not requested?'])[1]/preceding::select[1]</value>
      <webElementGuid>f1d33065-6cec-412d-9dd2-59a878274cb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[13]/preceding::select[1]</value>
      <webElementGuid>3cfe12a3-269c-4e86-abe1-91db8b8f8177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td/table/tbody/tr/td/select</value>
      <webElementGuid>7664b01b-9356-457f-90c6-89052158859e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OtherBusinessVenturesAnswer' and @name = 'OtherBusinessVenturesAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>6341b751-d17d-4c22-bd05-7defcde0bc0d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
