<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FormalSafetyProgramAnswer</name>
   <tag></tag>
   <elementGuidId>1000f261-f68b-4d8e-8be5-0898048e76d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FormalSafetyProgramAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FormalSafetyProgramAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>10115684-d6d9-46fc-97d6-1ecb53c99268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>49c330f9-8009-42df-9457-2a31d9e3fe3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormalSafetyProgramAnswer</value>
      <webElementGuid>3075ea03-5082-492b-8fc3-d70976031bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormalSafetyProgramAnswer</value>
      <webElementGuid>1ee49075-788d-4225-81a9-3698e79b4ea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>c6363809-4ca8-4878-bf8e-d32ae4394b64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>3cee2171-a1a4-4260-9802-8ac5ed78c056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>8439be67-8f50-4c5b-b4ef-18d6c9efebe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormalSafetyProgramAnswer&quot;)</value>
      <webElementGuid>ec876106-0e48-4fc6-af8c-13e6aa71d21b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FormalSafetyProgramAnswer']</value>
      <webElementGuid>6e0b5a71-d09a-4b02-885e-3f6d859a0cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2e518bb9-cb7e-4db0-b6f2-bf26d8bf8649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% Owned'])[2]/following::select[1]</value>
      <webElementGuid>d0364e31-4562-4fe8-b595-9b005449706b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship Description'])[2]/following::select[1]</value>
      <webElementGuid>4c57073d-3b37-43b5-aebd-44a5a0a1f317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is a formal safety program in operation?'])[1]/preceding::select[1]</value>
      <webElementGuid>7c0f5439-807d-42f8-b493-f391c8d065aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety Manual'])[1]/preceding::select[1]</value>
      <webElementGuid>aff1179e-38c6-4f11-9d02-2a9c7da6d39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>bc20f3f8-2a57-4d68-8a00-fb85e500ac78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FormalSafetyProgramAnswer' and @name = 'FormalSafetyProgramAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>23d2de84-5d5f-4525-84f4-0700be7fc4a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
