<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_CoverageDeclinedAnswer</name>
   <tag></tag>
   <elementGuidId>911a78d3-cac1-48df-9a13-ee690c428056</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CoverageDeclinedAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CoverageDeclinedAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b0709afc-44c7-4b43-948a-349e61925f2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>8ea2cd1f-2f65-4506-968b-112b364ec35c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoverageDeclinedAnswer</value>
      <webElementGuid>09ccd62f-d00e-4cc5-b19e-ed9a20845f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoverageDeclinedAnswer</value>
      <webElementGuid>6e4c300b-db5c-4190-b1b0-ad317b574b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>0f740451-e507-43d2-90e2-f345435cce0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>22</value>
      <webElementGuid>4e9edd75-318f-4335-a5f9-cb3a4a0920b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>de18a9ba-2ab5-4c71-b9af-2f84153c3130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoverageDeclinedAnswer&quot;)</value>
      <webElementGuid>e80da371-5516-4e5b-aadc-4d7bb02a9c50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CoverageDeclinedAnswer']</value>
      <webElementGuid>ddc506ad-5552-4df0-9e5b-ef78bd86ade2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>c5ef815a-a357-42ca-9af8-c43e4596ca0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e'])[1]/following::select[1]</value>
      <webElementGuid>45792485-369e-4d51-825f-9fabcaa0ef87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Payment'])[1]/preceding::select[1]</value>
      <webElementGuid>bcff9ef2-9e59-4f22-8edd-ff0f3a4bcf12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non-Renewal'])[1]/preceding::select[1]</value>
      <webElementGuid>d96edd55-6c54-4b17-abc2-b6c07419dfc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>44b84065-223b-4242-b397-23a98f53f981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CoverageDeclinedAnswer' and @name = 'CoverageDeclinedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>e18381ed-b1c3-41f2-9ef4-0a846d21baf3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
