<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ForeignOperationsAnswer</name>
   <tag></tag>
   <elementGuidId>8944fea1-7d56-4a92-8ea6-191ccadf0d51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ForeignOperationsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ForeignOperationsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a27c5406-98ad-4bd5-93c0-04e27a53f113</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>0bc50b5c-566e-43d7-90f3-fd9efd425a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForeignOperationsAnswer</value>
      <webElementGuid>d2236d2a-2448-4381-9131-f91384d4b61c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForeignOperationsAnswer</value>
      <webElementGuid>a2155ac2-cd4a-4378-8e32-85e5bae687e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>bf77dd1e-53cc-498c-9f46-ba8cfc84d54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>23711e22-ebc1-44ee-9e07-64ad88d6a95e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>d663c872-6e45-4eb5-957b-87a56265595d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ForeignOperationsAnswer&quot;)</value>
      <webElementGuid>a3a59c34-f48f-4269-93e7-213f8816414c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ForeignOperationsAnswer']</value>
      <webElementGuid>3f404dba-d8c6-4131-9bce-a9dc4a99fdba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>550f1dae-8bca-451d-ad0d-beeabd09d27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/following::select[1]</value>
      <webElementGuid>44affc2b-abf8-4529-9c70-e68b85e73507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has business been placed in trust?'])[1]/following::select[1]</value>
      <webElementGuid>67ff38e7-a2b4-4334-9e23-d7f379f58196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/preceding::select[1]</value>
      <webElementGuid>314a4709-0924-4fb1-8f7a-a0ab77b2938e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does Applicant have other business ventures for which coverage is not requested?'])[1]/preceding::select[2]</value>
      <webElementGuid>1810223a-94d1-477c-a6ef-829a54f03639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>24c002dd-fde4-4ffb-bb52-c2f7799ac1e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ForeignOperationsAnswer' and @name = 'ForeignOperationsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>32bc114c-8aa4-45b7-bdfe-da2bd03323b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
