<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_ApplicantHaveSubsidiariesAnswer</name>
   <tag></tag>
   <elementGuidId>0aecc0bb-ea90-4b3f-af4e-bdb5a3825640</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantHaveSubsidiariesAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ApplicantHaveSubsidiariesAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>35065e88-c2e7-4c1e-b360-770afc2ae673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>a58e9852-6794-4424-a0b0-c0c0bfbc8cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantHaveSubsidiariesAnswer</value>
      <webElementGuid>6dc15985-79e3-4464-8ffa-1bf4c8c03dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantHaveSubsidiariesAnswer</value>
      <webElementGuid>0174d27f-f16e-45f0-878d-bc9606a73a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>363bfad3-237e-4b3c-9979-995b92c2e96a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>5d3158ac-db7f-4b6e-ad7f-7ecefbd3c1e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>a1f264a6-1553-4cb9-bbaf-beedc9f4f46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantHaveSubsidiariesAnswer&quot;)</value>
      <webElementGuid>742234e9-a6f8-4e2d-ad9e-9aaa96eef55b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ApplicantHaveSubsidiariesAnswer']</value>
      <webElementGuid>f0089517-6eb6-4dc8-a488-84b54f530e63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>ed9c7f33-47b1-4830-a3b9-55678e8133ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% Owned'])[1]/following::select[1]</value>
      <webElementGuid>0e95987b-e7ed-4d5d-80f3-4c7fe10a601b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship Description'])[1]/following::select[1]</value>
      <webElementGuid>1113397d-02e4-4c84-a77d-4bfad5be70c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the Applicant have any subsidiaries?'])[1]/preceding::select[1]</value>
      <webElementGuid>429424ff-deaa-41af-bc42-79c84b8ed5d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsidiary Company'])[1]/preceding::select[1]</value>
      <webElementGuid>8a9dd7a9-c3f3-4f2c-af58-9f0c291b7edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>78ea6bae-8ac5-4735-931f-23ee6d118bce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ApplicantHaveSubsidiariesAnswer' and @name = 'ApplicantHaveSubsidiariesAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>0c5c1669-dcee-42a3-9ebc-f53b572364bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
