<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Territory_Territory</name>
   <tag></tag>
   <elementGuidId>54d0d49a-3109-486a-8435-27ecbf27f416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Territory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Territory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c500b6bc-2bb5-4293-b7ea-7eabc6c68c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>facb7e46-ea37-431e-870e-3004bba2efad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Territory</value>
      <webElementGuid>397ca99e-9336-46da-b4c7-55b557eae157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Territory</value>
      <webElementGuid>e5812f13-93c6-445c-a4ca-70923ea49963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>number_3_digits</value>
      <webElementGuid>95f7f0a6-9018-4c5d-bed1-980773f78d82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>279f1fe7-8a68-41af-b99c-d03cf096145b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter the territory with leading zeros.  &lt;b>Example 004&lt;/b></value>
      <webElementGuid>a1abc49e-51ba-47c2-a862-25bb461ce1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>qtip hmi-ui hmi-ui-text-focus</value>
      <webElementGuid>160568b1-57b8-408f-8838-ad4c177d764b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>6241eccf-8f98-461a-af15-eef9a08a81cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d51f3af3-1d1b-41a5-96c7-ee07468ebf80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Territory&quot;)</value>
      <webElementGuid>7a87ab9a-1dfe-4c4c-996f-ecd90e137e0b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Territory']</value>
      <webElementGuid>df41a510-d90a-4910-bfa6-1b9f8fb51d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[2]/table/tbody/tr/td[2]/div/form/div[2]/div[2]/div/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>e81e90dc-e25f-4c97-b44e-faaa5c03a8ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c9d29972-6794-4dff-b021-9d3b7e4ba16e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Territory' and @name = 'Territory' and @alt = 'number_3_digits' and @title = 'Enter the territory with leading zeros.  &lt;b>Example 004&lt;/b>' and @type = 'text']</value>
      <webElementGuid>c313238f-05e6-43e4-909f-8ef810e31c3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
