<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copy from Mailing Address</name>
   <tag></tag>
   <elementGuidId>db6bf22e-8efd-4a70-bc7e-d251c5d62478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#copyFromMailingAddress > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='copyFromMailingAddress']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8df0936e-3975-4047-8094-990afe20443b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>ab716ae4-9fae-4dfc-8957-f2b423b8553b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy from Mailing Address</value>
      <webElementGuid>99318f0d-dcd8-4878-9bfe-3c0be4941349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copyFromMailingAddress&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>9c6bc0c4-7c3f-4bd3-aff2-6432346e21da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='copyFromMailingAddress']/span[2]</value>
      <webElementGuid>38d98026-7988-4c36-9015-04e5d1f8815a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Address'])[2]/following::span[3]</value>
      <webElementGuid>cd377010-eb35-499a-a2b8-9cd5313f52f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverages'])[1]/following::span[4]</value>
      <webElementGuid>9a469d98-c5df-4ea4-9c1a-18a529ea314e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::span[1]</value>
      <webElementGuid>489e2724-1581-48fc-adfd-59315b1d23b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::span[1]</value>
      <webElementGuid>2d6c0d9f-044e-45e2-a3ad-3a94a180867f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy from Mailing Address']/parent::*</value>
      <webElementGuid>5721ffc3-f45b-44cb-b781-52eed2cba1c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/span[2]</value>
      <webElementGuid>6e9556f6-4db7-4a11-9781-1544fa982af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Copy from Mailing Address' or . = 'Copy from Mailing Address')]</value>
      <webElementGuid>469c2500-85c0-4721-8426-ba37b81f5698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
