<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Automation Test</name>
   <tag></tag>
   <elementGuidId>1e346ea6-9dfc-4450-9aeb-c3a09270cabc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PrincipalOperatorb830fd7146f47558095d8659e3ce66b</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'PrincipalOperator')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>437deada-b5b6-43a5-a655-70415990eac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>550d0405-d5cc-4664-9e36-72cfe408cbf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PrincipalOperatorb830fd7146f47558095d8659e3ce66b</value>
      <webElementGuid>df819053-d779-4af2-b602-d1022a465de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PrincipalOperatorb830fd7146f47558095d8659e3ce66b</value>
      <webElementGuid>3570364c-4411-40b3-a864-b6296c07096e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>2b8f8b9e-9c78-4ce2-8d63-d227b187052d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>427f5706-3985-4f39-857d-78029b786779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Automation Test </value>
      <webElementGuid>dfc4b5a5-319b-45c7-a534-d1c6200fcc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PrincipalOperatorb830fd7146f47558095d8659e3ce66b&quot;)</value>
      <webElementGuid>c1934043-4754-410d-9e6c-5d3998bc63ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PrincipalOperatorb830fd7146f47558095d8659e3ce66b']</value>
      <webElementGuid>bced0b25-2af0-438c-bbd4-aeb5b8bae870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vehiclelist']/div/table/tbody/tr[2]/td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>35a332dd-cadc-4f2c-8009-fba494a272fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GMC CANYON CREW CAB SLT'])[1]/following::select[1]</value>
      <webElementGuid>43afaad5-aba9-41bc-9275-dd4152c50ec0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Principal Operator'])[1]/following::select[1]</value>
      <webElementGuid>5e6f0133-fef9-4fcf-9d73-d192233afb4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Vehicle Information'])[1]/preceding::select[1]</value>
      <webElementGuid>f87fccb8-1f5e-46cb-8783-afc93df5bf31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue to Prior Carrier / Credits'])[1]/preceding::select[1]</value>
      <webElementGuid>16f638b6-bbc4-4bc5-8bcc-475af54b56c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7e643a9e-b337-4d3e-a2dc-5418816d7c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PrincipalOperatorb830fd7146f47558095d8659e3ce66b' and @name = 'PrincipalOperatorb830fd7146f47558095d8659e3ce66b' and (text() = ' (select)  Automation Test ' or . = ' (select)  Automation Test ')]</value>
      <webElementGuid>a0a7ba1e-875f-4ad0-a917-259854cf0d99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
