<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10</name>
   <tag></tag>
   <elementGuidId>8b755564-e3a9-423a-a7a6-c9ee8249f769</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JudgementOrLienAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#JudgementOrLienAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>34eab861-3377-4ac4-b020-ffa5a39c02a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>52fde829-6105-4386-bb7a-ed86d12e28db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>779f062d-e037-4cc0-bc5b-d6530c1485d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>630b80bd-8ec7-4dd4-823f-7736f892ef7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>d8276fea-ae7b-446e-8f23-fd2ab1fdc0a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>4bd63fb1-17e7-47b3-a1ad-13b3a77876d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>78981ca1-21d6-4ed8-9817-e30e01ed6a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JudgementOrLienAnswer&quot;)</value>
      <webElementGuid>16ca1717-2385-4b18-a45f-90a42039f676</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JudgementOrLienAnswer']</value>
      <webElementGuid>367ec9de-f889-4eab-84e0-4f7c5f252f3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2ffb1f0f-a228-41e7-9030-050fec2abbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[4]/following::select[1]</value>
      <webElementGuid>fb55edd2-a78f-4bab-be6f-356477fadd28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[4]/following::select[1]</value>
      <webElementGuid>8b32280b-a5eb-4362-966d-5b2102131752</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Applicant had a judgment or lien during the last five (5) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>976cb0eb-d64e-41c9-83be-4b33847f2d64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[5]/preceding::select[1]</value>
      <webElementGuid>8660cefa-7150-427e-af93-7a5ebc1c6300</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8e29dbf9-e6ca-4878-8d38-5a1cdaf22b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JudgementOrLienAnswer' and @name = 'JudgementOrLienAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>6213c8aa-02ea-45e5-ac0f-6d6384670122</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
