<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>a8816449-d086-447d-b8bc-a567e4859bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ForeclosureRepossessionOrBankruptcyAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ForeclosureRepossessionOrBankruptcyAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8d685db6-23aa-4420-a392-791641c72757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>495e736c-1d21-45b1-b430-8b16fcba6b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForeclosureRepossessionOrBankruptcyAnswer</value>
      <webElementGuid>96643265-0ddd-4cae-b4c4-bda8d94512ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForeclosureRepossessionOrBankruptcyAnswer</value>
      <webElementGuid>bb1048c4-ff5e-4253-88ba-c890d500c046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>5da335be-eb0b-4e8a-a08b-bf1af3ccbfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>a1fc088d-7a24-44fc-b61c-cc366311f8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>7c8baa8c-8388-4505-9d0b-1f4ac0dad525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ForeclosureRepossessionOrBankruptcyAnswer&quot;)</value>
      <webElementGuid>a0eb417f-2af4-4748-965a-0bfe992825ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ForeclosureRepossessionOrBankruptcyAnswer']</value>
      <webElementGuid>66a5ef46-a6fd-4f3a-b794-56ed7dab7f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[19]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2f77b9f5-56ba-406a-9a8a-96d5e0c5ec41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[2]/following::select[1]</value>
      <webElementGuid>110b6825-60ec-455d-9dca-ccc3c1fb6dd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[2]/following::select[1]</value>
      <webElementGuid>dd101b09-f9df-44a0-b8bc-b390f4fa0b43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[3]/preceding::select[1]</value>
      <webElementGuid>6e457017-a2f7-47e8-ada8-63b07c977ac5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[8]/preceding::select[1]</value>
      <webElementGuid>32483adb-8aed-4492-9b23-e788866922c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td/table/tbody/tr/td/select</value>
      <webElementGuid>46ffe27b-af66-49d0-883b-5a04c1e9c708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ForeclosureRepossessionOrBankruptcyAnswer' and @name = 'ForeclosureRepossessionOrBankruptcyAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>f3be8f54-5b38-4ef3-ac6e-c9cbd047398c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
