<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  0-100 miles  101-300 miles</name>
   <tag></tag>
   <elementGuidId>cb37e67b-b8d8-4f4a-8858-f1ac8646338c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-container']/table/tbody/tr/td[4]/table/tbody/tr/td/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Radiusabf47263446e860ecbe41ddebd37</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e9c0fff-e679-43f7-be1f-c39ec775c2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>66956c55-474a-4807-8620-4eec7e6cf6d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Radiusabf47263446e860ecbe41ddebd37</value>
      <webElementGuid>76cc8f40-bc01-4ba6-9330-fbf0addd2bce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Radiusabf47263446e860ecbe41ddebd37</value>
      <webElementGuid>45e0fb47-78a3-49ee-9455-d0e2ff26bd94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>7ffd974e-8e32-46a4-bd41-43f174f75f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>fc72c26b-8114-4a65-a27b-84ee739dfe73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  0-100 miles  101-300 miles </value>
      <webElementGuid>8dcacc4c-bc6f-4b3a-9ded-c7373868d811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Radiusabf47263446e860ecbe41ddebd37&quot;)</value>
      <webElementGuid>07e41f25-fab8-45eb-8648-dbf0d10bc96b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Radiusabf47263446e860ecbe41ddebd37']</value>
      <webElementGuid>75571977-f596-457f-9d6c-357a7f6d9329</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-container']/table/tbody/tr/td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>b61a3738-ef62-41cf-bc51-deaf63e5d237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radius'])[1]/following::select[1]</value>
      <webElementGuid>03eb4ff9-04d8-4415-8002-35bc509f4c6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Type'])[1]/following::select[2]</value>
      <webElementGuid>cc894603-8d78-4cc8-86d1-20785ae5c828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::select[1]</value>
      <webElementGuid>fec05a82-537a-422a-bd59-7eadeb0b49ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Territory'])[1]/preceding::select[1]</value>
      <webElementGuid>5f29cc38-2c71-4cb5-9ab0-f553d8bc2ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>5f18f046-3713-4828-909f-eb10e2cdf40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Radiusabf47263446e860ecbe41ddebd37' and @name = 'Radiusabf47263446e860ecbe41ddebd37' and (text() = ' (select)  0-100 miles  101-300 miles ' or . = ' (select)  0-100 miles  101-300 miles ')]</value>
      <webElementGuid>773d6f1a-1a93-418f-9130-e39ae997a021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
