<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>a0f99f3d-9ba7-4459-8314-19a4af668c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='EarthquakeIncludedForExteriorMasonryVeneer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#EarthquakeIncludedForExteriorMasonryVeneer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>35e3189b-4f05-48a3-a4d3-9bce51439adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5c736923-5712-4f9c-8c2a-9ee9bde6ffd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EarthquakeIncludedForExteriorMasonryVeneer</value>
      <webElementGuid>6f553127-f402-49c9-ba3d-d9d61cb96d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EarthquakeIncludedForExteriorMasonryVeneer</value>
      <webElementGuid>6ed5daad-dfad-4669-ad92-ed0befea75fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>97cf72e7-2b7f-462d-a505-18270ee63f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>62f413dc-6880-4462-9272-d48b839d9e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>ed37da2d-3741-49c4-8a0d-7ab55ed967fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EarthquakeIncludedForExteriorMasonryVeneer&quot;)</value>
      <webElementGuid>265be381-d171-4f1a-9ffd-98d7013c84ff</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='EarthquakeIncludedForExteriorMasonryVeneer']</value>
      <webElementGuid>8556340c-dfd1-444b-93eb-9e5fba5b4f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table[2]/tbody/tr/td[2]/div/form/div/table/tbody/tr[10]/td[2]/table/tbody/tr[3]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>36de361d-9598-4c49-a8f0-4e533599edcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include Coverage for Exterior Masonry Veneer'])[1]/following::select[1]</value>
      <webElementGuid>54a86d33-9230-428f-a862-36a121253066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zone'])[1]/following::select[1]</value>
      <webElementGuid>2c014e9b-8fa6-4aa7-88af-9815ca1c514f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farmers Personal Liability (HO 24 73)'])[1]/preceding::select[1]</value>
      <webElementGuid>e2c39852-f988-447e-a264-460b4aad241b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of farm locations'])[1]/preceding::select[1]</value>
      <webElementGuid>240fc266-98c7-4f27-aa36-8cff6d3d7bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>122bef07-c880-4e86-bb6f-e36a130dc7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'EarthquakeIncludedForExteriorMasonryVeneer' and @name = 'EarthquakeIncludedForExteriorMasonryVeneer' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>a3e43209-beca-40a0-8c8b-93c9d94c9448</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
