<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deductible_AudioVisualDataElectronicE_dda79f</name>
   <tag></tag>
   <elementGuidId>30a24424-fb8d-4e4e-97e0-96df6b732d64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AudioVisualDataElectronicEquipment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AudioVisualDataElectronicEquipment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78d6f103-f09f-41a0-a27a-511536b0e051</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>778e9de1-455c-40b6-bc0e-834ee6f02aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>33456252-393e-4064-b080-720f0828370c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AudioVisualDataElectronicEquipment</value>
      <webElementGuid>6271611d-7304-4472-9f39-dd141cb208e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AudioVisualDataElectronicEquipment</value>
      <webElementGuid>7e2c2cf1-2e48-45a2-8993-a76a9de5f337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>f561cd39-55c9-4105-82f3-61a6f6ee190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>43</value>
      <webElementGuid>6450f9b8-4ebb-4c4c-bcc6-efe68bc2e720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>76a6cce4-5b01-4258-9c52-8c3841c3f170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AudioVisualDataElectronicEquipment&quot;)</value>
      <webElementGuid>657f6f6e-9067-4d4f-a4fb-b70b4f785a0f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AudioVisualDataElectronicEquipment']</value>
      <webElementGuid>03f548ec-ced8-41a7-8b33-47cb431e7625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[9]/td/input</value>
      <webElementGuid>5d3f720f-0a2d-4d58-921b-27bbb554ba65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/input</value>
      <webElementGuid>e5ccdaa5-5b18-4579-b278-9e4dcabb9bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AudioVisualDataElectronicEquipment' and @name = 'AudioVisualDataElectronicEquipment' and @type = 'checkbox']</value>
      <webElementGuid>e31d7bb4-52fe-4da2-9ed6-70b3a19ba2dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
