<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_0_CostNew</name>
   <tag></tag>
   <elementGuidId>2eaa53f7-ebef-4b00-9e74-90b40a598fdd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CostNew</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='CostNew']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5828e5b0-43d7-4ad9-8542-92e0c99ae933</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d27fe288-dca8-4078-a436-9e7bcd5938a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CostNew</value>
      <webElementGuid>4214c6d3-cbaa-46d1-a872-8aa191e96b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CostNew</value>
      <webElementGuid>e2b474bc-93d1-4554-b1f5-f71c9b8e12b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit6</value>
      <webElementGuid>751690a1-b46d-49fe-a94f-76248680f2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>bb93726e-5816-4789-8c20-be894e3a84cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>d52af0c6-42b3-4f5b-a79b-e8dcb0ac384e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>af7aff36-1540-46de-8832-6bc9b2cea12a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CostNew&quot;)</value>
      <webElementGuid>7c1be441-ac08-4eb0-9a39-8f1dd3fccd1f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CostNew']</value>
      <webElementGuid>6c8fb26f-ad55-4faa-b0d8-c529919a9ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table[2]/tbody/tr[3]/td[4]/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>93c51a4b-eed8-4702-8a00-0eec6407eb0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>08f29225-e061-4f56-a993-11ef57cb36ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CostNew' and @name = 'CostNew' and @alt = 'limit6' and @type = 'text']</value>
      <webElementGuid>fd9a2fed-11a4-4299-9205-f89d2935f552</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
