<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Coverage_SingleLimitDeductible</name>
   <tag></tag>
   <elementGuidId>e5dd3dc5-3b42-45e2-9eb2-080a4317aaaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SingleLimitDeductible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SingleLimitDeductible']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>287364e3-dd7b-4f9e-86c8-23fa645fcc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>57086cd3-624c-4cfd-b00c-8b8fa66ae4ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>8096339b-13e5-4c89-8df9-b7c8c9abd080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SingleLimitDeductible</value>
      <webElementGuid>7100852f-771a-4df3-b033-d055b9492766</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SingleLimitDeductible</value>
      <webElementGuid>d0434df6-391e-41e1-a535-733e7bf7a0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>e609a622-20da-4aff-b30d-e1c11d343332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>41</value>
      <webElementGuid>9dbfe730-f40c-43d9-bd12-8cfb432ad530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1566980b-f024-4544-87f0-a8dd2742cdad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SingleLimitDeductible&quot;)</value>
      <webElementGuid>89931f72-465a-43df-83e4-e1ec62057a13</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SingleLimitDeductible']</value>
      <webElementGuid>6a891650-f552-4320-a537-52720463f9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[7]/td/input</value>
      <webElementGuid>e7b25a82-87b4-49d1-ab83-7710ade985f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/input</value>
      <webElementGuid>1bd32ac0-daf2-4c8b-a5f1-65958c09913f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SingleLimitDeductible' and @name = 'SingleLimitDeductible' and @type = 'checkbox']</value>
      <webElementGuid>8ffb546b-4e24-4b5b-a323-4766a83d8e8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
