<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Garaging Zip Code_Zip</name>
   <tag></tag>
   <elementGuidId>33311036-d417-448c-beb7-e9acc0f9040f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0b3502fa-7025-41f4-9f76-11e4c85deb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5fa01ab7-b8f7-4380-b9a5-86df9b100f1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>17a56e51-33ad-494b-9f1f-675807349b22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>9e3db387-f8e6-4f0e-bc6d-579ee699df08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>924ab3d5-8a2b-416e-b2be-835c0bc5dec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>a3946219-f93c-425c-b38b-c4c32fdc96ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>38fc0862-2ea0-4c11-9f72-810e2132f630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>01e91f28-27d7-49a6-bbca-b2f68f5b1c97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7596e355-82e7-4fe0-9f9d-5c6e2ebd9d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Zip&quot;)</value>
      <webElementGuid>0243b105-e429-4889-9035-23c8b0ebbf79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Zip']</value>
      <webElementGuid>d1cc8207-d64c-4929-acc0-9e99a2902193</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>b4002bcd-6cca-4906-aeab-c7d9ec07157d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>322bb0b1-8cdb-4725-ae10-9ba903924ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Zip' and @name = 'Zip' and @alt = 'zipCode' and @type = 'text']</value>
      <webElementGuid>389b0fa5-88d6-4128-aa99-1ab6c2fee322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
