<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Coverage_AudioVisualDataElectronicEqu_079d7c</name>
   <tag></tag>
   <elementGuidId>866192e0-9fc3-44d4-ac50-398c9fdd548c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AudioVisualDataElectronicEquipmentCoverage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AudioVisualDataElectronicEquipmentCoverage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad9f9eff-20d2-4adb-a07c-7164415a0361</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f42ac0e2-245c-4575-86ca-611bb3da77e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AudioVisualDataElectronicEquipmentCoverage</value>
      <webElementGuid>ad5b54da-bdaa-41ca-945a-8dc37c74a118</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AudioVisualDataElectronicEquipmentCoverage</value>
      <webElementGuid>f17e05e4-7020-4ceb-ae41-25f16d6067df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>81b70f36-a79f-4e9c-84c0-39d13f063ed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>10000</value>
      <webElementGuid>48f320f9-e205-4237-b06b-d2b7e67cb72f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>number_5_digits</value>
      <webElementGuid>a64dac46-139b-4274-ba55-2e19241f03b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Must be a number between 1 and 10,000</value>
      <webElementGuid>ef7cec75-8676-45f0-94aa-b7a834ac3e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>fe749dd3-b60d-4372-b608-a26a15d3438e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>0e99aa67-0c64-4ff8-919a-50289b6b412a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fd41ea3-5ae3-4a76-bfed-c884b8fa86d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AudioVisualDataElectronicEquipmentCoverage&quot;)</value>
      <webElementGuid>1a5fc80c-198a-4bad-bdcb-bf751e7e4e5c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AudioVisualDataElectronicEquipmentCoverage']</value>
      <webElementGuid>2f15c980-934d-4048-9239-1bd7e40bb49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[10]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c4dd4c8f-20ff-4275-9226-4e2f0f3b827b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>68cff200-4b94-4efa-a3cf-921f280d0f77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AudioVisualDataElectronicEquipmentCoverage' and @name = 'AudioVisualDataElectronicEquipmentCoverage' and @alt = 'number_5_digits' and @title = 'Must be a number between 1 and 10,000' and @type = 'text']</value>
      <webElementGuid>92aebc9c-8f1f-4c21-ad5f-0b0687638066</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
