<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close_VIN</name>
   <tag></tag>
   <elementGuidId>5115152e-73a1-49bd-aee9-fcc1f7ecf9ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VIN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VIN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c28d38f3-91a7-46ab-a366-d0a24a549340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>0367d609-7fed-4a94-8e94-da365bc3dfc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VIN</value>
      <webElementGuid>dc30a6ff-ea4c-4920-9e18-b9eea50e0730</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VIN</value>
      <webElementGuid>74bf75b8-edf7-4a53-b2cf-f3f41d4e46ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>68b320e2-b9a5-4453-b813-5cad6bef110a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>2e8e07a1-540b-445b-ae81-a223e2a53e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>229a1b20-d9e8-45a2-ab5a-555dff575992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/VehicleInfoByVIN/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>677fa07f-f8cd-4b6a-94ce-56484d61aa83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/VehicleInfoByVIN/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>d05c0c82-4342-4302-8143-4ff877f24883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>5ab81148-3fb7-4b38-b3c5-8f0b2f4f1ff8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(optional)</value>
      <webElementGuid>99335e59-eaa0-444f-bf51-a948f1d3ce2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>c6f9a6d1-3ebc-480d-ac5c-33b110584393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>18988c1f-58b1-4446-94f3-6e92e8e79b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VIN&quot;)</value>
      <webElementGuid>b1fde27c-1335-4b2c-84e7-17ad160677db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VIN']</value>
      <webElementGuid>d7febee3-0443-4e66-8dfc-5c6f8b4aa829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr[2]/td/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>6978d9a8-59a6-4bd2-ab3e-f14b38c01d01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>cf32cc3e-d920-4d89-9c67-ef803512182f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'VIN' and @name = 'VIN' and @href = '/CommercialAuto/ExpressQuote/VehicleInfoByVIN/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1' and @placeholder = '(optional)' and @type = 'text']</value>
      <webElementGuid>6439c375-5f45-4be0-8f6a-a54177b76e00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
