<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Deductible_Collision</name>
   <tag></tag>
   <elementGuidId>df8df77a-7d18-4f41-8a2c-51667aecf3ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Collision</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Collision']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7547eb6-d431-4b77-9f83-831d8b1e0212</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>9c91757e-b552-44df-8cbf-e0ebc339a51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>7a11bd8b-5d31-4fe8-be9b-2da2ec138dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Collision</value>
      <webElementGuid>59c0feff-8e65-4a58-8f86-73f6bcc9d28d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Collision</value>
      <webElementGuid>5c874aaf-0785-4e95-83c1-281116f695ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>update-costnew-required hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>8e699658-d0e6-4670-8fbc-5b02459c4c66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>36</value>
      <webElementGuid>1cfd8fd8-bb2d-4a40-a25e-3a6b153d98bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>2c4ac94e-47ad-49d0-8747-fa94386eb298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Collision&quot;)</value>
      <webElementGuid>eff76c70-e6fb-4548-8d98-d4c15bb11a21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Collision']</value>
      <webElementGuid>13cb6772-5d32-4e3d-8ba7-76738c41dfa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[3]/td/input</value>
      <webElementGuid>3348bec0-4b71-4149-89a2-25c01ca71f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>541e02bf-e137-45ca-b6df-13537c76e1a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Collision' and @name = 'Collision' and @type = 'checkbox']</value>
      <webElementGuid>9cff70b0-560f-463a-bbc7-daf65aa7148b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
