<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  011  012  013  017  018  0_f9c643</name>
   <tag></tag>
   <elementGuidId>22996ff4-da5b-40ab-ae35-84812cda6f81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Territory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Territory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3caf324c-04c6-4e06-84de-464b4abedb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>752f8dcf-b948-424b-a42c-4a739ac65639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Territory</value>
      <webElementGuid>8add9ce7-ee8e-447e-8e94-aeb9bb2e2da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Territory</value>
      <webElementGuid>4a140b19-3624-4173-b104-2a3064b27738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>b095b261-8a12-49ed-b431-3f7fbb80fe58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>04c5436f-0038-43bd-8dcf-505923db9f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  011  012  013  017  018  019  023  024  025  026  028  030  031  032  033  034  035 </value>
      <webElementGuid>3b930860-eadf-4c41-a096-216c5cb8f27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Territory&quot;)</value>
      <webElementGuid>e17bf412-a617-4e68-9884-d21a6d81e73b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Territory']</value>
      <webElementGuid>014cec99-11d7-46d3-8305-79ab45e4b7ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[2]/table/tbody/tr/td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>8f843ae9-a20b-421e-a8ad-df433fa87812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Territory Definitions'])[1]/following::select[1]</value>
      <webElementGuid>69c8306e-0373-4069-8cf4-d16948974d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Garaging Zip Code'])[1]/preceding::select[1]</value>
      <webElementGuid>bf0eb73f-24c7-4e8c-bffd-723605c842fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copy from Mailing Address'])[1]/preceding::select[1]</value>
      <webElementGuid>3b8d6ad2-c3f6-4002-a02a-e1fa857e2033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[4]/table/tbody/tr/td/select</value>
      <webElementGuid>a273546b-1b56-4b37-8c87-e601e838e416</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Territory' and @name = 'Territory' and (text() = ' (select)  011  012  013  017  018  019  023  024  025  026  028  030  031  032  033  034  035 ' or . = ' (select)  011  012  013  017  018  019  023  024  025  026  028  030  031  032  033  034  035 ')]</value>
      <webElementGuid>edf8c220-73fb-4dbf-a325-9c940c1c33d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
