<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Commercial  Farm  Retail  _c9dd22</name>
   <tag></tag>
   <elementGuidId>71298a96-e463-4a67-be7f-362b47d7bb52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehicleUsage</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehicleUsage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bec1499b-9532-4b37-bbc1-2e9f9ce5db02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3b042038-50c3-4b6f-a4c6-5192153c6f04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehicleUsage</value>
      <webElementGuid>50614783-4a7d-4e90-99b9-294fea5ce2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehicleUsage</value>
      <webElementGuid>3b837c18-c2cf-45cb-a59e-3ad7ddbae1d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>e4631f8b-ce73-4a97-8482-cf4a185a0fd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>e340c698-2752-4a94-a372-b519783b0bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Commercial  Farm  Retail  Selected Contractors  Service </value>
      <webElementGuid>afa9c795-15f5-4cc8-a587-17d7bd0775e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehicleUsage&quot;)</value>
      <webElementGuid>d851403a-ba88-4359-92a1-237f7976d074</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehicleUsage']</value>
      <webElementGuid>aeeaeab9-2096-485f-ac1a-e0d1dae4d264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[2]/table/tbody/tr[3]/td[2]/div/table/tbody/tr/td/select</value>
      <webElementGuid>39eb2de9-fdf0-4adb-a693-fadee374f8bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[3]/following::select[1]</value>
      <webElementGuid>a355bf28-e355-47e0-bd40-779b7fb7153b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Private Passenger Type Classifications'])[1]/following::select[1]</value>
      <webElementGuid>7b2dbc8a-4eee-4526-b084-510325bd9c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radius'])[1]/preceding::select[1]</value>
      <webElementGuid>a6cef7d3-279b-45d0-832d-0c4a591f84b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Radius Class'])[1]/preceding::select[1]</value>
      <webElementGuid>d547d270-76a4-40eb-8540-0687eb1734ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[3]/td[2]/div/table/tbody/tr/td/select</value>
      <webElementGuid>f082fd75-91a0-4b66-9b0f-058c83b7e21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehicleUsage' and @name = 'VehicleUsage' and (text() = ' (select)  Commercial  Farm  Retail  Selected Contractors  Service ' or . = ' (select)  Commercial  Farm  Retail  Selected Contractors  Service ')]</value>
      <webElementGuid>6405167e-e8c8-4eb3-80e7-6bc990a7090b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
