<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  100  250  500  1,000  2,00_1e562c</name>
   <tag></tag>
   <elementGuidId>c4f1891d-017b-41c3-97e3-a1058e012e7d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CollisionDeductible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CollisionDeductible']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>013d3d9f-a30a-4ae7-a83e-bdd238723483</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>453095a9-cecf-4de1-8357-017435a771a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CollisionDeductible</value>
      <webElementGuid>3a87d4d1-249e-4171-8e8d-a039c09c6e49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CollisionDeductible</value>
      <webElementGuid>9c83bbaf-06ba-4220-aae1-bc908dc7643d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/CollisionDeductibleOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>da0f39fb-79cb-4c51-9f68-1613e4cec83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/CollisionDeductibleOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>a2ff436e-119a-465e-8adc-68b19ee73833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>update-costnew-required hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>e78b4e4a-5c2a-4535-a4d2-1f4960dedca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>f08fce65-8a48-45bc-9213-a34e484146a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  100  250  500  1,000  2,000  3,000  5,000 </value>
      <webElementGuid>2a6c46a7-488c-40c3-8dff-2d7a1f3d19fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CollisionDeductible&quot;)</value>
      <webElementGuid>2a6d4ed3-9415-4929-bf26-7d9d2098667b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CollisionDeductible']</value>
      <webElementGuid>097c606f-02f7-4fd5-af70-ef74d1d91cc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[4]/td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>60ad91f9-750c-4a4e-8f55-b1cf14138682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[2]/following::select[1]</value>
      <webElementGuid>fc0f5faf-3b7f-4caf-bf36-2799b198fb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Type'])[1]/following::select[2]</value>
      <webElementGuid>dbc8c2a2-6b5b-4b26-bcca-ba67fe0dbd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Coordination of Benefits to this vehicle?'])[1]/preceding::select[1]</value>
      <webElementGuid>d1166bed-e0ec-41c1-81e2-9694d11f2229</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage'])[1]/preceding::select[1]</value>
      <webElementGuid>8eaf477f-993f-40de-8570-d093bcb95314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>ebcdd7d7-a23d-4798-a875-92ef6ac5a30c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CollisionDeductible' and @name = 'CollisionDeductible' and @href = '/CommercialAuto/ExpressQuote/CollisionDeductibleOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1' and (text() = ' (select)  100  250  500  1,000  2,000  3,000  5,000 ' or . = ' (select)  100  250  500  1,000  2,000  3,000  5,000 ')]</value>
      <webElementGuid>c53dba5e-e112-4b85-93f5-025079ff47de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
