<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)ACURAAUDIBMWBUICKCADILLACCHE_724d6d</name>
   <tag></tag>
   <elementGuidId>5d1cf555-de4f-4bf7-9d6a-b9e68492602d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehicleMake</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehicleMake']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa8cfd49-5a1b-408d-aeb6-5ad627c5581e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>23d4161e-efd9-4a2d-b89f-945144dff673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehicleMake</value>
      <webElementGuid>fbaff555-36e7-43b0-b6ce-f560a7855ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehicleMake</value>
      <webElementGuid>eb1cc231-aad6-4b17-8730-2f79f31e3382</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/VehicleMakeOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>be5aabe6-e45c-4887-aede-cb29270b43eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/VehicleMakeOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>13c22f75-f54f-445b-9713-3d98f16626b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>6c424911-4c34-4a53-b549-1a98fe4229d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>643a1490-3f1e-4fdd-a735-4667d146dcde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(select)ACURAAUDIBMWBUICKCADILLACCHEVROLETCHRYSLERDODGEFORDGMCHONDAHYUNDAIINFINITIJAGUARJEEPKIALANDROVERLEXUSLINCOLNLOTUSMAZDAMERCEDES BENZMERCURYMINIMITSUBISHINISSANPORSCHESAABSCIONSUBARUSUZUKITOYOTAVOLKSWAGENVOLVOVPG</value>
      <webElementGuid>62ad24a5-6138-46dd-a64b-8f2cc8189797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehicleMake&quot;)</value>
      <webElementGuid>ba17194a-e8c9-4f84-a9fc-f32af0a49f0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehicleMake']</value>
      <webElementGuid>7108b738-62bf-40f6-a759-656d8f284962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table[2]/tbody/tr/td[2]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>2b1b54b4-e20c-4ed1-b7f2-833d7563728f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Make'])[1]/following::select[1]</value>
      <webElementGuid>4925ddef-1f47-4b84-9e57-ad8ab7e9b723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::select[1]</value>
      <webElementGuid>528311ea-21a3-4740-96e2-4123fe016ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Model'])[1]/preceding::select[1]</value>
      <webElementGuid>14cd8a0a-68a7-44d2-b5a7-830e77025ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Type'])[1]/preceding::select[2]</value>
      <webElementGuid>2c68c2bc-9aff-4098-840d-ec98267f080a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>ca837a57-453f-4ea7-b668-28bcd17da049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehicleMake' and @name = 'VehicleMake' and @href = '/CommercialAuto/ExpressQuote/VehicleMakeOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1' and (text() = '(select)ACURAAUDIBMWBUICKCADILLACCHEVROLETCHRYSLERDODGEFORDGMCHONDAHYUNDAIINFINITIJAGUARJEEPKIALANDROVERLEXUSLINCOLNLOTUSMAZDAMERCEDES BENZMERCURYMINIMITSUBISHINISSANPORSCHESAABSCIONSUBARUSUZUKITOYOTAVOLKSWAGENVOLVOVPG' or . = '(select)ACURAAUDIBMWBUICKCADILLACCHEVROLETCHRYSLERDODGEFORDGMCHONDAHYUNDAIINFINITIJAGUARJEEPKIALANDROVERLEXUSLINCOLNLOTUSMAZDAMERCEDES BENZMERCURYMINIMITSUBISHINISSANPORSCHESAABSCIONSUBARUSUZUKITOYOTAVOLKSWAGENVOLVOVPG')]</value>
      <webElementGuid>3274fe14-823f-4cab-bd63-47831f0b4095</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
