<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)ACADIA DENALIACADIA DENALI A_ede497</name>
   <tag></tag>
   <elementGuidId>5010c9d4-10a2-4bc4-8624-8213e729b03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#VehicleModel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehicleModel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4c7d6d77-dafb-4539-9ba7-6d7d4d89a4b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>08037e88-b103-489d-8b49-87284b8e837c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehicleModel</value>
      <webElementGuid>af5b1152-bfe2-47b6-8bbc-db4bb2e8f283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehicleModel</value>
      <webElementGuid>06351c61-e279-4efe-b028-81cc32d85edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/VehicleModelOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>cccd2868-edc6-49a8-8937-32550eaeb29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/VehicleModelOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>a709774f-a4c0-4ad5-bd00-22ee4b3d9a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>e90c6238-64f7-4156-92b0-6e1eb738cf1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>15a7688d-66c0-4bc1-bc28-6019b8ac72fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(select)ACADIA DENALIACADIA DENALI AWDACADIA SLE1ACADIA SLE1 AWDACADIA SLT1ACADIA SLT1 AWDACADIA SLT2ACADIA SLT2 AWDCANYON CREW CAB SLECANYON CREW CAB SLTCANYON EXTENDED CABCANYON EXTENDED CAB SLECANYON EXTENDED CAB SLTCANYON REGULAR CABCANYON REGULAR CAB SLESAVANA G1500SAVANA G1500 AWDSAVANA G1500 LSSAVANA G1500 LS AWDSAVANA G1500 LTSAVANA G1500 LT AWDSAVANA G2500SAVANA G2500 EXTENDEDSAVANA G2500 LSSAVANA G2500 LTSAVANA G3500SAVANA G3500 EXTENDEDSAVANA G3500 LSSAVANA G3500 LS EXTENDEDSAVANA G3500 LTSAVANA G3500 LT EXTENDEDSIERRA 1500 CREW CABSIERRA 1500 CREW CAB SLSIERRA 1500 CREW CAB SLESIERRA 1500 CREW CAB SLTSIERRA 1500 DENALISIERRA 1500 DENALI AWDSIERRA 1500 EXTENDED CABSIERRA 1500 EXTENDED CAB SLSIERRA 1500 EXTENDED CAB SLESIERRA 1500 EXTENDED CAB SLTSIERRA 1500 REGULAR CABSIERRA 1500 REGULAR CAB SLESIERRA 2500HD CREW CABSIERRA 2500HD CREW CAB SLESIERRA 2500HD CREW CAB SLTSIERRA 2500HD DENALISIERRA 2500HD EXTENDED CABSIERRA 2500HD EXTENDED CAB SLESIERRA 2500HD EXTENDED CAB SLTSIERRA 2500HD REGULAR CABSIERRA 2500HD REGULAR CAB SLESIERRA 3500HD CREW CABSIERRA 3500HD CREW CAB SLESIERRA 3500HD CREW CAB SLTSIERRA 3500HD DENALISIERRA 3500HD EXTENDED CABSIERRA 3500HD EXTENDED CAB SLESIERRA 3500HD EXTENDED CAB SLTSIERRA 3500HD REGULAR CABSIERRA 3500HD REGULAR CAB SLESIERRA HYBRIDTERRAIN SLE1TERRAIN SLE1 AWDTERRAIN SLE2TERRAIN SLE2 AWDTERRAIN SLT1TERRAIN SLT1 AWDTERRAIN SLT2TERRAIN SLT2 AWDYUKON DENALIYUKON DENALI AWDYUKON DENALI HYBRIDYUKON HYBRIDYUKON SLEYUKON SLTYUKON SLT2YUKON XL 1500 SLEYUKON XL 1500 SLTYUKON XL 1500 SLT2YUKON XL 2500 SLEYUKON XL 2500 SLTYUKON XL 2500 SLT2YUKON XL DENALIYUKON XL DENALI AWD</value>
      <webElementGuid>445f9f61-b009-4260-8ae8-fd4c195c76c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehicleModel&quot;)</value>
      <webElementGuid>0de4a49e-ad16-4297-a404-0a256eb93ba9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehicleModel']</value>
      <webElementGuid>8c7449c9-3285-40dd-a7bf-4ccb36117c35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table[2]/tbody/tr/td[4]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>0a729972-2b8e-4036-9889-1fa88dee4e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Model'])[1]/following::select[1]</value>
      <webElementGuid>9329f2a5-e9ad-4880-91c2-09f64ab970e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Make'])[1]/following::select[2]</value>
      <webElementGuid>a501d15b-de1d-4c6b-b5df-8747823e9e02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Type'])[1]/preceding::select[1]</value>
      <webElementGuid>086d9236-5937-443f-ae07-ae643a64768c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Type'])[2]/preceding::select[1]</value>
      <webElementGuid>e287e3d9-e5c2-4b35-8d3f-f34ef90d0655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>4d9c10f4-9417-4328-a24b-9a5f2922e1d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehicleModel' and @name = 'VehicleModel' and @href = '/CommercialAuto/ExpressQuote/VehicleModelOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1' and (text() = '(select)ACADIA DENALIACADIA DENALI AWDACADIA SLE1ACADIA SLE1 AWDACADIA SLT1ACADIA SLT1 AWDACADIA SLT2ACADIA SLT2 AWDCANYON CREW CAB SLECANYON CREW CAB SLTCANYON EXTENDED CABCANYON EXTENDED CAB SLECANYON EXTENDED CAB SLTCANYON REGULAR CABCANYON REGULAR CAB SLESAVANA G1500SAVANA G1500 AWDSAVANA G1500 LSSAVANA G1500 LS AWDSAVANA G1500 LTSAVANA G1500 LT AWDSAVANA G2500SAVANA G2500 EXTENDEDSAVANA G2500 LSSAVANA G2500 LTSAVANA G3500SAVANA G3500 EXTENDEDSAVANA G3500 LSSAVANA G3500 LS EXTENDEDSAVANA G3500 LTSAVANA G3500 LT EXTENDEDSIERRA 1500 CREW CABSIERRA 1500 CREW CAB SLSIERRA 1500 CREW CAB SLESIERRA 1500 CREW CAB SLTSIERRA 1500 DENALISIERRA 1500 DENALI AWDSIERRA 1500 EXTENDED CABSIERRA 1500 EXTENDED CAB SLSIERRA 1500 EXTENDED CAB SLESIERRA 1500 EXTENDED CAB SLTSIERRA 1500 REGULAR CABSIERRA 1500 REGULAR CAB SLESIERRA 2500HD CREW CABSIERRA 2500HD CREW CAB SLESIERRA 2500HD CREW CAB SLTSIERRA 2500HD DENALISIERRA 2500HD EXTENDED CABSIERRA 2500HD EXTENDED CAB SLESIERRA 2500HD EXTENDED CAB SLTSIERRA 2500HD REGULAR CABSIERRA 2500HD REGULAR CAB SLESIERRA 3500HD CREW CABSIERRA 3500HD CREW CAB SLESIERRA 3500HD CREW CAB SLTSIERRA 3500HD DENALISIERRA 3500HD EXTENDED CABSIERRA 3500HD EXTENDED CAB SLESIERRA 3500HD EXTENDED CAB SLTSIERRA 3500HD REGULAR CABSIERRA 3500HD REGULAR CAB SLESIERRA HYBRIDTERRAIN SLE1TERRAIN SLE1 AWDTERRAIN SLE2TERRAIN SLE2 AWDTERRAIN SLT1TERRAIN SLT1 AWDTERRAIN SLT2TERRAIN SLT2 AWDYUKON DENALIYUKON DENALI AWDYUKON DENALI HYBRIDYUKON HYBRIDYUKON SLEYUKON SLTYUKON SLT2YUKON XL 1500 SLEYUKON XL 1500 SLTYUKON XL 1500 SLT2YUKON XL 2500 SLEYUKON XL 2500 SLTYUKON XL 2500 SLT2YUKON XL DENALIYUKON XL DENALI AWD' or . = '(select)ACADIA DENALIACADIA DENALI AWDACADIA SLE1ACADIA SLE1 AWDACADIA SLT1ACADIA SLT1 AWDACADIA SLT2ACADIA SLT2 AWDCANYON CREW CAB SLECANYON CREW CAB SLTCANYON EXTENDED CABCANYON EXTENDED CAB SLECANYON EXTENDED CAB SLTCANYON REGULAR CABCANYON REGULAR CAB SLESAVANA G1500SAVANA G1500 AWDSAVANA G1500 LSSAVANA G1500 LS AWDSAVANA G1500 LTSAVANA G1500 LT AWDSAVANA G2500SAVANA G2500 EXTENDEDSAVANA G2500 LSSAVANA G2500 LTSAVANA G3500SAVANA G3500 EXTENDEDSAVANA G3500 LSSAVANA G3500 LS EXTENDEDSAVANA G3500 LTSAVANA G3500 LT EXTENDEDSIERRA 1500 CREW CABSIERRA 1500 CREW CAB SLSIERRA 1500 CREW CAB SLESIERRA 1500 CREW CAB SLTSIERRA 1500 DENALISIERRA 1500 DENALI AWDSIERRA 1500 EXTENDED CABSIERRA 1500 EXTENDED CAB SLSIERRA 1500 EXTENDED CAB SLESIERRA 1500 EXTENDED CAB SLTSIERRA 1500 REGULAR CABSIERRA 1500 REGULAR CAB SLESIERRA 2500HD CREW CABSIERRA 2500HD CREW CAB SLESIERRA 2500HD CREW CAB SLTSIERRA 2500HD DENALISIERRA 2500HD EXTENDED CABSIERRA 2500HD EXTENDED CAB SLESIERRA 2500HD EXTENDED CAB SLTSIERRA 2500HD REGULAR CABSIERRA 2500HD REGULAR CAB SLESIERRA 3500HD CREW CABSIERRA 3500HD CREW CAB SLESIERRA 3500HD CREW CAB SLTSIERRA 3500HD DENALISIERRA 3500HD EXTENDED CABSIERRA 3500HD EXTENDED CAB SLESIERRA 3500HD EXTENDED CAB SLTSIERRA 3500HD REGULAR CABSIERRA 3500HD REGULAR CAB SLESIERRA HYBRIDTERRAIN SLE1TERRAIN SLE1 AWDTERRAIN SLE2TERRAIN SLE2 AWDTERRAIN SLT1TERRAIN SLT1 AWDTERRAIN SLT2TERRAIN SLT2 AWDYUKON DENALIYUKON DENALI AWDYUKON DENALI HYBRIDYUKON HYBRIDYUKON SLEYUKON SLTYUKON SLT2YUKON XL 1500 SLEYUKON XL 1500 SLTYUKON XL 1500 SLT2YUKON XL 2500 SLEYUKON XL 2500 SLTYUKON XL 2500 SLT2YUKON XL DENALIYUKON XL DENALI AWD')]</value>
      <webElementGuid>3505b577-5119-490c-8697-5ff092a4f4d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
