<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  30  50  75  100</name>
   <tag></tag>
   <elementGuidId>f323745c-1dd4-41a0-9f62-87455b021ac9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RentalReimbursementAmountPerDay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RentalReimbursementAmountPerDay']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>52741ce4-4866-4fa0-badb-ec73780a5919</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b8497f9b-161c-492b-8a41-3196db523b28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RentalReimbursementAmountPerDay</value>
      <webElementGuid>8e3deed4-91a6-4c43-bfb9-89786856f1ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RentalReimbursementAmountPerDay</value>
      <webElementGuid>0167be05-998f-484c-8763-0bcae1500dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>db64720d-893c-48da-bb15-3a1968a373f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>47</value>
      <webElementGuid>78a7c533-e101-4c92-86e7-08354bdca1ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  30  50  75  100 </value>
      <webElementGuid>ca787947-d843-4ab2-964f-a85d8f6aebb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RentalReimbursementAmountPerDay&quot;)</value>
      <webElementGuid>23fa9585-5962-47ed-9aeb-82591c4c6e2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RentalReimbursementAmountPerDay']</value>
      <webElementGuid>cb726b68-801e-4d28-8786-5c525fecda07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[13]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>87add4cb-faf7-4c5b-a624-a6fb11301add</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum number of days: 30.'])[1]/following::select[1]</value>
      <webElementGuid>86c49b65-f24a-4c6d-8ce9-66e5b6968773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount Per Day'])[1]/following::select[1]</value>
      <webElementGuid>e3ac30b2-f0d0-4668-ba78-d6a82006496f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roadside Assistance'])[1]/preceding::select[1]</value>
      <webElementGuid>95a619e7-e366-48a0-babf-41f40640d1f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Roadside Assistance Form'])[1]/preceding::select[1]</value>
      <webElementGuid>5201d6ab-b290-4a6f-9a96-53463ba57749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>77aa26cb-30fb-45a5-bce7-5d6473e30f42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RentalReimbursementAmountPerDay' and @name = 'RentalReimbursementAmountPerDay' and (text() = ' (select)  30  50  75  100 ' or . = ' (select)  30  50  75  100 ')]</value>
      <webElementGuid>9273a12b-81ed-498a-b9a1-177c496a26a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
