<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  250  500  1,000</name>
   <tag></tag>
   <elementGuidId>ca859ead-da00-41f1-8fcd-9f03f862495c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SingleLimitDeductibleDeductible</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SingleLimitDeductibleDeductible']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0fb0dda0-e919-4267-9eeb-91af117de6be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>2d874c7a-5705-4fc1-b601-92b87e20f5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SingleLimitDeductibleDeductible</value>
      <webElementGuid>f5c3317a-51ae-4dd3-8eee-30b796e50a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SingleLimitDeductibleDeductible</value>
      <webElementGuid>2232fa07-00e1-4426-bd2d-5f06f6515fa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>c053d0de-e0a6-47a0-bf68-d114cc8c5ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>42</value>
      <webElementGuid>d6b253a9-7456-45c2-aaf6-7ce1c955928d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  250  500  1,000 </value>
      <webElementGuid>81af4294-f74a-44f5-9b06-ae4c8c029e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SingleLimitDeductibleDeductible&quot;)</value>
      <webElementGuid>79188333-2248-4a86-b97c-83f63fb03050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SingleLimitDeductibleDeductible']</value>
      <webElementGuid>3c47947f-49a5-48de-b801-823589ac4dc6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[8]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>1185a8c0-61d8-4a80-9691-79ef6923fe63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[3]/following::select[1]</value>
      <webElementGuid>5434b06a-deb7-44a6-b156-2bbc301fd98a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Single Limit Deductible'])[1]/following::select[1]</value>
      <webElementGuid>dfcbd44c-fda5-4228-b10c-adc44a672f8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audio, Visual &amp; Data Electronic Equipment, All Other'])[1]/preceding::select[1]</value>
      <webElementGuid>89bb16d5-5688-4721-99dc-b2872cc88467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage'])[2]/preceding::select[1]</value>
      <webElementGuid>1b2c0b8a-373b-4775-8b06-5ef4ca64c72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>5a49cfcd-a2a3-4fd8-a0f4-c36aac543010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SingleLimitDeductibleDeductible' and @name = 'SingleLimitDeductibleDeductible' and (text() = ' (select)  250  500  1,000 ' or . = ' (select)  250  500  1,000 ')]</value>
      <webElementGuid>f76e618b-6c86-4c6c-8a99-7315a35df812</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
