<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)4DR PICKUP TRUCK 4X24DR PICK_4ab9de</name>
   <tag></tag>
   <elementGuidId>14aa4eb9-22c5-4121-b0b3-51ea8cab9ed4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BodyType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='BodyType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>befa55c8-7d37-447e-bc44-5eb0d5bacc35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e19a33f9-3fb2-4da8-9225-0a96d2f8b572</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BodyType</value>
      <webElementGuid>b651a30c-fcaa-4279-812b-c562f9808849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BodyType</value>
      <webElementGuid>0009b99d-bb9e-4c2a-acfb-2d0529b0bec9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/BodyTypeOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>512af879-7bde-4a7c-9ca3-a23ebac6558c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/CommercialAuto/ExpressQuote/BodyTypeOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1</value>
      <webElementGuid>cb98aaba-78b4-4660-9184-682c9f1fee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>b3c2b9eb-2035-474d-b396-6b078b9b0d0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>a10ffc9e-162a-4965-82b9-e5bf0d3e8ef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(optional)</value>
      <webElementGuid>65d8106e-37e9-4d56-9c0c-f7c841b44f05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e98df2c3-9786-4339-af0e-a44ce318037a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(select)4DR PICKUP TRUCK 4X24DR PICKUP TRUCK 4X4</value>
      <webElementGuid>082585f9-ee06-45b7-a52d-4d69fff5af6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BodyType&quot;)</value>
      <webElementGuid>a816276c-3d82-43dd-a4c7-56d9e49bceb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='BodyType']</value>
      <webElementGuid>e5db6aea-6638-40ce-bc32-0592d40cc2dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='body-type-partial-vin-row']/td[2]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>620345a5-feff-4974-a500-5abe5aedce7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Type'])[2]/following::select[1]</value>
      <webElementGuid>81c1fca0-6c3b-4f82-b7b9-67ab6b39b153</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Body Type'])[1]/following::select[1]</value>
      <webElementGuid>b7b4e226-5746-4254-a03e-582a6f04ecca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partial VIN'])[1]/preceding::select[1]</value>
      <webElementGuid>7bc7a17d-6ec2-498a-ae77-4fa6163ec58e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is the Make and/or Model missing from the drop down box?'])[1]/preceding::select[2]</value>
      <webElementGuid>82c0033a-625c-4a78-9156-822487a229cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>dfb867d8-6bfa-4f40-875b-a89b66cbad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'BodyType' and @name = 'BodyType' and @href = '/CommercialAuto/ExpressQuote/BodyTypeOptions/70126192-ACV?vehiclekey=cbba7bfabebb4c0bb315ae75d851c3f1' and @placeholder = '(optional)' and (text() = '(select)4DR PICKUP TRUCK 4X24DR PICKUP TRUCK 4X4' or . = '(select)4DR PICKUP TRUCK 4X24DR PICKUP TRUCK 4X4')]</value>
      <webElementGuid>24e49ce7-c761-4c57-bdfc-07134d78cc64</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
