<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK</name>
   <tag></tag>
   <elementGuidId>a5a749ff-f70c-4103-8366-ae431c4babe8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-icons.ui-state-hover > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='policy-express']/div[5]/table/tbody/tr[3]/td/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>6674ad56-b107-4238-b3e0-7d6f3478e2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>c2faf6a8-7715-4681-917c-5bf8a5b6b874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>9343c8c1-8f5f-4d2c-a7c1-0834f0114c78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-express&quot;)/div[@class=&quot;blockUI blockMsg blockPage&quot;]/table[@class=&quot;hmi-table hmi-table-centered&quot;]/tbody[1]/tr[3]/td[1]/button[@class=&quot;ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icons ui-state-hover&quot;]/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>fcf02f17-57e9-4eac-b922-a2ce8f5ce0b3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='policy-express']/div[5]/table/tbody/tr[3]/td/button/span</value>
      <webElementGuid>afe28e77-696d-43d4-bfc4-a915dc5c6fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A value is required'])[1]/following::span[1]</value>
      <webElementGuid>375d6c01-395b-4146-9d95-06f0cb055455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cost New'])[4]/following::span[2]</value>
      <webElementGuid>0f1ccbbc-b071-466c-a89d-0e4c7df20b7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>8826b8f9-a02e-45ed-b9d0-f5436691aa18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button/span</value>
      <webElementGuid>5855746c-54bc-4de7-a759-ca3337b41fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>360593d6-56a8-4450-a166-131153b2684b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
