<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)Full300 Medical300 Wage Loss_0e9f0d</name>
   <tag></tag>
   <elementGuidId>535c9ecf-bf4e-4ae6-8c17-92e8fb062ee7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CoordinationOfBenefits']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CoordinationOfBenefits</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e7c6864d-17c4-4cbb-b9b8-8cee2bfc44b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>041ec5ff-9ca1-4bd3-bf99-b995002867e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoordinationOfBenefits</value>
      <webElementGuid>4d064f82-a08e-40f7-bed6-41aa213409a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoordinationOfBenefits</value>
      <webElementGuid>494aed6c-c624-4a60-b309-217e3d176d97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/GetCoordinatedBenefitOptions/70126483</value>
      <webElementGuid>6b708538-eaec-4369-b96f-3b9c476e6419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/GetCoordinatedBenefitOptions/70126483</value>
      <webElementGuid>5a5bbe9e-ca8f-424b-86a3-61e36976030d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-dirty</value>
      <webElementGuid>f239c114-e274-4be9-9f31-399d6385ebcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>ef436324-d410-47b2-a911-3f059fb5c481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(select)Full$300 Medical$300 Wage Loss$300 Medical and Wage Loss</value>
      <webElementGuid>0eb1dc66-0bfa-467e-b2b4-fdfae6e453e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoordinationOfBenefits&quot;)</value>
      <webElementGuid>af0b2921-f367-4df1-8366-f14d4479f349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CoordinationOfBenefits']</value>
      <webElementGuid>14654651-74c2-4dc3-b7bb-14a7393fe0be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[2]/table/tbody/tr[8]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>fc881a44-54c9-4e82-a045-b256e23b1204</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coordination of Benefits'])[1]/following::select[1]</value>
      <webElementGuid>df336697-f204-4ac9-b0c7-d2cc38b83669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiver of Work Loss Rejection Form'])[1]/following::select[1]</value>
      <webElementGuid>e745e113-861a-4a8c-8215-d0f58d17fa48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicles'])[1]/preceding::select[1]</value>
      <webElementGuid>c6687ddf-1398-4817-b2f8-6bff8657e3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add A Vehicle'])[1]/preceding::select[1]</value>
      <webElementGuid>380ad003-bade-4c8c-aaf9-c72a9ebcaa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>44621f07-9f27-44b2-ba7c-4a6725d68428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CoordinationOfBenefits' and @name = 'CoordinationOfBenefits' and @href = '/PersonalAuto/ExpressQuote/GetCoordinatedBenefitOptions/70126483' and (text() = '(select)Full$300 Medical$300 Wage Loss$300 Medical and Wage Loss' or . = '(select)Full$300 Medical$300 Wage Loss$300 Medical and Wage Loss')]</value>
      <webElementGuid>59e2cf1e-bd1e-4d84-abf2-117da91577c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
