<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Reject  50,000-100,000  10_4268c1</name>
   <tag></tag>
   <elementGuidId>424c352b-f727-45fc-b5f4-2bc6b5a7d449</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='UninsuredMotorist']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UninsuredMotorist</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>27564a44-741a-4114-a5bb-ae9b182ce6a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d4977de7-5b36-4145-96c7-bc9539edf8ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UninsuredMotorist</value>
      <webElementGuid>750b7c4c-62ff-475c-a4d2-91b13a1ad914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UninsuredMotorist</value>
      <webElementGuid>a3ac1cc7-f733-432c-b7db-77210b9f190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/UninsuredMotoristLimitOptions/70126483</value>
      <webElementGuid>1b915991-cccb-4eae-82c8-fd046d808a84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/UninsuredMotoristLimitOptions/70126483</value>
      <webElementGuid>5c74a9c8-557a-4a7b-a61b-5fa5971c7d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>1e9c3975-b4f4-4acf-bebc-1eff83d159db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>cf73fcb0-181a-4748-a02a-0911ce40457a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Reject  50,000-100,000  100,000-300,000  250,000-500,000  300,000-300,000  500,000-500,000  500,000-1,000,000  1,000,000-1,000,000 </value>
      <webElementGuid>bec4ee80-4d38-4118-a3e4-9b5ce64e2d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UninsuredMotorist&quot;)</value>
      <webElementGuid>1fe2a330-4c3f-4378-a0b9-a1729d1dc030</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='UninsuredMotorist']</value>
      <webElementGuid>d7f8dac1-5f1f-407c-b2c4-b1190a4e8882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div/table/tbody/tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>f5542578-0cde-4e11-8626-121f031da61b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uninsured Motorists Bodily Injury'])[1]/following::select[1]</value>
      <webElementGuid>46508d30-cf57-47f5-87d3-02c603ef1bcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Medical Payments Rejection Form'])[1]/following::select[1]</value>
      <webElementGuid>28dddab4-f327-4ec3-8baf-c4939b7bd194</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retain signed form in your office.'])[1]/preceding::select[1]</value>
      <webElementGuid>1e9d50b6-04ba-429a-a558-2bcb2f3396c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uninsured Motorists Bodily Injury Rejection Form'])[1]/preceding::select[1]</value>
      <webElementGuid>04f183de-f34d-4743-9c20-6ffc0ffe0f4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>82ca9a35-e468-4a3f-b898-1c3b299991b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'UninsuredMotorist' and @name = 'UninsuredMotorist' and @href = '/PersonalAuto/ExpressQuote/UninsuredMotoristLimitOptions/70126483' and (text() = ' (select)  Reject  50,000-100,000  100,000-300,000  250,000-500,000  300,000-300,000  500,000-500,000  500,000-1,000,000  1,000,000-1,000,000 ' or . = ' (select)  Reject  50,000-100,000  100,000-300,000  250,000-500,000  300,000-300,000  500,000-500,000  500,000-1,000,000  1,000,000-1,000,000 ')]</value>
      <webElementGuid>05d37171-3abc-4200-91c6-cdb7fadbd20a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
