<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Option 1 - Unlimited PIP B_75a6cb</name>
   <tag></tag>
   <elementGuidId>72014662-8ecc-4e35-964c-b817da64e68c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PipLimitOption']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PipLimitOption</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0a9f94ac-3eaa-4fb3-aa3c-4669ce02dd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>30dc2f85-b00a-451e-b857-4e774857e5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PipLimitOption</value>
      <webElementGuid>82bf608e-caf6-4889-8c71-bd512ec3cc7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PipLimitOption</value>
      <webElementGuid>6ca3826e-0e23-4a6c-a889-7e6de435f194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-text-highlight hmi-ui-dirty</value>
      <webElementGuid>2250e394-2890-4b8d-87b9-4f73d36416af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5df17c3f-7b08-4f76-8335-fe851105b8c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Option 1 - Unlimited PIP Benefits  Option 2 – Limited Coverage of $500,000  Option 3 – Limited Coverage of $250,000  Option 4 – Limited Coverage of $250,000 with some or all persons excluded from PIP Medical  Option 5 – Limited Coverage of $50,000  Option 6 – No PIP Medical Coverage for anyone covered by this policy </value>
      <webElementGuid>20817fbc-2aad-4e92-8468-d44261210271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PipLimitOption&quot;)</value>
      <webElementGuid>5eeed9a4-d96a-477c-b6b2-d3774999557b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PipLimitOption']</value>
      <webElementGuid>a569884a-bab7-4354-8cde-7405604d5c34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>fdbb1a98-172c-44a9-a17c-dcbb8b9a1943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit'])[1]/following::select[1]</value>
      <webElementGuid>53697f70-936c-4dc4-95cb-34fb944fde53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Personal Injury Protection'])[1]/following::select[1]</value>
      <webElementGuid>91786398-172b-44fd-acc9-cd95ad453e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Michigan Selection of Personal Protection (PIP) Medical Coverage - Individuals'])[1]/preceding::select[1]</value>
      <webElementGuid>4f95427c-5ced-4fe0-b60b-e6e35096e1a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excess Attendant Care'])[1]/preceding::select[1]</value>
      <webElementGuid>17f30b2e-267f-475a-95b6-df7b1e213a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>0bbc803d-12ab-4826-a823-45ceac03868a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PipLimitOption' and @name = 'PipLimitOption' and (text() = ' (select)  Option 1 - Unlimited PIP Benefits  Option 2 – Limited Coverage of $500,000  Option 3 – Limited Coverage of $250,000  Option 4 – Limited Coverage of $250,000 with some or all persons excluded from PIP Medical  Option 5 – Limited Coverage of $50,000  Option 6 – No PIP Medical Coverage for anyone covered by this policy ' or . = ' (select)  Option 1 - Unlimited PIP Benefits  Option 2 – Limited Coverage of $500,000  Option 3 – Limited Coverage of $250,000  Option 4 – Limited Coverage of $250,000 with some or all persons excluded from PIP Medical  Option 5 – Limited Coverage of $50,000  Option 6 – No PIP Medical Coverage for anyone covered by this policy ')]</value>
      <webElementGuid>190b445c-b70b-4f5a-b843-ae1f0d297cad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
