<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  0-5,999  6,000-Over</name>
   <tag></tag>
   <elementGuidId>542dab81-57ef-4262-be8c-f6417083b21a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Income']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Income</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>98e7febb-ca33-44a9-9638-37ae053e5206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>09256f67-d05b-43b1-b9a8-b733d851d998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Income</value>
      <webElementGuid>650b6fec-6a7d-4a27-b44c-bb124ccf0034</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Income</value>
      <webElementGuid>6e33e023-d165-4038-bca8-524e6c898d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>20fb5775-6dd4-43eb-9a7a-2401bc727812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>20e8fb94-4b7b-422b-8eea-6a57d2b54e4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  0-5,999  6,000-Over </value>
      <webElementGuid>7ba4cfcb-9c0c-4f0a-92ca-0fd819624d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Income&quot;)</value>
      <webElementGuid>e64f6f24-d319-4c80-baf8-553f2d497fc6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Income']</value>
      <webElementGuid>b8f5790c-63ef-439a-b4e2-70ba44fb0687</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/div[2]/table/tbody/tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>ebb80a26-78ad-4e06-9657-e1df47b32054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Income'])[1]/following::select[1]</value>
      <webElementGuid>e5fe198f-206d-446a-8c44-6366f6e72bc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Excess Attendant Care'])[1]/following::select[2]</value>
      <webElementGuid>4c9c96f8-9b2c-4dde-9685-86a6e99e0ee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number in Household'])[1]/preceding::select[1]</value>
      <webElementGuid>21a44ad1-633d-437f-ba61-e9f661698a90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Waiver Of Work Loss'])[1]/preceding::select[2]</value>
      <webElementGuid>f3f03a79-bf3f-495c-a323-fe1d9f9af1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>b5c1a79a-7742-456d-9236-441e744cf984</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Income' and @name = 'Income' and (text() = ' (select)  0-5,999  6,000-Over ' or . = ' (select)  0-5,999  6,000-Over ')]</value>
      <webElementGuid>3c7e0179-b616-49f9-bb1e-af08cf780c07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
