<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK</name>
   <tag></tag>
   <elementGuidId>2efc9764-878c-4ada-bc94-316c5978c69e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='policy-express']/div[5]/table/tbody/tr[3]/td/button/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui-button.ui-widget.ui-state-default.ui-corner-all.ui-button-text-icons.ui-state-hover > span.ui-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9d889758-428b-400a-8a92-c98a8ec4cecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>b3d88a96-354e-4069-9040-b3440bc59285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>a1fc408e-ddaa-40d7-84fa-f4e4c33292c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;policy-express&quot;)/div[@class=&quot;blockUI blockMsg blockPage&quot;]/table[@class=&quot;hmi-table hmi-table-centered&quot;]/tbody[1]/tr[3]/td[1]/button[@class=&quot;ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icons ui-state-hover&quot;]/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>080affa8-9d6f-49cb-81b7-49928d3adfa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='policy-express']/div[5]/table/tbody/tr[3]/td/button/span</value>
      <webElementGuid>1cebef19-c773-49a9-865e-7be0eb00af17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A value is required'])[1]/following::span[1]</value>
      <webElementGuid>36b42b95-2a9f-41f1-99a1-dc0c6f156731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Limit'])[2]/following::span[1]</value>
      <webElementGuid>910d346e-b786-48ac-852e-a48852697cd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>a62f36a6-0177-47d0-b9df-2e21b30db6be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/button/span</value>
      <webElementGuid>bf144408-6e28-4b70-8ef7-2da402225ab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>2cafe499-696e-464e-9b40-4aa1210a026d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
