<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3</name>
   <tag></tag>
   <elementGuidId>47748ae9-5dc2-4174-a873-779f505ad4d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyListedOperationsSoldAcquiredLastFiveYearsAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AnyListedOperationsSoldAcquiredLastFiveYearsAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3829027b-9e57-484f-94ac-6055fea992a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4becf126-bade-4e74-833e-deb49b8a61b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyListedOperationsSoldAcquiredLastFiveYearsAnswer</value>
      <webElementGuid>f64f8498-e26a-4a6d-b3a6-db0f9be017f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyListedOperationsSoldAcquiredLastFiveYearsAnswer</value>
      <webElementGuid>ae335c50-9197-4091-88ea-0129e2992046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>776fa52c-eafc-4348-93c6-dbbd9ec425bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>09c941da-cdda-4806-a1e7-0c07dcadc6b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>aa7b77a9-79b3-4c6b-ae77-fa145ca75b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyListedOperationsSoldAcquiredLastFiveYearsAnswer&quot;)</value>
      <webElementGuid>2ff1ff7b-43f1-410a-9960-c3c8d66c6c4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyListedOperationsSoldAcquiredLastFiveYearsAnswer']</value>
      <webElementGuid>5dcd602e-f743-47e7-96f0-3e1486ae0d82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>4cdbd009-b592-491d-a057-ffff0052c1b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/following::select[1]</value>
      <webElementGuid>6bac47f6-e283-4351-a7bb-d51165b44d4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[2]/following::select[2]</value>
      <webElementGuid>058fb37f-a960-41ce-b02f-e060b276f4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any operations sold, acquired, or discontinued in last five (5) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>107ac431-29d6-453c-b01b-b50722e84137</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/preceding::select[1]</value>
      <webElementGuid>4bc79cc4-bf7a-4430-ba69-e5c8d17d5045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>490ccf00-40a9-4b05-b145-7e3aecdb2bcf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyListedOperationsSoldAcquiredLastFiveYearsAnswer' and @name = 'AnyListedOperationsSoldAcquiredLastFiveYearsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>fbd6c40f-f4a4-4fe9-8a88-f07ff4977de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
