<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>a5936f6b-a94e-4ca0-8e40-b7651a824173</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ea5a3ac-085d-4431-86d2-9fceac1522d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>fb012208-1c47-494f-80f0-09b916ecc16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer</value>
      <webElementGuid>dae67b7e-0bf8-4b23-83a4-616ebfa603d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer</value>
      <webElementGuid>b6db703b-76e9-4a32-9715-95950a0904e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-dirty</value>
      <webElementGuid>27cd922a-f04a-4785-8c29-a9bd6dd2887d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>b79d3c02-1f04-43b0-92d1-3475998b7636</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>5ba65418-2eea-421b-9d0f-cd7e24991158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer&quot;)</value>
      <webElementGuid>77ef8de3-7264-4aeb-ace5-95ec6bc4fc3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer']</value>
      <webElementGuid>396a78a5-b436-4e95-b343-8f9f3f638511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>7db87114-1255-4a71-9876-fde0882b9737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Liability General Information'])[2]/following::select[1]</value>
      <webElementGuid>985f8844-0979-4f50-a053-2570e28e67a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Application Finished'])[1]/following::select[1]</value>
      <webElementGuid>3863b253-7605-4a6f-b1c7-8f1f6d71db5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any medical facilities provided or medical professionals employed or contracted?'])[1]/preceding::select[1]</value>
      <webElementGuid>78fbf815-1686-4857-b935-cbd0bcddec56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/preceding::select[1]</value>
      <webElementGuid>aa21c45f-7717-48cd-a6fe-4e28186ad7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>08bbc636-d0f3-4d98-aaed-3e1afcec499a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer' and @name = 'AnyMedicalFacilitiesProvidedMedicalProfessionalsEmployedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>78d31837-11f2-4e99-a9fd-650bfbf9a50d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
