<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>ba1e0400-1095-4d44-b284-253fe1509887</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='WatercraftDocksFloatsOwnedHiredLeasedAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WatercraftDocksFloatsOwnedHiredLeasedAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d73f019c-813d-4625-b74a-3c9f6af03b05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>553e1978-fa49-4d19-bf49-034b50219482</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WatercraftDocksFloatsOwnedHiredLeasedAnswer</value>
      <webElementGuid>1c7fc941-23ce-4d9b-a48c-10dee69b4d22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WatercraftDocksFloatsOwnedHiredLeasedAnswer</value>
      <webElementGuid>d08a086e-f254-4a8d-b721-65d77f479231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>59d3ee28-45db-469a-bb60-d44c6512ea0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>1f81fafb-cd7c-4378-bf13-b411f3639f3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>45e07ad8-d8b4-405f-a5ec-1388448feb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WatercraftDocksFloatsOwnedHiredLeasedAnswer&quot;)</value>
      <webElementGuid>9b2df5c1-2ff7-49fa-83c9-87276cb9d15d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='WatercraftDocksFloatsOwnedHiredLeasedAnswer']</value>
      <webElementGuid>f509777d-e5e6-42b2-bdf5-8b50e109dcf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>a8fbbfc2-728c-4d59-b9e2-68c689d0dfab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/following::select[1]</value>
      <webElementGuid>f7ea28dc-8c02-4a92-a0a1-151731c229cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Machinery or equipment loaned or rented to others?'])[1]/following::select[1]</value>
      <webElementGuid>8f9fa25a-1548-4375-8d25-a15d56f4239f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any watercraft, docks, floats owned, hired or leased?'])[1]/preceding::select[1]</value>
      <webElementGuid>c2a9a3bc-d7af-4e1e-8e8b-b7e278ad1dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[6]/preceding::select[1]</value>
      <webElementGuid>12dae793-96ab-489a-b153-b13a3df11e8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>981a539c-b837-4956-84c9-8eb99a6e1eff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'WatercraftDocksFloatsOwnedHiredLeasedAnswer' and @name = 'WatercraftDocksFloatsOwnedHiredLeasedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>812fcea1-de52-4888-a9b8-65342695810b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
