<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>6eeb23e9-ba86-4155-bb46-26e2ac19351a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DemolitionExposureContemplatedAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DemolitionExposureContemplatedAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5bebba14-bcee-4fbf-acc9-9e07f4e21412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>c6a28b8d-f26c-42a6-aedd-10eb1d7f225c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DemolitionExposureContemplatedAnswer</value>
      <webElementGuid>f9f43615-7f80-4ce2-b108-8bd5ee851f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DemolitionExposureContemplatedAnswer</value>
      <webElementGuid>a00237c5-a51e-4877-ab73-3f0494bb0eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>477d0f83-a13e-46d5-8f10-f223b89e93f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>27</value>
      <webElementGuid>0b852249-7476-450d-95d4-902225d8ba1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>30e006b6-8118-432b-92d0-ce73d0609cb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DemolitionExposureContemplatedAnswer&quot;)</value>
      <webElementGuid>58feccfc-2cf1-42f0-8015-7aa19a7569fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DemolitionExposureContemplatedAnswer']</value>
      <webElementGuid>d02d03db-851e-42df-ae79-d07e8ef7fce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>ca2afb3f-dc27-45f1-925f-f29b3c9b85d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/following::select[1]</value>
      <webElementGuid>c1c8ff93-1778-4831-b3ae-76397407dba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any structural alterations contemplated?'])[1]/following::select[1]</value>
      <webElementGuid>fc8bbe5a-ec57-41e0-8044-5b8c50ff5b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any demolition exposure contemplated?'])[1]/preceding::select[1]</value>
      <webElementGuid>82fe9bcd-8b40-439c-aa25-4283c9392032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[13]/preceding::select[1]</value>
      <webElementGuid>53517e23-0af3-4103-8a3e-14858a3e38b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>5422743a-e608-4890-891c-7af2298e022e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DemolitionExposureContemplatedAnswer' and @name = 'DemolitionExposureContemplatedAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>d3ca5e8d-99b4-4576-b8d0-ca176c9fa340</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
