<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1</name>
   <tag></tag>
   <elementGuidId>36043fbe-340b-42b8-ad19-d1828daef372</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AnyExposureRadioactiveMaterialsAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AnyExposureRadioactiveMaterialsAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fd1c7e34-bfdc-4d32-9594-98afe1d1c8f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>87e4016c-ec31-4362-858d-d4cdc4b661bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AnyExposureRadioactiveMaterialsAnswer</value>
      <webElementGuid>e6e66cb4-4c60-4017-92a3-cb5aa7aaf4be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AnyExposureRadioactiveMaterialsAnswer</value>
      <webElementGuid>0e81036a-3370-4ddc-b01a-d4a5d5569d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>40340835-c8c5-49ba-a571-c2b201773703</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4bc8e100-60bf-4f96-b00c-d1d4fae84ab3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>634b6aad-8777-4837-9d3a-7b394d6abfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AnyExposureRadioactiveMaterialsAnswer&quot;)</value>
      <webElementGuid>a0fba91d-bd7e-4cc1-803f-5de16b227a56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='AnyExposureRadioactiveMaterialsAnswer']</value>
      <webElementGuid>3a3cebaf-bb2e-49d6-ab59-4aa7424a85a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>7fccbc58-51c7-4b93-8738-1a72ab8f331f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/following::select[1]</value>
      <webElementGuid>a67d459f-acd7-4561-9508-dd042091a744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any medical facilities provided or medical professionals employed or contracted?'])[1]/following::select[1]</value>
      <webElementGuid>ebd0bc77-ca1c-42ad-9e48-f045ad6419b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any exposure to radioactive/nuclear materials?'])[1]/preceding::select[1]</value>
      <webElementGuid>f0d93c4f-fa89-4014-bafc-e78aa35610e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[2]/preceding::select[1]</value>
      <webElementGuid>ee904ca8-ec6f-49ca-b19e-b503be6cbc71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>f1569ae5-5742-4693-9ae3-f4093d07865b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'AnyExposureRadioactiveMaterialsAnswer' and @name = 'AnyExposureRadioactiveMaterialsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>9e950e2b-3b32-4969-8451-1cae554a8efa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
