<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17</name>
   <tag></tag>
   <elementGuidId>8eab08aa-b4e8-4e3c-8005-03ca23c54f8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CrimesOccurredOrAttemptedLastThreeYearsAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CrimesOccurredOrAttemptedLastThreeYearsAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>994571f2-869a-4ac6-89cc-8f876553c6ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f5248f34-d6ed-4f94-87d4-774f721aa2da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CrimesOccurredOrAttemptedLastThreeYearsAnswer</value>
      <webElementGuid>ccef72e9-6c2a-4213-abe7-a5e1a8cf7ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CrimesOccurredOrAttemptedLastThreeYearsAnswer</value>
      <webElementGuid>bb091495-018f-4314-94d8-0ba2fe5748f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>986e25bf-4be9-48d5-b392-845d18f0ad5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>37</value>
      <webElementGuid>63500785-2ba3-4a87-9e53-4c77105e1d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>06613db2-51a3-4697-a217-806b82b62a92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CrimesOccurredOrAttemptedLastThreeYearsAnswer&quot;)</value>
      <webElementGuid>235ba7f8-db57-46a3-bde8-45ee126ebf09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CrimesOccurredOrAttemptedLastThreeYearsAnswer']</value>
      <webElementGuid>5244c0d1-6d59-4c9a-a15b-f9d318ac8e8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[35]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8019782c-2ade-425f-95db-d94be5712c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[17]/following::select[1]</value>
      <webElementGuid>a7284659-8741-41a8-9ae1-74306b754d4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are day care facilities operated or controlled?'])[1]/following::select[1]</value>
      <webElementGuid>a62eea41-9bd2-4746-8df5-14d9f8ba3e78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have any crimes occurred or been attempted on your premises within the last three (3) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>79ff4300-69c8-4751-ae42-465e38c1d806</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[18]/preceding::select[1]</value>
      <webElementGuid>2d152994-c2ed-43d9-865d-decde56899ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[35]/td/table/tbody/tr/td/select</value>
      <webElementGuid>06ab3fe0-67a3-4776-a756-fde24a34a64b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CrimesOccurredOrAttemptedLastThreeYearsAnswer' and @name = 'CrimesOccurredOrAttemptedLastThreeYearsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>a0538505-296c-4f67-ae76-a79cd2e85db7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
