<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18</name>
   <tag></tag>
   <elementGuidId>1168e811-afda-41b3-96f6-663e142990d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FormalSafetySecurityPolicyInEffectAnswer']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FormalSafetySecurityPolicyInEffectAnswer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f57572e6-ec88-4080-a2f8-036b132549bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e26813d0-3477-4b87-9478-733ad824708f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormalSafetySecurityPolicyInEffectAnswer</value>
      <webElementGuid>251780c5-328f-4f5d-a7be-2757bd505d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormalSafetySecurityPolicyInEffectAnswer</value>
      <webElementGuid>942341b3-e8f5-4985-9347-f1e4cee0bec5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>75957f2a-a164-4331-a68e-a821fa48d007</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>39</value>
      <webElementGuid>0579b115-f8b4-48cd-b8c5-e76bed2f739e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>9ba687f8-094d-40d2-b8de-176ee3a7f6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormalSafetySecurityPolicyInEffectAnswer&quot;)</value>
      <webElementGuid>d7a80e76-ce7c-4cd5-9b7d-c373e640d4ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FormalSafetySecurityPolicyInEffectAnswer']</value>
      <webElementGuid>85edb8d9-a551-4ea1-90ae-f0f7e410ea9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[37]/td/table/tbody/tr/td/select</value>
      <webElementGuid>fe3a2d81-5b5d-4947-b693-40e4e403c961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[18]/following::select[1]</value>
      <webElementGuid>9bae9d5c-ecbf-45ce-8038-7c17a33f7625</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Have any crimes occurred or been attempted on your premises within the last three (3) years?'])[1]/following::select[1]</value>
      <webElementGuid>3f1d4b04-f725-4296-a30a-9853914ecca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is there a formal, written safety and security policy in effect?'])[1]/preceding::select[1]</value>
      <webElementGuid>63df3b67-b004-4088-9e58-43774f815dba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[19]/preceding::select[1]</value>
      <webElementGuid>9fd83b94-4547-4305-aae1-b2213afcf1ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[37]/td/table/tbody/tr/td/select</value>
      <webElementGuid>1bf99eaa-3330-4bb2-9486-5410d551ba76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FormalSafetySecurityPolicyInEffectAnswer' and @name = 'FormalSafetySecurityPolicyInEffectAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>c280df65-a4a1-4307-a694-8f9f08630b4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
