<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit_EmployeeBenefitsLiablity</name>
   <tag></tag>
   <elementGuidId>e3a4db6e-4d51-4715-ade8-2cceb00d9ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmployeeBenefitsLiablity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmployeeBenefitsLiablity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ce633ccd-f5d0-4e5b-8a7d-9c38e19d8498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ad377550-caa0-4c47-bd5b-05ccfd10bd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>dcf99df5-171d-43f1-9ece-67deb4b71e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmployeeBenefitsLiablity</value>
      <webElementGuid>c59b18bc-0e8c-43f1-9690-7157cbed07ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmployeeBenefitsLiablity</value>
      <webElementGuid>4cd09ceb-bd18-477e-8b1d-b2549a9200f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui</value>
      <webElementGuid>6877008f-efa3-4fd1-8440-f20a19571ee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>95b74354-82aa-457b-aa30-997c9ff4f9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>1f85d47b-6df8-4d3d-9df5-1e9ef7565721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmployeeBenefitsLiablity&quot;)</value>
      <webElementGuid>197116b1-6755-4f50-9a47-c30620f4e053</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmployeeBenefitsLiablity']</value>
      <webElementGuid>057358d5-52c6-4d53-b2a9-cdf264c332a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[2]/table/tbody/tr/td[2]/div/form/div[2]/table/tbody/tr[10]/td/input</value>
      <webElementGuid>abf374e9-10fc-46f0-b89b-f2b09676ca16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td/input</value>
      <webElementGuid>3cbb38ba-c8fc-4608-8d63-de8353773385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmployeeBenefitsLiablity' and @name = 'EmployeeBenefitsLiablity' and @type = 'checkbox']</value>
      <webElementGuid>d250ae9e-046e-4092-bf2e-18e137ab5261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
