<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_25,000_TheftExclusion</name>
   <tag></tag>
   <elementGuidId>6457f415-aae4-4806-8976-9e0a21d9efb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TheftExclusion</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TheftExclusion']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b6ea7721-a7c0-4da8-9b81-ee18b38d50ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>6f22cff9-8fdb-4375-b9a4-94c14c0e20cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>ff1a6e87-059a-41cb-8564-c889a1e0351e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TheftExclusion</value>
      <webElementGuid>03b1e0f7-56d6-4e21-b51f-9c68ea3caea6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TheftExclusion</value>
      <webElementGuid>26048d97-5fdf-41b0-9831-4d619ac709b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui</value>
      <webElementGuid>31203133-c01e-4dd8-8c60-351d817541fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>46</value>
      <webElementGuid>a6eb8f14-2310-4975-9f54-ba9d51357551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>34504f9f-334c-4b05-89ef-262375dd00c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TheftExclusion&quot;)</value>
      <webElementGuid>472147ea-8719-4915-a86d-0a3a9e3ed44c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TheftExclusion']</value>
      <webElementGuid>83e8a81a-68e8-464f-a90f-ab14cfbc2a3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[2]/table/tbody/tr/td[2]/div/form/div[2]/table/tbody/tr[20]/td/input</value>
      <webElementGuid>e980fcad-077f-4214-ac06-7c36b9244f24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[20]/td/input</value>
      <webElementGuid>9bcd0d21-9190-44ff-849d-f59080863be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TheftExclusion' and @name = 'TheftExclusion' and @type = 'checkbox']</value>
      <webElementGuid>e51bc22c-6e02-4fb6-952d-fb876dcfef5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
