<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Businessowners</name>
   <tag></tag>
   <elementGuidId>22b024ee-d604-44c8-adab-cb7eb1ab5c31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#react-select-2-option-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id = 'react-select-2-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c28b9c46-0851-4f2b-a5eb-cb799e3ab066</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value> css-8lc6ki-option</value>
      <webElementGuid>f93d60a0-dbf9-498d-8c03-c6b676e2c3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>react-select-2-option-1</value>
      <webElementGuid>4b7e44ce-7640-42e5-907b-541c61b83379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>479f5fdc-4383-4c87-919f-b2157eb0f23c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Commercial Auto</value>
      <webElementGuid>40cce112-6660-4a0e-81ae-bef407bfb190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react-select-2-option-1&quot;)</value>
      <webElementGuid>6f750d49-0681-4588-825b-8523066d322f</webElementGuid>
   </webElementProperties>
</WebElementEntity>
