<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_NameOnPolicy</name>
   <tag></tag>
   <elementGuidId>d5ef379e-e7a5-4a7a-b3af-43c68e74a5df</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NameOnPolicy']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NameOnPolicy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>925f3f82-c060-4138-a286-21d52a534c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>8cdaec99-46f2-45cf-9bbb-1762a1e69a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>help</name>
      <type>Main</type>
      <value>NameHelp</value>
      <webElementGuid>86996b6e-ec34-4659-bf53-c6ef46298d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameOnPolicy</value>
      <webElementGuid>070290a2-5e5b-46d7-b27a-a4e8433d9505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NameOnPolicy</value>
      <webElementGuid>ccc96cdb-bb3f-4056-a425-373a8ec89b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>This name will appear in search results</value>
      <webElementGuid>d577df38-e285-4f68-ae2f-706c79742f9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>b6783461-ba5b-4a41-adbc-8a66bd4e0a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>be401a0d-09e6-46cf-9321-0a246a02ab46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[A-Za-z0-9\-'&amp;#,\.!\*\+ /]+$</value>
      <webElementGuid>2c1abcf2-01ad-4209-97dc-d2b7cd6795fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>5c69a64f-6d06-408e-8272-1f6fb6fc48b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e35f862-79a9-444e-9b70-37cfd1d42b69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameOnPolicy&quot;)</value>
      <webElementGuid>7eabc0e7-e961-4679-8f86-e41ab61ba819</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameOnPolicy']</value>
      <webElementGuid>ea6c04a6-04bb-416b-adc9-c6c95b774a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>75ad6100-0eae-43c2-a9a9-c87c518197d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>a14e39cd-a3c8-405e-8e7c-e1b124e25162</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NameOnPolicy' and @name = 'NameOnPolicy' and @title = 'This name will appear in search results' and @type = 'text']</value>
      <webElementGuid>75e7e7e9-8678-4517-bfb3-1ecccf9925d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
