<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>b1194e72-36a6-4f02-a565-94907187442f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JudgementOrLienAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='JudgementOrLienAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>543f168f-24b4-4728-aac7-c4f72e7eb5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d424d27e-2e02-4435-9b3f-8acfc74057e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>c0c1f2df-2f28-4a9b-a0fe-56cbd3504e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JudgementOrLienAnswer</value>
      <webElementGuid>becd6592-3fbf-42d2-a825-6a3eca263896</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>694059d6-c963-4065-845b-c5f2dbc59a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>53</value>
      <webElementGuid>d59ecb5e-dff1-41de-93f2-10728a9777b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>e723b8d4-16cd-49c2-8d22-bced7a834fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JudgementOrLienAnswer&quot;)</value>
      <webElementGuid>b592728b-f23f-4950-b04d-db6555b7dda3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='JudgementOrLienAnswer']</value>
      <webElementGuid>667d32f3-fbc9-4479-9b75-270e88d00b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>e7a988cf-4ffa-4c4f-aab0-89d89d8728e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[4]/following::select[1]</value>
      <webElementGuid>38d4f468-059c-4f62-991d-cf64380d1756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[4]/following::select[1]</value>
      <webElementGuid>59d5d6cc-6f3b-4b7e-a8c5-fb27ffa575c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has Applicant had a judgment or lien during the last five (5) years?'])[1]/preceding::select[1]</value>
      <webElementGuid>ecf5677f-0084-4268-93ff-8bf38d6058f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[5]/preceding::select[1]</value>
      <webElementGuid>395f0967-1880-45e1-9ca9-6b9b736bd7ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[21]/td/table/tbody/tr/td/select</value>
      <webElementGuid>d655681f-db5a-461b-9953-59809b74fd0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'JudgementOrLienAnswer' and @name = 'JudgementOrLienAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>04d0d62d-d1e5-47da-a8ac-bb3dbd0bbaa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
