<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>ef7de58c-ba36-40ef-9a52-0eb1f6083e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ForeignOperationsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ForeignOperationsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a3f7bdd5-25f1-4a16-b635-cacfa538588f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>45b6fbc2-a840-49da-8750-695c9fae6b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForeignOperationsAnswer</value>
      <webElementGuid>83b21c51-6035-4d83-bcee-3b2b485ddc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForeignOperationsAnswer</value>
      <webElementGuid>2b26cdfa-4813-48f9-a25b-37d19a739046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>ccfdac7f-6377-4da3-a921-581c2900b216</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>3a2d5bb3-2418-4adc-9a4f-4eefc2842ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>8b890c9a-ff36-4081-a9f3-a20d39c2474f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ForeignOperationsAnswer&quot;)</value>
      <webElementGuid>bfc781ba-c956-44d1-8494-6a2ab522c4a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ForeignOperationsAnswer']</value>
      <webElementGuid>2a752b09-be9e-477f-8526-79409cf9772e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>1d0042e7-bb5f-4a25-8ee4-5015a6173c87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/following::select[1]</value>
      <webElementGuid>1e04e5fc-6dc0-42f3-9926-565e4acb8b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has business been placed in trust?'])[1]/following::select[1]</value>
      <webElementGuid>4910493d-831b-47dc-a564-dbaf5d16c2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/preceding::select[1]</value>
      <webElementGuid>f7cb8eb6-ea31-412b-abb9-5aa591c3f8ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does Applicant have other business ventures for which coverage is not requested?'])[1]/preceding::select[2]</value>
      <webElementGuid>3a8edeb5-c85c-4488-a3f2-92c4470b78d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>56f04514-5f63-4b78-9f80-0b6287c6c061</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ForeignOperationsAnswer' and @name = 'ForeignOperationsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>21ee6f65-3bde-40c6-81ac-df664a8eee55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
