<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6</name>
   <tag></tag>
   <elementGuidId>e0ca4181-c1a0-4f58-aa94-ead8d4876bc8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LossesRelatingToSexualAbuseAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LossesRelatingToSexualAbuseAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c8032a8e-0aaf-4a44-b2f6-c63fe0717ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>1c990e6e-c13b-41c4-956b-d96877ce16b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LossesRelatingToSexualAbuseAnswer</value>
      <webElementGuid>efed60b9-fada-41bf-b43f-c757da795a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LossesRelatingToSexualAbuseAnswer</value>
      <webElementGuid>f2f75861-4888-4c23-9a25-99decec9b665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>1d8b47e9-26a8-4286-aaff-447ba7fdc6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>31</value>
      <webElementGuid>199d326b-b478-4d06-98d1-7db25264c10f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>14278c6f-d5c3-4922-923c-0127f63b39f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LossesRelatingToSexualAbuseAnswer&quot;)</value>
      <webElementGuid>fa075466-000f-4371-b447-30e55432630c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LossesRelatingToSexualAbuseAnswer']</value>
      <webElementGuid>ffed58d6-79f6-4884-92a3-33152ea547ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[13]/td/table/tbody/tr/td/select</value>
      <webElementGuid>53f4f607-95e6-42e1-b00f-98f82f47624c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[3]/following::select[1]</value>
      <webElementGuid>99fb793e-3a16-4d6f-aa4a-59a9013ce65a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[2]/following::select[1]</value>
      <webElementGuid>ec8880e4-7742-4018-9df1-4c1aa26819f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/preceding::select[1]</value>
      <webElementGuid>074e1b1c-f2a5-4f96-8685-32e24ae61e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/preceding::select[2]</value>
      <webElementGuid>17348f0d-02e8-4b6e-a7d4-9d3263d9e20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td/table/tbody/tr/td/select</value>
      <webElementGuid>b9d63002-0430-4bf6-a6cf-1210c688cdc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LossesRelatingToSexualAbuseAnswer' and @name = 'LossesRelatingToSexualAbuseAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>6f80f3eb-04d5-4bc3-8e04-7bec41732cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
