<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1</name>
   <tag></tag>
   <elementGuidId>d168f50c-84ba-4eca-9ae3-ab44fdfe022b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ApplicantHaveSubsidiariesAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ApplicantHaveSubsidiariesAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a18e5d6e-2ec4-41d6-b4df-4b3bbc2e6bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4f4a3d21-f7bb-44c4-8227-c0481bc9b13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ApplicantHaveSubsidiariesAnswer</value>
      <webElementGuid>4e9cfa54-e779-4eb9-9343-aa9518f7ab11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ApplicantHaveSubsidiariesAnswer</value>
      <webElementGuid>fa8ec808-f759-487c-868a-03f3c8692149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>05722d58-1a94-43e8-bf95-23b112d7bf91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>0b910eb6-ea0c-4a47-9570-a6c7dcfda5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>8c3124e3-d5cc-4694-8433-c1b4017fe770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ApplicantHaveSubsidiariesAnswer&quot;)</value>
      <webElementGuid>91969857-1155-48cb-830d-161b01793b2c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ApplicantHaveSubsidiariesAnswer']</value>
      <webElementGuid>f6f899ae-e072-4d8f-a60d-e8338dcea9f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>51409202-b0e8-4428-84d3-b8d233f81b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% Owned'])[1]/following::select[1]</value>
      <webElementGuid>7bd82780-af52-46be-beaa-0f8a1f6dd8f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship Description'])[1]/following::select[1]</value>
      <webElementGuid>534fafe4-3318-4ac5-89b8-b395519ab302</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the Applicant have any subsidiaries?'])[1]/preceding::select[1]</value>
      <webElementGuid>8eecfd80-1ed3-4d0e-bd38-495e05d5cee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subsidiary Company'])[1]/preceding::select[1]</value>
      <webElementGuid>dbbe44fd-48ea-476e-8af1-d76ef9850ef3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/select</value>
      <webElementGuid>772288d2-27d3-4e72-b668-6e80d43afb02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ApplicantHaveSubsidiariesAnswer' and @name = 'ApplicantHaveSubsidiariesAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>644efda3-d69a-4e4e-9de0-c36580cdfb40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
