<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11</name>
   <tag></tag>
   <elementGuidId>30f5e654-5cbb-43b0-922e-e8fbba61d17f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BusinessPlacedInTrustAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='BusinessPlacedInTrustAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6e3f4eda-b21d-4ef5-a53f-c92084809697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4d2fe2d4-0c34-49a4-8c0e-8ed3bccbeb6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BusinessPlacedInTrustAnswer</value>
      <webElementGuid>0419e6d4-7b46-4f6d-a1db-aaef23db7ed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BusinessPlacedInTrustAnswer</value>
      <webElementGuid>b1a81e6d-3ad2-40a1-be7a-b44e84e660fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>341a22cd-4839-4a6b-8f11-97fde02519a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>62</value>
      <webElementGuid>56247082-ae72-4566-95d9-e50039a84fbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>7c657d85-d922-40c4-b0be-d3a7394c818b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BusinessPlacedInTrustAnswer&quot;)</value>
      <webElementGuid>6b712fa2-f92d-44e3-83d2-84f194e6c542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='BusinessPlacedInTrustAnswer']</value>
      <webElementGuid>b7a046af-de46-488d-a1d1-aee946d9c0eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2b26a806-34b7-4389-b353-9a1dbd30f008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[6]/following::select[1]</value>
      <webElementGuid>09047c2b-620d-4ac1-9324-45237cb8f10e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[6]/following::select[1]</value>
      <webElementGuid>691ba231-4fd1-4b82-9df5-a790690a4cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has business been placed in trust?'])[1]/preceding::select[1]</value>
      <webElementGuid>53c2155a-7536-42fe-b50a-b1d7d6b364be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/preceding::select[1]</value>
      <webElementGuid>043d8bbf-43f0-4a2c-9057-c5b17f37c033</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[23]/td/table/tbody/tr/td/select</value>
      <webElementGuid>47a8a072-76d8-4790-b02f-51672ced0a74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'BusinessPlacedInTrustAnswer' and @name = 'BusinessPlacedInTrustAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>21ef8d98-972e-46f4-a057-dcb7c3671a83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
