<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>185781a6-80f7-48f2-9d81-87053684690f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FireOrSefetyCodeViolationsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FireOrSefetyCodeViolationsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c5619ef8-8a4e-4f09-8bca-cddfccd29776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>62622076-9290-46b3-8445-40e2c04170c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FireOrSefetyCodeViolationsAnswer</value>
      <webElementGuid>232e77bb-1156-4809-af8d-56174db59691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FireOrSefetyCodeViolationsAnswer</value>
      <webElementGuid>225193a6-9028-4f96-9b89-0dc3f853cc98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>086d9e1a-9e86-4d64-baf9-f770475b4f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>8c4836c4-f8a8-4691-b31f-4d9603d8d409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>bd32a2de-6b23-42a0-b4e4-5d9b91665215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FireOrSefetyCodeViolationsAnswer&quot;)</value>
      <webElementGuid>2451e1f6-843c-4700-877e-b2f4d225fc9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FireOrSefetyCodeViolationsAnswer']</value>
      <webElementGuid>a16e49d5-60dc-4b62-b43a-6bcd7553220c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>25b0913d-966b-4d2b-89d7-b4503254382d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/following::select[1]</value>
      <webElementGuid>a8bb71ca-53cd-469f-af43-06368bbb8bb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/following::select[2]</value>
      <webElementGuid>00477569-9d86-4364-9a91-99b828a49612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any uncorrected fire and/or safety code violations?'])[1]/preceding::select[1]</value>
      <webElementGuid>ed866480-c2a9-4acf-985e-28fd519921ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[1]/preceding::select[1]</value>
      <webElementGuid>cb4912e0-ed26-4ad3-8601-282e14fdb39e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>666e8296-471d-4c42-88ef-a4d73fdb77f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FireOrSefetyCodeViolationsAnswer' and @name = 'FireOrSefetyCodeViolationsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>23f900df-5b3f-44ce-857b-3222646876a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
