<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2</name>
   <tag></tag>
   <elementGuidId>e5839db4-bf42-488b-9d84-1f5d2f0528eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FormalSafetyProgramAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FormalSafetyProgramAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5939f1eb-2f71-495f-9c63-4761a68572c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4a29df69-23ec-4585-9c3e-314895c346b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormalSafetyProgramAnswer</value>
      <webElementGuid>3c2ba00c-b29a-4ac5-a6db-6dbcb32a1f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormalSafetyProgramAnswer</value>
      <webElementGuid>91986e2c-e724-4fba-863b-6e10372c89a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>96972e8f-ae9a-4f85-8751-a3c378b327dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>104f6460-5226-4689-8ef0-aef41db7def6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>94721c87-b757-4bcd-9674-991013bdb6f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormalSafetyProgramAnswer&quot;)</value>
      <webElementGuid>d067f717-c2f3-448a-9505-240c882d75ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FormalSafetyProgramAnswer']</value>
      <webElementGuid>6d8c8767-da65-46bf-9e1e-cdea65d755bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>b26d2df6-8124-442a-9aee-1ee86557a5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='% Owned'])[2]/following::select[1]</value>
      <webElementGuid>a33e94d3-7d41-4eac-a38f-0207c75c7c5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Relationship Description'])[2]/following::select[1]</value>
      <webElementGuid>679f4f5f-93a3-47a0-b874-8850666b75a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is a formal safety program in operation?'])[1]/preceding::select[1]</value>
      <webElementGuid>2eb5d8cd-0600-46fb-bc11-0044167a058a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Safety Manual'])[1]/preceding::select[1]</value>
      <webElementGuid>a07a172d-a5ca-43fc-93ce-d13a85fc31e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/table/tbody/tr/td/select</value>
      <webElementGuid>f32bed17-26a6-4221-b4a5-c1f1bd01668c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FormalSafetyProgramAnswer' and @name = 'FormalSafetyProgramAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>2b21d660-d648-4e3c-aac3-1131dd1b10d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
