<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>7ee9fd5f-7863-41d4-9397-72704cbc8364</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ForeclosureRepossessionOrBankruptcyAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ForeclosureRepossessionOrBankruptcyAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5eea173-bb3c-4d11-9b0e-38a7d0f610e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ff278b6a-3fe8-4e32-a1b9-cf138f7abb20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForeclosureRepossessionOrBankruptcyAnswer</value>
      <webElementGuid>0c8a60d2-9a61-4704-8102-f70c3c75e52a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForeclosureRepossessionOrBankruptcyAnswer</value>
      <webElementGuid>8d853c03-9116-452a-839c-7bfb9c2182a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>6d7d4523-556a-4af0-9e5e-434067fd816b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>5fcf4f95-8141-4d43-a392-2795e57769ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>e8371fc2-e95e-4ff9-91f3-3f4c4614fd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ForeclosureRepossessionOrBankruptcyAnswer&quot;)</value>
      <webElementGuid>ec36076b-8a1e-46c0-8571-4ff88bb9cf2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ForeclosureRepossessionOrBankruptcyAnswer']</value>
      <webElementGuid>456fb872-9913-410f-af6d-78f218d30ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr[19]/td/table/tbody/tr/td/select</value>
      <webElementGuid>67cd52a3-dc94-41dc-9840-d596456c3804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[2]/following::select[1]</value>
      <webElementGuid>ecf6ed89-6f17-4496-8fa0-ee88f811b30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[2]/following::select[1]</value>
      <webElementGuid>ec2fb54a-9b54-410e-be54-ac309573ad39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[3]/preceding::select[1]</value>
      <webElementGuid>95c1175b-f227-4c78-aa32-582b70a58a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[8]/preceding::select[1]</value>
      <webElementGuid>c2ff5a05-aa03-4023-8839-f190ae8c55db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td/table/tbody/tr/td/select</value>
      <webElementGuid>d1154383-1119-4b4a-b68e-5d31498bc991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ForeclosureRepossessionOrBankruptcyAnswer' and @name = 'ForeclosureRepossessionOrBankruptcyAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>f8dc7291-0398-438a-8c0c-dcd473bbb470</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
