<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone_Phone</name>
   <tag></tag>
   <elementGuidId>e4eeba13-9060-466e-845a-06f5f3940993</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Phone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Phone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc170c80-5bf8-4439-83af-347ab34409cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>962b9b2c-49d2-49ad-9320-619191384139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>help</name>
      <type>Main</type>
      <value>ContactHelp</value>
      <webElementGuid>caa1a900-d6a8-4da3-af3d-c262bea3ae15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>6c07c17c-a783-4779-8107-fb5a7ae4389e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Phone</value>
      <webElementGuid>589ba879-22c4-4c52-a66b-6ed53dcc9b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>11bc6083-3578-4fff-9de0-b48e479695ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui</value>
      <webElementGuid>6b943488-eb90-43b9-839d-37dfa4a33c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter phone number</value>
      <webElementGuid>a5a113ae-a224-4f89-ad12-2a1f15652246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter the telephone number without spaces or punctuation.&lt;br />&lt;br />&lt;b>Example: 6168675309&lt;/b></value>
      <webElementGuid>d717c4e4-f1b2-4f92-940e-fe56be1d169d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\(?\d{3}\)?.*\d{3}.*\d{4}$</value>
      <webElementGuid>eeca6767-9641-4bac-8ef3-8131f1943709</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>6a356928-6627-4534-a544-408eda01256e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f77234a-6447-4148-a13b-d6a07c1f670e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Phone&quot;)</value>
      <webElementGuid>d490b758-e8b0-42d5-9a86-a9ec7e4c7433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Phone']</value>
      <webElementGuid>5b64735e-ae2b-403d-9f8c-ee08fd938823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/table/tbody/tr/td[3]/div/form/div[4]/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>41e6a794-54fd-45c8-ae3d-c84e93198b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>49242177-5f07-4612-8f18-7709a14249b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Phone' and @name = 'Phone' and @alt = 'phoneNumber' and @title = 'Enter phone number' and @type = 'text']</value>
      <webElementGuid>eb470c8c-2c93-45a3-b298-516d5276bbda</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
