<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Is a formal safety program in operati_4dcc3d</name>
   <tag></tag>
   <elementGuidId>1dfac428-d317-436c-a346-38539d781ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FormalSafetyProgramSafetyManual</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='FormalSafetyProgramSafetyManual']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77869119-c572-4301-8d9c-2f560771b3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>dd0b0d04-9984-46e8-aff0-187edbc98e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>0237c8c4-210c-4f8d-93b4-4aba396f79db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FormalSafetyProgramSafetyManual</value>
      <webElementGuid>bd889e48-e424-4b04-8330-0643dcbb99cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FormalSafetyProgramSafetyManual</value>
      <webElementGuid>22b545f8-64e9-44ad-b78c-84a8f45b1e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>605e7bf9-1b13-46a9-b183-dcbbd74734f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>c2e0d05a-5754-4a94-8296-8ad9acdf1a72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e3780533-77f2-4771-a2dd-d30de4da4b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FormalSafetyProgramSafetyManual&quot;)</value>
      <webElementGuid>0ad766fb-5b6f-49b9-b41b-720922a7c66f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='FormalSafetyProgramSafetyManual']</value>
      <webElementGuid>be3e7f33-296a-40d1-a962-e31869d44b92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[6]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7deb6c6f-e1e0-43f2-9136-576ef1200990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>190e360a-0f2a-412b-b5b7-dadb2acb9e08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'FormalSafetyProgramSafetyManual' and @name = 'FormalSafetyProgramSafetyManual' and @type = 'checkbox']</value>
      <webElementGuid>3337b488-a5a6-49cc-9914-1f1d5b167b7e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
