<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12</name>
   <tag></tag>
   <elementGuidId>6070d05f-bff0-445d-8fd3-e1a8b88a0cb8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ForeignOperationsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ForeignOperationsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>36c7989a-7134-4f56-92b1-4a818ad602d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3505117d-a751-4fed-b546-86a4781e7ccd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForeignOperationsAnswer</value>
      <webElementGuid>3aeff5f0-ec9f-441d-9ad5-3616bf7b213d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForeignOperationsAnswer</value>
      <webElementGuid>45c567fa-c5ad-40da-8c03-f4fb9fa00751</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>6fb3c7e8-e436-4296-ad0c-76721e2cbbef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>64</value>
      <webElementGuid>bfce12a4-eaf6-487d-8872-eac2c06a00e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>74cf3274-7c63-4485-83af-699cd738f14a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ForeignOperationsAnswer&quot;)</value>
      <webElementGuid>cf00aea5-e192-4a45-ba45-a4f3e0ad1143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ForeignOperationsAnswer']</value>
      <webElementGuid>d83fa620-2fcd-4769-bda6-03324c2c74dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>749c8b73-095a-4a01-8646-2e7572d36471</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/following::select[1]</value>
      <webElementGuid>3c0ddcb7-8f39-42af-bda4-e1f0cda97b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Has business been placed in trust?'])[1]/following::select[1]</value>
      <webElementGuid>018cb168-2a1c-47b3-af95-81c07243abd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/preceding::select[1]</value>
      <webElementGuid>e085878b-a679-45db-9eb6-0014002f4120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does Applicant have other business ventures for which coverage is not requested?'])[1]/preceding::select[2]</value>
      <webElementGuid>d0859971-9208-4e59-b071-7ea263d9170a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[25]/td/table/tbody/tr/td/select</value>
      <webElementGuid>7611741b-2b5a-478e-bf4e-3cef6b1b0ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ForeignOperationsAnswer' and @name = 'ForeignOperationsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>cd86a19d-0aae-412f-bab0-0e50b7289678</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
