<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>bbcc5692-f491-4f4c-b224-d3ffac93a99d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtherInsuranceAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OtherInsuranceAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9f6ef19d-5acc-4159-8347-62f06fb26262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>a13fb372-1f96-40f2-b146-3f32ca1733f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtherInsuranceAnswer</value>
      <webElementGuid>8aab488c-77db-493c-892e-4e084dd394d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OtherInsuranceAnswer</value>
      <webElementGuid>86342bf4-1c2b-44d6-810c-2e53e9f6628c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>541ab775-be96-4cdb-b308-e0b395fe5b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>227edb10-6e61-4900-aa0a-5d3733f6d9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>0d1686f6-7535-4296-aec5-f1c1494a25f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtherInsuranceAnswer&quot;)</value>
      <webElementGuid>fd740310-1cb0-427d-9ad4-da4cfe8f399c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OtherInsuranceAnswer']</value>
      <webElementGuid>97805ed4-fd9c-4287-b23f-d1aeb536fe3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>48ab8e87-c906-490b-8fd0-87cc2eb3a051</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/following::select[1]</value>
      <webElementGuid>340ed3e2-ae19-4987-9a44-00dc00a08254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any exposure to flammables, explosives, chemicals?'])[1]/following::select[1]</value>
      <webElementGuid>483ebe8e-0a96-49c8-888b-df91311c4d29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any other insurance with this company?'])[1]/preceding::select[1]</value>
      <webElementGuid>34ddf55e-9684-4d46-b676-6c5c71fb69e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td/table/tbody/tr/td/select</value>
      <webElementGuid>89728c1b-9c56-4100-8356-5f5e51d10897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OtherInsuranceAnswer' and @name = 'OtherInsuranceAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>37500311-7ec4-4f8c-a984-b666a77f4778</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
