<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9_10_11_12_13</name>
   <tag></tag>
   <elementGuidId>b4ef104f-e902-4bcb-a457-45298cdeadb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OtherBusinessVenturesAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OtherBusinessVenturesAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2c76f620-1b13-495a-864a-ca258c175a33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d4502d60-9870-4b62-9105-1a0fdb9644fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OtherBusinessVenturesAnswer</value>
      <webElementGuid>b216607b-22cc-4109-a4e7-ecb49ef1914c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OtherBusinessVenturesAnswer</value>
      <webElementGuid>ef461326-572b-4086-9bc8-3682527616be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>3991e902-414f-489c-9714-2d3a52f288db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>66</value>
      <webElementGuid>3da0a01b-2954-47f7-8bee-d94f06376951</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>ff29c83e-a805-4f86-a9c6-3c7e62c04518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OtherBusinessVenturesAnswer&quot;)</value>
      <webElementGuid>2b4702ac-5551-4108-bc07-20ca1973ad4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OtherBusinessVenturesAnswer']</value>
      <webElementGuid>3c14b14b-29ba-4f9e-a69d-9b098032bb8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[27]/td/table/tbody/tr/td/select</value>
      <webElementGuid>0639b41a-2ded-4c8c-9ef7-851cfbff9ce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[12]/following::select[1]</value>
      <webElementGuid>da6b8d02-bf2c-4f14-ae46-f7a3ed3bbf4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name of Trust'])[1]/following::select[2]</value>
      <webElementGuid>85f8e9c8-0860-4ad8-9379-ae22433a5950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does Applicant have other business ventures for which coverage is not requested?'])[1]/preceding::select[1]</value>
      <webElementGuid>960c626f-bb8b-4a11-a7ba-f23f897fd57e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[13]/preceding::select[1]</value>
      <webElementGuid>63db28c0-553d-4470-9b1e-738ba9afa16a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[27]/td/table/tbody/tr/td/select</value>
      <webElementGuid>487dfe75-a93a-471a-97d6-b737c3d04b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OtherBusinessVenturesAnswer' and @name = 'OtherBusinessVenturesAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>3c9f0c93-b7f3-484a-a113-0b4ee94cd90b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
