<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8_9</name>
   <tag></tag>
   <elementGuidId>471aaad9-2eb9-4a53-a4db-0070ef4b17b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ForeclosureRepossessionOrBankruptcyAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ForeclosureRepossessionOrBankruptcyAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>349dca40-ba15-4a89-b74a-469f7fffdd5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cdc5438e-1ab2-4601-936c-2c5f43b7f982</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ForeclosureRepossessionOrBankruptcyAnswer</value>
      <webElementGuid>7cee92f7-ecaa-4f2c-8d0f-bcc28a50be4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ForeclosureRepossessionOrBankruptcyAnswer</value>
      <webElementGuid>c88a75e8-5907-44e4-a993-bad7b3647cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>1685b03c-4d77-4f21-b084-6d2552674554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>15008753-1053-4662-ae0e-1c3663cf0047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>c15e72d9-da1d-4063-adb3-3bff6e256b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ForeclosureRepossessionOrBankruptcyAnswer&quot;)</value>
      <webElementGuid>a40484ec-d988-42d3-ab86-295e55eb5c1e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ForeclosureRepossessionOrBankruptcyAnswer']</value>
      <webElementGuid>984b0255-61c8-4e4c-92c3-d7b7c7d8b202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[19]/td/table/tbody/tr/td/select</value>
      <webElementGuid>08743519-9f04-49ef-84e2-3f348062a023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution'])[2]/following::select[1]</value>
      <webElementGuid>cc628a9a-2191-4052-91a5-a736c640293a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resolution Date'])[2]/following::select[1]</value>
      <webElementGuid>40fe5a30-3112-4322-a821-a02a96af323e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[3]/preceding::select[1]</value>
      <webElementGuid>878afa16-837b-487c-84e5-ba5517b54f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[8]/preceding::select[1]</value>
      <webElementGuid>160f33a6-f5ff-4f51-b57b-4fdd0447f06e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td/table/tbody/tr/td/select</value>
      <webElementGuid>2a3a38a6-808a-410b-bf70-d561611ab501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ForeclosureRepossessionOrBankruptcyAnswer' and @name = 'ForeclosureRepossessionOrBankruptcyAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>ae759c13-d803-4881-abfc-60387e5de15d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
