<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3_4_5_6_7_8</name>
   <tag></tag>
   <elementGuidId>242e8652-4abb-47e9-be00-20ee7d67cee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#FireOrSefetyCodeViolationsAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FireOrSefetyCodeViolationsAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ba38685d-8e4f-4a1c-a0cb-6ca08df18a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>8349fc70-2a31-4107-931d-fec0e9470c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FireOrSefetyCodeViolationsAnswer</value>
      <webElementGuid>f47b82e8-798b-44d1-b3c4-6b57848aed17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FireOrSefetyCodeViolationsAnswer</value>
      <webElementGuid>e27fc1c2-d244-4fb4-a688-cf1835dc9f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>80524956-f2ed-4361-898f-2343a41b04b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>989ea812-556f-4975-8127-114db059f33c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>ae7630e9-7f34-4f54-809a-dc50effdd521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FireOrSefetyCodeViolationsAnswer&quot;)</value>
      <webElementGuid>4034a1f4-cccb-4db5-8603-b7a0125420b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FireOrSefetyCodeViolationsAnswer']</value>
      <webElementGuid>10817576-6355-4ef2-bb09-06d667acbf7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>fcbc0c07-2ccf-4f93-893c-1f7ae50b2315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[5]/following::select[1]</value>
      <webElementGuid>00304239-b8d9-4405-9a6a-8395647f2cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[4]/following::select[2]</value>
      <webElementGuid>fc01b4df-3361-4029-abc5-61759e99df2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any uncorrected fire and/or safety code violations?'])[1]/preceding::select[1]</value>
      <webElementGuid>307afc30-93d0-4fcd-92aa-737c1b3e3af0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Occurrence Date'])[1]/preceding::select[1]</value>
      <webElementGuid>f402ce3d-5f37-4e16-901f-32a458c2938d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[17]/td/table/tbody/tr/td/select</value>
      <webElementGuid>8c8532d0-63b2-4958-a88b-f20e1181ed1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FireOrSefetyCodeViolationsAnswer' and @name = 'FireOrSefetyCodeViolationsAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>7fa77bc5-40ad-4d41-98a6-ccb880b95d2d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
