<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No_1_2_3</name>
   <tag></tag>
   <elementGuidId>3b8d06fa-b281-4762-a911-ed6164be39bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ExposureToFlammablesAnswer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ExposureToFlammablesAnswer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8325c3e0-6d33-4a0e-80cf-b90739dc32e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>25626e57-b46b-4cf0-ae89-c1efbfd0ad40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExposureToFlammablesAnswer</value>
      <webElementGuid>53a46bee-0c00-4129-9890-7d80bc571d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ExposureToFlammablesAnswer</value>
      <webElementGuid>21a72b10-442b-4361-9362-74f68c58cba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>9e6bc53b-d9b3-4399-87e4-53a165d6fd22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>b8c02192-56dc-4fe2-a8c5-0e75f976f726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>8f89a6d8-4f53-4348-89be-fec3aba5c390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExposureToFlammablesAnswer&quot;)</value>
      <webElementGuid>5411ebeb-7988-4c6c-801b-8c16200334c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ExposureToFlammablesAnswer']</value>
      <webElementGuid>233639fd-8064-4f95-8624-fc7a55520be9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>a0e5029d-e9aa-4ec0-bda9-90a2da5f8e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Other'])[1]/following::select[1]</value>
      <webElementGuid>2b096207-8e4d-4a25-b6c8-c6fddbbc31a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OSHA'])[1]/following::select[1]</value>
      <webElementGuid>8e0b63bc-8e10-4b12-af4c-024d7b242191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any exposure to flammables, explosives, chemicals?'])[1]/preceding::select[1]</value>
      <webElementGuid>c0855487-8c9d-44d3-91ab-38c913f89f0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Explain'])[1]/preceding::select[1]</value>
      <webElementGuid>7f92966e-c98a-4cd5-8a2f-9981d74cf466</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td/table/tbody/tr/td/select</value>
      <webElementGuid>f79ce8a1-9668-4da8-b949-d5ad86beb633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ExposureToFlammablesAnswer' and @name = 'ExposureToFlammablesAnswer' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>8863dc41-24c1-4329-aa88-12926224b64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
