<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_AddressLine1</name>
   <tag></tag>
   <elementGuidId>dbe6e525-e509-46c3-bffb-7aaf6c8d73b9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressLine1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressLine1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>01f3d621-372f-4556-b0e3-050626e1917d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>13691349-c8ed-4b32-ad50-ef60c3783349</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressLine1</value>
      <webElementGuid>b9babe73-06d9-4b1b-982d-3c88a1fee437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressLine1</value>
      <webElementGuid>950aea30-ea0e-474a-b467-c8e5166a8c0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>f00f7ba3-42bd-4cab-a3bc-5a35a08ee8ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>435610a9-41c3-404c-8f7b-3597b05addad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter the street address or PO Box</value>
      <webElementGuid>b8ed616f-26c0-4d11-9c71-b13c25287308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>073a0f80-bb8d-4da4-b200-e752b66193e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[A-Za-z0-9\-'&amp;#,\.!\*\+ /]+$</value>
      <webElementGuid>b7b0a568-552e-4e65-bcde-7e7f14799c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>6ccc2ac5-34ab-45e6-8b7b-e47e518d1332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a2de977-ebe7-4f5a-9879-ed0b63d972b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressLine1&quot;)</value>
      <webElementGuid>21a72721-2990-4ddf-8ae6-e835a964ffe7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressLine1']</value>
      <webElementGuid>c62a9d30-038b-4dfd-90b1-20b39f134929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>98d26fd2-beab-45c6-8313-425b87efeba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>11dbba79-5ba9-4aee-a854-55f7176dc31c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressLine1' and @name = 'AddressLine1' and @type = 'text']</value>
      <webElementGuid>7cd9b230-c93c-46ab-a2fd-fae9c678f2aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
