<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_City</name>
   <tag></tag>
   <elementGuidId>3eb4cf9b-763c-4c43-8745-2024d286d4d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#City</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='City']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1dbcf512-c766-4f0f-94da-b1f0b9a8f41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e5ed2df3-2874-4100-972a-06fce7a09e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>3e2794d5-9e8d-4e8d-879a-f11377062726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>78248ae6-72e4-46bd-888d-e31f819db7dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>35</value>
      <webElementGuid>d27e3215-a73c-457c-b1f6-60d7141f5399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>50f3c157-8b67-4127-91af-de7b08cf28d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[A-Za-z0-9\-'&amp;#,\.!\*\+ /]+$</value>
      <webElementGuid>a4610d0b-9769-4dfd-932c-0afe453751b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>44a485b1-4d9a-46e8-9cb4-aac7aa7a6fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>296bd6b7-e079-4a2e-9b54-4dca8bb297ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7cfd3c39-882d-4987-9af2-8c4f71ad6c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;City&quot;)</value>
      <webElementGuid>88a27d97-99ae-440e-8e6a-1b9393e9a0ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='City']</value>
      <webElementGuid>4715f749-47ee-4376-bad0-54cee7932583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>9895a664-d7c3-4a3a-bb64-60e342e1aba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>9dc92ce6-02a8-45cb-9a7a-4183ba2ddc05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'City' and @name = 'City' and @type = 'text']</value>
      <webElementGuid>37a8924d-9feb-4bb4-b879-b78227374089</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
