<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- What role does this contact provi_893561</name>
   <tag></tag>
   <elementGuidId>c8e86df4-5d27-4662-8175-bf46bbf27231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContactRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>41908985-1eda-4923-8d0c-be5f312edbac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>dcf93e3c-3cc4-475a-aa7f-656b195702bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactRole</value>
      <webElementGuid>29f583dc-4368-4b6a-b42f-d131d003495d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactRole</value>
      <webElementGuid>1b3f89b3-824f-4425-a0e2-7558f409b009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>daa6c37f-3800-4a6a-9db8-52110012dcbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>382df13d-fc50-498b-81dd-1aba64bf8a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- What role does this contact provide? --  Accounting Records  Inspection  Both </value>
      <webElementGuid>098c6f24-dfbd-496f-aa68-baa053ba12ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactRole&quot;)</value>
      <webElementGuid>ab4f9dec-484e-411a-a830-3363f3855460</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContactRole']</value>
      <webElementGuid>38799939-7bbb-42fe-9bcd-06ab25f057dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>f9e94e6b-0750-44b6-adff-43bd68da6c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[1]/following::select[1]</value>
      <webElementGuid>97784e48-400d-488f-b8ba-2b4611bba392</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/following::select[1]</value>
      <webElementGuid>d27cac67-3ca5-4c40-9790-b61c870f5c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>0c6416e5-c703-47ca-aea7-7c344d611102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>6b086274-a6de-4ea4-ac13-51522066ebe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>288c17f5-778c-427e-98c2-4806907860d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ContactRole' and @name = 'ContactRole' and (text() = ' -- What role does this contact provide? --  Accounting Records  Inspection  Both ' or . = ' -- What role does this contact provide? --  Accounting Records  Inspection  Both ')]</value>
      <webElementGuid>5ebd10ae-4247-4fe1-b435-d73d489121ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
