<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Association  Corporation  _83d9d3</name>
   <tag></tag>
   <elementGuidId>8616b35d-9c15-46c4-9c14-82e12f4537de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Entity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Entity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a10bdedc-e697-4dee-aacd-9b973e129c4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>a9fb245f-9c75-4cd7-baf7-1e5ff6301da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>2f98c1bc-0ea1-4b74-abf5-40ba886f55df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>8e9f4359-c9f4-4f1e-9b61-db8d6825c2cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>0761bdc8-3c7f-45eb-9093-70d2baedbe03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>912cb204-adf3-484c-bfb1-690560545837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  LLC  Other  Partnership  Subchapter “S” Corp  Trust </value>
      <webElementGuid>3916b6b4-e263-40bc-a71c-946013bb84c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Entity&quot;)</value>
      <webElementGuid>879a0eec-533c-4dd6-9d76-8f75d98f7227</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Entity']</value>
      <webElementGuid>12184e19-6bbd-4f0c-9f56-7da31f193a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>67ec7227-3c3e-4ca9-926e-c4d7421a5206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity'])[1]/following::select[1]</value>
      <webElementGuid>7595e07d-4929-4205-9dec-f461e0b33d62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Information'])[1]/following::select[1]</value>
      <webElementGuid>e3dc62b4-399a-4ae5-9280-8a5191b73456</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Description'])[1]/preceding::select[1]</value>
      <webElementGuid>338b2188-9f50-4642-a588-caa1e0f554cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the applicant have a DBA name?'])[1]/preceding::select[1]</value>
      <webElementGuid>9d4ab75a-3202-4466-9980-16fdd74de555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>829e9c83-7d66-458f-849e-ecf24b91932e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Entity' and @name = 'Entity' and (text() = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  LLC  Other  Partnership  Subchapter “S” Corp  Trust ' or . = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  LLC  Other  Partnership  Subchapter “S” Corp  Trust ')]</value>
      <webElementGuid>b14c3aee-9dab-4210-b7f4-c3015c0c963c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
