<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  No  Yes, I have Loss Runs _504ea5</name>
   <tag></tag>
   <elementGuidId>21d9eca0-53ee-42f9-ae73-ad7577c26847</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LossesExist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LossesExist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a27e7fce-491c-49f5-bac1-c02134557447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>7016d6e8-d36e-43a4-aa4b-88c5a15f8344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>fc74bba2-9a19-4452-b65f-3f1191b89d55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>0a68ecb1-f104-4e28-b100-409b03e89d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>7ac1941f-9afd-4e52-a043-db31263dc5b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6d9e8d83-58dd-40db-aa10-66b8003939a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information </value>
      <webElementGuid>b171f45f-000c-43ee-8523-17872a2962a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LossesExist&quot;)</value>
      <webElementGuid>8ee6e685-a4da-46f5-95c1-160637c8d9b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LossesExist']</value>
      <webElementGuid>f3713311-de24-40a6-a7ac-25df5fe92e16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>b555e1b7-9d60-4db0-bf20-e76de89a4e37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any claims, losses, or occurrences in the last 3 years?'])[1]/following::select[1]</value>
      <webElementGuid>d0e32081-5583-4cba-95fb-afedd3a64076</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss History (3 Years)'])[1]/following::select[1]</value>
      <webElementGuid>8d4e3b16-4201-4f39-a52a-26f01fa33b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>fd989873-bef4-4144-8456-a6341a89ea3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please schedule all Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>69fc1ddc-bd78-4f43-a802-925c1bc711c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>549c0f84-4739-45b7-951f-edb0d8d7b3a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LossesExist' and @name = 'LossesExist' and (text() = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ' or . = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ')]</value>
      <webElementGuid>9fa53752-1f07-4e9f-bafe-8b1536d007cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
