<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Name_MailingAddressStreetName</name>
   <tag></tag>
   <elementGuidId>2877bcfc-26c8-4787-b59f-40153996d531</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MailingAddressStreetName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MailingAddressStreetName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d5eed93-0d02-458c-91ce-c091d078190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5457212f-4e81-4113-b2db-c8e55bdb1099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingAddressStreetName</value>
      <webElementGuid>1a5f4b3e-e134-4636-8d11-dbd0e32c2b72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MailingAddressStreetName</value>
      <webElementGuid>4bddfc1b-5e0e-40e9-8a0b-ac35598af42c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>86341054-47dd-49ce-8b2a-01cf0965d7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z '\/\-.]+$</value>
      <webElementGuid>0dcfcb38-60eb-445d-846c-4fcbf4de4294</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>ad01d815-c06d-4ba7-9031-dd39f7492da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>dcd2ddb4-8228-479f-abab-c470efc34b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>056f1fa5-cd0f-4919-a995-6eb1fab03b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingAddressStreetName&quot;)</value>
      <webElementGuid>3d229f46-2552-41d3-929b-272357ec8e9b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MailingAddressStreetName']</value>
      <webElementGuid>d2d4939b-9052-4de8-a46d-afa91329ee6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[4]/table/tbody/tr[3]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>74f1fd9d-f4ae-4f20-b1a7-4c5ed98ee5ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>fe274dfc-496a-4f18-86df-47f1e51765d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MailingAddressStreetName' and @name = 'MailingAddressStreetName' and @type = 'text']</value>
      <webElementGuid>1c448ed7-d8c1-4e5c-a02f-bfc2bbf6b581</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
