<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_fee8b744f5642ed980d7d156c2_4f50e4</name>
   <tag></tag>
   <elementGuidId>99c89dd5-aaff-4aa4-be23-91dd4f5499ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='insured-list']/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fee8b744f5642ed980d7d156c2ae92f_FirstName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>31f3c32c-d100-4a40-ab95-63063227d207</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>80a358fa-2362-470b-b903-f12fb54ed774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fee8b744f5642ed980d7d156c2ae92f_FirstName</value>
      <webElementGuid>80794d9d-120f-4525-af46-b26696cfa7f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fee8b744f5642ed980d7d156c2ae92f_FirstName</value>
      <webElementGuid>7ea72092-d231-4b68-a8ca-3290b3ea1cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z '\/\-]+$</value>
      <webElementGuid>6843644f-366c-4eb0-8095-b14996d79477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>9cdb8856-a7cb-408c-9c70-85c5cae22bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>68236e9d-90dc-4e6a-bdf6-4db4034ed814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>21e6bf5a-b18b-4086-9e3e-4b774e2fd2be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>491c8893-f7f9-4a62-bd77-746da11404d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fee8b744f5642ed980d7d156c2ae92f_FirstName&quot;)</value>
      <webElementGuid>fb9cdfc0-f82a-4897-b694-cb9db205aa67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fee8b744f5642ed980d7d156c2ae92f_FirstName']</value>
      <webElementGuid>7f8f056d-cb3a-4c61-801e-661c726d14ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured-list']/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>31c5f8c4-abfc-42a7-b360-00c3b8408757</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>55f67ee8-61ec-41e8-a22d-5a0c54154ca2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fee8b744f5642ed980d7d156c2ae92f_FirstName' and @name = 'fee8b744f5642ed980d7d156c2ae92f_FirstName' and @type = 'text']</value>
      <webElementGuid>54e331a3-6877-4f9d-a47c-8f3086802efe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
