<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last Name_fee8b744f5642ed980d7d156c2a_fc1bde</name>
   <tag></tag>
   <elementGuidId>3d5a0244-82e9-42e9-9fc3-831110852e52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='insured-list']/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fee8b744f5642ed980d7d156c2ae92f_LastName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>641abe99-8e8c-42d1-b9ff-f44a19134980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cd166c1f-eb0b-4e9b-b2e6-2ddea3718a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fee8b744f5642ed980d7d156c2ae92f_LastName</value>
      <webElementGuid>48d16c99-2c6c-4afe-90ae-a808fd2df404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fee8b744f5642ed980d7d156c2ae92f_LastName</value>
      <webElementGuid>c801e1d1-a4bc-4eb5-958a-789abc3d3cba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z '\/\-]+$</value>
      <webElementGuid>0701418e-0f2a-41be-b1f9-4d9769bdbfdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>8c28b8a3-b9ad-441e-b86b-ecfe1d706277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>0bf1ef75-15a5-483f-add3-6af609ea6509</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ba374a7e-b767-4f9b-8bcd-59e08ef5cd25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1718ae5c-b0c9-4ddd-b489-3dc7a23fb57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fee8b744f5642ed980d7d156c2ae92f_LastName&quot;)</value>
      <webElementGuid>1e34a48b-2840-4ea4-99bb-7ff2a332dbd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fee8b744f5642ed980d7d156c2ae92f_LastName']</value>
      <webElementGuid>aa774a4b-3b0c-4514-84d7-44e29d0adb4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured-list']/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>c7cfca72-9d50-479c-b132-e327bcbbcd6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>59d154b6-6fdc-4a45-8556-b2e6f1cd96db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fee8b744f5642ed980d7d156c2ae92f_LastName' and @name = 'fee8b744f5642ed980d7d156c2ae92f_LastName' and @type = 'text']</value>
      <webElementGuid>0994e7d1-a5c2-4c3b-b9b0-1fc9a5507cb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
