<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Social Security Number_fee8b744f5642e_2b6235</name>
   <tag></tag>
   <elementGuidId>788491ee-a721-4f63-b185-9b48a3fdbcb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'SocialSecurityNumber')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7df46c4-9ade-488f-833d-3b01432e7155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>0f823e98-962e-48b0-8a3d-6ddaa7561f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber</value>
      <webElementGuid>734654f2-dc38-4784-9603-624bb54752ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber</value>
      <webElementGuid>f5fb080c-024b-46de-83e8-0329f74c75ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>socialSecurityNumber</value>
      <webElementGuid>e55595e3-3478-4229-b2bd-21a38f9c53e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>8fc569bc-7b3f-4c32-a63a-c8f2614d04ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\d{3}\-\d{2}\-\d{4}$</value>
      <webElementGuid>b1c7fbbf-140f-4255-81d2-6d09bc2cb478</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>000-00-0000</value>
      <webElementGuid>b32e41ef-765b-45f6-9d4c-0569c1f9b574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ed6d4cf-8d83-4e64-8733-9b6bd714247a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca2e757c-bfc3-4b51-9e88-12734c7ff863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber&quot;)</value>
      <webElementGuid>cc01fd0c-b80c-4108-b483-7a00415d4d7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber']</value>
      <webElementGuid>c314d85e-ea39-4471-af74-bf55adfea019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured-list']/table/tbody/tr[3]/td/table/tbody/tr/td/input</value>
      <webElementGuid>ad66652b-930f-4b28-a3c3-3103d4eb7b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/input</value>
      <webElementGuid>cf222ec8-a9a6-49e2-921f-b76ca949e2b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber' and @name = 'fee8b744f5642ed980d7d156c2ae92f_SocialSecurityNumber' and @alt = 'socialSecurityNumber' and @placeholder = '000-00-0000' and @type = 'text']</value>
      <webElementGuid>0251267f-f553-43eb-92cb-397b958c1e13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
