<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Association  Corporation  _83d9d3</name>
   <tag></tag>
   <elementGuidId>69d6bc5c-a620-4b10-a88b-d527443d2e01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Entity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Entity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>785022b6-74e1-4e70-90e4-21785f4c5a11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>74bf91a9-a224-49f0-ad37-b66ced0e6825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>99945316-9d4a-424c-abb6-422d4d68ef50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>0ce027a6-a26f-4c47-bc53-f7dc6848ed47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>05e1c303-fe57-42d4-9096-854b8300c331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>f14ead44-2f15-4bcf-8b63-9b6eb7b35ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  LLC  Other  Partnership  Subchapter “S” Corp  Trust </value>
      <webElementGuid>e753523b-1f52-4c2d-b5be-180d341c6fa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Entity&quot;)</value>
      <webElementGuid>5e6c6032-91a0-4804-8f2e-9ee40d97f1a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Entity']</value>
      <webElementGuid>4b0dcd13-4603-45c0-a7df-bb2c42c7b2b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>555cd725-3c2a-4e22-9143-5379604007a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity'])[1]/following::select[1]</value>
      <webElementGuid>f2e6fc07-e5b3-46f6-98b0-69e4a805b35a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Information'])[1]/following::select[1]</value>
      <webElementGuid>62d1fb6f-a740-46a1-b3a6-01b4c7237632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Description'])[1]/preceding::select[1]</value>
      <webElementGuid>94f97cc7-a423-4dd1-87b9-5c4279613086</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the applicant have a DBA name?'])[1]/preceding::select[1]</value>
      <webElementGuid>a1cb18a9-57d9-45a8-b463-4b0f60846b37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e48e6b68-dc87-4551-9f00-8fdf313c54c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Entity' and @name = 'Entity' and (text() = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  LLC  Other  Partnership  Subchapter “S” Corp  Trust ' or . = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  LLC  Other  Partnership  Subchapter “S” Corp  Trust ')]</value>
      <webElementGuid>c437ecc6-a1b6-428c-b619-2b50a9f816dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
