<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description of Operation_Descripti_4b13ce</name>
   <tag></tag>
   <elementGuidId>4e657bd4-c2b3-45ce-8da6-99d701d80201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DescriptionOfOperation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DescriptionOfOperation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2dd66c30-09b4-4428-8670-2659ca99dedf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>eb3dbb60-f6e2-4269-b9ef-e0f7095f087b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>78b0c417-e85b-4f0d-9c9a-e7950c8977c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>15ea133e-0cb8-48e2-bce3-59e766aa0489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>62bc5c06-875f-49de-93ac-973c19a53eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>a2f936b6-778c-4598-9213-dad13ef07a8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>768</value>
      <webElementGuid>da26d413-e423-4edb-accf-eabc7f54e442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-editor hmi-ui-text-highlight</value>
      <webElementGuid>1f33f253-3606-4d67-a8b8-e919a505ee2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>2e36d5af-89e4-48c6-993d-b58bb5948e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DescriptionOfOperation&quot;)</value>
      <webElementGuid>9014250c-99ff-42b7-b116-589df1f827fa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DescriptionOfOperation']</value>
      <webElementGuid>c6156477-d9a8-45bd-964b-a13857273a6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/div[2]/div/div/form/div[4]/table/tbody/tr[2]/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>ad9839a0-2932-4623-b62d-6e6ccb7df9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>cc7d5b6f-cca5-4586-9a2f-f276eb44ed04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DescriptionOfOperation' and @name = 'DescriptionOfOperation']</value>
      <webElementGuid>57d49716-ff0e-4628-abf2-fb8246859da4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
