<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone Number_PhoneNumber</name>
   <tag></tag>
   <elementGuidId>41b379f3-9849-4ccb-9d30-7f8748d52a62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PhoneNumber</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PhoneNumber']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7f879c0b-b079-44cc-ac08-d0267b3e7c5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Submission</value>
      <webElementGuid>b4d8f707-0b16-4273-9743-30170f0cc9d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>122f1a6a-2cff-4e78-b6b3-2fde3c7d61a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>cedb044c-5db9-4a7d-98e0-7ef7bc2ac81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>f9739474-8605-40ef-8ea4-17ccb27a5927</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>b977fe73-7c93-4d4b-97b1-519c32711921</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vcardname</name>
      <type>Main</type>
      <value>vCard.Business.Phone</value>
      <webElementGuid>cfd4d796-f921-46a7-b099-f5e5aaa4b837</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui</value>
      <webElementGuid>b0e3ecd8-76d9-4ef1-9caa-72cef2072508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter phone number</value>
      <webElementGuid>39700a4a-af2d-47e7-b5c7-975aa0568417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter the telephone number without spaces or punctuation.&lt;br />&lt;br />&lt;b>Example: 6168675309&lt;/b></value>
      <webElementGuid>0ab58897-7bed-42ff-9e7d-118eb706228b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\(?\d{3}\)?.*\d{3}.*\d{4}$</value>
      <webElementGuid>8a0b7151-09b9-46d0-8381-0863ed121590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>15dcb27b-d9d2-41d3-8952-7c8c3757e28a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>988a34fe-e63e-4b8f-ac40-6b298276cbd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PhoneNumber&quot;)</value>
      <webElementGuid>5d7b9998-7efe-40bb-99a4-2e9d46963119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PhoneNumber']</value>
      <webElementGuid>0ace646e-9262-49f4-be99-5951c5b628db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/div[2]/form/div[5]/table/tbody/tr[3]/td/table/tbody/tr/td/input</value>
      <webElementGuid>9ed76413-5d32-4ccb-b93d-524e9e66f630</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/table/tbody/tr/td/input</value>
      <webElementGuid>b7595198-c7e8-4afc-8297-f9bd15fb62f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PhoneNumber' and @name = 'PhoneNumber' and @alt = 'phoneNumber' and @title = 'Enter phone number' and @type = 'text']</value>
      <webElementGuid>51a49250-a83b-4957-8b33-3e8604588b3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
