<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  No  Yes, I have Loss Runs _504ea5</name>
   <tag></tag>
   <elementGuidId>d6d2ce5c-65b0-41dd-863a-bfb626a88284</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#LossesExist</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='LossesExist']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e5c10339-0fad-4796-9c53-be27bce494c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>49a0da2e-a43e-4608-8862-73890416301a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>60775822-51e9-4321-a4f8-3b45a4b88879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LossesExist</value>
      <webElementGuid>168bd1f0-09c1-46f2-8c6c-ab509bb39480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>2d3ec13f-a404-4f9c-9119-a6bf6e3e7d0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>4911c696-373e-430c-8c55-4515e15d1f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information </value>
      <webElementGuid>c63cfc53-e3ef-4ef9-b760-30d03fac5311</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;LossesExist&quot;)</value>
      <webElementGuid>1578276b-f868-4da1-98eb-fcebdd84846f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='LossesExist']</value>
      <webElementGuid>d96f45d7-6d22-49f3-8dfd-98904198d868</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr/td/table/tbody/tr/td/select</value>
      <webElementGuid>b45ff3dd-adf5-4b22-8b6b-a4817fefec0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Any claims, losses, or occurrences in the last 3 years?'])[1]/following::select[1]</value>
      <webElementGuid>b0ff069b-d12f-4e3c-bdf9-4a7e1ece38fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loss History (3 Years)'])[1]/following::select[1]</value>
      <webElementGuid>bf7d410a-c576-4cfd-a6ae-d68f6eb38bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>a0db82db-65f8-47f3-ab59-32493341bb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please schedule all Prior Loss Information'])[1]/preceding::select[1]</value>
      <webElementGuid>68deea09-7b77-49ed-a95e-f06de7ce342d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>407c658f-4bf7-42c7-8073-1b324d8e2f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'LossesExist' and @name = 'LossesExist' and (text() = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ' or . = ' (select)  No  Yes, I have Loss Runs to attach  Yes, I want to schedule prior loss information ')]</value>
      <webElementGuid>56b2f465-01d1-4b76-a006-cbec1fb005a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
