<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_3860301</name>
   <tag></tag>
   <elementGuidId>f31e5d99-3ae6-45c8-8ec4-7bb50c573e50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='quote-status-table']/tbody/tr[4]/td[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(4) > td:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1633bb45-db6d-4e66-b5f4-86de153c34dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>nowrap</value>
      <webElementGuid>e750dc3c-fccf-41fc-8e01-6fc0c9b7871b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                3860301
            </value>
      <webElementGuid>d3a25587-5337-49aa-a61e-83bc37309ad7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;quote-status-table&quot;)/tbody[1]/tr[4]/td[2]</value>
      <webElementGuid>ee9b8c0f-2414-4de0-a0e5-744b1cb7808f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='quote-status-table']/tbody/tr[4]/td[2]</value>
      <webElementGuid>6e5a1021-c82a-4395-b240-8a6c31688374</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Policy Number'])[1]/following::td[1]</value>
      <webElementGuid>33262c1e-36c1-45bb-aabc-c468ef0ee889</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quote Number'])[1]/following::td[3]</value>
      <webElementGuid>8d68bee1-3926-4fab-8e42-15732f287516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::td[1]</value>
      <webElementGuid>8a8062ab-6e81-45ae-bb7d-854feb2606c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Business'])[1]/preceding::td[2]</value>
      <webElementGuid>7d8573bb-32f7-4f91-9b60-66a3476821de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='3860301']/parent::*</value>
      <webElementGuid>b89c3e1d-18e3-4d2a-8088-420421ade989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]</value>
      <webElementGuid>69fdf6a9-05b9-4ba8-872a-dd1028369910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = '
                3860301
            ' or . = '
                3860301
            ')]</value>
      <webElementGuid>3e27a5fd-315f-4fbe-8d4c-d14ab04267aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
