<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_browse complete list of classification codes</name>
   <tag></tag>
   <elementGuidId>51451f59-e23e-40d3-8996-c861da219c17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='browse-class-codes']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#browse-class-codes</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2bc8ee44-b3bb-4be2-a9bc-c53614a5e576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>56e04be8-32bf-4ac7-8281-cd2ba26f5c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>browse-class-codes</value>
      <webElementGuid>3286068c-5e97-4eb1-9848-046bafe56a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>browse complete list of classification codes</value>
      <webElementGuid>b40498f0-8d8c-4087-8475-be06ed9333f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;browse-class-codes&quot;)</value>
      <webElementGuid>fd15cc35-5f18-4b05-a9d3-2d98480a4b08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='browse-class-codes']</value>
      <webElementGuid>d9cfd1df-d33b-41d6-b8bb-9b89be5871e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='hmi-form-save-classification']/table/tbody/tr/td/a</value>
      <webElementGuid>59ebf8dc-db6b-4673-8106-bf79e032ccb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'browse complete list of classification codes')]</value>
      <webElementGuid>b61026e9-c359-4d0e-9581-299a048449e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exposure'])[1]/preceding::a[1]</value>
      <webElementGuid>73ff2ad7-68d0-4fde-9d31-73e709658f6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Exposure Basis'])[1]/preceding::a[1]</value>
      <webElementGuid>bccfdc69-ae74-4831-b883-81dfde6b5bc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='browse complete list of classification codes']/parent::*</value>
      <webElementGuid>922d8e8b-104c-45de-96a3-76478d614884</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[2]</value>
      <webElementGuid>695c1541-d98e-4002-bee9-f16abee65da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/a</value>
      <webElementGuid>0902cc32-29e3-43a1-8281-876b1e523048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'browse-class-codes' and (text() = 'browse complete list of classification codes' or . = 'browse complete list of classification codes')]</value>
      <webElementGuid>ceffeb57-4d97-4401-a633-3aba9e486955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
