<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue to Farm Personal</name>
   <tag></tag>
   <elementGuidId>28c5053e-0b3e-46aa-a2a5-e80cefd982ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#next-button > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='next-button']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1645c69c-44ae-4d33-bfb9-697d9c4b6a22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>61ddcf1c-1f8f-43b4-8a48-b889feb49c8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue to Farm Personal</value>
      <webElementGuid>631b98c3-1237-4854-8e3e-24222e44a88c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;next-button&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>65a77037-f687-497c-aa48-79f298c5b30e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='next-button']/span[2]</value>
      <webElementGuid>a9278c30-fdb3-4b5c-9d80-2fb95bd8045e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Applicants'])[1]/following::span[2]</value>
      <webElementGuid>9ff58cb7-cafd-4709-845e-13072e2be4b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add/Edit Structures'])[1]/following::span[4]</value>
      <webElementGuid>944ede53-3a0e-40cc-9c91-45168b48a11c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue to Farm Personal']/parent::*</value>
      <webElementGuid>8ab07378-9a37-4ae6-8876-28814fd677ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td[3]/button/span[2]</value>
      <webElementGuid>20a875ac-71e0-4d81-b9ce-28c72ea86b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Continue to Farm Personal' or . = 'Continue to Farm Personal')]</value>
      <webElementGuid>156bda28-a9b8-47ae-a2ee-5829c1b803ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
