<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Limit_Limit</name>
   <tag></tag>
   <elementGuidId>2c1a5b4a-9446-43cd-ba6c-4d5e91b36a4f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Limit</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Limit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71fe8ab5-452a-4fb6-9deb-9134afe71a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>AddScheduledFarmPersonal</value>
      <webElementGuid>1f4a6240-12c8-4e69-8744-4cbdc93dc874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Limit</value>
      <webElementGuid>60824cdc-ece7-4c1d-b49c-08b685ed7323</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Limit</value>
      <webElementGuid>66d08b6b-ab16-4517-93c6-56184ab8956f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>e3e07e4f-56f4-445f-993a-d4f7d5600f09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text-focus</value>
      <webElementGuid>e8c0548c-ba2e-4e64-8fcc-1efc648655d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>af428469-79c9-46c6-94d3-8683bd412afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>9999999</value>
      <webElementGuid>84e7c63e-c28d-43ce-9c2a-33491860570f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>0616c1e9-75e6-415d-b189-646169b8192c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a70f68e3-8966-46d2-967e-070e2e360ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Limit&quot;)</value>
      <webElementGuid>f3c6d7df-0f30-4de6-aee7-823e61e0b04b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Limit']</value>
      <webElementGuid>7c8f9936-e175-4c89-a0a4-a43684c7c623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-form-ScheduledFarmPersonal']/form/table/tbody/tr/td/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>a9353a72-e7b1-44c0-a446-e2d645ff35d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>9d345349-ba63-4fff-872f-7b447a31229e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Limit' and @name = 'Limit' and @alt = 'limit' and @type = 'text']</value>
      <webElementGuid>17b6280e-8cdb-4336-828e-6e6bd9893ee4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
