<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Producer Name_ContactName</name>
   <tag></tag>
   <elementGuidId>ec22503d-5bd4-464e-af86-00c412acdd66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContactName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d96296c4-a988-4654-a6a9-5dda868e84c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>85fa8eff-9b14-4346-b3b7-c586136da016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactName</value>
      <webElementGuid>f2b72e54-d52b-49c3-a699-1edad25f7d6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactName</value>
      <webElementGuid>5ac9c9b5-a7c3-403e-9559-333d72b80bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>a41fb5bf-22e7-43d5-87f1-cc3c5abe67d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>271a7bd9-00f4-48c4-a4f5-c6e7606dd4a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ab45249e-2b21-44d1-b238-a2324c7c1bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c88fd096-0935-444a-a4f5-41efaaef5b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactName&quot;)</value>
      <webElementGuid>e98f3ffe-c325-468b-8693-4fa00fb6479e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContactName']</value>
      <webElementGuid>4b10e750-46a7-485c-8e0c-16a1ef10cdae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[3]/form/div[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>784abd2f-eaee-4df3-a07f-494b570e0522</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>991098e1-f45a-4bcf-8e2e-2e39e3ed4a18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContactName' and @name = 'ContactName' and @type = 'text']</value>
      <webElementGuid>44fa7d38-76d0-4545-ad8e-cfbc5172d84b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
