<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit Referral</name>
   <tag></tag>
   <elementGuidId>a418cce6-67aa-48e0-a47a-a505fa99fcc4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Submit-Referral > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Submit-Referral']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>bd4b0e4e-a4ac-45dc-8780-9c9e3a1af020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>74d512c6-60d9-4140-8541-7ecb7834b4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit Referral</value>
      <webElementGuid>e3358719-2467-43d8-812c-af89c23fab6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Submit-Referral&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>858aa14c-3983-4b42-a886-86b47f449d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='Submit-Referral']/span</value>
      <webElementGuid>49f0233f-a4d9-476f-b489-4badd3379714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This comment will only be visible to Hastings Mutual employees'])[1]/following::span[1]</value>
      <webElementGuid>8e6c7147-cbef-4a53-af63-c1f45609294d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter comments'])[1]/following::span[1]</value>
      <webElementGuid>f1b89596-9b56-4c0e-8c0d-709119dc4450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit Referral']/parent::*</value>
      <webElementGuid>bad93585-d73f-4737-b7a9-a1077eadfc90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/a/span</value>
      <webElementGuid>5fea7fbf-46d0-4262-97e2-74eb4b1cac73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submit Referral' or . = 'Submit Referral')]</value>
      <webElementGuid>20662d7d-b5aa-4cf1-a0c3-fc6dade3d609</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
