<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Square Footage_SquareFootage</name>
   <tag></tag>
   <elementGuidId>e1aa2b84-724a-4489-823f-52774e9ba144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SquareFootage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SquareFootage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d385905b-8483-414e-82e2-44d6a54a3681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>593e9025-d29a-4095-9263-ef6ed22e2883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SquareFootage</value>
      <webElementGuid>40cffd4e-fb17-4dea-af41-cacd398d0f36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SquareFootage</value>
      <webElementGuid>65663844-0531-4759-ac88-c8d78230ca11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c032eae1-9e92-4193-ba3a-c241c04d0958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit5</value>
      <webElementGuid>8dc90fb2-6568-4578-99d9-bdec6947d441</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>741d8054-43f1-4a8c-bd81-696cd4321c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>887675c6-c83c-4c42-a23b-88018a7c590b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3981b926-c1c8-4909-83ed-eaac8cc50974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SquareFootage&quot;)</value>
      <webElementGuid>50da1814-2c77-4772-9d51-646a35d84f47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SquareFootage']</value>
      <webElementGuid>baa3de13-6ad6-44d6-8029-0196b00e67aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[8]/table/tbody/tr[13]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>e0ff77d0-353a-41ec-94c4-fb47277390a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>35aac305-d892-4126-84f5-b31b26e3f491</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SquareFootage' and @name = 'SquareFootage' and @alt = 'limit5' and @type = 'text']</value>
      <webElementGuid>9d04df1d-ba43-4a8f-883f-837512980ad5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
