<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Replacement Cost_ReplacementCost</name>
   <tag></tag>
   <elementGuidId>c1143c36-4fb7-42aa-81d3-031b6c1e692a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReplacementCost']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ReplacementCost</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10ae76e8-96f6-4aff-ad58-ea7d4c3bd0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>e53d492a-4e64-4d23-8f38-63967ee7a6fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReplacementCost</value>
      <webElementGuid>98b6a698-f304-4fa8-974a-5e4736f75b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ReplacementCost</value>
      <webElementGuid>1943d4de-fc9e-4396-812f-3a3c0ffbee0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit6</value>
      <webElementGuid>fbf882b9-c210-4799-a52b-a4ab95f6eb7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6742000b-e9c5-4b30-b3f6-11e3fa472734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>d94f9a50-b4bb-4096-a73f-0c9b51a60846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>30965231-5033-4920-a781-45fa603b6172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3e2cf760-9261-4e8b-8044-0921cd5895a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReplacementCost&quot;)</value>
      <webElementGuid>ff419587-3a46-4167-92a0-2c873257849e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReplacementCost']</value>
      <webElementGuid>bf571982-a34c-495a-b599-c7de2aa6503f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[8]/table/tbody/tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>dc8034bf-c46a-4d69-af70-f5d81069fb2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c3dd1786-2237-40d2-a52b-87d8cdfc349a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReplacementCost' and @name = 'ReplacementCost' and @alt = 'limit6' and @type = 'text']</value>
      <webElementGuid>1b3dc132-d99a-4832-90ec-c8bfe26f0602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
