<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  1,000  2,000  3,000  4,000  5,000</name>
   <tag></tag>
   <elementGuidId>c849c6e7-4cd2-445b-a527-36f83ee0520c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CoverageF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CoverageF</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1db36cb3-27ab-4615-99ba-1b969d4d10a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f0b813e0-381e-43c0-a957-5cc255573afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoverageF</value>
      <webElementGuid>67bf260c-e8fa-45e9-880f-9470d7476923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoverageF</value>
      <webElementGuid>0d01e87b-5a58-4530-a4bf-47cead546e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>7ad174b8-bd93-4c9e-836f-fa30731cd605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>59cfb471-b85a-44e6-8212-9cdf4aac7b9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  1,000  2,000  3,000  4,000  5,000 </value>
      <webElementGuid>734f4850-e2aa-4767-ac77-4cc621b511bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoverageF&quot;)</value>
      <webElementGuid>ff6789a4-52db-4b96-9017-6ec06c0bc5c0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CoverageF']</value>
      <webElementGuid>b533e2c1-8ab1-41ff-85f8-473b88b1a19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-coverages']/div/table/tbody/tr[8]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>696fe8e9-0fcf-4ce3-b0e5-092d964bc633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage F - Medical Payments'])[1]/following::select[1]</value>
      <webElementGuid>ed20bbe2-5499-40c1-9eb9-1321facb5ec1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage E - Personal Liability'])[1]/following::select[2]</value>
      <webElementGuid>a19ab0c8-d5fe-457d-a062-c3a5fe6a9101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/preceding::select[1]</value>
      <webElementGuid>84ee5962-32da-47d1-b6ff-0ef8ff20ca7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wind/Hail Deductible'])[1]/preceding::select[2]</value>
      <webElementGuid>56c5076a-5901-45f9-9d6a-97a8d0d6adc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[8]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>a80cdec2-a7ed-4669-807c-e089c54f5e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CoverageF' and @name = 'CoverageF' and (text() = ' (select)  1,000  2,000  3,000  4,000  5,000 ' or . = ' (select)  1,000  2,000  3,000  4,000  5,000 ')]</value>
      <webElementGuid>426d965b-7daf-43f6-bb96-38226fa0bc17</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
