<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)1,0001,5002,0002,5003,0004,0_abb474</name>
   <tag></tag>
   <elementGuidId>bba57ec8-0cef-44d1-90bf-fcbaa8a12e87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='WindHailDeductible']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WindHailDeductible</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>64aecb35-5eb7-4308-ba3b-164e8ec77ebf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>69421e4c-644b-4cc2-b0ab-7f40ac906a61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WindHailDeductible</value>
      <webElementGuid>ca20dc33-8c34-48e1-a6b3-f6e807aa5e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>WindHailDeductible</value>
      <webElementGuid>73ee39aa-219b-4e1a-a897-f88c54db64d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>d0b59425-fa56-45cb-9a04-5d7187222846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>18</value>
      <webElementGuid>778a3474-6559-4997-b6d2-e6d74e064981</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(select)1,0001,5002,0002,5003,0004,0005,0006,0007,50010,00012,50015,000</value>
      <webElementGuid>4e9272af-a869-49d0-a654-26890e96fffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;WindHailDeductible&quot;)</value>
      <webElementGuid>f3bcd8f4-313c-4fa0-97a7-86c78dc31a6b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='WindHailDeductible']</value>
      <webElementGuid>b588350c-2009-4b20-b315-cb67cb2c0845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-coverages']/div/table/tbody/tr[10]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>5af69c17-f501-4d47-98a0-6f2b0fcc71bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wind/Hail Deductible'])[1]/following::select[1]</value>
      <webElementGuid>75556878-4b7f-4d6a-9d7a-f696f9f47a0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[2]</value>
      <webElementGuid>fc32074b-cc9b-400c-a69f-d290c98b90f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Windstorm or Hail Deductible'])[1]/preceding::select[1]</value>
      <webElementGuid>a3ac3e5f-cf59-43e6-8018-d7fac9012f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage Plus PD 0097 (Incl. RCC)'])[1]/preceding::select[1]</value>
      <webElementGuid>e40c245d-8ae0-43a6-a69b-c94e0781b8f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[10]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>448e3723-bff6-4a9d-bbc0-1912d172ee4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'WindHailDeductible' and @name = 'WindHailDeductible' and (text() = '(select)1,0001,5002,0002,5003,0004,0005,0006,0007,50010,00012,50015,000' or . = '(select)1,0001,5002,0002,5003,0004,0005,0006,0007,50010,00012,50015,000')]</value>
      <webElementGuid>148aa69f-625f-47f6-ac2f-84e224f732a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
