<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  1  2  3  4</name>
   <tag></tag>
   <elementGuidId>ca93f429-347f-4cd4-a2d8-86ff28f98508</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='NumberOfFamilies']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NumberOfFamilies</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa2f6072-865f-4716-afbf-fdb997041093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>d5920f8d-d3f3-4679-9d25-7ce41ce5c3dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberOfFamilies</value>
      <webElementGuid>f2e0594b-bebd-4d61-b563-70cf11efd04e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumberOfFamilies</value>
      <webElementGuid>5db6359e-b3ff-4404-afc3-701513b0decd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>aa04090f-2b2e-4c16-b8a2-196d4cbd1102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>fa17c168-77d1-4124-8d67-c429ec740281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  1  2  3  4 </value>
      <webElementGuid>fa4f42e0-6917-4f76-8627-9cd91d40f9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberOfFamilies&quot;)</value>
      <webElementGuid>ce8d2137-8c05-4ca6-a635-a2c45fc8db82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='NumberOfFamilies']</value>
      <webElementGuid>3e164175-e17c-404d-8486-6f140f017a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-dwelling']/div[8]/table/tbody/tr[7]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>a39102ea-5461-4c9f-8fae-1ff187fa5017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Number of Families'])[1]/following::select[1]</value>
      <webElementGuid>85ebe1f2-9acb-4bd1-a706-a1ab7d118e3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does Hastings Mutual insure the primary location?'])[1]/following::select[2]</value>
      <webElementGuid>8b325119-4a3b-4e7b-a6c8-b43d68899455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Form'])[1]/preceding::select[1]</value>
      <webElementGuid>314d3727-77bf-47d9-b59b-999be6849148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Market Value'])[1]/preceding::select[2]</value>
      <webElementGuid>a75f7772-458b-4f91-8bd7-f89556af3ed3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>98fd5bb0-f2eb-4f13-8992-1174907762e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'NumberOfFamilies' and @name = 'NumberOfFamilies' and (text() = ' (select)  1  2  3  4 ' or . = ' (select)  1  2  3  4 ')]</value>
      <webElementGuid>4e0f9a74-dcc7-4482-afaa-438d5897a368</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
