<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  100,000  200,000  300,000 _627a03</name>
   <tag></tag>
   <elementGuidId>1ebcca1c-3565-445a-b512-cb9058667d58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CoverageE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CoverageE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4ec92707-3ece-4072-b3f6-79b59870eea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b93acff7-60fe-41c2-9803-cda6b956ecbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoverageE</value>
      <webElementGuid>90c41c73-ece7-49c0-ac46-603735c590b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoverageE</value>
      <webElementGuid>75b08d46-5512-4660-9c99-7231f910e82e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>f4a7072d-bb22-4f0e-93d0-7da9ecc7024a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>f10d1d07-4d8e-4fcb-8305-3d68d8d5f4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  100,000  200,000  300,000  500,000  1,000,000 </value>
      <webElementGuid>197e342a-fb3f-4772-8423-f5db6a3a38f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoverageE&quot;)</value>
      <webElementGuid>7db73dac-a14f-4e60-b07d-2f79c6ed2f2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CoverageE']</value>
      <webElementGuid>8bf4a0de-6e61-496e-b651-b8b9cedd0c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-coverages']/div/table/tbody/tr[7]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>7b6d377c-5cfd-40e9-8136-6501b667a5cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage E - Personal Liability'])[1]/following::select[1]</value>
      <webElementGuid>1c6d70e3-0951-4700-bf91-24259bde10e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage D - Loss of Use'])[1]/following::select[1]</value>
      <webElementGuid>56991236-782e-400d-b9ab-120743698b70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coverage F - Medical Payments'])[1]/preceding::select[1]</value>
      <webElementGuid>5d499791-ad48-473a-b2c2-02e08311578f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/preceding::select[2]</value>
      <webElementGuid>306786d3-2a41-4aa6-b9bc-f595d1d33566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[7]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>1986f391-1654-42b8-b6cf-34690c93522f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CoverageE' and @name = 'CoverageE' and (text() = ' (select)  100,000  200,000  300,000  500,000  1,000,000 ' or . = ' (select)  100,000  200,000  300,000  500,000  1,000,000 ')]</value>
      <webElementGuid>c8e7f6d9-5b04-4a6e-9ca3-1266a79c21c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
