<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Office Phone_OfficePhone</name>
   <tag></tag>
   <elementGuidId>ae236279-1edc-4049-863a-2db9938a265a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='OfficePhone']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OfficePhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>81c4bee4-db0e-498b-8f82-974849378c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>0179a4bc-361b-4f74-b610-08996f0ecad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OfficePhone</value>
      <webElementGuid>8bce5149-a04e-488c-af39-a181ccf104f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OfficePhone</value>
      <webElementGuid>d7f0b11f-93f8-4e11-9531-10c676957b6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pair-id</name>
      <type>Main</type>
      <value>contact-phone</value>
      <webElementGuid>393ddfbf-d834-415c-84e7-f33acddcdc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>29cb44df-163f-4add-ae50-7a763328af42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter phone number</value>
      <webElementGuid>c629508f-2788-4e9f-8811-1d6328ca1e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter the telephone number without spaces or punctuation.&lt;br />&lt;br />&lt;b>Example: 6168675309&lt;/b></value>
      <webElementGuid>a3969467-809b-42d3-b24b-4d1f9627f282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>87fabaeb-6baa-4cf1-b9a9-e05b80d6916e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\(?\d{3}\)?.*\d{3}.*\d{4}$</value>
      <webElementGuid>c8043b73-c9e8-4fe1-982a-0f86f3c6f82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>384a0e78-0e98-4c08-b5b2-ba839acae5d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bff3213b-d282-4aaa-aa28-aad3e2cfd6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OfficePhone&quot;)</value>
      <webElementGuid>0ede8e23-d318-4d87-9783-97a1e4bca01b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='OfficePhone']</value>
      <webElementGuid>2c4a9cb8-ccf1-4684-9202-7cbca11da367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>1a3954b7-2850-4af5-a13d-92f7b8a2108b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>1f415c7c-1228-40cf-9fcb-ed2927048e60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'OfficePhone' and @name = 'OfficePhone' and @title = 'Enter phone number' and @alt = 'phoneNumber' and @type = 'text']</value>
      <webElementGuid>17da063f-faa0-499d-b5a7-23c772387b91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
