<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description of Operation_Descripti_4b13ce</name>
   <tag></tag>
   <elementGuidId>4a538659-aad4-48a4-9e95-d6a536a976e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DescriptionOfOperation']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DescriptionOfOperation</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>eb48d642-3ac3-49ab-9689-e123e2a4ea92</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>22b3c4e6-efd3-4eaf-9a15-b6d103120155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>a5293ad2-5444-46e3-a979-400cc1249cef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>6ab759d8-7bf1-4389-8788-bbc06208fa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>c7b4a077-c6c7-4e2e-9e33-688c6d29b4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>a368ffac-29d8-4eb2-9213-ed75f58cde12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>768</value>
      <webElementGuid>372e0c39-bab0-41c2-a763-df23a40a5667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-editor</value>
      <webElementGuid>fc691dee-1823-46f7-99a3-a6d5c5fb5ede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>f6782c84-07ee-4795-b76b-2d8a4176a002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DescriptionOfOperation&quot;)</value>
      <webElementGuid>a74a9a72-725e-4694-9f41-1de8766c8368</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DescriptionOfOperation']</value>
      <webElementGuid>4d83bd9f-69b9-4a4d-9525-d45d7e6ce58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[4]/table/tbody/tr[2]/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>d7f8be8e-e4dc-4e92-b8b2-9ef5dcd6cc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>84146be3-fb88-44c4-a296-ab3bde4bede4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DescriptionOfOperation' and @name = 'DescriptionOfOperation']</value>
      <webElementGuid>86c34611-2ed1-4e62-8966-3877d443624a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
