<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close_contractorsEquipment</name>
   <tag></tag>
   <elementGuidId>9b8da75f-aaee-4f57-b0f9-0e3cb57c5d9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contractorsEquipment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contractorsEquipment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02eabc27-afc4-4b85-adfc-11eb79d29caa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>db9970da-bba5-4588-8658-1d60d3f732bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>b73aa1f3-3ab2-478e-ace5-51a3221986a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contractorsEquipment</value>
      <webElementGuid>93684a80-1126-481e-a6f2-50867a254821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contractorsEquipment</value>
      <webElementGuid>723e1da2-e2a0-4f60-9fcc-460d6d85e2fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>129e68a0-1cb6-4c54-943f-bf41c0e413b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>11</value>
      <webElementGuid>81bd3982-b1eb-43b2-97dc-f88bf1f484c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>0153a37e-333a-4c59-b542-2153c92b1fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contractorsEquipment&quot;)</value>
      <webElementGuid>50c64d10-f55b-4c5c-acda-d4513ec786a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contractorsEquipment']</value>
      <webElementGuid>5f41a044-e592-41a0-a34a-bca4b6f417a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div/table/tbody/tr[3]/td/input</value>
      <webElementGuid>a62203be-e307-470a-ad7a-4143146cd9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>5c3f230d-8f0e-444b-91ad-f61e349631af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contractorsEquipment' and @name = 'contractorsEquipment' and @type = 'checkbox']</value>
      <webElementGuid>a9a0dc31-fa32-4306-8830-2d64ce55cf57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
