<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rate_buildersRiskRate</name>
   <tag></tag>
   <elementGuidId>0c547d01-b3fb-4ff5-bdff-bd23130e459b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildersRiskRate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildersRiskRate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>05675a79-3ebf-4e6d-8b11-83fa5783792a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ad76f6a7-5578-45c0-b741-acb756b19f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildersRiskRate</value>
      <webElementGuid>b49fab2a-2e5e-4d94-a7b7-64faddae284f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildersRiskRate</value>
      <webElementGuid>483c9aa6-2ba2-4269-b79b-51340342471f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\d*(\.\d+)?$</value>
      <webElementGuid>06680b78-f5ed-45bc-8c22-986f51fc51d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.001</value>
      <webElementGuid>d72bbf92-f4cd-499c-8bd1-9002b2021ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatRate hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight hmi-ui-text-focus</value>
      <webElementGuid>4fc64639-dbcb-40a9-bde5-72c65ab7d753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>091cdb5e-944b-47e0-b6e1-76fdbb09f5f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bd3a9cd6-2b6b-4fea-9f08-d2db2d6a3b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildersRiskRate&quot;)</value>
      <webElementGuid>c301e9da-20eb-42cb-8b2d-fdf8bd3933da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildersRiskRate']</value>
      <webElementGuid>4d80b98b-c9f8-41f8-af24-7ba2a3d681dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div/table/tbody/tr[2]/td[2]/table/tbody/tr/td[3]/div/table/tbody/tr/td/input</value>
      <webElementGuid>4377c7c5-d790-4aef-aa6b-319f063b741e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/table/tbody/tr/td/input</value>
      <webElementGuid>ab5b9311-7214-4d54-8f3a-780ec05998b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buildersRiskRate' and @name = 'buildersRiskRate' and @type = 'text']</value>
      <webElementGuid>5171259e-bbfd-42fa-a049-8f951f2140c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
