<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Limit_d7ca904a324bacada281fbed9_68bd36</name>
   <tag></tag>
   <elementGuidId>d7340752-c4e5-4124-a593-4ccb66e3f910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contractors-equipment-list']/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d7ca904a324bacada281fbed978063_ContractorsEquipment_Limit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a1c8e1e1-5c84-477f-b944-d7ba3ff0641e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4208ca5d-13cb-4370-a0bd-88aeeb9baaea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d7ca904a324bacada281fbed978063_ContractorsEquipment_Limit</value>
      <webElementGuid>da1f147b-11c7-46ec-b338-35be049cdd3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d7ca904a324bacada281fbed978063_ContractorsEquipment_Limit</value>
      <webElementGuid>537bb400-e3e5-46ef-9fd6-e6d38155cf85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>largelimit</value>
      <webElementGuid>714a4241-73b3-4ccd-b7f7-9f3d2833fed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>ba326746-4b61-4b19-9b5b-5013e729003f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>81a12634-4908-4124-9cec-a6b355e34e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>be307145-d289-458e-86c3-d2606d4e2cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1c70a744-4d6a-493b-b30e-2a1da5c850bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d7ca904a324bacada281fbed978063_ContractorsEquipment_Limit&quot;)</value>
      <webElementGuid>67d66af5-f713-497d-8686-a5fe68c88a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d7ca904a324bacada281fbed978063_ContractorsEquipment_Limit']</value>
      <webElementGuid>c57553ce-0ea4-4edd-b9a5-e942b9c9c4af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contractors-equipment-list']/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>663a4f26-5e05-42dc-b297-98417d476634</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>f36c4498-4625-42a9-bc16-13468ec10ece</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd7ca904a324bacada281fbed978063_ContractorsEquipment_Limit' and @name = 'd7ca904a324bacada281fbed978063_ContractorsEquipment_Limit' and @alt = 'largelimit' and @type = 'text']</value>
      <webElementGuid>6bf8b562-3b07-423e-9bb0-af17510c1d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
