<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CSP Class Code_CspLookup_a96904ad4543_cbba9b</name>
   <tag></tag>
   <elementGuidId>4b37f20b-8d17-4cbd-a068-d3c65db24df7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CspLookup_a96904ad45434eaaa3c4a511800fcbea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e10a5cc8-bc06-4bdd-8495-c089b66a6b68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>fb1b94e9-8fd2-4877-8161-5cd6ad59ab8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CspLookup_a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>13141858-163b-493c-be3c-4417ec8e1735</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CspLookup_a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>6044d9e3-39cd-4775-83b3-5dd483875f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>conditional-display hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>499981bc-955b-42b3-87f0-c81e82204176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>dc190c6f-86dd-4892-9206-f692793d41c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 0844 or Zoo</value>
      <webElementGuid>08c9d6cc-6c8d-4c04-99b4-66bcd92924c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>begin typing...</value>
      <webElementGuid>81f92443-1e01-4e33-a383-36305ddffa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>98</value>
      <webElementGuid>802287f1-aa50-4c85-852b-3e2eb2a80ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d7074cd9-c94c-4f94-a09f-3884a3719b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>75584dac-3eb8-4fa1-9a92-633d2d6255a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CspLookup_a96904ad45434eaaa3c4a511800fcbea&quot;)</value>
      <webElementGuid>d74b97ae-594e-4c97-910f-ea0e5f582e3d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='CspLookup_a96904ad45434eaaa3c4a511800fcbea']</value>
      <webElementGuid>2543f534-207c-4b59-8eee-2af8eff32d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>156cec5a-eec2-4eed-a09a-eb52b470484a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>9d9bc168-3a58-4c20-b7af-4feb63e2d2ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'CspLookup_a96904ad45434eaaa3c4a511800fcbea' and @name = 'CspLookup_a96904ad45434eaaa3c4a511800fcbea' and @placeholder = 'Ex: 0844 or Zoo' and @title = 'begin typing...' and @type = 'text']</value>
      <webElementGuid>bda4569e-5903-4554-a14b-36ab3110abf8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
