<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Accounts Receivable_AccountsReceivabl_eb8eb5</name>
   <tag></tag>
   <elementGuidId>e4c3d6c1-725c-4830-ba2a-9465308ac9bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr[2]/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>498f21d5-134c-40f9-b3ef-4f3c9f7da115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>24021972-d299-481a-a15a-f8d023e68c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>26f4743f-f3b0-4e66-8303-63d9215078f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>902f6d85-75a7-424f-8860-dd4885dd28eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>95f4d9a1-be16-4624-a521-0fabc717e3c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>triggers-conditional-rule hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>a0399d10-dd30-4923-9bd4-ad00d2e73e24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-locationkey</name>
      <type>Main</type>
      <value>a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>169361d3-e558-4852-80e7-425687d5326f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>56</value>
      <webElementGuid>f0ca86b5-1771-4c34-af6e-ebec019dd197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>79847696-8ed6-4f41-a9b8-05df47773758</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea&quot;)</value>
      <webElementGuid>aa325813-c729-404a-90f8-7131a5f18cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea']</value>
      <webElementGuid>c7b00a33-f254-4c90-8b5a-a1e792d224d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>e8a4ed87-5988-426d-92d6-8f0c4aa80c9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td/input</value>
      <webElementGuid>b998cf2a-b8bc-4598-930d-1b68d3e3f42c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea' and @name = 'AccountsReceivable_a96904ad45434eaaa3c4a511800fcbea' and @type = 'checkbox']</value>
      <webElementGuid>d263198b-c375-4218-bfe5-b8bc56702771</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
