<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy Level Coverages_buildersRisk</name>
   <tag></tag>
   <elementGuidId>a9796cdb-913e-4523-8f31-8ff1261c4c73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buildersRisk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='buildersRisk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f226225b-c4e8-43a4-9f83-23c618d8349d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>db84a4fc-1ecb-4ab9-873a-ea816b640dca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>True</value>
      <webElementGuid>2fcf4c3f-9761-42d5-9a12-9c33ae012ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buildersRisk</value>
      <webElementGuid>3c34e0e4-3510-4bed-bb2a-24719356bc89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>buildersRisk</value>
      <webElementGuid>dfeb1d33-764a-4eb3-a439-f3f5a9cfb2ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-checkbox hmi-ui-editor</value>
      <webElementGuid>d9fc04eb-b4be-4820-83b9-20cd2030efc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>edc94733-8331-47ea-a76e-276f50f3dbde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>eab0c16b-ffe7-4f68-9309-764e054f16d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buildersRisk&quot;)</value>
      <webElementGuid>cd0eed6b-de2e-4e95-bb12-14e1abd4cee0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='buildersRisk']</value>
      <webElementGuid>77604bbb-8a28-472e-9f7b-eed8b5e5c47c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div/table/tbody/tr/td/input</value>
      <webElementGuid>c994e1d8-e3f8-4d70-932f-27d0dc13c842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>575a6f56-d9df-41ea-a29c-18da502b4187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'buildersRisk' and @name = 'buildersRisk' and @type = 'checkbox']</value>
      <webElementGuid>955485a4-70ef-4b69-80e8-3b1a66efd7db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
