<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Rate_d7ca904a324bacada281fbed978063_C_c9af53</name>
   <tag></tag>
   <elementGuidId>85da55d2-daca-4677-804d-01989ac5a82f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contractors-equipment-list']/table/tbody/tr/td[5]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#d7ca904a324bacada281fbed978063_ContractorsEquipment_Rate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8ae84d2-d0c7-47e2-9233-5b5ee67c6cca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ce102c19-ea02-409d-997c-c298e67ac68b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>d7ca904a324bacada281fbed978063_ContractorsEquipment_Rate</value>
      <webElementGuid>d5c155a3-1e7e-4ff0-9ba9-a93544e7105a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>d7ca904a324bacada281fbed978063_ContractorsEquipment_Rate</value>
      <webElementGuid>0900704a-eb98-4165-8c23-ae925c368959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\d*(\.\d+)?$</value>
      <webElementGuid>af4a75c1-6bfb-439a-ab2f-1bc3379b2c85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0.001</value>
      <webElementGuid>12aa6ba7-d098-4c57-b8e3-0d6d5825bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>formatRate hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-highlight</value>
      <webElementGuid>c52e68e4-1e37-4cac-a886-0feccb80dee3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>6f61423c-7a9a-4e66-a4d3-aa5b39c38bf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>16</value>
      <webElementGuid>4d7a43b9-61da-43af-9f86-f111651a2a31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3dd92855-5ec1-4bc9-a491-454ec24b1a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;d7ca904a324bacada281fbed978063_ContractorsEquipment_Rate&quot;)</value>
      <webElementGuid>7be9790c-908b-4ec7-9f24-6a27d1e969bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='d7ca904a324bacada281fbed978063_ContractorsEquipment_Rate']</value>
      <webElementGuid>47acd50d-cee3-4f2d-84e0-1cdf2f19940d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contractors-equipment-list']/table/tbody/tr/td[5]/table/tbody/tr/td/input</value>
      <webElementGuid>4a177c07-f820-4725-8b8a-3d338359c0fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/table/tbody/tr/td/input</value>
      <webElementGuid>cc8e4f84-7555-4d3e-8da6-2620fe8a10d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'd7ca904a324bacada281fbed978063_ContractorsEquipment_Rate' and @name = 'd7ca904a324bacada281fbed978063_ContractorsEquipment_Rate' and @type = 'text']</value>
      <webElementGuid>dcc3000a-3e93-4144-9208-d5f457b00b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
