<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Choose a type --  Frame  Joisted _44e5e4</name>
   <tag></tag>
   <elementGuidId>ad44d123-3bc5-4d36-8002-3eb9c0e2910f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ConstructionType_a96904ad45434eaaa3c4a511800fcbea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>181b40d2-93d6-40f0-99a4-881ca245fde3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4189d300-1459-4279-b81b-db580731b0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ConstructionType_a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>c81ee7aa-df52-478b-8c68-4b0f3ff00abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ConstructionType_a96904ad45434eaaa3c4a511800fcbea</value>
      <webElementGuid>8b4d2aa1-a413-4ffd-9474-7b28d0362dcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>conditional-display hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>5602a9fd-cac5-423b-8118-635ff90d02c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>99</value>
      <webElementGuid>647ea436-b946-4d6a-a584-a06f86cf7e15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Choose a type --  Frame  Joisted Masonry  Non-combustible  Masonry Non-combustible  Modified Fire Resistive  Fire Resistive </value>
      <webElementGuid>f7006a3f-4db1-44d9-9819-cb37f8c3be27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ConstructionType_a96904ad45434eaaa3c4a511800fcbea&quot;)</value>
      <webElementGuid>47c3bb39-c88c-44bc-906b-356e872c1bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ConstructionType_a96904ad45434eaaa3c4a511800fcbea']</value>
      <webElementGuid>c6316dfd-20cb-4905-88f6-7d26a650759b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/div[2]/div[2]/div/div/form/div[3]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>5b473531-588a-4e0d-9f2a-59663578cdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Construction Type'])[1]/following::select[1]</value>
      <webElementGuid>acfdf47e-1248-413e-84b7-256006c3f1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='browse complete list of CSP Class codes'])[1]/following::select[1]</value>
      <webElementGuid>4876f66d-9a6d-4ff0-b3af-12a6f0e1a7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rate Plan'])[1]/preceding::select[1]</value>
      <webElementGuid>f0a99ee7-16dc-4ce9-bfbe-98b00976dbc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Group I Specific Rate'])[1]/preceding::select[2]</value>
      <webElementGuid>99c5e99f-36eb-4fbd-9852-c59f944a1975</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>6c30e7d0-3821-409b-8664-28eeb5c37e57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ConstructionType_a96904ad45434eaaa3c4a511800fcbea' and @name = 'ConstructionType_a96904ad45434eaaa3c4a511800fcbea' and (text() = ' -- Choose a type --  Frame  Joisted Masonry  Non-combustible  Masonry Non-combustible  Modified Fire Resistive  Fire Resistive ' or . = ' -- Choose a type --  Frame  Joisted Masonry  Non-combustible  Masonry Non-combustible  Modified Fire Resistive  Fire Resistive ')]</value>
      <webElementGuid>d1655a9d-a9ad-4189-b7e3-9e2dde92d676</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
