<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Previous Carrier Name_NameOfThePrevio_d2a9bb</name>
   <tag></tag>
   <elementGuidId>f6b1392c-2a4c-439a-ab11-de296d158ba1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NameOfThePreviousCarrier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NameOfThePreviousCarrier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9bd8d989-ea71-41df-8425-16462cce9431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>981615d4-c6e6-40a5-b115-87455550b0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameOfThePreviousCarrier</value>
      <webElementGuid>a044a485-3d14-4e9c-a539-6ef9c46fccba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NameOfThePreviousCarrier</value>
      <webElementGuid>237f5ad2-3808-469c-bb5d-0c6a9d3a3e94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>3b5ca453-3885-47ca-9f10-ad7236b11996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>51b0ec9f-25ee-49c0-8078-533693fe980d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>e7933f06-7895-4363-ad92-b6e7c9466012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>43c3e820-8320-4e82-aa0b-1e754b4fd1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameOfThePreviousCarrier&quot;)</value>
      <webElementGuid>84f338b7-ef19-40fd-a18e-f1276f34a6eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameOfThePreviousCarrier']</value>
      <webElementGuid>fce261bb-88cd-4d4a-ae17-2058684f6c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[3]/form/div/table/tbody/tr/td/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>11cccab8-3ed6-4958-9eea-a2c70039c8d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>e033d983-66f5-4560-a509-4d1c68ff450d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NameOfThePreviousCarrier' and @name = 'NameOfThePreviousCarrier' and @type = 'text']</value>
      <webElementGuid>08082097-1420-4839-a223-bbdd7f6ecf89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
