<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search by Class Code or Description_C_15c1d5</name>
   <tag></tag>
   <elementGuidId>fec46555-c5da-4a52-bc88-6dc8cb34939e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ClassCodeSearch</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ClassCodeSearch']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbafc825-7f89-4b2d-bf43-047227591535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>cf2164dd-334a-4bf7-9ef2-c036eb6ed497</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClassCodeSearch</value>
      <webElementGuid>a1d6af0d-56e2-4991-becc-58f662f4bcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClassCodeSearch</value>
      <webElementGuid>0dc96d4c-7a81-41d8-b3f7-c6f578c90b8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>bc3720cb-59a1-4898-89e0-27874ab87f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 0531 or Beverage</value>
      <webElementGuid>2da7aa5b-845c-40ab-ab0d-8440fc501f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>type 3 letters or more to search...</value>
      <webElementGuid>ba89474d-3fe9-4df2-a34f-f454a8fd148e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>15056325-1786-4d2a-b80a-b4e02ff1d958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>a581fe58-adea-4749-a1ca-77bc4692aa28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>72de87a3-9c5a-4a37-bf9e-1b65dd160b23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>4ef1df91-e918-4528-a5b2-381a41e49105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClassCodeSearch&quot;)</value>
      <webElementGuid>7c1e44f3-8f65-444c-bb29-056973ede8c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ClassCodeSearch']</value>
      <webElementGuid>15a2ae18-6210-4234-915e-712d27289656</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='classificationSection']/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>748f22b9-d082-4f99-b0a4-0f78883c2b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>2d779d46-38fe-4001-bff0-d0d7b9412770</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ClassCodeSearch' and @name = 'ClassCodeSearch' and @placeholder = 'Ex: 0531 or Beverage' and @title = 'type 3 letters or more to search...' and @type = 'text']</value>
      <webElementGuid>e4bcd531-1060-44ff-a83d-d6a78ae9f57f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
