<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Contact Name_ContactName</name>
   <tag></tag>
   <elementGuidId>382085a8-bcab-4ecb-b6b0-c5fe4a35ee10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContactName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2dc89c5f-b902-48b6-a67c-6429f4137aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Submission</value>
      <webElementGuid>05215752-2e33-46b8-9523-9bc2c48b8ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactName</value>
      <webElementGuid>42a08719-2d08-49de-834a-5e600ceca4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactName</value>
      <webElementGuid>9690cbe6-1ad8-4c1c-959b-2f9d83424a86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>ae0d581a-93d0-45f6-b623-2286607ebaf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vcardname</name>
      <type>Main</type>
      <value>vCard.DisplayName</value>
      <webElementGuid>f91e4259-2da8-41a2-ad12-3cb5a745fe32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>fff2fc0f-2f92-4458-b2a1-cc2ef56115e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>af762424-a68f-4c26-b8c2-fd977eb34505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49412b04-e699-48a8-9558-a26ddb25730b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactName&quot;)</value>
      <webElementGuid>e258923f-5fc8-4dd1-978a-ede85923bf6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContactName']</value>
      <webElementGuid>63ab049c-b63a-43a4-8d23-85272cdd26ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div/form/div[2]/table/tbody/tr/td/table/tbody/tr/td/input</value>
      <webElementGuid>8d6616f2-7a69-47a1-98cb-9ccb97e44ea7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>9d4ac360-206f-4228-8a0c-ac3cb9bb3d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContactName' and @name = 'ContactName' and @type = 'text']</value>
      <webElementGuid>4be372e6-e18d-47bd-83a3-9018294109b0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
