<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Agent Comments to Underwriting_Comment</name>
   <tag></tag>
   <elementGuidId>310d32b7-0755-4366-beac-61f03367daee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Comment</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='Comment']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>b2ae5528-59dd-4907-be4f-40fe34e45c47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Submission</value>
      <webElementGuid>87de4ed0-f239-44eb-bcb2-2d55254323a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>64770d13-ac67-4bb9-9c33-7d8caedb4096</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Comment</value>
      <webElementGuid>90350134-d06c-4960-9483-ba5061a6fea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>615585c0-f81c-4805-a8a2-6e9eddab8176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>953dbfb9-d8ea-4240-bfab-ab73202b4ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>960aa309-a952-49e3-93da-29b80bc42904</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-editor</value>
      <webElementGuid>2f67c90e-1ea4-4f15-90b0-cc932f00eb85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>(optional)</value>
      <webElementGuid>5d96520d-bb7b-4bb6-b2f3-dc3990b55ec7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>fe781a6a-a671-4601-b6a8-25d44a8a3727</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Comment&quot;)</value>
      <webElementGuid>ff73b356-f6d2-4fa1-9c29-32ac8dc6c7a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='Comment']</value>
      <webElementGuid>9cbe125e-e127-40de-bb37-b1d72e4cd3b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div/form/div[2]/table[2]/tbody/tr/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>8fceb111-25b8-4aa6-8697-482cacbcd005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>176a7b6a-3ab1-490f-945a-6725304986c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'Comment' and @name = 'Comment' and @placeholder = '(optional)']</value>
      <webElementGuid>073774ba-7293-4222-878f-76ed95657fcb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
