<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QUOTE</name>
   <tag></tag>
   <elementGuidId>7c0dc67c-e39d-458c-850f-f85cda4a20ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#QUOTE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='QUOTE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>98cfd474-65b3-4dfe-a8f6-4fd7a3de4ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-links left</value>
      <webElementGuid>279fceec-36bc-49b4-aa37-86c5255d1df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>QUOTE</value>
      <webElementGuid>5b2d79f5-5e0b-4d42-a4a0-3a2b416bc83b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/agent-dashboard/openquotes</value>
      <webElementGuid>48b86ba0-b8bb-4adc-8fec-73e5e02a6e0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QUOTE</value>
      <webElementGuid>a80460fe-dc0e-4a94-b978-f86c2221309b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;QUOTE&quot;)</value>
      <webElementGuid>5f0ac8e4-20f0-45d2-891e-4977ef13fcfd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='QUOTE']</value>
      <webElementGuid>686d0f1c-f9e4-4cac-80ff-13962ac5b4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Contentplaceholder1_T99701C38002_Col00']/div[2]/div/div/a[2]</value>
      <webElementGuid>3d4c6638-fb62-4b78-971e-35977b9d6b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'QUOTE')]</value>
      <webElementGuid>3cf3fabe-d4da-4d47-b2a6-ff4597f7c890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='HOME'])[1]/following::a[1]</value>
      <webElementGuid>9ef6ba86-45ed-426d-a71d-ea4a040cce5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Logout'])[1]/following::a[2]</value>
      <webElementGuid>5d486e84-cec1-4332-acd8-5be1d997773b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ACCOUNTS'])[1]/preceding::a[1]</value>
      <webElementGuid>ba4356e3-e88a-4258-8404-7c2021f5a244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='POLICIES'])[1]/preceding::a[2]</value>
      <webElementGuid>42335acd-c579-4f6b-9cb8-c6a5058fdede</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='QUOTE']/parent::*</value>
      <webElementGuid>f17fa9cf-85db-4365-9019-439f02effcc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/agent-dashboard/openquotes')]</value>
      <webElementGuid>fc2a14bc-689d-4e0b-81c2-4a75b420a779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>765348d5-3fee-4b29-aede-0615c630800c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'QUOTE' and @href = '/agent-dashboard/openquotes' and (text() = 'QUOTE' or . = 'QUOTE')]</value>
      <webElementGuid>8ddf9920-0916-412d-b5fe-f2dae00c45a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
