<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_-- Choose how you would like to subm_913466</name>
   <tag></tag>
   <elementGuidId>41df0b09-32c9-48f3-90fa-edf8dd2b536e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SubmissionType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SubmissionType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>13310b59-6e79-486f-ab48-3e7922d38ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Continue</value>
      <webElementGuid>999477df-06d7-48f3-8d35-02db6f88daf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SubmissionType</value>
      <webElementGuid>09384ee4-d379-47a9-8252-23f3a3060ab4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SubmissionType</value>
      <webElementGuid>e362f046-3a24-4f00-8de6-31b16f5ca849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>37468d4c-ac94-4c67-8e72-cff92133b33d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>6f45e991-1ee8-4c0d-8e5d-126f3e48a4a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> -- Choose how you would like to submit this quote --  Formal Quote  New Business </value>
      <webElementGuid>e7af0676-3348-4bab-ab7a-7c9fdef13a4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SubmissionType&quot;)</value>
      <webElementGuid>d8081eb3-df8e-49a7-ab7c-efb5641d680b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SubmissionType']</value>
      <webElementGuid>83b91f85-de66-477a-bdd1-43e9b26cb066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/form/div/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>36a35485-7930-412d-ae7a-1e7f8154ce30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit to Hastings Mutual as'])[1]/following::select[1]</value>
      <webElementGuid>608741a1-d7e6-4096-a17d-c7c11642f1f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submission'])[2]/following::select[1]</value>
      <webElementGuid>447ac92a-4338-419b-a95c-861b28d727e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Quote'])[1]/preceding::select[1]</value>
      <webElementGuid>4778718e-8ab6-4ff5-9300-d0bef45a0eb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Continue submission process'])[1]/preceding::select[1]</value>
      <webElementGuid>2d989607-47b3-4642-9aee-dd06635d1824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d96237ef-d345-425d-803e-572bd3c4f103</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SubmissionType' and @name = 'SubmissionType' and (text() = ' -- Choose how you would like to submit this quote --  Formal Quote  New Business ' or . = ' -- Choose how you would like to submit this quote --  Formal Quote  New Business ')]</value>
      <webElementGuid>c2a6137e-c55d-49b8-bdaf-cddf3ff3ebdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
