<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Click on a picture to select a program__42143d</name>
   <tag></tag>
   <elementGuidId>5622c70d-06aa-4074-8eed-3491391f5457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.farm-program.hmi-layout-centered.ui-state-hover</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='hmi-layout-mainContent']/div/div[3]/table/tbody/tr/td[3]/div/form/div[7]/table/tbody/tr[2]/td/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ccd1e8ea-aa84-4942-9f79-7c37cfe735ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>farm-program hmi-layout-centered ui-state-hover</value>
      <webElementGuid>6d7fb6c9-3477-4b93-84f6-88f715f75a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static.hmic.us/images/Farmowners.jpg?2</value>
      <webElementGuid>d08fd711-4015-4e76-9f96-0aa037289a21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Farmowners</value>
      <webElementGuid>69cfb0b7-2a30-4e4c-915b-7afd7dfe1b46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Farmowners Program</value>
      <webElementGuid>ff7a16e3-c824-4a0f-b680-f729b27585ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmi-layout-mainContent&quot;)/div[1]/div[3]/table[1]/tbody[1]/tr[1]/td[3]/div[@class=&quot;hmi-layout-wrap ui-widget-content&quot;]/form[1]/div[@class=&quot;hmi-layout-wrap&quot;]/table[@class=&quot;hmi-table-centered&quot;]/tbody[1]/tr[2]/td[1]/img[@class=&quot;farm-program hmi-layout-centered ui-state-hover&quot;]</value>
      <webElementGuid>f8d7c45b-cd52-42e8-a81b-38261ecd4c0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/table/tbody/tr/td[3]/div/form/div[7]/table/tbody/tr[2]/td/img</value>
      <webElementGuid>4148f87b-96d6-4ae8-b723-b4759fcfc73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Farmowners']</value>
      <webElementGuid>73d18458-493c-4adf-9d42-72d85b8e87d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/img</value>
      <webElementGuid>6e51b6b8-f27d-4eb6-b4a7-e647b92d84f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://static.hmic.us/images/Farmowners.jpg?2' and @alt = 'Farmowners' and @title = 'Farmowners Program']</value>
      <webElementGuid>d3c7a58d-a39a-4080-b961-8afbb6d23442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
