<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>f7894b8a-3386-4c50-81b8-71f512913210</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RegisteredWithCentralRegistry']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RegisteredWithCentralRegistry</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b5ac43a5-1d1c-49c9-9443-c8d6a7cd03ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f78cf806-5069-4d87-9013-604625e4b27a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RegisteredWithCentralRegistry</value>
      <webElementGuid>6003683b-0955-4613-ac76-f3bcb7dc8d84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RegisteredWithCentralRegistry</value>
      <webElementGuid>be5a1fb4-fbd9-45fd-b221-4fb84afbe834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>248c31f8-380b-42f7-87e8-9a921b5c0230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>8e7a7b78-db62-4ad6-93bb-a88dc12ac8e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>3139f6a3-9198-4482-a990-f011619bceb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RegisteredWithCentralRegistry&quot;)</value>
      <webElementGuid>b43ee637-d625-4ad8-807f-c0c891a2dc33</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RegisteredWithCentralRegistry']</value>
      <webElementGuid>166f9252-8d9d-4620-9a6e-81fced6451ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-Jewelry-Add']/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>3b6a2c93-f53c-4bc4-b72c-5803ecbae05b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[1]</value>
      <webElementGuid>3170ab77-6af3-4e35-89b8-ea77ee810d9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deductible'])[1]/following::select[2]</value>
      <webElementGuid>b5699c0f-8da3-4ae8-b1f9-644c7da6cf00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Appraisal ($4,000 or more)'])[1]/preceding::select[1]</value>
      <webElementGuid>cd65f7de-b279-4bc0-894c-64d9a813d9f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[2]</value>
      <webElementGuid>adeffc37-fe3e-4e61-a422-e5a431551fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>85959e52-3911-4d20-8e17-1e3ef553a53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RegisteredWithCentralRegistry' and @name = 'RegisteredWithCentralRegistry' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>01625daf-9597-4f1d-b0d4-70b9a97a0269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
