<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No_1</name>
   <tag></tag>
   <elementGuidId>0f1cff74-336e-4236-a9f2-7472aab39b7a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Appraisal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Appraisal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>68af3d6d-8437-4381-9c3b-b72deff1a576</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>95ec5196-39c3-47b9-bc42-c20b0f22e9ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Appraisal</value>
      <webElementGuid>8277955c-57c9-4f9e-8ac9-3e055ef3eaae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Appraisal</value>
      <webElementGuid>bd0a0bb2-c972-4a61-9c23-23b7fe21d277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>55a071b8-3e92-46d4-ab82-e59560c00fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>467fc552-dc8f-466c-b6ee-cf4eac2e6c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a0542475-8a26-4781-ade5-f1d1209a2cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>1e556b9f-31ae-497a-8b16-3b39129a60c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Appraisal&quot;)</value>
      <webElementGuid>16d0bb27-09b4-4017-8af5-04e94402724b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Appraisal']</value>
      <webElementGuid>3f1622ec-2588-4c54-a8eb-de22e784e315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-Jewelry-Add']/div/table/tbody/tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>60ab8357-263f-42c0-a70c-babb38ef71a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Current Appraisal ($4,000 or more)'])[1]/following::select[1]</value>
      <webElementGuid>68b66d8a-8880-42e3-9802-ae2ccce78dbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/following::select[2]</value>
      <webElementGuid>d63dd06e-f115-400a-a354-01ca54eb8de0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>42fc9f4b-c607-407a-952c-1d82115c8c7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>325753d4-e1ec-45f1-ab1d-7b76a985ff40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>1b8c6e37-8baf-4a7b-9324-1d5283dbc77e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Appraisal' and @name = 'Appraisal' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>bf0fdb45-3b3d-420b-937a-0c0feb628af7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
