<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_EditPersonalComputer</name>
   <tag></tag>
   <elementGuidId>ddd4aaff-9ebb-4f53-b246-44312b21cb8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.ui-button.ui-widget.ui-state-default.ui-corner-all.edit-scheduled-item.ui-button-text-icon-primary.ui-state-hover > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[contains(@href,'EditPersonalComputer')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7733c6c-1699-4cc9-8928-f7f5efbf2a54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>4efd8de4-7c15-42ba-aac3-453fd3cc6b99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>48426b89-3667-44f9-a38d-c4f8c0f02105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-jewelry-list&quot;)/table[@class=&quot;hmi-table&quot;]/tbody[1]/tr[2]/td[6]/button[@class=&quot;ui-button ui-widget ui-state-default ui-corner-all edit-scheduled-item ui-button-text-icon-primary ui-state-hover&quot;]/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>ca92139e-99af-4ce4-a679-2aecbec70a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-jewelry-list']/table/tbody/tr[2]/td[6]/button/span[2]</value>
      <webElementGuid>100b3a62-a4d1-4db0-9088-d5866840e682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::span[2]</value>
      <webElementGuid>225924b2-225d-4c6c-9b2d-b9ade051ee35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[1]/following::span[2]</value>
      <webElementGuid>3befc351-48ef-4a40-b5a5-331803eee278</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[2]</value>
      <webElementGuid>553fc413-5899-4d82-9903-b4b0e0d9835a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule an Item'])[13]/preceding::span[4]</value>
      <webElementGuid>9e141909-9ffd-423a-b553-6935426df54c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>50c910e3-94b2-439c-a9b8-5dc2cb924d6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button/span[2]</value>
      <webElementGuid>24584983-01cc-4461-8678-dc753a4fa951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>6dca5b23-3654-40c7-b6d7-4f99ce397f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
