<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Edit</name>
   <tag></tag>
   <elementGuidId>cfb3d13e-e7ae-458e-8cf0-7e28cf4b0440</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='wrapper-jewelry-list']/table/tbody/tr[2]/td[6]/button/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ui-button.ui-widget.ui-state-default.ui-corner-all.edit-scheduled-item.ui-button-text-icon-primary.ui-state-hover > span.ui-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c4e915e3-86d4-4496-a2ef-e21b3b5b78ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>455fa332-79a8-4771-a9ed-deb0877b3d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit</value>
      <webElementGuid>bf6f8ca2-c95d-4340-8d32-c17ee107bc94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrapper-jewelry-list&quot;)/table[@class=&quot;hmi-table&quot;]/tbody[1]/tr[2]/td[6]/button[@class=&quot;ui-button ui-widget ui-state-default ui-corner-all edit-scheduled-item ui-button-text-icon-primary ui-state-hover&quot;]/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>6201606b-c73f-40c2-89d5-62d9b5cf58f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrapper-jewelry-list']/table/tbody/tr[2]/td[6]/button/span[2]</value>
      <webElementGuid>3cc86526-ea63-4445-b985-3472fb32eb13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Yes'])[1]/following::span[2]</value>
      <webElementGuid>231f2ef6-7675-4cad-8198-10971f5aab00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$100'])[1]/following::span[2]</value>
      <webElementGuid>c86d2e97-0567-4ddd-9fcd-c22a5ae510ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::span[2]</value>
      <webElementGuid>a0bf8b1f-4c7e-48bf-a90f-dae803372f89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule an Item'])[13]/preceding::span[4]</value>
      <webElementGuid>d2882b1b-89e9-42a4-b58e-de7f1c9893ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit']/parent::*</value>
      <webElementGuid>e1cfd9d9-3900-4800-8c09-3212319e93f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/button/span[2]</value>
      <webElementGuid>5b9e56f3-a729-4f5d-8310-2113bbe39619</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Edit' or . = 'Edit')]</value>
      <webElementGuid>394ba66d-6dae-485b-801d-9d94ed4c969e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
