<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Street Name_MailingAddressStreetName</name>
   <tag></tag>
   <elementGuidId>3fa00933-a5ef-4e78-922f-a08e53872bca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MailingAddressStreetName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#MailingAddressStreetName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>338c3944-040a-4fc2-be13-88193072f330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4b771a87-7eef-42f7-9e84-85e89a0f4555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MailingAddressStreetName</value>
      <webElementGuid>4cbee19b-0613-4ceb-8c63-a21c155d0c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MailingAddressStreetName</value>
      <webElementGuid>62b0c497-60d9-4ccc-8a75-30323ab2cee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>eb9cd5e8-7b87-4700-b64c-e9138d3d2ef5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z '/-]+$</value>
      <webElementGuid>0b8d197c-998b-4745-b2cc-c42ae6d1eeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>8cabee69-36e5-4740-88d8-14a6f9dbef38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6ede2362-43cd-4ac7-9ef3-5fff9a9753ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6d89f307-f04e-4a03-acb6-1f9804452c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MailingAddressStreetName&quot;)</value>
      <webElementGuid>5eb81836-66d2-4461-8af2-273eefa1fddb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MailingAddressStreetName']</value>
      <webElementGuid>6c191e3a-774c-4073-a572-9cb629287c97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table[2]/tbody/tr/td[2]/div/form/div[4]/table/tbody/tr[3]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>865bc59c-bc48-4bbc-99b2-342d579eb61d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>ca6a86eb-9710-48f3-b9af-3fea7ab647b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MailingAddressStreetName' and @name = 'MailingAddressStreetName' and @type = 'text']</value>
      <webElementGuid>91258a15-af29-42fc-8bd8-674d12e5265e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
