<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>f3ea2f54-ccda-4173-baa3-47fa0759060f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Dwelling1000FeetFromHydrant']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Dwelling1000FeetFromHydrant</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cd264c51-45bb-4d2c-b1ac-f1db64b4f4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>68a15200-4cef-4c48-a505-eb5317f067a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Dwelling1000FeetFromHydrant</value>
      <webElementGuid>953af212-5167-4b45-bb2d-16fa9355d492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Dwelling1000FeetFromHydrant</value>
      <webElementGuid>fb3c7d6c-553a-4d97-a3ea-ae3502080282</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor hmi-ui-text-highlight</value>
      <webElementGuid>e24540f8-7395-4cd8-adce-c88d1f637a5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e128b49a-00c7-4475-b579-651cadcd3e39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>9206e92c-da99-426d-8a19-0c09cbea463d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Dwelling1000FeetFromHydrant&quot;)</value>
      <webElementGuid>26dcaf3e-1704-494b-a5b1-99c6cf596e57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Dwelling1000FeetFromHydrant']</value>
      <webElementGuid>d9dcbacb-c286-4029-9805-4e6608c7d3e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table[2]/tbody/tr/td[2]/div/form/div[4]/div[4]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>a21fbabb-c8b5-4e37-b37d-214832b59bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is dwelling within 1000 feet of a fire hydrant?'])[1]/following::select[1]</value>
      <webElementGuid>2ce79477-5113-41ea-8d70-e1822ce7daa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zip Code'])[2]/following::select[1]</value>
      <webElementGuid>c97a09e1-6621-4cc0-b2d7-13048dc49b47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous Address'])[1]/preceding::select[1]</value>
      <webElementGuid>40be9b6e-0a03-4152-8a65-0d7460993068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is the mailing address new for the applicant within the last 12 months?'])[1]/preceding::select[1]</value>
      <webElementGuid>84d43592-f712-4e4f-84eb-e5b5f019940d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[4]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>48bb0bc6-2d6d-4756-b15d-de43ed9a9b62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Dwelling1000FeetFromHydrant' and @name = 'Dwelling1000FeetFromHydrant' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>cdc59cae-7738-4ebf-885a-fdd2b1c4481c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
