<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Divorced  Single  Married _b78225</name>
   <tag></tag>
   <elementGuidId>88ec297f-1b97-464d-82c8-fe28744c6859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'MaritalStatus')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3649dcc1-e54d-43e2-ba88-a82d84c8e772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5dcce6f0-7386-4a97-b2e1-65f30d5ede03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus</value>
      <webElementGuid>7f9961fe-af0d-4bfd-bcd2-075abfb4a96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus</value>
      <webElementGuid>0d39e47e-127f-4ec6-8ec8-2877b01b533d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>3c1004dc-d4a4-4db5-b551-0454a72a76ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>80c13f42-f1e5-4fbb-9c3c-d2fe51cba9d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Divorced  Single  Married  Widowed </value>
      <webElementGuid>eaf655c0-abea-4761-b828-5cda5aea39ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus&quot;)</value>
      <webElementGuid>bac63d7c-4432-44b2-bb92-0c6eee274726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus']</value>
      <webElementGuid>52e070d0-f1af-46f4-977b-1cb3bb50f7df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='insured-list']/table/tbody/tr[3]/td[3]/table/tbody/tr/td/select</value>
      <webElementGuid>5b6341b0-7cdc-42df-afe4-ece2ad311267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Marital Status'])[1]/following::select[1]</value>
      <webElementGuid>0e017e45-18f6-4ee6-bfc2-50d274eb63b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Social Security Number'])[1]/following::select[1]</value>
      <webElementGuid>5f84b23d-c17f-4032-9fcc-5e21b5e2843f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Occupation / Employer', &quot;'&quot;, 's Name:')])[1]/preceding::select[1]</value>
      <webElementGuid>5a9a8459-8851-4d21-9d0a-92b00c8e1eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nature of Business if Self-Employed'])[1]/preceding::select[1]</value>
      <webElementGuid>046c9459-c481-4753-93cb-87a2a5791905</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr/td/select</value>
      <webElementGuid>fef44917-4be1-4951-a5a7-b39d57b29d32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus' and @name = 'ccec95c43c9247d7b9c5d78ce7bc96fa_MaritalStatus' and (text() = ' (Select)  Divorced  Single  Married  Widowed ' or . = ' (Select)  Divorced  Single  Married  Widowed ')]</value>
      <webElementGuid>2fb2e406-5c92-47ad-b646-a943fe7ee13d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
