<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_NameOnPolicy</name>
   <tag></tag>
   <elementGuidId>3e628d9e-5a01-4009-8cf7-c8660b30024a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NameOnPolicy</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8303a9ae-d172-491f-9a43-b2112765d846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>c311abae-fd62-4261-9771-305d0007de2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NameOnPolicy</value>
      <webElementGuid>973e6c59-25b4-4f98-9848-1970c653e637</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NameOnPolicy</value>
      <webElementGuid>d90e6a25-e8a6-4882-b29e-f349347310b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>This name will appear in search results</value>
      <webElementGuid>6634b8d8-f940-46c4-aa35-374c3ded19cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>3f8a5c8a-fa5c-4fd5-a313-056eb56ad680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>da124b59-e05e-49f3-b71f-fe4fd81ac25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[A-Za-z0-9\-'&amp;#,\.!\*\+ /]+$</value>
      <webElementGuid>1ef88c74-4378-45fb-b5b2-641c4499effd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>62da2564-f2f4-4090-95c1-a37a453eb17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3928d127-c272-4ee1-b46a-323c425680ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NameOnPolicy&quot;)</value>
      <webElementGuid>feb19e18-5a0d-4ece-a706-7492b10446de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NameOnPolicy']</value>
      <webElementGuid>41db4538-3ae0-465e-a6e6-4603e9642725</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>8479fa4b-411b-4d5b-a69b-c0ff538ae3f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>b4365784-3cb6-4bb2-962e-ea60214bd936</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NameOnPolicy' and @name = 'NameOnPolicy' and @title = 'This name will appear in search results' and @type = 'text']</value>
      <webElementGuid>70d9ebd4-32e5-4f61-adba-497994367e60</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
