<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_AddressLine1</name>
   <tag></tag>
   <elementGuidId>e596e892-b0db-441d-894f-59b3f1775053</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AddressLine1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AddressLine1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f59364e1-dc7a-4471-8429-1181c3063ad3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>4504a151-8064-44ec-94a3-b7dbb0ee105f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AddressLine1</value>
      <webElementGuid>210abd1b-c510-4a20-9c18-4fd3db886196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>AddressLine1</value>
      <webElementGuid>5aaf9b7b-76d6-4b8f-b46b-ca42368f9e74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>45</value>
      <webElementGuid>d6d8a11c-6292-4a9f-bfc5-7108472e118e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>5bc07304-c82a-4138-b40b-7e3b920f2dab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>76d51dda-5ed1-41d5-bf00-ab91666762cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5164795f-2a46-43aa-b475-fc397f01685b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AddressLine1&quot;)</value>
      <webElementGuid>393c5e9a-c3d5-47cf-8e91-8d811d2af7ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AddressLine1']</value>
      <webElementGuid>d82f747e-33ae-41bc-a89c-f6cbc1085a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>3f28ded0-50d2-4ba3-9994-8094565f095b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table[2]/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>fa976292-f3d1-4db3-a056-e148c89d3305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AddressLine1' and @name = 'AddressLine1' and @type = 'text']</value>
      <webElementGuid>8259319c-031a-4e2e-b3f6-3d7396fa9b3b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
