<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Zip Code_Zip</name>
   <tag></tag>
   <elementGuidId>cb1f8b83-e6d6-4c98-becc-f2a1a189127f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Zip</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Zip']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d2363053-78ee-4880-bd5a-8ca95bdc96bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3de5ef5a-7ab8-4731-88b0-2ce40975ce81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>3452054b-9997-4449-b059-065ec2160e3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Zip</value>
      <webElementGuid>4a7592fa-ddc5-4175-a8ab-356e59207245</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>75bfc2d6-dcab-445a-be34-040516712d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>zipCode</value>
      <webElementGuid>065f3e38-9407-4f3b-84ff-b79183475d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>805323a3-b4ef-4490-9bac-448384bfec7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter zip code</value>
      <webElementGuid>5a41f136-236d-4ca0-9cc4-a083af99243e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter 5 digit or Zip+4 format:&lt;br />&lt;br />&lt;b>49058:&lt;/b>&lt;br />or&lt;br />&lt;b>49058-1091&lt;/b></value>
      <webElementGuid>87715bd3-a5f6-4206-868a-607fbf7461e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>c625826b-665a-4ce6-9c7e-97098b8f9905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\d{5}(\-\d{4})?$</value>
      <webElementGuid>ad070976-5d9f-45a1-8332-ae97cc762285</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>78c6969b-5961-4b5b-b216-543e801d2586</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0b117334-4604-451d-a4c0-bafad616f5ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8300ca9e-2f89-43dc-87b0-5a81852d05cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Zip&quot;)</value>
      <webElementGuid>ef1eb698-1d59-463d-82c8-dbee47be4349</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Zip']</value>
      <webElementGuid>037454d4-9c03-42fb-9c46-4ee7ca5ffc48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[3]/table[2]/tbody/tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>e4148e80-1a91-4814-9635-5eea7b3a596a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>71995e87-56af-4ed6-bc75-2cdb6f4e1fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Zip' and @name = 'Zip' and @alt = 'zipCode' and @title = 'Enter zip code' and @type = 'text']</value>
      <webElementGuid>aa3041e0-0cc1-414f-b62d-5464cdcc681c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
