<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_of miles one way to work_NumberOfMilesToWork</name>
   <tag></tag>
   <elementGuidId>5a3385b5-51c2-4575-8c8d-b6e80d1e4d1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumberOfMilesToWork']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#NumberOfMilesToWork</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0da5a1d7-5921-4aec-b729-46ad30f1a583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>434afd00-ba66-4ece-9919-1b45acade849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberOfMilesToWork</value>
      <webElementGuid>bec1ea20-ada8-43a2-a301-c8e03ae9e1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumberOfMilesToWork</value>
      <webElementGuid>f30f8f4b-8197-4d93-80f6-b7fb14917699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>2ccc2267-2807-41b2-ae1e-da6541a2f0e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>number_2_digits</value>
      <webElementGuid>d0340ba5-5f15-4805-9171-61d190b52ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>4760f22c-6c9c-4ae8-8446-a6f90d022aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>39fd0948-5ba9-40a8-9397-063c7423985b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ba4343e1-5094-4677-a539-c3639cb089a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberOfMilesToWork&quot;)</value>
      <webElementGuid>94fa5359-3215-4db9-a27f-d5295a9d629b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumberOfMilesToWork']</value>
      <webElementGuid>12fc9177-9708-435f-93f6-7a915ef10a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vehicle-detail-container']/div[3]/table/tbody/tr[4]/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>0e4e8a8c-6f20-4911-a694-488cd3c0e4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>cff31008-7e85-471b-891b-e0292bc532e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NumberOfMilesToWork' and @name = 'NumberOfMilesToWork' and @alt = 'number_2_digits' and @type = 'text']</value>
      <webElementGuid>3054235f-8c81-4522-98bf-2a19aa5720c6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
