<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_VIN_VIN</name>
   <tag></tag>
   <elementGuidId>bdcb98bb-c4c9-4b9f-849a-1d1c017e2995</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='VIN']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VIN</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8efd5d7d-4b4d-41ea-a8c1-e3d2f607e2f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5ccfc6f7-2fef-4ff7-a80b-08b81de16da6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VIN</value>
      <webElementGuid>d7c80c65-63e1-4113-932a-e1270fb8bc1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VIN</value>
      <webElementGuid>2b1f3b75-4145-447a-874c-3f94363a4c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>28</value>
      <webElementGuid>acce5041-0770-47f2-80e7-07e7da5e7c98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>14552a7f-5606-4bc6-88e7-b5b6770c9dd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/VehicleInfoByVIN/70126483?vehiclekey=b830fd7146f47558095d8659e3ce66b</value>
      <webElementGuid>759701e9-726d-4878-a2b2-e628fd939186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/VehicleInfoByVIN/70126483?vehiclekey=b830fd7146f47558095d8659e3ce66b</value>
      <webElementGuid>227a0a29-6fdc-4a37-8f4b-4720b4e3e6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^[0-9a-zA-Z]+$</value>
      <webElementGuid>e76140fc-4813-4929-877a-050fa8b5487b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>&amp; is not allowed.</value>
      <webElementGuid>ac16403c-7dad-4950-a0bf-575e14fa6ce2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>9a331bf0-3c82-4202-97bc-10fca2c310f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>eaee4cb8-1d90-48c5-971a-d0f4488ed6fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8db7410a-5b95-41ce-bccc-426e5c2b255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VIN&quot;)</value>
      <webElementGuid>4e4e8571-e0ab-4128-9222-29e5c0d74eb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='VIN']</value>
      <webElementGuid>16d7ef0b-33f5-452b-9456-f4370a0717cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vehicle-detail-container']/div[2]/table/tbody/tr[2]/td[2]/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>49ab7d49-ec12-42b5-a9d7-9859468b754d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/table/tbody/tr/td/input</value>
      <webElementGuid>0780f72b-1609-44f6-994d-a8a0b6bd8a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'VIN' and @name = 'VIN' and @href = '/PersonalAuto/ExpressQuote/VehicleInfoByVIN/70126483?vehiclekey=b830fd7146f47558095d8659e3ce66b' and @title = '&amp; is not allowed.' and @type = 'text']</value>
      <webElementGuid>0ea8116f-ef78-4ff4-bdfb-0541227b70f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
