<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>d4472302-d7c5-4e5d-a25f-8579820d8a84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehicleSolelyTitledToNamedInsureds']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VehicleSolelyTitledToNamedInsureds</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0e9da539-e7dd-4a0f-a043-405533352975</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>c355d379-ebfb-4407-8b8e-dc27d09e2867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehicleSolelyTitledToNamedInsureds</value>
      <webElementGuid>071d7688-896b-42cc-a2a6-fbc8a9307c5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehicleSolelyTitledToNamedInsureds</value>
      <webElementGuid>6273b487-f857-4eba-993b-fcbb67e37c7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>f916fa6e-a3f8-4064-8392-f46626881ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>0c0ee1b6-3522-49e4-86f0-27294f0dea1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>48a0abd2-d888-4374-a9e2-4836490b00ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehicleSolelyTitledToNamedInsureds&quot;)</value>
      <webElementGuid>1b5cf026-7ef6-42e6-9792-ad9668952032</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehicleSolelyTitledToNamedInsureds']</value>
      <webElementGuid>2bc9e036-4092-4bb1-bf6b-6313c032d039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vehicle-detail-container']/div[3]/table/tbody/tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>6c2aa148-5ecb-49f7-8e6c-c6644a2b1bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this vehicle solely titled to the named insured(s)?'])[1]/following::select[1]</value>
      <webElementGuid>abfd37b7-eee9-4cf9-ba0a-338caf167c86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='# of miles one way to work'])[1]/following::select[1]</value>
      <webElementGuid>6dac0ae3-bf34-437f-89c3-21b9b5153716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Do you want to add Joint Ownership to this vehicle?'])[1]/preceding::select[1]</value>
      <webElementGuid>5c38f1b9-c47d-4dc1-9d0e-99e20513bbce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joint Ownership Form'])[1]/preceding::select[2]</value>
      <webElementGuid>e3e55de5-626e-436f-bb4a-56884b9c1e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>14fe2ef4-7610-48bc-aa11-a0d8242e1a32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehicleSolelyTitledToNamedInsureds' and @name = 'VehicleSolelyTitledToNamedInsureds' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>16b8b47e-f6ac-4485-9690-bd7c06964e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
