<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Private Passenger  Pickup _020192</name>
   <tag></tag>
   <elementGuidId>ff5165f8-1448-444a-95c6-6fe58f8b52ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='VehicleType']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#VehicleType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>c26e11c4-a567-436e-a1e7-b3744ce39b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>f5fa7458-ee36-46bc-88f5-a83f5b1f03f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>VehicleType</value>
      <webElementGuid>50e03a35-d8e9-496b-a105-4a4719a4bb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>VehicleType</value>
      <webElementGuid>7d465fe9-45c5-452e-a8d4-eafc49d390db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/VehicleUsageOptions/70126483?vehiclekey=b830fd7146f47558095d8659e3ce66b</value>
      <webElementGuid>36436ee4-abb7-4419-8ed8-b1c667645327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>route</name>
      <type>Main</type>
      <value>/PersonalAuto/ExpressQuote/VehicleUsageOptions/70126483?vehiclekey=b830fd7146f47558095d8659e3ce66b</value>
      <webElementGuid>c2ea7fa6-33b0-42ca-9193-28d1a9991848</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>d927c21f-75ca-487c-8a2a-280f0398cda7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>fc43d188-e4b6-49bb-85b3-d019895fa2d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Private Passenger  Pickup  Van  Antique  Classic  Electric  Motor Home  Recreational Trailer  Trailer </value>
      <webElementGuid>dac3919e-d9a9-46d1-bf0f-6b7b69f66308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;VehicleType&quot;)</value>
      <webElementGuid>ba665e6b-80ec-4df6-aaa7-8c62d5e7bb8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='VehicleType']</value>
      <webElementGuid>3ab96eb1-11f8-4fc5-bdf3-3e2bece09d6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='vehicle-detail-container']/div[2]/table/tbody/tr/td[2]/div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>922f48b1-12a8-4556-a0a4-d94024d2cca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vehicle Type'])[1]/following::select[1]</value>
      <webElementGuid>ab01abb9-d0f2-4b22-81d3-5574896a8cda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quoting with an incomplete or inaccurate VIN will produce an inaccurate rate.'])[1]/following::select[1]</value>
      <webElementGuid>a85bb1f7-da6e-4d72-b0c9-34afed4502d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Year'])[1]/preceding::select[1]</value>
      <webElementGuid>296b12a2-15fa-4868-8acb-ffbdd265aebc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VIN'])[1]/preceding::select[1]</value>
      <webElementGuid>d4734c6c-a6d9-415b-b38f-85504278c624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td/select</value>
      <webElementGuid>41e006df-4b13-492e-a773-aace46620c29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'VehicleType' and @name = 'VehicleType' and @href = '/PersonalAuto/ExpressQuote/VehicleUsageOptions/70126483?vehiclekey=b830fd7146f47558095d8659e3ce66b' and (text() = ' (select)  Private Passenger  Pickup  Van  Antique  Classic  Electric  Motor Home  Recreational Trailer  Trailer ' or . = ' (select)  Private Passenger  Pickup  Van  Antique  Classic  Electric  Motor Home  Recreational Trailer  Trailer ')]</value>
      <webElementGuid>aa4da28c-5106-4d53-a275-975e1e91e7f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
