<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_of Stories_NumberOfStories</name>
   <tag></tag>
   <elementGuidId>b550104b-213c-425d-8714-5c86da87ae72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NumberOfStories</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumberOfStories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10f8cae2-1a57-4507-a248-b1bdd2eb5383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>09d5f1f8-d515-43e6-8d2f-4be0c044394b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberOfStories</value>
      <webElementGuid>a34d3957-bb83-491e-8809-b2599cf8d642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumberOfStories</value>
      <webElementGuid>9ef95501-1555-4750-8787-72d4d99748cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>edd7d21c-359f-451e-acb3-0e53a104b994</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>05116321-49bc-4789-a2c6-0a574e1d1737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>afa80fe2-9bb2-43f3-8d6f-6a3faafaafb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7003b82a-6eac-4556-b523-4d73000e901a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberOfStories&quot;)</value>
      <webElementGuid>0c68274e-8809-4b5c-9a40-7d9af129f5c4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumberOfStories']</value>
      <webElementGuid>6bc74895-3447-4bbc-b0e8-f9e997e7ffee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div/table/tbody/tr[2]/td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>1bee3d11-70e3-4c15-af86-94a2773004dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/table/tbody/tr/td/input</value>
      <webElementGuid>1c14dc2a-5708-4f90-9e87-a4d44d1d1f69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NumberOfStories' and @name = 'NumberOfStories' and @type = 'text']</value>
      <webElementGuid>0e47d457-9707-492a-8ebe-b43262dbb49f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
