<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Of Stories_NumberOfStories</name>
   <tag></tag>
   <elementGuidId>ce9e8625-3d69-49ff-842b-5c72c4df2223</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#NumberOfStories</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='NumberOfStories']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71d1b90a-98f7-44e0-bb3c-f025afaefb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>df33db5c-9965-4f05-83cf-7dd0005c858b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>NumberOfStories</value>
      <webElementGuid>5b72394a-675d-45bb-ad3a-cf79a0acfd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>NumberOfStories</value>
      <webElementGuid>14149597-2bb6-453f-887c-180017a67b50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>b1c5e7c1-c985-4b0f-b919-12a3f941eeb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>999</value>
      <webElementGuid>c066c7e0-2c7d-4eb1-bcce-5eddc8ca49c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text-focus</value>
      <webElementGuid>446d198e-8515-45a4-9416-a6b1ef779852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>bcb5890d-d97e-4536-bd18-0c400ecd59aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8bef33be-491b-4990-9b6e-b27b1e4fce9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;NumberOfStories&quot;)</value>
      <webElementGuid>00a370da-b5ef-4ea1-b336-b0472eb85ce2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='NumberOfStories']</value>
      <webElementGuid>e07dc289-7f98-4308-a683-aea3aef1214a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div[2]/table[3]/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>22a3159e-27da-4f0d-a747-29a9233cc9da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>7a5484d0-a77b-4b07-9eec-0ab955db0fcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'NumberOfStories' and @name = 'NumberOfStories' and @alt = '999' and @type = 'text']</value>
      <webElementGuid>2ebbd7d6-4a13-4443-a8d9-2d38b8f6f025</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
