<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Total Building Square Feet_BuildingSq_4bcac1</name>
   <tag></tag>
   <elementGuidId>f43e4fbb-e5f0-4641-8ae3-b3507097c163</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#BuildingSquareFeet</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='BuildingSquareFeet']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f9cdaa3-886b-4786-bdde-2379eb585bc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>20247b42-996f-45c6-9e69-9f129ae87c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>BuildingSquareFeet</value>
      <webElementGuid>37d0eee2-aa6d-491c-b933-91f8f90ffbba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BuildingSquareFeet</value>
      <webElementGuid>0f00563a-0260-4ace-b850-dd89769031f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>3f617d40-47b1-43ca-bc70-cd8d09332cdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>35eed890-c36a-4d2a-9ec7-5c797b6b41b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-edit-text</name>
      <type>Main</type>
      <value>Square footage not eligible for BOP.  Please see our CPP Program</value>
      <webElementGuid>505175eb-2bcc-46ec-8a40-2a1b25585331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-when-greater-than</name>
      <type>Main</type>
      <value>7500</value>
      <webElementGuid>765b2989-4a6c-45ba-8ed1-d616099a9c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui</value>
      <webElementGuid>50b911ce-78ef-4950-a95a-fdef97f8ab70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>71094bc9-f27c-4c19-a229-d89c02ba24e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>eb675618-9e21-4fec-97bb-fa0b9979d7f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;BuildingSquareFeet&quot;)</value>
      <webElementGuid>285e1a2e-3ce5-4632-9492-0d762c91a7ac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='BuildingSquareFeet']</value>
      <webElementGuid>bffbe202-71b2-43c4-b90d-d942e6912f28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div[2]/table[3]/tbody/tr[2]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>ef195663-cc46-415c-902e-bc9bdb1b75df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>cf0d5f80-d2ef-41f7-919c-41d7882a1d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'BuildingSquareFeet' and @name = 'BuildingSquareFeet' and @alt = 'limit' and @type = 'text']</value>
      <webElementGuid>3e6c9cdf-c594-4020-bd36-a44d1c78e26c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
