<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Square Feet occupied by applicant_Squ_6f8c99</name>
   <tag></tag>
   <elementGuidId>1496caf6-3fea-4d0d-b208-6b9acda49e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SquareFeetOccupiedByApplicant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SquareFeetOccupiedByApplicant']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>70ecb3b4-4ea4-4947-adbb-cc0f9a41377f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>eaf22d65-4a48-4e23-b875-cdc3ea81ff13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SquareFeetOccupiedByApplicant</value>
      <webElementGuid>4e621815-1f33-47f4-b7d6-51f1ba517128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SquareFeetOccupiedByApplicant</value>
      <webElementGuid>43bd975e-f26f-4878-b5fb-d18ea3e8d3d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9d63649e-5abb-438f-ae4b-773948274fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit</value>
      <webElementGuid>8dc21cbd-015d-4934-9d46-dad0b2459cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text-focus</value>
      <webElementGuid>33eebe1e-7a91-43d9-b75d-aaa50cba273c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>54203e76-fb8e-413b-90bf-7c35e8e15090</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e4b7897-8cf9-445e-b188-b215fb8378ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SquareFeetOccupiedByApplicant&quot;)</value>
      <webElementGuid>2d1fb8ee-c3f3-4f08-be2d-82ea238ecdb5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SquareFeetOccupiedByApplicant']</value>
      <webElementGuid>49f06f7d-763f-44ff-8071-c08411b55042</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div[2]/table[3]/tbody/tr[2]/td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>aaf7192e-a8db-41b6-ac09-a5ca3e04ac31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/table/tbody/tr/td/input</value>
      <webElementGuid>62c73d19-875f-4992-9f5d-73c5a964ecd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SquareFeetOccupiedByApplicant' and @name = 'SquareFeetOccupiedByApplicant' and @alt = 'limit' and @type = 'text']</value>
      <webElementGuid>875a5a0d-3b65-461c-a48d-a698ef38a9b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
