<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description of operations at the p_3e354e</name>
   <tag></tag>
   <elementGuidId>c291142c-4ff1-430c-b5ef-781529fa2d24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DescriptionOfOperationsAtThePremises</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DescriptionOfOperationsAtThePremises']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c9e60e72-14d2-4011-ae45-882aa519734e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>759f9140-ef8a-4ca5-98c2-9120845d1694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DescriptionOfOperationsAtThePremises</value>
      <webElementGuid>3edbe970-43fa-4c4a-a25d-821453354189</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DescriptionOfOperationsAtThePremises</value>
      <webElementGuid>8ce7aae8-cac6-43c7-807a-7a99f4c06726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>06aaeed0-462e-4c56-b913-c1563abda701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>5ae31add-113b-4538-8fd0-d95553fb532f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-state-dirty</value>
      <webElementGuid>1933b543-928b-4409-9ff2-a47255c29da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>af5291a6-d7c1-4e8c-b36f-35186da3c7eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DescriptionOfOperationsAtThePremises&quot;)</value>
      <webElementGuid>4c7e9aaf-b638-4b2d-aa2c-ec477aa1850f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DescriptionOfOperationsAtThePremises']</value>
      <webElementGuid>7acd1358-6b49-46e3-b609-c2bd8f6dd71a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div/div[3]/table/tbody/tr/td[2]/div/form/div[2]/table[3]/tbody/tr/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>8f6a2831-a0b4-4d95-81aa-96531b3c5ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>46459a62-1105-4c8c-ba25-934513e99935</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DescriptionOfOperationsAtThePremises' and @name = 'DescriptionOfOperationsAtThePremises']</value>
      <webElementGuid>64fc4b4d-a276-4a92-97c9-de3923ba3de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
