<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)  Yes  No_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>9e90b8fb-a9c2-417e-84d0-952ea2876c3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CoverageDeclined']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#CoverageDeclined</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ad886bf-1e4e-479a-886d-ae098d780179</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>814588d4-f7a8-48dd-9a78-64738fac82d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CoverageDeclined</value>
      <webElementGuid>7a5e8189-8861-4d23-bf56-9a670fb949da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CoverageDeclined</value>
      <webElementGuid>a9c6b44f-c440-49b4-b6b3-fa9ba04f573c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>4a87ff5b-5a91-4a46-86c1-e706a5450c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>bced8eed-2aa0-40a7-b108-0b33226a16ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Select)  Yes  No </value>
      <webElementGuid>3a50e93d-e4c8-446c-a591-85d220b10fdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CoverageDeclined&quot;)</value>
      <webElementGuid>787fb0e1-fbda-4369-925e-1e410eb3615a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CoverageDeclined']</value>
      <webElementGuid>e549f6d1-a89a-4a48-97cc-be2714342e73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/table[2]/tbody/tr/td[2]/div/form/table/tbody/tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>11a17f4c-edff-4188-89c4-53ed56f85edd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Describe Use:'])[1]/following::select[1]</value>
      <webElementGuid>6517c8fa-c936-43e4-9e52-914bcdfea996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description:'])[4]/following::select[2]</value>
      <webElementGuid>2c47f29f-7f00-41da-b129-94e389a90dad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason:'])[1]/preceding::select[1]</value>
      <webElementGuid>79eb981b-51e8-436b-9db7-a192d5eadc30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Property Type:'])[1]/preceding::select[2]</value>
      <webElementGuid>7ec6fafd-74d8-4765-aec9-941d2949d059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[11]/td/table/tbody/tr/td/select</value>
      <webElementGuid>99161790-0e72-45bb-b151-144f9af80069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CoverageDeclined' and @name = 'CoverageDeclined' and (text() = ' (Select)  Yes  No ' or . = ' (Select)  Yes  No ')]</value>
      <webElementGuid>6161e38c-ceb7-4185-a6c7-cd958a9f56c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
