<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy Number_PolicyNumbereb6a269232a_ebd805</name>
   <tag></tag>
   <elementGuidId>b773110f-a4c9-41a8-9f4d-34a97fef3bdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy-container']/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PolicyNumbereb6a269232ae4485a41489434a1e273c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c73248e1-fbfc-4b97-8d2d-efd44fba0ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b7b17ad4-e1cf-4165-93f3-c5981fcb02c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolicyNumbereb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>1d14114c-b32f-4711-a420-3bb9f81ac32e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PolicyNumbereb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>323b13f5-d9e4-450c-9665-58329ad9368f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>54510115-5e67-4f2d-8ba8-a8d92d0b7d43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>5262f432-3522-4701-b07c-c32cd102ade8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>300e89c7-692f-492d-9bfd-711fcd1dfad9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a23d4403-ddb8-4511-9511-a91d40c1e052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e479fca3-c55c-4825-bb40-f2770d0db9a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyNumbereb6a269232ae4485a41489434a1e273c&quot;)</value>
      <webElementGuid>4a45d3b3-b528-4488-9ccb-03d421cf689c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PolicyNumbereb6a269232ae4485a41489434a1e273c']</value>
      <webElementGuid>bcca36e8-d435-4090-b837-b3ac3b17edbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-container']/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>00d03758-4a41-4009-83b5-36857fdea02e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>33fd4867-cac8-4554-bb75-5b3e80e8c655</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PolicyNumbereb6a269232ae4485a41489434a1e273c' and @name = 'PolicyNumbereb6a269232ae4485a41489434a1e273c' and @type = 'text']</value>
      <webElementGuid>0cdcac0d-e84e-4610-8134-8c5d82b062b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
