<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Underlying Premium_UnderlyingPremiume_37880d</name>
   <tag></tag>
   <elementGuidId>ea1f9b4f-0c11-47f8-8f22-834aaef53774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy-container']/div/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UnderlyingPremiumeb6a269232ae4485a41489434a1e273c</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>97e1cd13-cd51-4687-8ee7-dd794832e05c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>ac9dc5ab-2103-45cd-b7e9-498a3dc48f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UnderlyingPremiumeb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>a0ae8b37-ae0e-48ad-999c-b839daaa7edd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UnderlyingPremiumeb6a269232ae4485a41489434a1e273c</value>
      <webElementGuid>9ffee3cc-326a-4326-91f1-ecca35198059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>488b0e2d-139f-4286-a1fa-26a125207df5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>limit8</value>
      <webElementGuid>6156ddb1-6be4-4026-9293-62a28f443ffb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>a0fde189-b224-4653-aef9-a9b2bbe2e7e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>67656a40-aa3b-422b-8f0a-4a22ca5740fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>83b73177-1f16-44e5-87f4-e382c5e5f0bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UnderlyingPremiumeb6a269232ae4485a41489434a1e273c&quot;)</value>
      <webElementGuid>4b292517-9436-448d-b5b2-819921b43cb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UnderlyingPremiumeb6a269232ae4485a41489434a1e273c']</value>
      <webElementGuid>b1e59985-75d8-408f-9364-ab536a6d26f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-container']/div/table/tbody/tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>1d1449e0-e67f-43e9-8e0a-f2614882be5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>c379d164-4ab2-4553-afff-e544c90ba8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UnderlyingPremiumeb6a269232ae4485a41489434a1e273c' and @name = 'UnderlyingPremiumeb6a269232ae4485a41489434a1e273c' and @alt = 'limit8' and @type = 'text']</value>
      <webElementGuid>1eeb487f-01ae-4bb5-b99d-72ad855bc698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
