<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_No  Yes</name>
   <tag></tag>
   <elementGuidId>bf84cd00-f2ef-483d-bee6-549aa45390f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#HiredCarNonOwnedAutoOnly</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='HiredCarNonOwnedAutoOnly']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5ce6c85d-6263-451a-8608-88300a3c5910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>29f5768d-4d49-4024-af75-af7c6c518125</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>HiredCarNonOwnedAutoOnly</value>
      <webElementGuid>f9243ec8-ca99-4950-882c-53541cd15ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>HiredCarNonOwnedAutoOnly</value>
      <webElementGuid>87644e67-8b8c-44b2-beff-8bda01dd4e8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>optional</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>32a0e681-a419-4b19-954a-68477fe9bc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>92b6d132-b1ba-4f35-b4de-8207369d5e68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>41b9de69-7ae9-435d-adb5-43d80631c6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> No  Yes </value>
      <webElementGuid>8cf213fb-662d-4bc3-9196-1f63d74e6834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;HiredCarNonOwnedAutoOnly&quot;)</value>
      <webElementGuid>c31923ac-b595-4542-91dd-89db5e8db347</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='HiredCarNonOwnedAutoOnly']</value>
      <webElementGuid>da515b55-7d26-40dd-920f-8c9d093d4675</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hired-car-non-owned-auto']/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>bd91fbc1-a3f2-4712-add5-109e35bec8e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Owned / Hired Car Included'])[1]/following::select[1]</value>
      <webElementGuid>2c12ae50-5dff-4b4e-ba30-0ad7483e7997</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Additional Underlying Classifications'])[1]/following::select[1]</value>
      <webElementGuid>169ddfcc-c46c-4ea8-8ba9-0caa0a14265f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='e'])[1]/preceding::select[1]</value>
      <webElementGuid>c1fe201d-2f31-43dd-8e8f-a7d70d7e6254</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>45a3f09c-2e66-43ff-bf91-884907ff9096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'HiredCarNonOwnedAutoOnly' and @name = 'HiredCarNonOwnedAutoOnly' and (text() = ' No  Yes ' or . = ' No  Yes ')]</value>
      <webElementGuid>d8aca970-2a90-4d31-9421-18caba2344e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
