<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)Appliance Stores and Distrib_4864c3</name>
   <tag></tag>
   <elementGuidId>64db79bd-40e9-4ad1-8924-d5acede67914</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-container']/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ClassCodeSearchf1dcd725aa41a48235948fc2598109</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dc35b149-72f0-4b33-aace-0e8f72050e57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>1f89f39d-a16c-4425-b2c0-dea26af9eaac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClassCodeSearchf1dcd725aa41a48235948fc2598109</value>
      <webElementGuid>5ea5a700-a81c-446c-b34f-677326a60529</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClassCodeSearchf1dcd725aa41a48235948fc2598109</value>
      <webElementGuid>de43a93e-3786-445b-8192-1850c8af4b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>93c12a45-d295-4cee-b025-f258838c6720</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>aab80a18-2094-49a6-a50d-a9cd53179102</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>(select)Appliance Stores and Distributors - Household N.O.C.Appliance Stores and Distributors - Radio, TV., &amp; Phonographic (incl. parts/supplies)Appliance Stores and Distributors - Sewing MachinesArtists’ &amp; Drafting SuppliesAutomobile Parts and SuppliesBath AccessoriesBicycle Sales, Service, and Distributors – Sponsoring of biking events, but no arranging of biking events*Blanket, Bedspread &amp; Linen StoresBook and Magazine Dealers and DistributorsBookbinding and Printing SuppliesBridal ShopsCamera and Photographic EquipmentCandy, Nut, and ConfectionaryCatalogue or Coupon Redemption StoresCeramicsChina StoresClothing or Wearing Apparel StoresCoffee Bars or Coffee Shops – limited cookingCoffee, Tea and Spice Shops – no cookingComputer StoresCosmetic, Hair, or Skin Products (no preparations)Curtain &amp; Drapery StoresDairy Products (incl. ice cream, butter, eggs, etc.)Delicatessens &amp; Sandwich Shops - limited cookingDelicatessens (incl. deli sandwich shops) - no cookingDepartment or Discount StoresDonut Shops - limited cookingDrug Stores - limited cookingDrug Stores - no cookingDry Goods Dealers (incl. fabrics, yarn, &amp; piece goods)Electrical Supply StoresElectronics StoresEquipment – Office &amp; StoresFabric Stores and DistributorsFloor CoveringsFlorists and Floral SuppliesFruit or Vegetable Dealers and DistributorsFurniture: UpholsteredFurniture: Wood or MetalGardening and Light Farming Supply Dealers and DistributorsGift Shops and NoveltiesGlass Dealers and GlaziersHardwareHearing Aid Stores and DistributorsHobby, Craft, Model Maker, or Artist’s SuppliesHome Improvement SuppliesIce Cream &amp; Yogurt Stores – limited cooking – year-round operationJewelry (imitation &amp; novelty only)Kitchen AccessoriesLamps &amp; Lighting Fixture StoresLeather Goods (incl. luggage)Mail Order HousesMarble Products – Retail onlyMini WarehouseMusic Stores – Pre-RecordedMusical Instruments, Sheet Music &amp; Supplies – including lessons on premisesNewsstandsOffice Machines or Appliances (no repair)Office SuppliesOptical Goods Stores and DistributorsPaint, Wallpaper, or Wall coveringsPaintings, Pictures, or FramesPet Stores (no sales of exotic animals)Pet Supply StoresPizza Shops – limited cooking (not eligible for Hired and Nonowned Auto Liability)Plumbing Supplies Fixtures Dealers and DistributorsPottery ShopsPowered Equipment Dealers and Distributors (yard, garden, etc.)Precision and Scientific Tools and InstrumentsSeed MerchantsShoes and FootwearSporting Goods and Athletic EquipmentStationery or Paper ProductsToys and GamesTuxedo RentalVariety StoresVideo Stores (incl. Rental) and DistributorsWigs – Retail only</value>
      <webElementGuid>6cf288a9-00fa-4652-9622-0514c1ee9e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClassCodeSearchf1dcd725aa41a48235948fc2598109&quot;)</value>
      <webElementGuid>f193efab-1a21-4213-bc06-452861742325</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ClassCodeSearchf1dcd725aa41a48235948fc2598109']</value>
      <webElementGuid>14d53f6e-80a7-457f-87b7-fe267272805b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-container']/div/table/tbody/tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>0e9aaf28-3519-42bc-9149-8565fa93748a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Code'])[1]/following::select[1]</value>
      <webElementGuid>deaa180f-b987-406c-a703-e16fb4f707cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Class Description'])[1]/following::select[1]</value>
      <webElementGuid>4d1dd1ef-6227-4fd5-b245-369122eca23d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Schedule Additional Underlying Classifications'])[1]/preceding::select[1]</value>
      <webElementGuid>3472c7ce-a69c-4c4b-8420-898358e9c56b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Non Owned / Hired Car Included'])[1]/preceding::select[1]</value>
      <webElementGuid>88056298-e55a-46d3-a67f-d372d6d3adfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>6f518ad1-2f64-43de-9a13-4bcf4b1db47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ClassCodeSearchf1dcd725aa41a48235948fc2598109' and @name = 'ClassCodeSearchf1dcd725aa41a48235948fc2598109' and (text() = '(select)Appliance Stores and Distributors - Household N.O.C.Appliance Stores and Distributors - Radio, TV., &amp; Phonographic (incl. parts/supplies)Appliance Stores and Distributors - Sewing MachinesArtists’ &amp; Drafting SuppliesAutomobile Parts and SuppliesBath AccessoriesBicycle Sales, Service, and Distributors – Sponsoring of biking events, but no arranging of biking events*Blanket, Bedspread &amp; Linen StoresBook and Magazine Dealers and DistributorsBookbinding and Printing SuppliesBridal ShopsCamera and Photographic EquipmentCandy, Nut, and ConfectionaryCatalogue or Coupon Redemption StoresCeramicsChina StoresClothing or Wearing Apparel StoresCoffee Bars or Coffee Shops – limited cookingCoffee, Tea and Spice Shops – no cookingComputer StoresCosmetic, Hair, or Skin Products (no preparations)Curtain &amp; Drapery StoresDairy Products (incl. ice cream, butter, eggs, etc.)Delicatessens &amp; Sandwich Shops - limited cookingDelicatessens (incl. deli sandwich shops) - no cookingDepartment or Discount StoresDonut Shops - limited cookingDrug Stores - limited cookingDrug Stores - no cookingDry Goods Dealers (incl. fabrics, yarn, &amp; piece goods)Electrical Supply StoresElectronics StoresEquipment – Office &amp; StoresFabric Stores and DistributorsFloor CoveringsFlorists and Floral SuppliesFruit or Vegetable Dealers and DistributorsFurniture: UpholsteredFurniture: Wood or MetalGardening and Light Farming Supply Dealers and DistributorsGift Shops and NoveltiesGlass Dealers and GlaziersHardwareHearing Aid Stores and DistributorsHobby, Craft, Model Maker, or Artist’s SuppliesHome Improvement SuppliesIce Cream &amp; Yogurt Stores – limited cooking – year-round operationJewelry (imitation &amp; novelty only)Kitchen AccessoriesLamps &amp; Lighting Fixture StoresLeather Goods (incl. luggage)Mail Order HousesMarble Products – Retail onlyMini WarehouseMusic Stores – Pre-RecordedMusical Instruments, Sheet Music &amp; Supplies – including lessons on premisesNewsstandsOffice Machines or Appliances (no repair)Office SuppliesOptical Goods Stores and DistributorsPaint, Wallpaper, or Wall coveringsPaintings, Pictures, or FramesPet Stores (no sales of exotic animals)Pet Supply StoresPizza Shops – limited cooking (not eligible for Hired and Nonowned Auto Liability)Plumbing Supplies Fixtures Dealers and DistributorsPottery ShopsPowered Equipment Dealers and Distributors (yard, garden, etc.)Precision and Scientific Tools and InstrumentsSeed MerchantsShoes and FootwearSporting Goods and Athletic EquipmentStationery or Paper ProductsToys and GamesTuxedo RentalVariety StoresVideo Stores (incl. Rental) and DistributorsWigs – Retail only' or . = '(select)Appliance Stores and Distributors - Household N.O.C.Appliance Stores and Distributors - Radio, TV., &amp; Phonographic (incl. parts/supplies)Appliance Stores and Distributors - Sewing MachinesArtists’ &amp; Drafting SuppliesAutomobile Parts and SuppliesBath AccessoriesBicycle Sales, Service, and Distributors – Sponsoring of biking events, but no arranging of biking events*Blanket, Bedspread &amp; Linen StoresBook and Magazine Dealers and DistributorsBookbinding and Printing SuppliesBridal ShopsCamera and Photographic EquipmentCandy, Nut, and ConfectionaryCatalogue or Coupon Redemption StoresCeramicsChina StoresClothing or Wearing Apparel StoresCoffee Bars or Coffee Shops – limited cookingCoffee, Tea and Spice Shops – no cookingComputer StoresCosmetic, Hair, or Skin Products (no preparations)Curtain &amp; Drapery StoresDairy Products (incl. ice cream, butter, eggs, etc.)Delicatessens &amp; Sandwich Shops - limited cookingDelicatessens (incl. deli sandwich shops) - no cookingDepartment or Discount StoresDonut Shops - limited cookingDrug Stores - limited cookingDrug Stores - no cookingDry Goods Dealers (incl. fabrics, yarn, &amp; piece goods)Electrical Supply StoresElectronics StoresEquipment – Office &amp; StoresFabric Stores and DistributorsFloor CoveringsFlorists and Floral SuppliesFruit or Vegetable Dealers and DistributorsFurniture: UpholsteredFurniture: Wood or MetalGardening and Light Farming Supply Dealers and DistributorsGift Shops and NoveltiesGlass Dealers and GlaziersHardwareHearing Aid Stores and DistributorsHobby, Craft, Model Maker, or Artist’s SuppliesHome Improvement SuppliesIce Cream &amp; Yogurt Stores – limited cooking – year-round operationJewelry (imitation &amp; novelty only)Kitchen AccessoriesLamps &amp; Lighting Fixture StoresLeather Goods (incl. luggage)Mail Order HousesMarble Products – Retail onlyMini WarehouseMusic Stores – Pre-RecordedMusical Instruments, Sheet Music &amp; Supplies – including lessons on premisesNewsstandsOffice Machines or Appliances (no repair)Office SuppliesOptical Goods Stores and DistributorsPaint, Wallpaper, or Wall coveringsPaintings, Pictures, or FramesPet Stores (no sales of exotic animals)Pet Supply StoresPizza Shops – limited cooking (not eligible for Hired and Nonowned Auto Liability)Plumbing Supplies Fixtures Dealers and DistributorsPottery ShopsPowered Equipment Dealers and Distributors (yard, garden, etc.)Precision and Scientific Tools and InstrumentsSeed MerchantsShoes and FootwearSporting Goods and Athletic EquipmentStationery or Paper ProductsToys and GamesTuxedo RentalVariety StoresVideo Stores (incl. Rental) and DistributorsWigs – Retail only')]</value>
      <webElementGuid>d244ecbd-e4ed-4694-ad8e-bd8694dd048b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
