<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(Select)Full PaySemi-annualQuarterly_69046b</name>
   <tag></tag>
   <elementGuidId>e32d00c5-7820-417f-862a-9eb0b6a97e66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#InstallmentPlan</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='InstallmentPlan']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0015a46a-c8bd-4b2e-b2f1-da4ae3a69653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>109efb9d-c9e7-4691-bdcd-9fc41714bc4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>InstallmentPlan</value>
      <webElementGuid>e15a7af5-0c39-463c-a7d6-709e8c120987</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>InstallmentPlan</value>
      <webElementGuid>29304120-76d0-4ea2-a69b-815665df3e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>installmentPlan hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>5e9f58a8-6a43-4f26-ad7c-e35a0a53c77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>566a0d7e-a074-4c5c-8a7b-83bbf3d51540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>

(Select)Full PaySemi-annualQuarterly20% down with 8 monthly installments</value>
      <webElementGuid>91a1904e-bc59-4bb3-ac5a-aca2a72a445e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;InstallmentPlan&quot;)</value>
      <webElementGuid>e987e31c-1a18-4f62-991d-9aa336898b2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='InstallmentPlan']</value>
      <webElementGuid>b08bd58f-cf11-45f1-a17c-6943086ad64a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[2]/table/tbody/tr/td/div/form/div[5]/table/tbody/tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>1dde9ef9-8a0f-4aa3-831b-be2ca80385a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Installment Plan'])[1]/following::select[1]</value>
      <webElementGuid>2e9737de-1f99-4a1c-9282-0385fc451e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How will this policy be billed?'])[1]/following::select[2]</value>
      <webElementGuid>5a2882e0-bc62-430e-bf55-107c8ea49d78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does an account number exist for this applicant?'])[1]/preceding::select[1]</value>
      <webElementGuid>7484230b-b5b9-4618-9f2b-b87b9342f93c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Existing Account Number'])[1]/preceding::select[2]</value>
      <webElementGuid>553e59c4-c0d0-421a-9664-a0eaa1857f07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>9ad43673-50b3-44d3-8ec0-e2dea4e81075</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'InstallmentPlan' and @name = 'InstallmentPlan' and (text() = '

(Select)Full PaySemi-annualQuarterly20% down with 8 monthly installments' or . = '

(Select)Full PaySemi-annualQuarterly20% down with 8 monthly installments')]</value>
      <webElementGuid>dca2e14c-90a4-451e-9e18-9d44b6fb7377</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
