<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Policy Number_PolicyNumberab0099d0506_92a434</name>
   <tag></tag>
   <elementGuidId>a7896f61-d277-41ad-95c5-c8494f4f9e19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='policy-container']/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PolicyNumberab0099d05064836b464d0053b8c53a5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3c5e838-8596-4259-a029-e84bc7b57126</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>3acabba6-4785-4de7-b13c-d7e7a1e13ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PolicyNumberab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>653d3059-a025-4577-a412-32f76370c31e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PolicyNumberab0099d05064836b464d0053b8c53a5</value>
      <webElementGuid>d6e10435-51a3-421a-ace6-d83237ee0e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>20d1b50b-eec0-45f2-a51e-b00ec589a6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>42d90010-d91a-4b48-9181-28e59d894435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>7681d07f-035b-487f-92ac-9c6cdb8cd972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>b95bc34b-5bbe-4610-9d44-d18bb2e48f6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3cb9bc9b-d716-4edb-a141-5cbb3f380a3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PolicyNumberab0099d05064836b464d0053b8c53a5&quot;)</value>
      <webElementGuid>ec4360b2-6fcb-4f7f-a50b-0d103d6deed3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PolicyNumberab0099d05064836b464d0053b8c53a5']</value>
      <webElementGuid>476c11b0-8980-4813-b3ec-b095502509cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='policy-container']/div/table/tbody/tr/td[3]/table/tbody/tr/td/input</value>
      <webElementGuid>34b34672-9b56-4f98-9b71-4e64050260e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>99fb5ea0-0b43-4690-ba9f-3391b560c709</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PolicyNumberab0099d05064836b464d0053b8c53a5' and @name = 'PolicyNumberab0099d05064836b464d0053b8c53a5' and @type = 'text']</value>
      <webElementGuid>06112934-cc1c-4cec-ae6a-e89ba0ce53f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
