<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Class Code_ClassCodeSearche32236d3223_663913</name>
   <tag></tag>
   <elementGuidId>2bb7444c-353d-4753-8c9f-60b8b64b55c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-container']/div/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ClassCodeSearche32236d3223a40759e139e2b01b527bd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64cb66b2-7e79-45d0-9d11-61664b61c824</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>56a3edb5-1e53-453b-b1b4-5403d18001b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ClassCodeSearche32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>bd2ca2f2-83ee-413a-808d-f57ad43d73fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ClassCodeSearche32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>427c483c-4602-4077-90f2-73c3d919b02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>75</value>
      <webElementGuid>59c5b79b-d16a-4eab-9259-3d0b5dcb1f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Ex: 91340 or Carpentry</value>
      <webElementGuid>5b41c729-e2bc-4297-ad8f-f248007589e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>begin typing...</value>
      <webElementGuid>38884f47-facd-437e-9ca7-d74b2769fc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-key</name>
      <type>Main</type>
      <value>e32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>ac4b49ea-0823-4a0f-ad07-5101f5b8a75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>55f4d6bf-3b75-4275-b2e0-0aec00fcc825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>973866db-c8b4-49eb-8721-dc5ba33cdbe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b1841bf1-66e1-4d91-a413-be90a08f8f4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>749061eb-6ac6-45b5-bf0e-b3eb89183c63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ClassCodeSearche32236d3223a40759e139e2b01b527bd&quot;)</value>
      <webElementGuid>4e3188ce-e7da-4558-8981-3748ba9c288b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ClassCodeSearche32236d3223a40759e139e2b01b527bd']</value>
      <webElementGuid>ea922985-b457-42a3-a757-e44df16adb11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-container']/div/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>bb782787-8698-48f2-9b78-82e581378782</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>c1750262-764d-4243-930f-3d4f3b71f890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ClassCodeSearche32236d3223a40759e139e2b01b527bd' and @name = 'ClassCodeSearche32236d3223a40759e139e2b01b527bd' and @placeholder = 'Ex: 91340 or Carpentry' and @title = 'begin typing...' and @type = 'text']</value>
      <webElementGuid>967ad09b-e617-4943-be1c-00f357691c65</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
