<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Underlying Premises Premium_Underlyin_608e27</name>
   <tag></tag>
   <elementGuidId>d9ee0212-9ed6-438f-a6dc-0b56d91f2328</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-container']/div/table/tbody/tr[5]/td[2]/table/tbody/tr/td/input</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efeaf48e-659f-4c42-853f-09eb7d1f3466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>5d03a41a-30e9-4ec4-a77f-522a446631c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>d70509d9-843e-4a10-9b99-3c822a66c9a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>782ac702-bb58-4874-b864-f25cb2cd7360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fe7e72fb-6c43-49ef-9daa-4e0d1e17b989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>800ec998-c6ef-4932-9ff5-20fb217ffef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>6996c631-a5f6-46cd-9ff0-d86c6e297f06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ea7e98f4-aaad-47a0-8f3b-550386643ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd&quot;)</value>
      <webElementGuid>5f42f95e-71d1-4e9b-99b2-b0645a3e3a48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd']</value>
      <webElementGuid>ddf4870a-fc65-4b35-9971-8ad3148fbc97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-container']/div/table/tbody/tr[5]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>87ad37ec-cfbd-4c39-87ea-9b66aeda78df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>bd260e40-d5f2-4102-b6eb-bd95a7bdd4c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd' and @name = 'UnderlyingPremisesPremiume32236d3223a40759e139e2b01b527bd' and @type = 'text']</value>
      <webElementGuid>c58703a7-de92-40ea-a93a-fdf463bcc31c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
