<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Apartment  Auto Service Ri_04f673</name>
   <tag></tag>
   <elementGuidId>e2befcc4-d292-49d4-94e3-1ac827795c7f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='list-container']/div/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ProgramTypee32236d3223a40759e139e2b01b527bd</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d99b9d4a-d4fc-48aa-93e0-cebaf420cc10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>13a95fe5-68a4-4d0b-a8b5-55242a3b688d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProgramTypee32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>9923b714-12d4-427a-a1d2-298aec56f855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProgramTypee32236d3223a40759e139e2b01b527bd</value>
      <webElementGuid>c2b20f98-3cba-4b82-b100-28dd348d9de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>7703659e-94e4-43b6-999b-0535d43b0f1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>838d50d6-79e8-4d72-87e0-c44faab7f9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Apartment  Auto Service Risk (ASR)  Choice Auto Repair Service (CARS)  Church Program  Motel/Hotel  Selected Contractors I  Selected Contractors II  Selected Mercantile  Selected Metalists I  Selected Metalists II  Select Motel  All Other (Including Monoline GL) </value>
      <webElementGuid>5659d81e-f9fe-48db-b1e2-df9a2bf2d6b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProgramTypee32236d3223a40759e139e2b01b527bd&quot;)</value>
      <webElementGuid>01026f1a-13c1-4e46-a447-4dd9b4b03f35</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ProgramTypee32236d3223a40759e139e2b01b527bd']</value>
      <webElementGuid>24956caa-1761-4e94-95cb-e106da475bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='list-container']/div/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>289bac2e-14f3-4163-9233-ff2d691032dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Program Type'])[1]/following::select[1]</value>
      <webElementGuid>e8f300be-b77e-4480-9720-46942da0091b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#1'])[2]/following::select[1]</value>
      <webElementGuid>e6d84a02-be1e-4ccd-b786-e15f8b603bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/preceding::select[1]</value>
      <webElementGuid>f349f788-9f91-45fa-8171-4ee28de02cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Underlying Limit'])[1]/preceding::select[1]</value>
      <webElementGuid>a19f657d-269d-4e79-a0e0-2f33d9626f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>27211ed1-727f-4b85-a2d6-887a724ae7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ProgramTypee32236d3223a40759e139e2b01b527bd' and @name = 'ProgramTypee32236d3223a40759e139e2b01b527bd' and (text() = ' (select)  Apartment  Auto Service Risk (ASR)  Choice Auto Repair Service (CARS)  Church Program  Motel/Hotel  Selected Contractors I  Selected Contractors II  Selected Mercantile  Selected Metalists I  Selected Metalists II  Select Motel  All Other (Including Monoline GL) ' or . = ' (select)  Apartment  Auto Service Risk (ASR)  Choice Auto Repair Service (CARS)  Church Program  Motel/Hotel  Selected Contractors I  Selected Contractors II  Selected Mercantile  Selected Metalists I  Selected Metalists II  Select Motel  All Other (Including Monoline GL) ')]</value>
      <webElementGuid>98236b73-f26d-4d27-af32-226beee06f8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
