<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile Phone_MobilePhone</name>
   <tag></tag>
   <elementGuidId>1c70a85b-c850-4f1f-9eb2-346875fd3894</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MobilePhone</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MobilePhone']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8780927f-0fcd-4db5-ad49-ee82443cee81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>form</value>
      <webElementGuid>4935e5d4-3cb6-419b-bf4a-e6c8436f9ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>12439156-976e-4bd8-a193-d2dac843c885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>f849fc50-0a13-45e2-9514-470ee11c1ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-pair-id</name>
      <type>Main</type>
      <value>contact-phone</value>
      <webElementGuid>12c122e4-4adf-4eaa-9c54-539a24389556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor</value>
      <webElementGuid>c13f25fb-1384-4fa2-9884-efe2cad328c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter phone number</value>
      <webElementGuid>8eaf5e07-9c69-413b-94f4-d143cbcec72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>Enter the telephone number without spaces or punctuation.&lt;br />&lt;br />&lt;b>Example: 6168675309&lt;/b></value>
      <webElementGuid>98c3707b-96ac-4bd1-926f-de2b64bab451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>phoneNumber</value>
      <webElementGuid>a2f22077-c464-4ddc-83d3-f39d8a52cb51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\(?\d{3}\)?.*\d{3}.*\d{4}$</value>
      <webElementGuid>11882afb-4ef1-4969-9536-d972bc0dbc8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d9f69101-e83e-43e4-8cab-85117ecc4bb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8165604d-32c7-46d9-8125-0388a3d2738d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MobilePhone&quot;)</value>
      <webElementGuid>2482c79a-847f-4579-b200-5eec462fd974</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MobilePhone']</value>
      <webElementGuid>58fcd46b-d005-4672-ac10-cf13881cd89c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popupLayer_popupForm']/div/form/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>3390fbe1-f842-4379-b0ce-f62f1926b062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr[3]/td[2]/table/tbody/tr/td/input</value>
      <webElementGuid>89c1bab5-9ecc-41f5-bba3-3973395e99c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MobilePhone' and @name = 'MobilePhone' and @title = 'Enter phone number' and @alt = 'phoneNumber' and @type = 'text']</value>
      <webElementGuid>f6f8cebd-d0ec-4b12-b220-c94a1815af99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
