<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description of Operation_Descripti_4b13ce</name>
   <tag></tag>
   <elementGuidId>4d269073-bfb5-4d74-8e2a-580ce087a48d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DescriptionOfOperation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='DescriptionOfOperation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c3086bb2-218f-4f0f-a528-50253cc367c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>0c779806-0204-4223-a2e1-725b9d894398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>32a9e7e2-6991-451f-9cec-4421346c6f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DescriptionOfOperation</value>
      <webElementGuid>7d7785af-7eb7-4f88-b959-91fe119e853e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>1587757f-d338-4ce0-9772-e9d7bd12731f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>d36ca6b2-6609-4298-9e5d-d8c5bf242010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>768</value>
      <webElementGuid>5fc7f1e1-b1bf-4094-8380-9396926c8022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-editor</value>
      <webElementGuid>ab9eb003-9adb-4b9c-955b-b6d641f91673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>1a992b67-5831-4a75-9b5e-d533b4bcd7e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DescriptionOfOperation&quot;)</value>
      <webElementGuid>e70a0d89-77b4-4676-bf6e-9ec7f049f477</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='DescriptionOfOperation']</value>
      <webElementGuid>369d8107-49f5-4ade-aa91-1afe547396ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div/div[2]/div/div/form/div[4]/table/tbody/tr[2]/td/table/tbody/tr/td/textarea</value>
      <webElementGuid>4872b07a-7813-44b1-840d-45a75abd59c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f60f710a-a6de-4d34-9609-b5e690099eb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'DescriptionOfOperation' and @name = 'DescriptionOfOperation']</value>
      <webElementGuid>b1250eb6-a6de-4140-a1bf-02bd46e9ba0a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
