<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Copy from Mailing Address</name>
   <tag></tag>
   <elementGuidId>99996b69-a2d8-40c4-ae4e-83df9b4802e2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#copyFromMailingAddress > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='copyFromMailingAddress']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fd9c01ce-8dc5-4e2c-b5a1-abdca65cf6d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>f1001862-3f05-4b4f-aa1e-171fb7c3d31a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Copy from Mailing Address</value>
      <webElementGuid>2f34088a-62a4-4841-afae-63ffd9519e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;copyFromMailingAddress&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>9fb66a63-f8b1-41d8-be0b-a8c00adb8afb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='copyFromMailingAddress']/span[2]</value>
      <webElementGuid>31886088-1994-4123-9a42-18ed47a992ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Address'])[1]/following::span[3]</value>
      <webElementGuid>118dcc39-3fae-472c-b4a6-e6be96f2823f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter a name for this location'])[1]/following::span[4]</value>
      <webElementGuid>375656f0-6ae3-4740-80f6-8202d0c2952e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/preceding::span[1]</value>
      <webElementGuid>bde9dd97-63be-47d8-89c2-df3d49ed63c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/preceding::span[1]</value>
      <webElementGuid>817eddfe-3428-4801-9428-c9285e98572d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Copy from Mailing Address']/parent::*</value>
      <webElementGuid>e99c243f-7953-44af-92af-80d1a1a27ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/a/span[2]</value>
      <webElementGuid>eb2fbd23-fa79-42a4-93d3-def9ca19d310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Copy from Mailing Address' or . = 'Copy from Mailing Address')]</value>
      <webElementGuid>7640ec58-d3e3-43d6-8f69-6785b122f88a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
