<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email Address_EmailAddress</name>
   <tag></tag>
   <elementGuidId>ec7facbf-1668-4d53-90e9-b0432c3d52cd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#EmailAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='EmailAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>464f2b14-2b98-4543-afc1-563657993d7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Submission</value>
      <webElementGuid>ec5a5170-b96a-4f4b-b993-f49d546b5475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>EmailAddress</value>
      <webElementGuid>1eee737b-c0bb-4608-9d39-034f8fdba433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>EmailAddress</value>
      <webElementGuid>3a3447d4-2723-469f-b036-30c1fc53565b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>7c08d74c-bd0c-4feb-9095-7a6d4cd2864a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>vcardname</name>
      <type>Main</type>
      <value>vCard.Email</value>
      <webElementGuid>3dd79afd-e017-49f6-b285-90581e5f01c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-text hmi-ui-editor hmi-ui-text-focus</value>
      <webElementGuid>5d10a7f8-6866-4a4c-be64-d5588bbb250f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Enter email address</value>
      <webElementGuid>b709c261-85af-4f0e-9f3b-26d64edad10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>helptext</name>
      <type>Main</type>
      <value>&lt;b>Example: you@yourcompany.com&lt;/b></value>
      <webElementGuid>3592fa55-ee83-4e31-9b56-9977e23726cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6417fc2c-5b1b-4839-b3a0-ca25767d9e4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-regex</name>
      <type>Main</type>
      <value>^\w+([-+.']\w+)*@\w+([-.]\w+)*\.\w+([-.]\w+)*$</value>
      <webElementGuid>c8874489-2af4-4cb2-b1b6-6a09b79dc555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>83691767-6ea0-4b0f-81dc-70fb2a3a37ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f2f6896c-7a4f-4e05-831c-ea1d5eb224fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EmailAddress&quot;)</value>
      <webElementGuid>6fa40282-8e20-4725-9b6f-0fd778a61e4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='EmailAddress']</value>
      <webElementGuid>1a2f2f62-984b-4700-b568-5429de97115a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/form/div[2]/table/tbody/tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>620ba886-4a21-4615-ada9-2c7c806ebcbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td/input</value>
      <webElementGuid>14bf7a10-3e8f-40e7-8678-96e59c109b2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'EmailAddress' and @name = 'EmailAddress' and @title = 'Enter email address' and @type = 'text']</value>
      <webElementGuid>fce2f5a2-79fa-40a4-aa9e-871deedeedaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
