<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Yes  No</name>
   <tag></tag>
   <elementGuidId>baa1df26-0bee-409f-87ea-5ae9b051d7e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IsFarmRisk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IsFarmRisk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>795be7ba-33bd-4693-b088-d4577ffedd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>Submission</value>
      <webElementGuid>5a13f4a3-73bd-400d-9e0e-a0e908289583</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IsFarmRisk</value>
      <webElementGuid>2221d447-cd6f-4d5c-9185-8024459eb93c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>IsFarmRisk</value>
      <webElementGuid>0e8e8228-f0ee-472b-ae17-5633b73919d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>b797177b-4525-477d-975c-acf284674daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>c6e2890e-a21a-494d-bff5-3221bbcec4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Yes  No </value>
      <webElementGuid>c95c5ae3-437c-4cfb-b653-25c865310e04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IsFarmRisk&quot;)</value>
      <webElementGuid>1021ea89-c6c0-404a-817a-cceb82f2da47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IsFarmRisk']</value>
      <webElementGuid>81e417c6-664b-4d22-bdab-7391a69b071e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div/form/div[3]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>717c9a14-eaa4-4ae2-8aaf-78733878a040</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Is this a farm risk?'])[1]/following::select[1]</value>
      <webElementGuid>1aeb80b7-ba87-40bb-b3dc-bba8221a710e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Farm Risk'])[1]/following::select[1]</value>
      <webElementGuid>6277eafd-316d-4849-a72f-2587071ec227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit Application'])[1]/preceding::select[1]</value>
      <webElementGuid>669fdafc-1ee2-42d5-9771-7b2ae4b9b92e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::select[1]</value>
      <webElementGuid>bc042a4b-71bb-42a7-b8bf-618c503ec998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>8dd09b66-9b63-4253-965e-57d90b6c8ba9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IsFarmRisk' and @name = 'IsFarmRisk' and (text() = ' (select)  Yes  No ' or . = ' (select)  Yes  No ')]</value>
      <webElementGuid>816d250d-fa63-455a-828d-cf06bc57bfaf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
