<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Add Contact Information_blockUI blockOverlay</name>
   <tag></tag>
   <elementGuidId>399d2522-1aad-484a-a97a-b3ef59504cdc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.blockUI.blockOverlay</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>812c0691-e5d1-4ff8-8b49-84c8bfed9691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>blockUI blockOverlay</value>
      <webElementGuid>57986785-5936-4e7e-a68b-006605d1e6e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;hmi-layout-mainContent&quot;)/div[1]/div[@class=&quot;ui-tabs ui-widget ui-widget-content ui-corner-all&quot;]/div[@class=&quot;hmi-layout-column-container ui-helper-clearfix&quot;]/div[2]/div[@class=&quot;ui-widget-content&quot;]/div[1]/form[1]/div[@class=&quot;hmi-layout-wrap&quot;]/div[@class=&quot;blockUI blockOverlay&quot;]</value>
      <webElementGuid>0234435c-341f-4382-b384-41aff5cf4607</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[6]/div[4]</value>
      <webElementGuid>150ef2a9-1fe7-4ab0-bd1f-2c8b7d2cb917</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[4]</value>
      <webElementGuid>4b21eb2f-9f3f-4fe0-9fff-18bb216ca5aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
