<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_(select)  Association  Corporation  _a924a5</name>
   <tag></tag>
   <elementGuidId>2e04089e-759c-481b-9205-351edeb61c42</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Entity</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Entity']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>13e163c9-bb1f-464b-8518-bbe339ac1099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>group</name>
      <type>Main</type>
      <value>default</value>
      <webElementGuid>b87121bf-58ee-49ef-8727-01191a9f2c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>557f57b3-6162-45c0-b796-05c130d54fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Entity</value>
      <webElementGuid>cbf59b8e-9d0a-43e0-9c0f-ba459697b77c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>hmi-ui hmi-ui-select hmi-ui-editor</value>
      <webElementGuid>26420faf-eae3-4644-b5af-fe7bdf07c722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ccf3ab45-cad2-487c-88c9-fbe04eea1032</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  Other  Partnership  LLC  Subchapter “S” Corp  Trust </value>
      <webElementGuid>04cd48c7-8296-44b7-9d59-e499d188a5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Entity&quot;)</value>
      <webElementGuid>01c25451-4998-4368-910b-19bf4369f5b7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Entity']</value>
      <webElementGuid>c695efee-b5a5-4408-9040-b8ef74f4fe93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='hmi-layout-mainContent']/div/div[3]/div[2]/div[2]/div/div/form/div[2]/table/tbody/tr/td[2]/table/tbody/tr/td/select</value>
      <webElementGuid>cfed592e-9d10-463c-a520-bdb66272c7d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity'])[1]/following::select[1]</value>
      <webElementGuid>b5b2e9d7-4cc5-41a6-8e57-05ba86fa096e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Information'])[1]/following::select[1]</value>
      <webElementGuid>5b74db5e-1392-4c2c-80cc-00ec303d535a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Entity Description'])[1]/preceding::select[1]</value>
      <webElementGuid>03b83f97-df0d-43f5-9353-67a224f3b5e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Does the applicant have a DBA name?'])[1]/preceding::select[1]</value>
      <webElementGuid>9de96aac-23e5-41bb-8e43-3245a149665e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d7b6b9e3-4228-4a44-8783-6922ead0f978</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Entity' and @name = 'Entity' and (text() = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  Other  Partnership  LLC  Subchapter “S” Corp  Trust ' or . = ' (select)  Association  Corporation  Estate  Individual  Joint Venture  Limited Partnership  Other  Partnership  LLC  Subchapter “S” Corp  Trust ')]</value>
      <webElementGuid>0850f703-680a-447d-a376-fc5d4abfd109</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
